### ISSUE TITLE
Flink CDC will hang up in local test with IDEA

### ISSUE THREAD

**Issue by hqbhoho** [ververica/flink-cdc-connectors#1610] opened 2022-10-10 03:19 UTC
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  1.13.6
 - Flink CDC version: 2.2.0
 - Database and version: mysql 8.0.22

**To Reproduce**
1. The test data :
2. The test code :
```
public static void testFlink2() throws Exception{
        StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
        env.setRuntimeMode(RuntimeExecutionMode.STREAMING);
        MySqlSource<String> mySqlSource = MySqlSource.<String>builder()
                .hostname("localhost")
                .port(3306)
                .username("root")
                .password("123456")
                .deserializer(new JsonDebeziumDeserializationSchema())
                .includeSchemaChanges(true)
                .databaseList("test002")
                .tableList("test002.test")
                .build();

        // enable checkpoint
        env.enableCheckpointing(3000);

        env
                .fromSource(mySqlSource, WatermarkStrategy.noWatermarks(), "MySQL Source")
                // set 4 parallel source tasks
                .setParallelism(4)
                .print().setParallelism(1); // use parallelism 1 for sink to keep message ordering

        env.execute("Print MySQL Snapshot + Binlog");
    }
```

3. The error :

**Flink CDC will hang up in local test with IDEA with two cases as shown below**
a. databaseList or tableList not set
b. test002.test is a table without primary key
   
**Otherwise，DDL message will lost  as shown below**
a. tableChanges lost
```
mysql> alter table test002.test add column name354689 varchar(2);
Query OK, 0 rows affected (0.04 sec)
Records: 0  Duplicates: 0  Warnings: 0
```
<img width="1668" alt="image" src="https://user-images.githubusercontent.com/37388552/194793795-4d8043bf-af63-4584-80b2-c51b5510728e.png">

```
mysql> alter table test002.test04 add column name354689 varchar(2);
Query OK, 0 rows affected (0.03 sec)
Records: 0  Duplicates: 0  Warnings: 0
```
<img width="1653" alt="image" src="https://user-images.githubusercontent.com/37388552/194793926-afd0bf41-80a0-44fa-a23a-30231832ff5e.png">
b. create view/table as select  in other db message lost only last two have message

```
mysql> create table default.test2 as select * from test002.test;
Query OK, 22 rows affected (0.04 sec)
Records: 22  Duplicates: 0  Warnings: 0

mysql> create view default.test3 as select * from test002.test;
Query OK, 0 rows affected (0.01 sec)

mysql> create table default.test34(id int);
Query OK, 0 rows affected (0.03 sec)

mysql> create view test002.test3 as select * from test002.test;
Query OK, 0 rows affected (0.01 sec)
```
<img width="1662" alt="image" src="https://user-images.githubusercontent.com/37388552/194794238-7469b501-0d53-4c3a-9c79-c2012ac79c1d.png">

    

**Additional Description**

**Comment by PatrickRen** [comment] 2024-02-28 15:28
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:28 UTC
Labels: bug
