### ISSUE TITLE
[Mysql cdc] MySqlSourceEnumerator - Received invalid request meta group id 5, the invalid meta group id range is [0, 4]

### ISSUE THREAD

**Issue by ancongxue** [ververica/flink-cdc-connectors#1327] opened 2022-06-29 05:28 UTC
**Describe the bug(Please use English)**
遇到报错：
MySqlSourceEnumerator - Received invalid request meta group id 5, the invalid meta group id range is [0, 4]
导致sourceReader不能正常消费binlog。

**Environment :**
 - Flink version : 1.14.4
 - Flink CDC version: 2.2.0
 - Database and version: mysql 5.7.28-31-57.2-log

**To Reproduce**
1. 任务的StartupMode为INITIAL，scanNewlyAddedTableEnabled为true，checkpoint开启，先正常消费表到binlog阶段，停任务；
2. 修改任务配置，新增加需要监听的表，从上次ck启动；
3. 新增表的snapshot阶段做完，往enumerator反馈完FinishedSnapshotSplitsReportEvent，此时又做完一个ck2；
4. 把任务停掉，从ck2启动，出现图下报错，导致source reader不能继续消费binlog。

**Additional Description**
MySqlSourceEnumerator在2022-06-23 14:25:39挂掉后，之后的每一次故障恢复都会报这个错
![image](https://user-images.githubusercontent.com/26142121/176357946-46d5f02d-6a17-463a-99e1-14d313f29d08.png)

MySqlSourceEnumerator报错
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/26142121/176358073-ebbeab69-f943-4af8-a61f-7999cd663d9a.png">

'Mysql Source account_0'这个MysqlSourceReader启动从ck恢复，没能正常继续消费binlog文件
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/26142121/176358346-5b86e5b8-57e6-4fd4-be50-3c2f90093a77.png">

**Comment by qg-lin** [comment] 2023-09-08 08:22
Environment :

Flink version : 1.16.0
Flink CDC version: 2.4.1
Database and version: 5.7.36-txsql-log

logs:

2023-09-08 10:24:00,838 INFO  com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator [] - The enumerator assigns split MySqlSnapshotSplit{tableId=new-vehicle.activity_push_record, splitId='DB.TABLE:0', splitKeyType=[`id` BIGINT NOT NULL], splitStart=null, splitEnd=null, highWatermark=null} to subtask 0
2023-09-08 10:24:06,402 INFO  com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator [] - The enumerator under NEWLY_ADDED_ASSIGNING receives finished split offsets FinishedSnapshotSplitsReportEvent{finishedOffsets={DB.TABLE:0={ts_sec=0, file=mysql-bin.001378, pos=98360821, kind=SPECIFIC, gtids=01b31c24-9c0a-11ea-8e1d-18ded7a37a9a:1-2682623367,
03511c36-696b-11e8-8005-6c92bf482149:1-10,
1039af25-696b-11e8-869f-246e96731c88:1-806,
2bf9298a-8b4a-11ea-a01c-b8599fe50033:1-7891,
608d96fb-6e46-11ea-b341-b8599fe5d21a:1-10259,
72492b69-68f8-11ea-96c7-30809b6be5c0:1-592655585,
7482be6a-42df-11e8-bfda-6c92bf48ca86:1-107,
a4a017fc-ee79-11e9-b355-6c92bf482a0d:1-1006839233,
b28a794b-bdb7-11e9-82b2-c81fbecfd697:1-343011186,
ba8cb8da-2026-11ec-afca-246e964114b8:1-2287571541,
bb0fc3db-bdb7-11e9-9864-c81fbecfd65d:1-2,
c452744c-24c4-11ee-9421-80e455f3a875:1-188063093,
e48f07b6-bdbe-11e9-a524-b8599f26a4f9:1-11033,
e83139bd-42d8-11e8-bf9f-f0983879a214:1-5972768884,
f4205308-9c09-11ea-8bff-18ded7a37c4a:1-280267139,
f59cbf66-42d8-11e8-9e0a-18ded7a37c50:1-808, row=0, event=0}}} from subtask 0.
2023-09-08 10:24:06,402 INFO  com.ververica.cdc.connectors.mysql.source.assigners.AssignerStatus [] - Assigner status changes from NEWLY_ADDED_ASSIGNING to NEWLY_ADDED_ASSIGNING_SNAPSHOT_FINISHED
2023-09-08 10:24:06,402 INFO  com.ververica.cdc.connectors.mysql.source.assigners.MySqlSnapshotSplitAssigner [] - Snapshot split assigner received all splits finished and the job parallelism is 1, snapshot split assigner is turn into finished status.
2023-09-08 10:24:06,402 INFO  com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator [] - The enumerator requests subtask 0 to update the binlog split after newly added table.
2023-09-08 10:24:06,404 INFO  org.apache.flink.runtime.source.coordinator.SourceCoordinator [] - Source Source: MySQL Source received split request from parallel task 0 (#0)
2023-09-08 10:24:06,405 INFO  com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator [] - The enumerator requests subtask 0 to update the binlog split after newly added table.
2023-09-08 10:24:15,320 INFO  com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator [] - The enumerator requests subtask 0 to update the binlog split after newly added table.
2023-09-08 10:24:16,715 INFO  com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator [] - The enumerator receives request from subtask 0 for the latest finished splits number after added newly tables. 
2023-09-08 10:24:16,993 INFO  com.ververica.cdc.connectors.mysql.source.assigners.AssignerStatus [] - Assigner status changes from NEWLY_ADDED_ASSIGNING_SNAPSHOT_FINISHED to NEWLY_ADDED_ASSIGNING_FINISHED
2023-09-08 10:24:16,993 INFO  com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator [] - The enumerator receives event that the binlog split has been updated from subtask 0. 
2023-09-08 10:24:17,415 ERROR com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator [] - The enumerator received invalid request meta group id 4, the valid meta group id range is [0, 3]

**Comment by PatrickRen** [comment] 2024-02-28 15:05
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:05 UTC
Labels: bug
