### ISSUE TITLE
使用mysql cdc对binlog会不会造成很大压力

### ISSUE THREAD

**Issue by ghost** [ververica/flink-cdc-connectors#324] opened 2021-08-17 03:03 UTC
有100张表，如果使用mysql cdc定义flink动态表，会不会对binlog造成很大压力，现在的机制是好像每张表都会去 启动一个线程读取mysql的binlog，生成一个流，这样100张表不就会产生100个线程，有100个流吗，这样是不是可能对mysql服务器造成很大压力

**Comment by xiangtao** [comment] 2021-08-18 07:11
no ,  according to parallelism setting , when parallelism is 100  it has 100 thread

**Comment by LiangXiam** [comment] 2021-08-18 09:18
> no , according to parallelism setting , when parallelism is 100 it has 100 thread

you means if we set the default parallelism in the flink-default.yaml to 2, when we define 8 flink table using mysql-cdc, when we join 8 table together, it will only produce 2 thread to read mysql binlog ?

**Comment by PatrickRen** [comment] 2024-02-28 15:40
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:40 UTC
Labels: question
