### ISSUE TITLE
[MySQL] Caused by: io.debezium.DebeziumException: Received DML xxx binlog probably contains events generated with statement or mixed based replication format

### ISSUE THREAD

**Issue by yangrong688** [ververica/flink-cdc-connectors#1017] opened 2022-03-28 10:06 UTC
**Describe the bug(Please use English)**
Binlog will have mixed replcation format when Cloud db like CDB HA transition and send statement format replication to binlog
In debezium 1.5.4 Final, it will fail and cannot restore from checkpoint when ocurring  DB HA transition, we should cherry pick https://github.com/debezium/debezium/pull/3319 this pr to solve this problem.

**Environment :**
 - Flink version :  1.13.3
 - Flink CDC version: 2.1.0
 - Database and version: MySQL 5.7

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :
`Caused by: io.debezium.DebeziumException: Received DML 'DELETE FROM `_cdbcksum__329_124080501_1648309680`.`checksums` WHERE db = 'xx' AND tbl = 'a'' for processing, binlog probably contains events generated with statement or mixed based replication format
        at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleQueryEvent(MySqlStreamingChangeEventSource.java:556) ~[flink-sql-connector-mysql-cdc-2.1.1.jar:2.1.1]
        at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleEvent(MySqlStreamingChangeEventSource.java:352) ~[flink-sql-connector-mysql-cdc-2.1.1.jar:2.1.1]
        at com.ververica.cdc.connectors.mysql.debezium.task.MySqlBinlogSplitReadTask.handleEvent(MySqlBinlogSplitReadTask.java:94) ~[flink-sql-connector-mysql-cdc-2.1.1.jar:2.1.1]
        at com.github.shyiko.mysql.binlog.BinaryLogClient.notifyEventListeners(BinaryLogClient.java:1118) ~[flink-sql-connector-mysql-cdc-2.1.1.jar:2.1.1]
        at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:966) ~[flink-sql-connector-mysql-cdc-2.1.1.jar:2.1.1]
        at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:606) ~[flink-sql-connector-mysql-cdc-2.1.1.jar:2.1.1]
        at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:850) ~[flink-sql-connector-mysql-cdc-2.1.1.jar:2.1.1]
        ... 1 more`

**Additional Description**

**Comment by yangrong688** [comment] 2022-03-28 10:25
@leonardBang shall we fix this issue like we did in https://github.com/ververica/flink-cdc-connectors/pull/911

**Comment by leonardBang** [comment] 2022-03-29 03:06
@yangrong688 I think we can fix this in flink cdc code,  If we want to use debezium's PR I tend to bump debezium version  to fix the issue.

**Comment by yangrong688** [comment] 2022-03-29 03:11
> @yangrong688 I think we can fix this in flink cdc code, If we want to use debezium's PR I tend to bump debezium version to fix the issue.

OK, I will try to commit a pr to fix this in flink cdc code.

**Comment by ruanhang1993** [comment] 2022-08-17 09:09
This issue will be fixed by #1236.

**Comment by PatrickRen** [comment] 2024-02-28 15:31
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:31 UTC
Labels: bug
