### ISSUE TITLE
Table/SQL - add support of whitelist of Postgres tables across all schemas?

### ISSUE THREAD

**Issue by ypt** [ververica/flink-cdc-connectors#169] opened 2021-04-23 19:22 UTC
Postgres offers an additional level of namespacing, called "[schemas](https://www.postgresql.org/docs/current/ddl-schemas.html)". In practice, organizations may leverage Postgres schemas as an additional layer of logical isolation between tenants in a multi-tenant app/database architecture.

For example:

```sql
-- In Postgres

CREATE SCHEMA schema1;

CREATE TABLE schema1.users (
  id BIGSERIAL PRIMARY KEY,
  full_name VARCHAR
);

CREATE SCHEMA schema2;

CREATE TABLE schema2.users (
  id BIGSERIAL PRIMARY KEY,
  full_name VARCHAR
);

SELECT * FROM schema1.users; -- This only returns the users in schema1
SELECT * FROM schema2.users; -- This only returns the users in schema2
```

However, from a Flink dynamic table / change-data-capture perspective, one might actually desire to (re)unify these logically isolated tables into a single dynamic table / stream.

For example, one simple example use case might be to more easily compute aggregates across _all of the_ Postgres schemas. i.e. 

```sql
-- In Flink SQL
-- a continuous query with a count of users from both schema1 and schema2

SELECT COUNT(1) FROM users;
```

This might be possible with a Flink Postgres CDC connector interface like this:

```sql
-- in Flink SQL

CREATE TABLE users (
  id BIGINT NOT NULL,
  full_name STRING,
  schema STRING METADATA VIRTUAL -- <-- Proposing this - which surfaces the Postgres schema name here
) WITH (
  'connector' = 'postgres-cdc',
  'decoding.plugin.name' = 'pgoutput',
  'hostname' = 'localhost',
  'port' = '5432',
  'username' = 'username',
  'password' = 'password',
  'database-name' = 'database-name',
  'table-list' = '.*\.users' -- <-- Proposing this - which uses _all_ tables that match the regex to create the Flink dynamic table
);
```

From an implementation perspective, Debezium Engine supports the notion of a [table whitelist](https://github.com/ververica/flink-cdc-connectors/blob/release-1.3/flink-connector-postgres-cdc/src/main/java/com/alibaba/ververica/cdc/connectors/postgres/PostgreSQLSource.java#L173), so I _think_ this aligns with that.

I'm happy to take a stab at implementing this. But, for now, I just wanted to check to see if this idea is something that people are open to.

**Comment by PatrickRen** [comment] 2024-02-28 15:14
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:14 UTC
Labels: enhancement
