### ISSUE TITLE
 建mysql 的cdc表突然异常了, kafka.connect.errors.DataException: NAME is not a valid field name??

### ISSUE THREAD

**Issue by ithjz** [ververica/flink-cdc-connectors#134] opened 2021-03-23 03:09 UTC
前几天 建mysql 的cdc表还是正常的,今天咋就出问题了

CREATE TABLE products_mysql2222 (
  id INT,
  NAME STRING,
  description STRING
) WITH (
  'connector' = 'mysql-cdc',
  'hostname' = '192.168.ip.22',
  'port' = '3306',
  'username' = 'root',
  'password' = '111111111',
  'database-name' = 'mydb',
  'table-name' = 'products_mysql2222'

[ERROR] Could not execute SQL statement. Reason:
org.apache.kafka.connect.errors.DataException: NAME is not a valid field name

**Comment by wasys1314** [comment] 2021-09-16 03:18
我也是差不多的问题，我的pg之前是可以跑的。后来我在表上加了一个新字段，然后把新字段放到程序里面，就报这个错了。

**Comment by wasys1314** [comment] 2021-09-16 03:40
运行环境 ：win10
flink版本 ：1.13.0 
flink-connector-postgres-cdc 版本 ：2.0.1

代码：
`


    public static void main(String[] args) throws Exception {
        //获取flink流环境变量
        StreamExecutionEnvironment exeEnv = StreamExecutionEnvironment.getExecutionEnvironment();

        //表执行环境
        StreamTableEnvironment tableEnv = StreamTableEnvironment.create(exeEnv);

        //拼接souceDLL
        String sourceDDL =
                "CREATE TABLE pgsql_source (\n" +
                        " user_id INT primary key,\n" +
                        " page_id INT,\n" +
                        " status STRING\n" +
                        " ,aa STRING\n" +
                        ") WITH (\n" +
                        " 'connector' = 'postgres-cdc',\n" +
                        " 'hostname' = '192.168.100.213',\n" +
                        " 'port' = '15432',\n" +
                        " 'username' = 'xwdevelop',\n" +
                        " 'password' = 'Develop_4021',\n" +
                        " 'database-name' = 'spatial_testdb',\n" +
                        " 'schema-name' = 'public',\n" +
                        " 'table-name' = 't_student_cdc',\n" +
                        " 'debezium.snapshot.mode' = 'never',\n" +
                        " 'debezium.slot.name' = 't_student_cdc',\n" +
                        " 'decoding.plugin.name' = 'pgoutput'\n" +
                        ")";

        //执行source表ddl
        tableEnv.executeSql(sourceDDL);

        Table table = tableEnv.sqlQuery("select * from pgsql_source");

        DataStream<Tuple2<Boolean, Row>> tuple2DataStream = tableEnv.toRetractStream(table, Row.class);
        tuple2DataStream.print();

        exeEnv.execute();
    }
`

之前的 t_student_cdc 表没加aa字段的时候，程序是可以的。
后来加了 字段后 执行报错
`Caused by: org.apache.kafka.connect.errors.DataException: aa is not a valid field name`

**Comment by wasys1314** [comment] 2021-09-16 04:36
运行环境 ：win10
flink版本 ：1.13.0 
flink-connector-postgres-cdc 版本 ：2.0.1

代码：
`


    public static void main(String[] args) throws Exception {
        //获取flink流环境变量
        StreamExecutionEnvironment exeEnv = StreamExecutionEnvironment.getExecutionEnvironment();

        //表执行环境
        StreamTableEnvironment tableEnv = StreamTableEnvironment.create(exeEnv);

        //拼接souceDLL
        String sourceDDL =
                "CREATE TABLE pgsql_source (\n" +
                        " user_id INT primary key,\n" +
                        " page_id INT,\n" +
                        " status STRING\n" +
                        " ,aa STRING\n" +
                        ") WITH (\n" +
                        " 'connector' = 'postgres-cdc',\n" +
                        " 'hostname' = 'localhost',\n" +
                        " 'port' = '5432',\n" +
                        " 'username' = 'root',\n" +
                        " 'password' = 'root',\n" +
                        " 'database-name' = 'test',\n" +
                        " 'schema-name' = 'public',\n" +
                        " 'table-name' = 't_student_cdc',\n" +
                        " 'debezium.snapshot.mode' = 'never',\n" +
                        " 'debezium.slot.name' = 't_student_cdc',\n" +
                        " 'decoding.plugin.name' = 'pgoutput'\n" +
                        ")";

        //执行source表ddl
        tableEnv.executeSql(sourceDDL);

        Table table = tableEnv.sqlQuery("select * from pgsql_source");

        DataStream<Tuple2<Boolean, Row>> tuple2DataStream = tableEnv.toRetractStream(table, Row.class);
        tuple2DataStream.print();

        exeEnv.execute();
    }
`

之前的 t_student_cdc 表没加aa字段的时候，程序是可以的。
后来加了 字段后 执行报错
`Caused by: org.apache.kafka.connect.errors.DataException: aa is not a valid field name`

**Comment by PatrickRen** [comment] 2024-02-28 15:34
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:34 UTC
Labels: question
