### ISSUE TITLE
error： Supplemental logging not configured for table  

### ISSUE THREAD

**Issue by asushiye** [ververica/flink-cdc-connectors#562] opened 2021-11-04 09:35 UTC
**Describe the bug**

When submitting the Oracle CDC, I falsely report the information of supplementary logging not configured for table. I have set the table level supplementary log in the database。such as alter table asu.products add supplementary log data (all) columns

**Environment :**
 - Flink version :  1.13.1
 - Flink CDC version:   2.1-snapshots
 - Database and version:  oracle 11

**Comment by asushiye** [comment] 2021-11-04 09:39
The reason has been found out. For Oracle 11 version, debezium-connector-oracle-1.5.4.final.jar, it will help me tableidcasesensitive by default
If it is set to true, the table name will be updated to lowercase, so the table completion log setting cannot be queried in Oracle, resulting in a false alarm of the supplementary logging not configured for table error

**Comment by gong** [comment] 2024-02-03 06:38
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
cc @GOODBOY008

**Comment by PatrickRen** [comment] 2024-02-28 15:42
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:42 UTC
Labels: bug
