### ISSUE TITLE
FLINK集群环境下,关联三个MYSQL数据源,运行初期快照过程出现MYSQL异常

### ISSUE THREAD

**Issue by 15608447849** [ververica/flink-cdc-connectors#183] opened 2021-05-14 05:46 UTC
Caused by: java.sql.SQLNonTransientConnectionException: Can't call rollback when autocommit=true
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
	at com.mysql.cj.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:1833) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
	at io.debezium.connector.mysql.SnapshotReader.execute(SnapshotReader.java:766) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
	... 3 more

1. 首次出现在集群内,flink log source error, 指示 针对一张28W数据的表,扫描花了15分钟后, 出现上述错误, 检查点设置为文档所示10分钟间隔,失败重复100次,间隔30分钟
2. 随后IDEA测试 , 在本地关闭检查点后,没有出现

**Comment by PatrickRen** [comment] 2024-02-28 15:14
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:14 UTC
Labels: bug, question
