### ISSUE TITLE
[test][cdc-base]Implement test for cdc-base that test in mysql

### ISSUE THREAD

**Issue by molsionmo** [ververica/flink-cdc-connectors#1362] opened 2022-07-11 12:06 UTC
**Is your feature request related to a problem? Please describe.**
cdc-base module lack tests so that many fixs for cdc-base is diffcult to implement.

**Describe the solution you'd like**
we should implement tests in cdc-base like tests in mysql module.

**Describe alternatives you've considered**
some tests I can think of is below:
1. MySqlSourceTestBase
2.  BinlogSplitReaderTest
3. SnapshotSplitReaderTest
4. MySqlHybridSplitAssignerTest
5. MySqlSnapshotSplitAssignerTest
6. MySqlRecordEmitterTest
7. MySqlSourceReaderTest
8. MySqlSplitSerializerTest
9. MySqlSplitStateTest
10. RecordUtilsTest
11. MySqlSourceITCase

**Comment by PatrickRen** [comment] 2024-02-28 15:29
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:29 UTC
Labels: enhancement
