### ISSUE TITLE
[BUG][PostgreSQL CDC] java.lang.IllegalAccessError: io/debezium/embedded/EmbeddedEngineChangeEvent

### ISSUE THREAD

**Issue by JiangfeiLiu** [ververica/flink-cdc-connectors#1147] opened 2022-05-02 04:04 UTC
**Describe the bug(Please use English)**
see picture,

**Environment :**
 - Flink version :  1.14.3
 - Flink CDC version: 2.2.0
 - Database and version: 11

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :

**Additional Description**
![image](https://user-images.githubusercontent.com/100289093/166182637-55e78c44-76ee-4e08-991a-ecadca282d18.png)
![image](https://user-images.githubusercontent.com/100289093/166182609-cf648dff-7376-4ce4-917d-eb0950aa41bb.png)
![image](https://user-images.githubusercontent.com/100289093/166182736-1a714ce0-1dae-4e55-b3bd-da1e83bc5f30.png)
![image](https://user-images.githubusercontent.com/100289093/166182798-c8c031c1-1ba9-457b-85f5-a73a4f228c6f.png)
![image](https://user-images.githubusercontent.com/100289093/166182541-27e6c9d7-18de-4bc6-a22c-2ec16aca2445.png)

**Comment by bossingyou** [comment] 2022-06-17 02:00
debezium-embedded-1.5.4.Final.jar和flink-connector-debezium-2.2.1.jar含有重复的io.debezium.embedded.EmbeddedEngineChangeEvent，把debezium-embedded-1.5.4.Final.jar这个里面的重复类删了就可以了

**Comment by JodeZer** [comment] 2022-12-23 07:57
@leonardBang could you please take a look at this question?

**Comment by JodeZer** [comment] 2022-12-23 07:59
> debezium-embedded-1.5.4.Final.jar和flink-connector-debezium-2.2.1.jar含有重复的io.debezium.embedded.EmbeddedEngineChangeEvent，把debezium-embedded-1.5.4.Final.jar这个里面的重复类删了就可以了

有实操过了，试了下不太行。会有其他运行时问题

**Comment by PatrickRen** [comment] 2024-02-28 15:07
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:07 UTC
Labels: bug
