### ISSUE TITLE
lock table when started

### ISSUE THREAD

**Issue by jasonsenssylvain** [ververica/flink-cdc-connectors#1641] opened 2022-10-20 12:20 UTC
flinkcdc version: 2.0.0

I already config the property: properties.setProperty("debezium.snapshot.locking.mode", "none");
but still, it will lock table when started.

Now sure is this a bug, or it cannot start without locking table?

**Comment by PatrickRen** [comment] 2024-02-28 15:03
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:03 UTC
Labels: bug
