### ISSUE TITLE
Expose MySQL transaction id as metadata column

### ISSUE THREAD

**Issue by tao-xiao-sn** [ververica/flink-cdc-connectors#1572] opened 2022-09-22 10:12 UTC
**Is your feature request related to a problem? Please describe.**
Unable get `transaction.id` from MySQL CDC while the underlying Debezium provides it

**Describe the solution you'd like**
Something like below would work

```
CREATE TABLE products (
    transtaction_id STRING METADATA FROM 'transaction_id' VIRTUAL,
    order_id INT,
    order_date TIMESTAMP(0),
    customer_name STRING,
    price DECIMAL(10, 5),
    product_id INT,
    order_status BOOLEAN,
    PRIMARY KEY(order_id) NOT ENFORCED
) WITH (
    'connector' = 'mysql-cdc',
    'hostname' = 'localhost',
    'port' = '3306',
    'username' = 'root',
    'password' = '123456',
    'database-name' = 'mydb',
    'table-name' = 'orders'
);
```

**Describe alternatives you've considered**
No alternative

**Comment by PatrickRen** [comment] 2024-02-28 15:03
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:03 UTC
Labels: enhancement
