### ISSUE TITLE
The event ordering of the FlinkCDC connector for TiDB

### ISSUE THREAD

**Issue by phamtai97** [ververica/flink-cdc-connectors#1316] opened 2022-06-27 01:45 UTC
Hi all,
I read the document here: https://ververica.github.io/flink-cdc-connectors/master/content/connectors/tidb-cdc.html and i have concern related to the ordering when FlinkCDC read data from TiDB source.

If i set the parallel of the source to larger than 1 such as 4, the FlinkCDC will parallel read data from TiDB source. So, the data after reading by multiple threads is no longer in the correct order. Example the data is sorted by time field in the table. **Do I understand that right?**

**How to ensure the order when reading this but still ensure performance?**
I think that i can set the parallel is 1 but it is can be bad performance. Or I can use multiple thread and than i sort them before keyBy().
<img width="822" alt="Screen Shot 2022-06-27 at 08 50 14" src="https://user-images.githubusercontent.com/38773351/175845481-5cdbc131-78ba-4e27-b58a-1696a06af9bd.png">

**Comment by PatrickRen** [comment] 2024-02-28 15:05
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:06 UTC
Labels: bug
