### ISSUE TITLE
Is there a plan to support Ogg?

### ISSUE THREAD

**Issue by snycc15** [ververica/flink-cdc-connectors#222] opened 2021-06-23 03:19 UTC
Is there a plan to support Ogg?

**Comment by GOODBOY008** [comment] 2021-07-05 06:49
Debezium ingests change events from Oracle using the native LogMiner database package or the XStream API. And also flink-cdc-connector integrates Debezium as the engine to capture data changes. I think this function is on way~

**Comment by snycc15** [comment] 2021-07-12 07:47
> Debezium ingests change events from Oracle using the native LogMiner database package or the XStream API. And also flink-cdc-connector integrates Debezium as the engine to capture data changes. I think this function is on way~

ths

**Comment by snycc15** [comment] 2022-01-14 03:22
For some requirements, Ogg tools have been clearly used, so it is also necessary to consider being able to directly connect to Ogg

**Comment by PatrickRen** [comment] 2024-02-28 15:13
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:13 UTC
Labels: discussion
