### ISSUE TITLE
Flink Connector Postgres CDC sql-client模式下报错

### ISSUE THREAD

**Issue by grontorino** [ververica/flink-cdc-connectors#36] opened 2020-09-17 08:00 UTC
env version:
`flink 1.11.2`
`flink-connector-postgres-cdc 1.0 & 1.1`

DDL:
```sql
CREATE TABLE order_cdc(
    id BIGINT,
    user_id BIGINT,
    create_time TIMESTAMP(0),
    operate_time TIMESTAMP(0),
    province_id INT,
    order_status STRING,
    total_amount DECIMAL(10, 5)
  ) WITH (
    'connector' = 'postgres-cdc',
    'hostname' = '***',
    'port' = '5432',
    'username' = 'postgres',
    'password' = '***',
    'schema-name' = 'public',
    'database-name' = 'cdc',
    'table-name' = 'order_cdc'
);
```
进行查询时会报错：
```
[ERROR] Could not execute SQL statement. Reason:
java.lang.ClassNotFoundException: com.alibaba.ververica.cdc.connectors.postgres.table.PostgresValueValidator
```
尝试更换了1.0以及1.1的connector jar包，都会报这个错误，请大佬帮忙看一下

**Comment by wuchong** [comment] 2020-09-22 07:34
1. 请检查下 flink/lib 下是否有 flink-sql-connector-postgres-cdc-1.1.0.jar
2. 保证 flink/lib 下所有 cdc connectors 的版本一致，比如都用 1.1.0 版本，不要混用。
3. 更新 jar 包后，记得重启 sql client 和 flink cluster.

**Comment by PatrickRen** [comment] 2024-02-28 15:38
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:38 UTC
Labels: question
