### ISSUE TITLE
[Bug][PostgreSQL] snapshot-mode is nerver and no data come in,checkpoint failed

### ISSUE THREAD

**Issue by JiangfeiLiu** [ververica/flink-cdc-connectors#1229] opened 2022-05-28 05:36 UTC
env:
    Flink: 1.14.3
    Flink CDC: 2.2.1

Please see pictures:
![image](https://user-images.githubusercontent.com/100289093/170810657-10f521be-d571-4e82-9577-4e9edc43be35.png)
![image](https://user-images.githubusercontent.com/100289093/170810662-f3ba140c-0246-4ecb-8822-1dee80b87259.png)
![image](https://user-images.githubusercontent.com/100289093/170810671-020e8604-64b3-4859-aac9-bf602f4f78d5.png)
![image](https://user-images.githubusercontent.com/100289093/170810673-2dfcdf4e-d015-4f8c-aff8-1e9d8ab4ba15.png)
![image](https://user-images.githubusercontent.com/100289093/170810679-77c84ae5-dbc4-4970-886c-d349a543075b.png)
![image](https://user-images.githubusercontent.com/100289093/170810683-b53e0763-f1bd-42cd-8bd9-11ecd7688696.png)

I also test checkpoint with Flink and Flink CDC in different version,see that:
![image](https://user-images.githubusercontent.com/100289093/170811667-5794a814-e230-4f36-99fa-e5ee87be1174.png)

**Comment by PatrickRen** [comment] 2024-02-28 15:29
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:30 UTC
Labels: bug
