### ISSUE TITLE
Allow to limit speed when read database snapshot

### ISSUE THREAD

**Issue by undefang** [ververica/flink-cdc-connectors#510] opened 2021-10-19 03:25 UTC
I expect a limit-speed configuration when I read database snapshot， to reduce impact on db.

**Comment by shidayang** [comment] 2021-12-02 09:43
@wuchong cc.  Does this feature make sense？I have the similar requirement not only the cdc but any source

**Comment by wuchong** [comment] 2021-12-02 10:13
Yes. I think it makes sense. AFAIK, only Google PubSub connector supports this using `GuavaFlinkConnectorRateLimiter` util.

**Comment by shidayang** [comment] 2021-12-02 11:44
> Yes. I think it makes sense. AFAIK, only Google PubSub connector supports this using `GuavaFlinkConnectorRateLimiter` util.

Thanks for your reply, ah , Google PubSub is using.  
1. The rate limiter need every connector to implement at present. Is it a good idea to do this in flink SourceOutput? so that connectors don't need to resolve this.
2. The rate limiter only has effecting in per parallelism not in global , this may cause the global rate not correct.  the new source api can communicate with JM， can we use this to make a global rate limiter?

**Comment by wuchong** [comment] 2021-12-02 12:35
@shidayang , good question, but this question would be better to discussion in Flink community (JIRA or dev ML) if it will end with a framework ability.

**Comment by shidayang** [comment] 2021-12-02 13:15
ok, I will discuss this ideas in ML later

**Comment by ChenShuai1981** [comment] 2024-01-02 08:24
How about the status of this issue now? Can we support it?

**Comment by PatrickRen** [comment] 2024-02-28 15:11
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:11 UTC
Labels: enhancement
