### ISSUE TITLE
Add a new startup mode that only do the snapshot phase

### ISSUE THREAD

**Issue by zhjwpku** [ververica/flink-cdc-connectors#816] opened 2022-01-20 07:20 UTC
**Is your feature request related to a problem? Please describe.**

Some one may only want the snapshot phase, not consuming the binlog.

It is important that to make sure that after the job is done, it should
be consistent with the source db, which means the sink side database
reflect a point-in-time of the source db.

**Describe the solution you'd like**

Add a new startup mode, may be call it  INIT_ONLY?
when snapshot phase ends, create a binlog with maxBinlogOffset instead
of the BinlogOffset.NO_STOPPING_OFFSET.

Some considerations:

- After the job done, is it possible to show the finished binlog offset(which
   is maxBinlogOffset) somewhere in the finished job's status?
- How to stop the job gracefully?

**Comment by hzh2955** [comment] 2022-01-25 08:56
This features is also needed here

**Comment by sonyfoxcn** [comment] 2022-03-15 15:01
I want it too

**Comment by PatrickRen** [comment] 2024-02-28 15:10
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:10 UTC
Labels: enhancement
