### ISSUE TITLE
CDC Stream API deserialize column type like `bigint(20) unsigned` Covert to wrong type

### ISSUE THREAD

**Issue by guixin** [ververica/flink-cdc-connectors#798] opened 2022-01-14 02:27 UTC
**Describe the bug**
my table defined some column type like `bigint(20) unsigned`. I got wrong value by JsonDebeziumDeserializationSchema

**Environment :**
 - Flink version :  flink 1.13
 - Flink CDC version:  2.2-snapshot
 - Database and version: mysql 5.7

**To Reproduce**
use com.ververica.cdc.connectors.mysql.source.MySqlSource to build source

**Additional Description**

this is my test table，and dataset

![image](https://user-images.githubusercontent.com/9494454/149440348-96e487e9-0e71-429a-b2f6-6c6d5df24e20.png)

my map operator get string like this.  order_id column and fee column is wrong value

![image](https://user-images.githubusercontent.com/9494454/149440618-5099c0f0-8e22-4786-b3bc-68dea24376dc.png)

**Comment by guixin** [comment] 2022-01-14 02:38
Hi, @leonardBang, i want to fix it

**Comment by yaoboxu** [comment] 2022-01-15 05:58
case BIGINT_UNSIGNED:
                return DataTypes.DECIMAL(20, 0);

IN CDC SOURCE CODE DESCRIBE

**Comment by guixin** [comment] 2022-01-18 08:07
add debeziumProperties `bigint.unsigned.handling.mode = long` can fixed it;

- exmaple

```java
        Properties p = new Properties();
        p.put("bigint.unsigned.handling.mode", "long");

        MySqlSource<String> mySqlSource = MySqlSource.<String>builder()
                .hostname("127.0.0.1")
                .port(3307)
                .databaseList("")
                .tableList("")
                .username("")
                .password("")
                .serverId("")
                .deserializer(new JsonDebeziumDeserializationSchema())
                .debeziumProperties(p)
                .build();
```

default bigint.unsigned.handling.mode configure is precise. it will set column type is bytes, so JsonDebeziumDeserializationSchema class deserialize wrong.

![image](https://user-images.githubusercontent.com/9494454/149895692-939dd7db-817e-48ff-a4e5-030f90910a04.png)
![image](https://user-images.githubusercontent.com/9494454/149895734-c4e0b4c2-84a9-4ef0-b01d-d52b534ba16d.png)

**Comment by wuchong** [comment] 2022-01-18 09:13
I think it's also fine to introduce `bigint.unsigned.handling.mode` option for mysql cdc connector. 
cc @fsk119

**Comment by PatrickRen** [comment] 2024-02-28 15:10
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:10 UTC
Labels: bug
