### ISSUE TITLE
TiDB cdc demo improve

### ISSUE THREAD

**Issue by lsyldliu** [ververica/flink-cdc-connectors#1371] opened 2022-07-14 03:55 UTC
**Describe the bug(Please use English)**
TiDB cdc demo run failed.

**Environment :**
 - Flink version :  1.13.5
 - Flink CDC version: 2.2.1
 - Database and version: 5.4

**To Reproduce**
![image](https://user-images.githubusercontent.com/17698589/178894874-acead5a9-4210-4245-a043-f54ee0edef61.png)

**Comment by lsyldliu** [comment] 2022-07-14 03:55
cc @leonardBang

**Comment by conwel** [comment] 2022-07-29 07:13
you can send out the error message。

**Comment by PatrickRen** [comment] 2024-02-28 15:29
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:29 UTC
Labels: bug
