### ISSUE TITLE
does mysql cdc connector support temporal joins?

### ISSUE THREAD

**Issue by Gavineil** [ververica/flink-cdc-connectors#168] opened 2021-04-21 01:24 UTC
does mysql cdc connector support temporal joins?

**Comment by PatrickRen** [comment] 2024-02-28 15:14
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:14 UTC
Labels: enhancement
