### ISSUE TITLE
如何拓展功能，比如解密配置项的密文？

### ISSUE THREAD

**Issue by ice-llz** [ververica/flink-cdc-connectors#1251] opened 2022-06-06 17:15 UTC
在项目里我使用Flink-CDC来将数据从mysql同步到ES。然而项目需要，数据库和ES的用户名和密码不能明文写在Flink sql里。那么我该如何修改源码使其能够支持解密呢？（特别是ES的，我没有找到开源代码）

**Comment by PatrickRen** [comment] 2024-02-28 15:07
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:07 UTC
Labels: enhancement
