### ISSUE TITLE
数据传输过程中，job无法cancel掉

### ISSUE THREAD

**Issue by laifulin** [ververica/flink-cdc-connectors#72] opened 2020-12-18 14:43 UTC
2020-12-18 22:38:00,329 WARN  org.apache.flink.runtime.taskmanager.Task                    [] - Task 'Source: TableSourceScan(table=[[default_catalog, default_database, 表名]], fields=[字段名]) -> MiniBatchAssigner(interval=[2000ms], mode=[ProcTime]) -> Calc(select=[sql语句]) (1/1)' did not react to cancelling signal for 30 seconds, but is stuck in method:
 org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.runThrowing(StreamTaskActionExecutor.java:91)
org.apache.flink.streaming.runtime.tasks.mailbox.Mail.run(Mail.java:78)
org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.processMail(MailboxProcessor.java:282)
org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxStep(MailboxProcessor.java:190)
org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:181)
org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:566)
org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:536)
org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:721)
org.apache.flink.runtime.taskmanager.Task.run(Task.java:546)
java.lang.Thread.run(Thread.java:748)

当表的数据量很多的时候，任务运行中，在web ui上cancel任务时，发现无法关闭任务，一直显示CANCELING，暂用slot也没有释放掉   ---   standalone集群模式下出现

**Comment by jasonzhangz** [comment] 2021-06-29 09:33
目前也遇到这样的问题，pg cdc , 使用 flink cancel 命令方式，web ui 方式， flink rest api方式尝试取消任务，都一直处于CANCELING。

**Comment by yaoyi** [comment] 2022-08-30 19:04
@jasonzhangz 请问还有出现这种情况吗，我这边使用最新2.2.1版本，pg cdc还是会出现无法取消的情况

**Comment by PatrickRen** [comment] 2024-02-28 15:41
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:41 UTC
Labels: bug
