### ISSUE TITLE
flink cdc(mysql) -> elasticsearch7, 任务每次持续跑了一段时间之后(elasticsearch connection reset by peer)，就自动结束了

### ISSUE THREAD

**Issue by kim-up** [ververica/flink-cdc-connectors#1517] opened 2022-08-30 02:24 UTC
**Describe the bug(Please use English)**
Elasticsearch7 connection reset by peer 

**Environment :**
 - Flink version :  1.13.6
 - Flink CDC version: 2.2.1
 - Database and version: mysql-5.7
 - Flink-sql-connector-elasticsearch7: 2.11-1.13.6

**Additional Description**
=====================================================================================================
LogType:taskmanager.out
LogLastModifiedTime:Sat Aug 27 09:56:53 +0800 2022
LogLength:2107
LogContents:
10:27:27.535 [I/O dispatcher 1] ERROR org.apache.flink.streaming.connectors.elasticsearch.util.NoOpFailureHandler - Failed Elasticsearch item request: Connection reset by peer
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_272]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_272]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_272]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[?:1.8.0_272]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[?:1.8.0_272]
	at org.apache.http.impl.nio.reactor.SessionInputBufferImpl.fill(SessionInputBufferImpl.java:231) ~[danchuang-flink-.jar:?]
	at org.apache.http.impl.nio.codecs.AbstractMessageParser.fillBuffer(AbstractMessageParser.java:136) ~[danchuang-flink-.jar:?]
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:241) [danchuang-flink-.jar:?]
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81) [danchuang-flink-.jar:?]
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39) [danchuang-flink-.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114) [danchuang-flink-.jar:?]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) [danchuang-flink-.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) [danchuang-flink-.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) [danchuang-flink-.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) [danchuang-flink-.jar:?]
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) [danchuang-flink-.jar:?]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) [danchuang-flink-.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]

End of LogType:taskmanager.out
********************************************************************************

LogAggregationType: AGGREGATED
LogType:jobmanager.out
LogLastModifiedTime:Sat Aug 27 09:56:53 +0800 2022
LogLength:1842
LogContents:
04:33:35.767 [BLOB connection for /127.0.0.1:41280] ERROR org.apache.flink.runtime.blob.BlobServerConnection - Error while executing BLOB connection.
java.io.IOException: Unknown operation 80
	at org.apache.flink.runtime.blob.BlobServerConnection.run(BlobServerConnection.java:116) [danchuang-flink-.jar:?]
04:33:46.509 [BLOB connection for /127.0.0.1:41332] ERROR org.apache.flink.runtime.blob.BlobServerConnection - Error while executing BLOB connection.
java.io.IOException: Unknown operation 71
	at org.apache.flink.runtime.blob.BlobServerConnection.run(BlobServerConnection.java:116) [danchuang-flink-.jar:?]
04:34:04.300 [BLOB connection for /127.0.0.1:41494] ERROR org.apache.flink.runtime.blob.BlobServerConnection - Error while executing BLOB connection.
java.io.IOException: Unknown operation 80
	at org.apache.flink.runtime.blob.BlobServerConnection.run(BlobServerConnection.java:116) [danchuang-flink-.jar:?]
04:31:28.665 [BLOB connection for /127.0.0.1:48824] ERROR org.apache.flink.runtime.blob.BlobServerConnection - Error while executing BLOB connection.
java.io.IOException: Unknown operation 80
	at org.apache.flink.runtime.blob.BlobServerConnection.run(BlobServerConnection.java:116) [danchuang-flink-.jar:?]
04:31:28.814 [BLOB connection for /127.0.0.1:48842] ERROR org.apache.flink.runtime.blob.BlobServerConnection - Error while executing BLOB connection.
java.io.IOException: Unknown operation 80
	at org.apache.flink.runtime.blob.BlobServerConnection.run(BlobServerConnection.java:116) [danchuang-flink-.jar:?]
04:32:25.780 [BLOB connection for /127.0.0.1:49126] ERROR org.apache.flink.runtime.blob.BlobServerConnection - Error while executing BLOB connection.
java.io.IOException: Unknown operation 71
	at org.apache.flink.runtime.blob.BlobServerConnection.run(BlobServerConnection.java:116) [danchuang-flink-.jar:?]

End of LogType:jobmanager.out
*******************************************************************************

**Comment by PatrickRen** [comment] 2024-02-28 15:04
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:04 UTC
Labels: bug
