### ISSUE TITLE
同步Mysqlbinlog数据不一致

### ISSUE THREAD

**Issue by github202008** [ververica/flink-cdc-connectors#1239] opened 2022-05-31 05:50 UTC
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  1.13.5
 - Flink CDC version: 2.1.0
 - Database and version: 

**To Reproduce**
1. Thes test data :
2. The test code : 
3. The error :

**Additional Description**

问题场景: mysqlxa事务回滚，prepare时数据已经捕获发送到下游,没有同步回滚数据或者事务状态标识
测试步骤：

CREATE TABLE `tb202201` (
  `id` int(11) NOT NULL,
  `age` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

xa start 'xid'
insert into  test2022.tb202201 values(10,100)
xa end 'xid' 
xa prepare 'xid'
xa recover
xa rollback 'xid'

**Comment by github202008** [comment] 2022-05-31 10:25
prepare的时候数据已经读到发送到下游，rollback的时候下游会比原系统条数据

**Comment by MrLiuFang** [comment] 2023-01-11 09:59
大佬们 这个问题我也碰到了   事物回滚了 CDC 不会山删除数据  导致宽表数据多了已经回滚的数据   怎么处理

**Comment by PatrickRen** [comment] 2024-02-28 15:29
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:29 UTC
Labels: bug
