### ISSUE TITLE
Add more tests for the PG plug-in

### ISSUE THREAD

**Issue by fsk119** [ververica/flink-cdc-connectors#477] opened 2021-09-29 03:46 UTC
Currently all tests in PG uses the `decoderbuf` as the plugin. We should add more tests to cover all plugins, e.g `pgoutput` and `wal2json`.

Also we need to bump the docker version used in the test if we want to test `pgoutput`, whichi only works in the PG whose version >= 10.

**Comment by PatrickRen** [comment] 2024-02-28 15:12
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:12 UTC
Labels: enhancement
