### ISSUE TITLE
oracle cdc是否支持19c版本？

### ISSUE THREAD

**Issue by tigerfeilin** [ververica/flink-cdc-connectors#1271] opened 2022-06-10 08:48 UTC
11g上使用cdc测试没有问题，在19c上使用cdc测试不太稳定，总是出现延时较大或者失败的情况，是不是oracle 19c对logminer有限制导致无法正常cdc？

**Comment by Myliox** [comment] 2023-04-27 01:43
请问后续解决了么

**Comment by supercena** [comment] 2023-07-26 05:51
环境： oracle 19c ，  flink-connector-oracle-cdc 2.2.0 
报错：设置参数 properties.setProperty("log.mining.continuous.mine", "true");
          Caused by: Error : 44609, Position : 0, Sql = BEGIN sys.dbms_logmnr.start_logmnr(startScn => '2427825', endScn => '2427868', OPTIONS => DBMS_LOGMNR.DICT_FROM_ONLINE_CATALOG  + DBMS_LOGMNR.CONTINUOUS_MINE  + DBMS_LOGMNR.NO_ROWID_IN_STMT);END;, OriginalSql = BEGIN sys.dbms_logmnr.start_logmnr(startScn => '2427825', endScn => '2427868', OPTIONS => DBMS_LOGMNR.DICT_FROM_ONLINE_CATALOG  + DBMS_LOGMNR.CONTINUOUS_MINE  + DBMS_LOGMNR.NO_ROWID_IN_STMT);END;, Error Msg = ORA-44609: CONTINOUS_MINE 已经不支持用于 DBMS_LOGMNR.START_LOGMNR。
ORA-06512: 在 "SYS.DBMS_LOGMNR", line 72
ORA-06512: 在 line 1
问题：未解决

**Comment by Jetol** [comment] 2023-08-10 09:46
> 

这个问题啥时候有结果，我也遇到了，mark一下

**Comment by gong** [comment] 2024-02-03 05:58
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
cc @GOODBOY008

**Comment by PatrickRen** [comment] 2024-02-28 15:06
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:06 UTC
Labels: bug
