### ISSUE TITLE
postgres-cdc 什么时候支持postgres 14+

### ISSUE THREAD

**Issue by fzxs8** [ververica/flink-cdc-connectors#1549] opened 2022-09-09 08:00 UTC
草率了. 使用了postgres14+

想用CDC做数据同步 发现没有这个版本

请问有没有计划支持 postgres14 
什么时候能支持.

**Comment by GOODBOY008** [comment] 2022-09-15 12:58
@fzxs8 We will plan to bump dbz verison and supoort more versions of pg.

**Comment by PatrickRen** [comment] 2024-02-28 15:03
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:04 UTC
Labels: enhancement
