### ISSUE TITLE
[sqlserver] [wiki] Add FAQ for sqlserver connector.

### ISSUE THREAD

**Issue by GOODBOY008** [ververica/flink-cdc-connectors#1455] opened 2022-08-08 06:53 UTC
Add sqlserver schema evolution  in wiki  FAQ page.

**Comment by GOODBOY008** [comment] 2022-08-08 06:54
![image](https://user-images.githubusercontent.com/13617900/183357528-ecb8d063-c164-441f-b41f-f9c0a63a1631.png)

**Comment by PatrickRen** [comment] 2024-02-28 15:35
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:35 UTC
Labels: docs
