### ISSUE TITLE
The order of the sql of the insert statement will affect the task recovery from the checkpoint

### ISSUE THREAD

**Issue by klovec** [ververica/flink-cdc-connectors#1597] opened 2022-09-30 06:27 UTC
**The order of multiple insert into select statements will affect the task recovery from the checkpoint and data loss**

**Environment :**
 - Flink version :  1.13.2
 - Flink CDC version:  2.2.1
 - Database and version: Mysql 8.0.18, Doris 1.1.0-rc05

**To Reproduce**
1. The test data :
```
-- mysql
CREATE TABLE `test_a` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
);
CREATE TABLE `test_b` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `age` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ;

INSERT INTO `test_a` (`id`, `name`) VALUES (1, 'jack');
INSERT INTO `test_b` (`id`, `age`) VALUES (1, 18);

-- doris
CREATE TABLE test_a (
 id BIGINT, 
 NAME VARCHAR ( 255 ) 
 ) ENGINE = OLAP 
 UNIQUE KEY ( id ) 
 DISTRIBUTED BY HASH ( id ) BUCKETS 1 PROPERTIES (
'replication_allocation' = 'tag.location.default: 1' 
);
CREATE TABLE test_b (
 id BIGINT, 
 age int
 ) ENGINE = OLAP 
 UNIQUE KEY ( id ) 
 DISTRIBUTED BY HASH ( id ) BUCKETS 1 PROPERTIES (
'replication_allocation' = 'tag.location.default: 1' 
);
```
2. The test code :
```
        Configuration configuration = new Configuration();
        StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment(configuration);
        env.enableCheckpointing(10000L);
        env.setParallelism(1);
        env.getCheckpointConfig().setCheckpointStorage("file:///D:/tmp");
        env.getCheckpointConfig().enableExternalizedCheckpoints(CheckpointConfig.ExternalizedCheckpointCleanup.RETAIN_ON_CANCELLATION);

        StreamTableEnvironment tableEnv = StreamTableEnvironment.create(env, EnvironmentSettings.newInstance().inStreamingMode().useBlinkPlanner().build());
        tableEnv.getConfig().setSqlDialect(SqlDialect.DEFAULT);
        String source_table_a_create = "CREATE TABLE IF NOT EXISTS source_test_a (" +
                "  `id` bigint NOT NULL ," +
                "  `name` varchar(255)  NOT NULL ," +
                "  PRIMARY KEY (`id`) NOT ENFORCED " +
                " ) with ('connector' = 'mysql-cdc', 'hostname' = '******', 'port'= '3306', 'username' = '******', 'password' = '******', 'database-name' = 'flink_test', 'table-name' = 'test_a', 'server-time-zone' = 'Asia/Shanghai' )";
        tableEnv.executeSql(source_table_a_create);
        String target_table_a_create = "CREATE TABLE `target_test_a` (" +
                " `id` bigint NOT NULL," +
                "  `name` varchar(255)  NOT NULL" +
                " ) with ( 'connector' = 'doris', 'fenodes' = '******:8030', 'username' = 'root', 'password' = '******', 'table.identifier' = 'data_db.test_a' )";
        tableEnv.executeSql(target_table_a_create);

        StatementSet statementSet = tableEnv.createStatementSet();
        statementSet.addInsertSql("insert into target_test_a select * from source_test_a");
        statementSet.execute();
```

3. The error :

First, execute the above code, and the data in the "test_a" table will be synchronized to the doris , and generate a checkpoint

Then stop the task, delete the data in "test_a" in doris, and add code as follows: 
```
        Configuration configuration = new Configuration();
        // add this line,  set your checkpoint here
        configuration.setString("execution.savepoint.path", "file:///D:/tmp/719790deac1c5eaefc072144306ae4ca/chk-9");
        StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment(configuration);

        ........

        // add table_b
        String source_table_b_create = "CREATE TABLE IF NOT EXISTS source_test_b (" +
                "  `id` bigint NOT NULL ," +
                "  `age` int," +
                "  PRIMARY KEY (`id`) NOT ENFORCED " +
                " ) with ('connector' = 'mysql-cdc', 'hostname' = '******', 'port'= '3306', 'username' = '******', 'password' = '******', 'database-name' = 'flink_test', 'table-name' = 'test_b', 'server-time-zone' = 'Asia/Shanghai' )";
        tableEnv.executeSql(source_table_b_create);
        String target_table_b_create = "CREATE TABLE `target_test_b` (" +
                " `id` bigint NOT NULL," +
                "  `age` int" +
                " ) with ( 'connector' = 'doris', 'fenodes' = '******:8030', 'username' = 'root', 'password' = '******', 'table.identifier' = 'data_db.test_b' )";
        tableEnv.executeSql(target_table_b_create);

        StatementSet statementSet = tableEnv.createStatementSet();

        // test_b is in front of test_a
        statementSet.addInsertSql("insert into target_test_b select * from source_test_b");
        statementSet.addInsertSql("insert into target_test_a select * from source_test_a");
        statementSet.execute();
```
Note that the insert statement of the "test_b" table is placed in front of the "test_a" table, restart the task. in the doris db, expect test_a have no data, and test_b has .  However, the result is that there is no data in the "test_b" table, but "test_a" has

Stop the task, delete the “test_a”data  in doris again and change the order of the insert SQL statements, then restart , The results I just expected have come out

I don't understand why checkpoint recovery is related to sql order

**Comment by PatrickRen** [comment] 2024-02-28 15:28
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:28 UTC
Labels: bug
