### ISSUE TITLE
Is logical deletion currently supported?

### ISSUE THREAD

**Issue by nyingping** [ververica/flink-cdc-connectors#1314] opened 2022-06-24 08:25 UTC
**Is your feature request related to a problem? Please describe.**
Some tables are designed for logical deletion rather than physical deletion, such as a state field where 0 indicates deletion and 1 indicates not deletion.

**Describe alternatives you've considered**

Is it possible to pass the parameter to changelog and get `-D` instead of `+U` on logical deletion?

**Comment by gong** [comment] 2022-06-26 09:24
Maybe, you can filter deleted data if you want to remove deleted data.

**Comment by PatrickRen** [comment] 2024-02-28 15:06
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:06 UTC
Labels: enhancement
