### ISSUE TITLE
Close connection in jobmanager to MySQL after it assigned splits.

### ISSUE THREAD

**Issue by pensz** [ververica/flink-cdc-connectors#1015] opened 2022-03-28 07:15 UTC
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when too many connections from CDC.

When I check the connections from CDC, I find that JobManger remains connected to MySQL even after splits are assigned.

**Describe the solution you'd like**

Can JobManger close the connection to MySQL after split assignment?

**Describe alternatives you've considered**

**Comment by pensz** [comment] 2022-03-28 09:53
BTW

It seems that every Flink CDC table have two connections to MySQL while one is in "Sleep" state and another in "Binlog Dump" state.

Can Flink CDC table shares connection in taskmanager?

**Comment by PatrickRen** [comment] 2024-02-28 15:31
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:31 UTC
Labels: enhancement
