### ISSUE TITLE
tidb-cdc-connector 组件有考虑service GC safepoint吗

### ISSUE THREAD

**Issue by SoulSong** [ververica/flink-cdc-connectors#1593] opened 2022-09-29 03:28 UTC
tidb-cdc-connector 组件有考虑service GC safepoint吗？如果不考虑，怎会在任务中断的情况下，由于tikv的gc导致数据丢失。

**Comment by PatrickRen** [comment] 2024-02-28 15:28
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:28 UTC
Labels: enhancement
