### ISSUE TITLE
Flink  PostgreSql  cdc 报 PSQLException: 错误: 内存用尽

### ISSUE THREAD

**Issue by William-Kaiser** [ververica/flink-cdc-connectors#113] opened 2021-03-02 11:14 UTC
使用flink sql cdc 同步数据库两张表到ES，tm的内存是8G，jm的内存是4G，报错内容:
Caused by: org.postgresql.util.PSQLException: 错误: 内存用尽
  Detail: 无法为包含1073741301字节的字符串缓冲区扩大1416个更多字节.
  Where: 槽 "dbd_xxx", 输出插件 "wal2json", 在 change 回调, 关联的 LSN 地址为300/659E0A18

**Comment by PatrickRen** [comment] 2024-02-28 15:41
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:41 UTC
Labels: bug, enhancement
