### ISSUE TITLE
NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper

### ISSUE THREAD

**Issue by abovegrd** [ververica/flink-cdc-connectors#867] opened 2022-02-18 08:07 UTC
**Describe the bug**
Flink-1.13.5版本, 从MySQL同步数据到Kafka中, 执行insert语句时报错.

![lQLPDhspcLYTufzNAuLNBMCwFfVwvf89EX8CFJGm7sDuAA_1216_738](https://user-images.githubusercontent.com/9048966/154642827-9893d5db-9883-4fef-b1da-61a76665d1f3.png)

![lQLPDhspcMMwqNjNAY7NAtewFXd0OrQpY8wCFJG8bMCiAA_727_398](https://user-images.githubusercontent.com/9048966/154642961-d0eeeb72-f74b-48c3-9409-6ffcb2d49e46.png)

**Comment by abovegrd** [comment] 2022-02-18 08:34
![image](https://user-images.githubusercontent.com/9048966/154645861-4df6567f-8ee0-4650-8830-3aba05f8ce0d.png)

把changelog包更新成新版本后,仍然存在该问题.

**Comment by abovegrd** [comment] 2022-02-18 12:57
已经解决.
移除了flink-connect-kafka 和 flink-connect-mysql-cdc 两个jar包, 避免了冲突.

![image](https://user-images.githubusercontent.com/9048966/154686344-a14cee59-e623-46b9-8b23-9697a6cc8913.png)

**Comment by PatrickRen** [comment] 2024-02-28 15:09
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:10 UTC
Labels: bug
