### ISSUE TITLE
mysql-cdc采用DataStream Api方式 如何获取DDL语句呢？

### ISSUE THREAD

**Issue by jazzyMin** [ververica/flink-cdc-connectors#236] opened 2021-07-07 02:18 UTC
flink DataStream API how to get ddl ？

**Comment by fsk119** [comment] 2021-07-12 02:57
获取 ddl 是为了什么呢？

**Comment by PatrickRen** [comment] 2024-02-28 15:13
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:13 UTC
Labels: question
