### ISSUE TITLE
[Oracle CDC Connector]There is a probability that the flashback query fails, resulting in the failure of creating a snapshot

### ISSUE THREAD

**Issue by MaoHJ-Official** [ververica/flink-cdc-connectors#1165] opened 2022-05-10 06:44 UTC
**Describe the bug(Please use English)**
Debezium Connector for Oracle uses flashback query to create initial snapshot, but the flashback query has a certain probability of failure, such as when the undo log is overwritten. When synchronizing big tables, the failure probability will increase greatly.

**Environment :**
 - Flink version :  1.14.4
 - Flink CDC version: 2.2.0
 - Database and version: oracle 12

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :

**Additional Description**

**Comment by molsionmo** [comment] 2022-05-21 14:38
@MaoHJ-Official Could you try to config some log cleanup strategies to prune useless log periodically?

**Comment by PatrickRen** [comment] 2024-02-28 15:39
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:39 UTC
Labels: bug
