### ISSUE TITLE
时区问题

### ISSUE THREAD

**Issue by moonService** [ververica/flink-cdc-connectors#1671] opened 2022-10-28 06:35 UTC
在MySQL CDC FAQ中第2条描述的情况(数据比库中快8h)下通过其提供的两条建议实践后均不可行。
1.设置server-time-zone在MySqlSource中设置该值时，如果数据库是CST，设置UTC+8会快8小时，设置UTC会报错：org.apache.flink.table.api.ValidationException: The MySQL server has a timezone offset (28800 seconds ahead of UTC) which does not match the configured timezone UTC. Specify the right server-time-zone to avoid inconsistencies for time-related fields.

2.自定义Converter会报错：org.apache.kafka.connect.data.SchemaBuilder cannot be cast to com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.data.SchemaBuilder

**Comment by ruanhang1993** [comment] 2022-10-31 03:39
@moonService 
1. The configuration 'server-time-zone' should be the same as the time zone setting in the MySQL server.
2. The cdc connector has shaded some dependencies. Please take a look at the pom.xml in the module flink-sql-connector-mysql-cdc. If you need use these classes, maybe you should use the shaded class path.

**Comment by moonService** [comment] 2022-11-03 01:55
@ruanhang1993 设置CTS也会报错

**Comment by moonService** [comment] 2022-11-03 02:21
@ruanhang1993 数据库是CTS的情况下，'server-time-zone' 应该设置什么？设置CTS会报错没有此时间ID，设置UT会报错，设置UT+8数据时间会快8h，设置UTC会报错，设置UTC+8数据时间也会快8h，那请问how to configure this option to meet the conditions you mentioned ‘The configuration 'server-time-zone' should be the same as the time zone setting in the MySQL server’

**Comment by gefulai** [comment] 2024-01-13 12:09
> @ruanhang1993 设置CTS也会报错

server-time-zone: 'Asia/Shanghai'

**Comment by PatrickRen** [comment] 2024-02-28 15:02
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:02 UTC
Labels: bug
