### ISSUE TITLE
Log MySQL server information when startup

### ISSUE THREAD

**Issue by wuchong** [ververica/flink-cdc-connectors#1093] opened 2022-04-20 09:14 UTC
Currently, the mysql-cdc connector doesn't print the server information (e.g. version, binlog_format) which is very useful when debugging. We can print them like how debezium does.

```
2022-04-20 16:05:23,332 INFO  io.debezium.connector.common.BaseSourceTask                  [] - Starting MySqlConnectorTask with configuration:
2022-04-20 16:05:23,333 INFO  io.debezium.connector.common.BaseSourceTask                  [] -    connector.class = io.debezium.connector.mysql.MySqlConnector
2022-04-20 16:05:23,333 INFO  io.debezium.connector.common.BaseSourceTask                  [] -    database.user = root
2022-04-20 16:05:23,333 INFO  io.debezium.connector.common.BaseSourceTask                  [] -    bigint.unsigned.handling.mode = precise
2022-04-20 16:05:23,333 INFO  io.debezium.connector.common.BaseSourceTask                  [] -    offset.storage = com.ververica.cdc.debezium.internal.FlinkOffsetBackingStore
2022-04-20 16:05:23,333 INFO  io.debezium.connector.common.BaseSourceTask                  [] -    database.server.name = mysql_binlog_source
2022-04-20 16:05:23,333 INFO  io.debezium.connector.common.BaseSourceTask                  [] -    include.schema.changes = false
2022-04-20 16:05:23,333 INFO  io.debezium.connector.common.BaseSourceTask                  [] -    database.port = 3306
2022-04-20 16:05:23,333 INFO  io.debezium.connector.common.BaseSourceTask                  [] -    table.whitelist = mydb.products
2022-04-20 16:05:23,333 INFO  io.debezium.connector.common.BaseSourceTask                  [] -    offset.flush.interval.ms = 9223372036854775807
2022-04-20 16:05:23,333 INFO  io.debezium.connector.common.BaseSourceTask                  [] -    tombstones.on.delete = false
2022-04-20 16:05:23,333 INFO  io.debezium.connector.common.BaseSourceTask                  [] -    database.serverTimezone = UTC
2022-04-20 16:05:23,333 INFO  io.debezium.connector.common.BaseSourceTask                  [] -    database.hostname = localhost
2022-04-20 16:05:23,333 INFO  io.debezium.connector.common.BaseSourceTask                  [] -    database.password = ********
2022-04-20 16:05:23,334 INFO  io.debezium.connector.common.BaseSourceTask                  [] -    name = engine
2022-04-20 16:05:23,334 INFO  io.debezium.connector.common.BaseSourceTask                  [] -    database.history.skip.unparseable.ddl = true
2022-04-20 16:05:23,334 INFO  io.debezium.connector.common.BaseSourceTask                  [] -    database.whitelist = mydb
2022-04-20 16:05:23,334 INFO  io.debezium.connector.common.BaseSourceTask                  [] -    database.history.instance.name = 2e0f880c-324a-4705-ba71-02220b6a7b72
2022-04-20 16:05:23,334 INFO  io.debezium.connector.common.BaseSourceTask                  [] -    snapshot.mode = initial
2022-04-20 16:05:23,334 INFO  io.debezium.connector.common.BaseSourceTask                  [] -    database.history = com.ververica.cdc.debezium.internal.FlinkDatabaseSchemaHistory
2022-04-20 16:05:23,403 INFO  io.debezium.connector.mysql.MySqlConnectorTask               [] - No previous offset found
2022-04-20 16:05:23,470 INFO  io.debezium.connector.mysql.MySqlConnectorTask               [] - Connector started for the first time, database history recovery will not be executed
2022-04-20 16:05:23,506 INFO  io.debezium.util.Threads                                     [] - Requested thread factory for connector MySqlConnector, id = mysql_binlog_source named = change-event-source-coordinator
2022-04-20 16:05:23,507 INFO  io.debezium.util.Threads                                     [] - Creating thread debezium-mysqlconnector-mysql_binlog_source-change-event-source-coordinator
2022-04-20 16:05:23,509 INFO  io.debezium.pipeline.ChangeEventSourceCoordinator            [] - Metrics registered
2022-04-20 16:05:23,509 INFO  io.debezium.pipeline.ChangeEventSourceCoordinator            [] - Context created
2022-04-20 16:05:23,514 INFO  io.debezium.connector.mysql.MySqlSnapshotChangeEventSource   [] - No previous offset has been found
2022-04-20 16:05:23,514 INFO  io.debezium.connector.mysql.MySqlSnapshotChangeEventSource   [] - According to the connector configuration both schema and data will be snapshotted
2022-04-20 16:05:23,514 INFO  io.debezium.relational.RelationalSnapshotChangeEventSource   [] - Snapshot step 1 - Preparing
2022-04-20 16:05:23,517 INFO  io.debezium.relational.RelationalSnapshotChangeEventSource   [] - Snapshot step 2 - Determining captured tables
2022-04-20 16:05:23,517 INFO  io.debezium.connector.mysql.MySqlSnapshotChangeEventSource   [] - Read list of available databases
2022-04-20 16:05:23,519 INFO  io.debezium.connector.mysql.MySqlSnapshotChangeEventSource   [] - 	 list of available databases is: [information_schema, inventory, mysql, performance_schema, sys]
2022-04-20 16:05:23,519 INFO  io.debezium.connector.mysql.MySqlSnapshotChangeEventSource   [] - Read list of available tables in each database
2022-04-20 16:05:23,578 INFO  io.debezium.connector.mysql.MySqlSnapshotChangeEventSource   [] - 	snapshot continuing with database(s): []
2022-04-20 16:05:23,581 INFO  io.debezium.relational.RelationalSnapshotChangeEventSource   [] - Snapshot step 3 - Locking captured tables []
2022-04-20 16:05:23,587 INFO  io.debezium.connector.mysql.MySqlSnapshotChangeEventSource   [] - Flush and obtain global read lock to prevent writes to database
2022-04-20 16:05:23,592 INFO  io.debezium.relational.RelationalSnapshotChangeEventSource   [] - Snapshot step 4 - Determining snapshot offset
2022-04-20 16:05:23,594 INFO  io.debezium.connector.mysql.MySqlSnapshotChangeEventSource   [] - Read binlog position of MySQL primary server
2022-04-20 16:05:23,596 INFO  io.debezium.connector.mysql.MySqlSnapshotChangeEventSource   [] - 	 using binlog 'mysql-bin.000004' at position '154' and gtid ''
```

**Comment by PatrickRen** [comment] 2024-02-28 15:08
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:08 UTC
Labels: enhancement
