### ISSUE TITLE
Improve MySqlSourceITCase

### ISSUE THREAD

**Issue by zhjwpku** [ververica/flink-cdc-connectors#1029] opened 2022-03-31 02:39 UTC
**Is your feature request related to a problem? Please describe.**
In current MySqlSourceITCase test frame work, Failover in Snapshot phase can
not be guaranteed to triggered exactly in Snapshot phase, most of the time the
failover happened after Snapshot phase has finished.

**Describe the solution you'd like**
maybe expose some `VisibleForTesting` in the Classes to be test so that we can
take full control of their behavior.

**Comment by PatrickRen** [comment] 2024-02-28 15:37
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:37 UTC
Labels: enhancement
