### ISSUE TITLE
postgres@13.4的版本是不是无法使用flink-cdc?

### ISSUE THREAD

**Issue by cha1Yi** [ververica/flink-cdc-connectors#321] opened 2021-08-16 09:09 UTC
我在使用postgres 13.4的版本（目前是最新的版本），使用flink的postgres-cdc无法获取wal日志信息。
`final Log log = LogFactory.getLog(PostgresCDC.class);
        final StreamExecutionEnvironment executionEnvironment = StreamExecutionEnvironment.createLocalEnvironment();
        executionEnvironment.setParallelism(1);

        final Properties properties = new Properties();
        properties.setProperty("heartbeat.interval.ms", "10000");
        final DebeziumSourceFunction<String> debeziumSourceFunction = PostgreSQLSource.<String>builder()
                .hostname("127.0.0.1")
                .port(15432)
                .database("test")
                .schemaList("public")
                .tableList("pg_cdc_source")
                .username("test")
                .password("ch199407")
                .decodingPluginName("pgoutput")
                .debeziumProperties(properties)
                .deserializer(new StringDebeziumDeserializationSchema() {
                    @Override
                    public void deserialize(SourceRecord record, Collector<String> out) throws Exception {
                        log.info(record);
                        log.info(out);
                        super.deserialize(record, out);
                    }
                })
                .build();

        executionEnvironment.addSource(debeziumSourceFunction).print();
        executionEnvironment.execute("postgres cdc");

`

flink-cdc的版本
`        <dependency>
            <groupId>com.alibaba.ververica</groupId>
            <artifactId>flink-connector-postgres-cdc</artifactId>
            <version>1.2.0</version>
        </dependency>
`
部分日志
`16:55:57.977 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "column.whitelist" is deprecated and will be removed in future versions. Please use "column.include.list" instead.
16:55:57.977 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "column.blacklist" is deprecated and will be removed in future versions. Please use "column.exclude.list" instead.
16:55:57.977 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "column.whitelist" is deprecated and will be removed in future versions. Please use "column.include.list" instead.
16:55:57.977 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "column.blacklist" is deprecated and will be removed in future versions. Please use "column.exclude.list" instead.
16:55:57.978 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "column.whitelist" is deprecated and will be removed in future versions. Please use "column.include.list" instead.
16:55:57.978 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "column.blacklist" is deprecated and will be removed in future versions. Please use "column.exclude.list" instead.
16:55:57.978 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "column.whitelist" is deprecated and will be removed in future versions. Please use "column.include.list" instead.
16:55:57.978 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "column.blacklist" is deprecated and will be removed in future versions. Please use "column.exclude.list" instead.
16:55:57.983 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "table.whitelist" is deprecated and will be removed in future versions. Please use "table.include.list" instead.
16:55:57.983 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "table.blacklist" is deprecated and will be removed in future versions. Please use "table.exclude.list" instead.
16:55:57.984 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "table.whitelist" is deprecated and will be removed in future versions. Please use "table.include.list" instead.
16:55:57.984 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "table.blacklist" is deprecated and will be removed in future versions. Please use "table.exclude.list" instead.
16:55:57.984 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "schema.whitelist" is deprecated and will be removed in future versions. Please use "schema.include.list" instead.
16:55:57.984 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "schema.blacklist" is deprecated and will be removed in future versions. Please use "schema.exclude.list" instead.
16:55:57.984 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "schema.whitelist" is deprecated and will be removed in future versions. Please use "schema.include.list" instead.
16:55:57.984 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "schema.blacklist" is deprecated and will be removed in future versions. Please use "schema.exclude.list" instead.
16:55:57.984 [debezium-engine] INFO  i.d.connector.common.BaseSourceTask - Starting PostgresConnectorTask with configuration:
16:55:57.985 [debezium-engine] INFO  i.d.connector.common.BaseSourceTask -    connector.class = io.debezium.connector.postgresql.PostgresConnector
16:55:57.985 [debezium-engine] INFO  i.d.connector.common.BaseSourceTask -    database.user = test
16:55:57.985 [debezium-engine] INFO  i.d.connector.common.BaseSourceTask -    database.dbname = test
16:55:57.985 [debezium-engine] INFO  i.d.connector.common.BaseSourceTask -    offset.storage = com.alibaba.ververica.cdc.debezium.internal.FlinkOffsetBackingStore
16:55:57.985 [debezium-engine] INFO  i.d.connector.common.BaseSourceTask -    slot.name = flink
16:55:57.985 [debezium-engine] INFO  i.d.connector.common.BaseSourceTask -    database.server.name = postgres_cdc_source
16:55:57.986 [debezium-engine] INFO  i.d.connector.common.BaseSourceTask -    heartbeat.interval.ms = 10000
16:55:57.986 [debezium-engine] INFO  i.d.connector.common.BaseSourceTask -    include.schema.changes = false
16:55:57.986 [debezium-engine] INFO  i.d.connector.common.BaseSourceTask -    database.port = 15432
16:55:57.986 [debezium-engine] INFO  i.d.connector.common.BaseSourceTask -    plugin.name = pgoutput
16:55:57.986 [debezium-engine] INFO  i.d.connector.common.BaseSourceTask -    schema.whitelist = public
16:55:57.986 [debezium-engine] INFO  i.d.connector.common.BaseSourceTask -    table.whitelist = pg_cdc_source
16:55:57.986 [debezium-engine] INFO  i.d.connector.common.BaseSourceTask -    offset.flush.interval.ms = 9223372036854775807
16:55:57.986 [debezium-engine] INFO  i.d.connector.common.BaseSourceTask -    key.converter.schemas.enable = false
16:55:57.986 [debezium-engine] INFO  i.d.connector.common.BaseSourceTask -    tombstones.on.delete = false
16:55:57.986 [debezium-engine] INFO  i.d.connector.common.BaseSourceTask -    database.hostname = 127.0.0.1
16:55:57.986 [debezium-engine] INFO  i.d.connector.common.BaseSourceTask -    database.password = ********
16:55:57.986 [debezium-engine] INFO  i.d.connector.common.BaseSourceTask -    value.converter.schemas.enable = false
16:55:57.986 [debezium-engine] INFO  i.d.connector.common.BaseSourceTask -    name = engine
16:55:57.986 [debezium-engine] INFO  i.d.connector.common.BaseSourceTask -    database.history.instance.name = 4555c471-6f26-40a2-886b-2d1d9fab7701
16:55:57.986 [debezium-engine] INFO  i.d.connector.common.BaseSourceTask -    database.history = com.alibaba.ververica.cdc.debezium.internal.FlinkDatabaseHistory
16:55:57.998 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "schema.whitelist" is deprecated and will be removed in future versions. Please use "schema.include.list" instead.
16:55:58.000 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "schema.blacklist" is deprecated and will be removed in future versions. Please use "schema.exclude.list" instead.
16:55:58.000 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "table.whitelist" is deprecated and will be removed in future versions. Please use "table.include.list" instead.
16:55:58.000 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "table.blacklist" is deprecated and will be removed in future versions. Please use "table.exclude.list" instead.
16:55:58.001 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "column.blacklist" is deprecated and will be removed in future versions. Please use "column.exclude.list" instead.
16:55:58.137 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "schema.blacklist" is deprecated and will be removed in future versions. Please use "schema.exclude.list" instead.
16:55:58.137 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "table.blacklist" is deprecated and will be removed in future versions. Please use "table.exclude.list" instead.
16:55:58.137 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "table.whitelist" is deprecated and will be removed in future versions. Please use "table.include.list" instead.
16:55:58.138 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "schema.whitelist" is deprecated and will be removed in future versions. Please use "schema.include.list" instead.
16:55:58.139 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "column.whitelist" is deprecated and will be removed in future versions. Please use "column.include.list" instead.
16:55:58.139 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "column.blacklist" is deprecated and will be removed in future versions. Please use "column.exclude.list" instead.
16:55:58.140 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "schema.blacklist" is deprecated and will be removed in future versions. Please use "schema.exclude.list" instead.
16:55:58.140 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "table.blacklist" is deprecated and will be removed in future versions. Please use "table.exclude.list" instead.
16:55:58.141 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "table.whitelist" is deprecated and will be removed in future versions. Please use "table.include.list" instead.
16:55:58.141 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "schema.whitelist" is deprecated and will be removed in future versions. Please use "schema.include.list" instead.
16:55:58.141 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "column.whitelist" is deprecated and will be removed in future versions. Please use "column.include.list" instead.
16:55:58.141 [debezium-engine] WARN  io.debezium.config.Configuration - Using configuration property "column.blacklist" is deprecated and will be removed in future versions. Please use "column.exclude.list" instead.
16:55:58.180 [debezium-engine] INFO  i.d.c.p.PostgresConnectorTask - user 'test' connected to database 'test' on PostgreSQL 13.4 on x86_64-apple-darwin20.4.0, compiled by Apple clang version 12.0.5 (clang-1205.0.22.9), 64-bit with roles:
	role 'test' [superuser: false, replication: true, inherit: true, create role: false, create db: false, can log in: true]
16:55:58.184 [debezium-engine] INFO  i.d.c.p.c.PostgresConnection - Obtained valid replication slot ReplicationSlot [active=false, latestFlushedLsn=LSN{0/16C3518}, catalogXmin=548]
16:55:58.184 [debezium-engine] INFO  i.d.c.p.PostgresConnectorTask - No previous offset found
16:55:58.184 [debezium-engine] INFO  i.d.c.p.snapshot.InitialSnapshotter - Taking initial snapshot for new datasource
16:55:58.205 [debezium-engine] INFO  io.debezium.util.Threads - Requested thread factory for connector PostgresConnector, id = postgres_cdc_source named = change-event-source-coordinator
16:55:58.209 [debezium-engine] INFO  io.debezium.util.Threads - Creating thread debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator
16:55:58.211 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO  i.d.p.ChangeEventSourceCoordinator - Metrics registered
16:55:58.212 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO  i.d.p.ChangeEventSourceCoordinator - Context created
16:55:58.215 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO  i.d.c.p.snapshot.InitialSnapshotter - Taking initial snapshot for new datasource
16:55:58.215 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO  i.d.c.p.PostgresSnapshotChangeEventSource - According to the connector configuration data will be snapshotted
16:55:58.216 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO  i.d.r.RelationalSnapshotChangeEventSource - Snapshot step 1 - Preparing
16:55:58.271 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO  i.d.r.RelationalSnapshotChangeEventSource - Snapshot step 2 - Determining captured tables
16:55:58.274 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] WARN  io.debezium.config.Configuration - Using configuration property "table.whitelist" is deprecated and will be removed in future versions. Please use "table.include.list" instead.
16:55:58.275 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO  i.d.r.RelationalSnapshotChangeEventSource - Snapshot step 3 - Locking captured tables []
16:55:58.276 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO  i.d.c.p.PostgresSnapshotChangeEventSource - Waiting a maximum of '10' seconds for each table lock
16:55:58.297 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO  i.d.r.RelationalSnapshotChangeEventSource - Snapshot step 4 - Determining snapshot offset
16:55:58.299 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO  i.d.c.p.PostgresSnapshotChangeEventSource - Creating initial offset context
16:55:58.301 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO  i.d.c.p.PostgresSnapshotChangeEventSource - Read xlogStart at 'LSN{0/16DECB0}' from transaction '555'
16:55:58.302 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO  i.d.c.p.PostgresSnapshotChangeEventSource - Read xlogStart at 'LSN{0/16DECB0}' from transaction '555'
16:55:58.303 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO  i.d.r.RelationalSnapshotChangeEventSource - Snapshot step 5 - Reading structure of captured tables
16:55:58.324 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO  i.d.r.RelationalSnapshotChangeEventSource - Snapshot step 6 - Persisting schema history
16:55:58.324 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO  i.d.r.RelationalSnapshotChangeEventSource - Snapshot step 7 - Snapshotting data
16:55:58.328 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO  i.d.p.s.AbstractSnapshotChangeEventSource - Snapshot - Final stage
16:55:58.328 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO  i.d.p.ChangeEventSourceCoordinator - Snapshot ended with SnapshotResult [status=COMPLETED, offset=PostgresOffsetContext [sourceInfoSchema=Schema{io.debezium.connector.postgresql.Source:STRUCT}, sourceInfo=source_info[server='postgres_cdc_source'db='test', lsn=LSN{0/16DECB0}, txId=555, timestamp=2021-08-16T08:55:58.303Z, snapshot=FALSE], partition={server=postgres_cdc_source}, lastSnapshotRecord=true, lastCompletelyProcessedLsn=null, lastCommitLsn=null, transactionContext=TransactionContext [currentTransactionId=null, perTableEventCount={}, totalEventCount=0]]]
16:55:58.329 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] WARN  i.d.r.RelationalDatabaseSchema - After applying the include/exclude list filters, no changes will be captured. Please check your configuration!
16:55:58.331 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO  i.d.p.m.StreamingChangeEventSourceMetrics - Connected metrics set to 'true'
16:55:58.332 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO  i.d.p.ChangeEventSourceCoordinator - Starting streaming
16:55:58.332 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO  i.d.c.p.PostgresStreamingChangeEventSource - Retrieved latest position from stored offset 'LSN{0/16DECB0}'
16:55:58.332 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO  i.d.c.p.c.WalPositionLocator - Looking for WAL restart position for last commit LSN 'null' and last change LSN 'LSN{0/16DECB0}'
16:55:58.333 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO  i.d.c.p.c.PostgresReplicationConnection - Initializing PgOutput logical decoder publication
16:55:58.348 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO  i.d.c.p.c.PostgresConnection - Obtained valid replication slot ReplicationSlot [active=false, latestFlushedLsn=LSN{0/16C3518}, catalogXmin=548]
16:55:58.351 [pool-3-thread-1] INFO  io.debezium.jdbc.JdbcConnection - Connection gracefully closed
16:55:58.398 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO  i.d.c.p.PostgresStreamingChangeEventSource - Searching for WAL resume position
16:56:28.496 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO  i.d.c.p.c.WalPositionLocator - First LSN 'LSN{0/16DED10}' received
16:56:28.496 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO  i.d.c.p.PostgresStreamingChangeEventSource - WAL resume position 'LSN{0/16DED10}' discovered
16:56:28.497 [pool-5-thread-1] INFO  io.debezium.jdbc.JdbcConnection - Connection gracefully closed
16:56:28.502 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO  i.d.c.p.c.PostgresReplicationConnection - Initializing PgOutput logical decoder publication
16:56:28.515 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO  i.d.c.p.PostgresStreamingChangeEventSource - Processing messages
16:56:28.516 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] INFO  i.d.c.p.c.WalPositionLocator - Message with LSN 'LSN{0/16DED10}' arrived, switching off the filtering
16:56:28.529 [debezium-postgresconnector-postgres_cdc_source-change-event-source-coordinator] WARN  i.d.c.p.c.p.PgOutputMessageDecoder - Primary keys are not defined for table 'pg_cdc_source', defaulting to unique indices
16:56:28.535 [pool-7-thread-1] INFO  io.debezium.jdbc.JdbcConnection - Connection gracefully closed`

**Comment by xiangtao** [comment] 2021-08-18 07:25
not support . 
support version as ablove: 
![image](https://user-images.githubusercontent.com/2025439/129855935-688a0067-4c0c-49ee-bf10-f09853c753f2.png)

**Comment by PatrickRen** [comment] 2024-02-28 15:40
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:40 UTC
Labels: question
