### ISSUE TITLE
Do you not support the AriCloud database?

### ISSUE THREAD

**Issue by laizhouzhang** [ververica/flink-cdc-connectors#155] opened 2021-04-10 02:10 UTC
AliCloud RDS not support

**Comment by wuchong** [comment] 2021-04-29 07:55
RDS for MySQL or Postgres is supported.

**Comment by PatrickRen** [comment] 2024-02-28 15:15
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:15 UTC
Labels: discussion
