### ISSUE TITLE
The db history topic or its content is fully or partially missing.Please check database history topic configuration and re-execute the snapshot.

### ISSUE THREAD

**Issue by peigenxiao** [ververica/flink-cdc-connectors#326] opened 2021-08-17 10:13 UTC
I have 2 cdc-tables to calculate，but I have a problem
envs:  flink1.13.2  +  flinkclient + yarnsession

### flinkSQL
CREATE TABLE SFY_LIVE_ACT_EMPLOY (
    id int,
    live_id int,
    openid string,
    dealer_code string,
    deleted_at string,
 primary key (id) not enforced
)WITH (
    'connector' = 'mysql-cdc', -- 连接器
    'hostname' = 'xxx',   --mysql地址
    'port' = '3306',  -- mysql端口
    'username' = 'xxx',  --mysql用户名
    'password' = 'xxx',  -- mysql密码
    'database-name' = 'xxx', --  数据库名称
    'table-name' = 'xxx'
);

CREATE TABLE SFY_LIVE_SHARE_RELATION (
                                     id int,
                                     fans_openid string,
                                     employ_openid string,
                                     live_id int,
                                     primary key (id) not enforced
)WITH (
    'connector' = 'mysql-cdc', -- 连接器
    'hostname' = 'xxx',   --mysql地址
    'port' = '3306',  -- mysql端口
    'username' = 'xxx',  --mysql用户名
    'password' = 'xxx',  -- mysql密码
    'database-name' = 'xxx', --  数据库名称
    'table-name' = 'xxx'
);

create view SFY_LIVE_SHARE_RELATION_VIEW as
SELECT
    COUNT(DISTINCT (r.fans_openid)) AS su_multi,
    r.employ_openid AS employ_openid,
    r.live_id AS live_id
FROM
    SFY_LIVE_SHARE_RELATION AS r
GROUP BY
    r.employ_openid,
    r.live_id;

SELECT
    d.su_multi,
    cast(e.id as STRING),
    e.live_id,
    e.openid,
    e.dealer_code,
    e.deleted_at
FROM
    SFY_LIVE_ACT_EMPLOY AS e
        LEFT JOIN SFY_LIVE_SHARE_RELATION_VIEW AS d ON
                d.employ_openid = e.openid
            AND d.live_id = e.live_id
WHERE
    e.deleted_at IS NULL;

### here are flink Exceptions logs;
Caused by: java.lang.RuntimeException: One or more fetchers have encountered exception
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcherManager.checkErrors(SplitFetcherManager.java:199)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.getNextFetch(SourceReaderBase.java:154)
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:116)
	at org.apache.flink.streaming.api.operators.SourceOperator.emitNext(SourceOperator.java:294)
	at org.apache.flink.streaming.runtime.io.StreamTaskSourceInput.emitNext(StreamTaskSourceInput.java:69)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:66)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:423)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:204)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:681)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.executeInvoke(StreamTask.java:636)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runWithCleanUpOnFail(StreamTask.java:647)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:620)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:779)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:566)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: SplitFetcher thread 0 received unexpected exception while polling the records
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:146)
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:101)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
Caused by: io.debezium.DebeziumException: The db history topic or its content is fully or partially missing. Please check database history topic configuration and re-execute the snapshot.
	at io.debezium.relational.HistorizedRelationalDatabaseSchema.recover(HistorizedRelationalDatabaseSchema.java:47)
	at com.ververica.cdc.connectors.mysql.debezium.task.context.StatefulTaskContext.validateAndLoadDatabaseHistory(StatefulTaskContext.java:173)
	at com.ververica.cdc.connectors.mysql.debezium.task.context.StatefulTaskContext.configure(StatefulTaskContext.java:125)
	at com.ververica.cdc.connectors.mysql.debezium.reader.SnapshotSplitReader.submitSplit(SnapshotSplitReader.java:91)
	at com.ververica.cdc.connectors.mysql.debezium.reader.SnapshotSplitReader.submitSplit(SnapshotSplitReader.java:62)
	at com.ververica.cdc.connectors.mysql.source.reader.MySqlSplitReader.checkSplitOrStartNext(MySqlSplitReader.java:143)
	at com.ververica.cdc.connectors.mysql.source.reader.MySqlSplitReader.fetch(MySqlSplitReader.java:69)
	at org.apache.flink.connector.base.source.reader.fetcher.FetchTask.run(FetchTask.java:56)
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:138)
	... 6 more

**Comment by fsk119** [comment] 2021-08-18 09:46
Which cdc connector version do you use?  Are you restart from the checkpoint?  Does the database have the expected table before?

**Comment by peigenxiao** [comment] 2021-08-20 07:09
> Which cdc connector version do you use? Are you restart from the checkpoint? Does the database have the expected table before?

2.0 version   
no checkpoint set up
of course

**Comment by fsk119** [comment] 2021-08-20 09:07
It's very strange.. The excepton is thrown during the recover but your answer tells me you are not start the job from the checkpoint/savepoint. Could you share more details about how to reproduce this problems

**Comment by peigenxiao** [comment] 2021-08-20 10:15
![image](https://user-images.githubusercontent.com/20840982/130218501-50c41a04-f6a2-4b1c-b25a-b21aa53f5b63.png)
![image](https://user-images.githubusercontent.com/20840982/130218533-05b8fc63-cb6c-4e6e-9b01-871421b49374.png)
one step : start a yarn-session
two step :  bin/sql-client.sh embedded

**Comment by peigenxiao** [comment] 2021-08-20 10:16
three step : set two cdc-tables and one view
four step : select

**Comment by fsk119** [comment] 2021-08-20 10:32
Could you share the ddl of the source table?

**Comment by frey66** [comment] 2021-08-23 02:11
assigned me

**Comment by frey66** [comment] 2021-08-23 03:28
hi, could you share the ddl of source table? this exception is caused by the tableSchemas is empty

**Comment by leonardBang** [comment] 2021-08-25 03:57
Hi,@frey66
Because @Jiabao-Sun has kindly opened this PR，is it ok if I assign this ticket to him?

**Comment by frey66** [comment] 2021-08-25 07:05
> Hi,@frey66
> Because @Jiabao-Sun has kindly opened this PR，is it ok if I assign this ticket to him?

OK @leonardBang

**Closed** 2021-08-25 08:49 UTC
Labels: task
