### ISSUE TITLE
CDC sometimes stop synchronous data

### ISSUE THREAD

**Issue by lykpass** [ververica/flink-cdc-connectors#481] opened 2021-10-08 02:07 UTC
**Describe the bug**

**Environment :**
 - Flink version :  1.13.1
 - Flink CDC version: 1.14
 - Database and version: 5.6

Using CDC to synchronize data and flinksql for calculation, SQL is complex and involves many tables. Sometimes tables will stop during synchronization，but flink

this is the error

2021-10-08 09:34:59,774 ERROR io.debezium.connector.mysql.SnapshotReader                   [] - Failed due to error: Aborting snapshot due to error when last running 'select * from XXX where create_time >= "2021-09-01 00:00:00"': Stream
ing result set com.mysql.cj.protocol.a.result.ResultsetRowsStreaming@4d0a62b5 is still active. No statements may be issued when any streaming result sets are open and in use on a given connection. Ensure that you have called .close() on any active streamin
g result sets before attempting more queries.
org.apache.kafka.connect.errors.ConnectException: Streaming result set com.mysql.cj.protocol.a.result.ResultsetRowsStreaming@4d0a62b5 is still active. No statements may be issued when any streaming result sets are open and in use on a given connection. Ens
ure that you have called .close() on any active streaming result sets before attempting more queries. Error code: 0; SQLSTATE: S1000.
        at io.debezium.connector.mysql.AbstractReader.wrap(AbstractReader.java:241) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
        at io.debezium.connector.mysql.AbstractReader.failed(AbstractReader.java:218) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
        at io.debezium.connector.mysql.SnapshotReader.execute(SnapshotReader.java:857) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.sql.SQLException: Streaming result set com.mysql.cj.protocol.a.result.ResultsetRowsStreaming@4d0a62b5 is still active. No statements may be issued when any streaming result sets are open and in use on a given connection. Ensure that you hav
e called .close() on any active streaming result sets before attempting more queries.
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
        at com.mysql.cj.jdbc.ConnectionImpl.commit(ConnectionImpl.java:814) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
        at io.debezium.connector.mysql.SnapshotReader.execute(SnapshotReader.java:773) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
        ... 3 more

**Comment by lykpass** [comment] 2021-10-08 03:53
[https://github.com/ververica/flink-cdc-connectors/issues/57](url)

**Comment by PatrickRen** [comment] 2024-02-28 15:12
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:12 UTC
Labels: bug
