### ISSUE TITLE
Mysql DDl exception

### ISSUE THREAD

**Issue by xuhaiL** [ververica/flink-cdc-connectors#1422] opened 2022-07-27 12:15 UTC
I now use mysql cdc to create dataSource, after setting tableList, I can still capture ddl changes of other tables, I think this is a bug.

flink version 1.13
cdc version 2.2.1
mysql version 5.6

**Comment by xuhaiL** [comment] 2022-07-27 12:18
not in tableList，SourceRecord.sourceOffset.table is null

**Comment by PatrickRen** [comment] 2024-02-28 15:36
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:36 UTC
Labels: bug
