### ISSUE TITLE
java1.8.0_181 、flink1.13.1 、 flink-sql-connector-mysql-cdc-1.4.0 组合 cdc 失败

### ISSUE THREAD

**Issue by yandavid163** [ververica/flink-cdc-connectors#212] opened 2021-06-14 14:37 UTC
版本依赖：
flink： 1.13.1
mysql CDC：flink-sql-connector-mysql-cdc-1.4.0.jar

在 Flink SQL 创建表：
CREATE TABLE users (
  user_id BIGINT,
  user_name STRING,
  region STRING
) WITH (
  'connector' = 'mysql-cdc',
  'hostname' = '127.0.0.1',
  'port' = '3306',
  'database-name' = 'flink',
  'table-name' = 'users',
  'username' = 'root',
  'password' = 'root123'
);

执行 select * from users;

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.flink.api.java.ClosureCleaner (file:/usr/local/Cellar/apache-flink/1.13.1/libexec/lib/flink-dist_2.12-1.13.1.jar) to field java.lang.Class.ANNOTATION
WARNING: Please consider reporting this to the maintainers of org.apache.flink.api.java.ClosureCleaner
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

[ERROR] Could not execute SQL statement. Reason:
java.lang.NoSuchMethodError: 'void sun.misc.Unsafe.monitorEnter(java.lang.Object)'

查询日志：

2021-06-14 21:12:36,666 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - For table 'flink.users' using select statement: 'SELECT * FROM `flink`.`users`'
2021-06-14 21:12:36,672 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - Step 8: - Completed scanning a total of 3 rows from table 'flink.users' after 00:00:00.005
2021-06-14 21:12:36,672 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - Step 8: scanned 3 rows in 1 tables in 00:00:00.008
2021-06-14 21:12:36,672 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - Step 9: committing transaction
2021-06-14 21:12:36,673 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - Completed snapshot in 00:00:01.191
2021-06-14 21:12:36,683 INFO  io.debezium.jdbc.JdbcConnection                              [] - Connection gracefully closed
2021-06-14 21:12:36,942 INFO  io.debezium.connector.common.BaseSourceTask                  [] - Stopping down connector
2021-06-14 21:12:36,942 INFO  io.debezium.connector.mysql.MySqlConnectorTask               [] - Stopping MySQL connector task
2021-06-14 21:12:36,942 INFO  io.debezium.connector.mysql.ChainedReader                    [] - ChainedReader: Stopping the snapshot reader
2021-06-14 21:12:36,942 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - Discarding 0 unsent record(s) due to the connector shutting down
2021-06-14 21:12:36,943 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - Discarding 0 unsent record(s) due to the connector shutting down
2021-06-14 21:12:36,943 INFO  io.debezium.connector.mysql.MySqlConnectorTask               [] - Connector task finished all work and is now shutdown
2021-06-14 21:12:36,945 ERROR com.alibaba.ververica.cdc.debezium.DebeziumSourceFunction    [] - Reporting error:
java.lang.NoSuchMethodError: 'void sun.misc.Unsafe.monitorEnter(java.lang.Object)'
	at com.alibaba.ververica.cdc.debezium.internal.DebeziumChangeConsumer.handleBatch(DebeziumChangeConsumer.java:154) ~[flink-sql-connector-mysql-cdc-1.4.0.jar:1.4.0]
	at io.debezium.embedded.ConvertingEngineBuilder.lambda$notifying$2(ConvertingEngineBuilder.java:82) ~[flink-sql-connector-mysql-cdc-1.4.0.jar:1.4.0]
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:812) [flink-sql-connector-mysql-cdc-1.4.0.jar:1.4.0]
	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:171) [flink-sql-connector-mysql-cdc-1.4.0.jar:1.4.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by vampireDuke07** [comment] 2021-06-25 08:19
遇到同样的问题
flink：1.12.2
pg-connector：1.1.0

**Comment by shuitao** [comment] 2021-06-30 08:58
> 遇到同样的问题
> flink：1.12.2
> pg-connector：1.1.0

12.x 应该用1.2或者1.3的connector

**Comment by fsk119** [comment] 2021-07-12 11:51
可以试试最新的master， 这个 #194 应该解了。

**Comment by PatrickRen** [comment] 2024-02-28 15:13
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:13 UTC
Labels: discussion, fixed
