### ISSUE TITLE
support read all mysql database data with no schema restrict

### ISSUE THREAD

**Issue by EMsnap** [ververica/flink-cdc-connectors#1135] opened 2022-04-29 03:34 UTC
**Is your feature request related to a problem? Please describe.**

The thing is sometime user want to export all data from database with diffrent schema to kafka with canal json
This is something flinkcdc cannot do since we all need to specify the source shema when writing sql

**Describe the solution you'd like**

 1 The solution is that we can create a new DeserializationRuntimeConverter to convert all data into a Map<String, Object> where the key is column name and the value is the actual data.

 2 And modify MySqlReadableMetadata to extract the Map object and construct a canalJson object, then put all the fields canal need into a meta data called DATA.

 3 So user can use such below sql to realize the goal :   select data (string) from METADATA data, and then sink the data to kafka

**Describe alternatives you've considered**

I guess there are no alternative solutions if user want to use sql and flink to ahieve this.

**Comment by leonardBang** [comment] 2022-08-04 10:09
The solution looks a little weird, could you describe the user case more precise, It's great if you can put some sql or data . I don't understand the SQL `select data (string) from METADATA` 😶

**Comment by PatrickRen** [comment] 2024-02-28 15:07
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:07 UTC
Labels: enhancement
