### ISSUE TITLE
Potential transaction leak during MySQL snapshot phase

### ISSUE THREAD

**Issue by kylemeow** [ververica/flink-cdc-connectors#1552] opened 2022-09-13 07:01 UTC
**Describe the bug(Please use English)**
We have found that during the MySQL snapshot phase, a transaction is initiated but never committed, resulting in the transaction being left there for a long time. 

For instance, the binlog is like 

```
SET autocommit=0  // a transaction is started by com.ververica.cdc.connectors.mysql.source.utils.StatementUtils#initStatement

SELECT * FROM `database`.`table` WHERE id >= 1111 AND NOT (id = 2222) AND id <= 2222

SHOW MASTER STATUS

SHOW GLOBAL VARIABLES LIKE 'GTID_MODE'

SHOW MASTER STATUS

SELECT @@global.gtid_purged

rollback  // the transaction is aborted without a commit after a long wait
```

**Environment :**
 - Flink version :  1.13.6
 - Flink CDC version: 2.3
 - Database and version: MySQL 5.7

**To Reproduce**
1. The test data : Any MySQL database with existing data in the table
2. The test code : INSERT INTO any_sink SELECT * FROM mysql_cdc_source_table;
3. The error : A transaction is left without being committed.

From the code, maybe it is the `connection.setAutoCommit(false)` that causes this issue, but we are still not sure why it is there in the first place.
![image](https://user-images.githubusercontent.com/5620838/189831936-522c8ae7-a116-4948-8b5d-41b4d0eaab72.png)

**Comment by kylemeow** [comment] 2022-09-13 07:07
Hi @leonardBang , may I know if this is a bug or a feature? The uncommitted transaction is identified by our database monitoring system, but it seems not yet to have caused any explicit errors anyway.

**Comment by GOODBOY008** [comment] 2022-09-16 03:54
@kylemeow  I will try to reproduce on my local and confirm this issue.

**Comment by PatrickRen** [comment] 2024-02-28 15:03
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:03 UTC
Labels: bug
