### ISSUE TITLE
Flink SQL 读取Mysql binlog 报错 Can''t call rollback when autocommit=true

### ISSUE THREAD

**Issue by kimmazhenxin** [ververica/flink-cdc-connectors#79] opened 2020-12-28 08:37 UTC
使用Flink SQL 读取Mysql时，刚开始任务运行正常，过段时间就挂了，一直报下面这个错，请问在SQL的配置中有参数解决么？
2020-12-28 16:33:30.017 [debezium-engine] ERROR io.debezium.connector.mysql.SnapshotReader  - Unable to unregister the MBean 'debezium.mysql:type=connector-metrics,context=snapshot,server=mysql_binlog_source'
2020-12-28 16:33:30.017 [debezium-engine] ERROR io.debezium.connector.mysql.BinlogReader  - Unable to unregister the MBean 'debezium.mysql:type=connector-metrics,context=binlog,server=mysql_binlog_source'
2020-12-28 16:33:30.019 [Source: TableSourceScan(table=[[default_catalog, default_database, tb_order]], fields=[id, order_num, counter_code, num, price, user_id, trans_date, status, isactive, inserttime, updatetime, cost, domain_name, order_cabinet_id, order_group_id]) -> (Calc(select=[id, price, inserttime]), Calc(select=[id, counter_code])) (1/1)] INFO  io.debezium.embedded.EmbeddedEngine  - Stopping the embedded engine
2020-12-28 16:33:30.023 [debezium-mysqlconnector-mysql_binlog_source-snapshot] ERROR io.debezium.connector.mysql.SnapshotReader  - Failed due to error: Aborting snapshot due to error when last running 'SELECT * FROM `ods`.`tb_order`': Can''t call rollback when autocommit=true
org.apache.kafka.connect.errors.ConnectException: Can''t call rollback when autocommit=true Error code: 0; SQLSTATE: 08003.
	at io.debezium.connector.mysql.AbstractReader.wrap(AbstractReader.java:230)
	at io.debezium.connector.mysql.AbstractReader.failed(AbstractReader.java:207)
	at io.debezium.connector.mysql.SnapshotReader.execute(SnapshotReader.java:831)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLNonTransientConnectionException: Can''t call rollback when autocommit=true
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:1851)
	at io.debezium.connector.mysql.SnapshotReader.execute(SnapshotReader.java:740)
	... 3 common frames omitted

**Comment by chenxiaoliang0901** [comment] 2021-01-29 03:31
我也遇到了同样的问题，你解决了吗

**Comment by a626411464** [comment] 2021-02-03 03:18
> 我也遇到了同样的问题，你解决了吗

请问解决了吗

**Comment by chenxiaoliang0901** [comment] 2021-02-20 11:28
> > 我也遇到了同样的问题，你解决了吗
> 
> 请问解决了吗

我没解决呢，有人解决了没啊

**Comment by a626411464** [comment] 2021-02-20 11:38
> > > 我也遇到了同样的问题，你解决了吗
> > 
> > 
> > 请问解决了吗
> 
> 我没解决呢，有人解决了没啊

这个我是在数据入库之前就开启Flink任务就避免了

**Comment by chenxiaoliang0901** [comment] 2021-02-20 11:41
> > > > 我也遇到了同样的问题，你解决了吗
> > > 
> > > 
> > > 请问解决了吗
> > 
> > 
> > 我没解决呢，有人解决了没啊
> 
> 这个我是在数据入库之前就开启Flink任务就避免了

怎么提前开始Flink任务啊

**Comment by a626411464** [comment] 2021-02-20 11:44
> > > > > 我也遇到了同样的问题，你解决了吗
> > > > 
> > > > 
> > > > 请问解决了吗
> > > 
> > > 
> > > 我没解决呢，有人解决了没啊
> > 
> > 
> > 这个我是在数据入库之前就开启Flink任务就避免了
> 
> 怎么提前开始Flink任务啊

我是直接开启Flink任务之后，再开启数据采集任务

**Comment by chenxiaoliang0901** [comment] 2021-02-22 04:49
> > > > > > 我也遇到了同样的问题，你解决了吗
> > > > > 
> > > > > 
> > > > > 请问解决了吗
> > > > 
> > > > 
> > > > 我没解决呢，有人解决了没啊
> > > 
> > > 
> > > 这个我是在数据入库之前就开启Flink任务就避免了
> > 
> > 
> > 怎么提前开始Flink任务啊
> 
> 我是直接开启Flink任务之后，再开启数据采集任务

方便加个微信吗，我还没解决这个问题

**Comment by yaoboxu** [comment] 2021-04-30 00:50
我的任务也报这个错误了

**Comment by PatrickRen** [comment] 2024-02-28 15:41
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:41 UTC
Labels: question, discussion
