### ISSUE TITLE
postgres-cdc can not catch change data

### ISSUE THREAD

**Issue by JiangfeiLiu** [ververica/flink-cdc-connectors#1121] opened 2022-04-25 11:10 UTC
**Describe the bug(Please use English)**
datastream api and sql api in old database can not catch change data running a period of time
but,when i create new database,new table,can catch change data

**Environment :**
 - Flink version :  1.13.5
 - Flink CDC version: 2.1.0
 - Database and version: 11

**To Reproduce**
1. Thes test data :
3. The test code :
'connector' = 'postgres-cdc',
'hostname' = 'xxx.xxx.xxx.xxx',
'port' = '5432',
'username' = 'xxx',
'password' = 'xxx',
'database-name' = 'postgres',
'schema-name' = 'public',
'table-name' = 'isp_as_maintenance_items',
'debezium.publication.autocreate.mode'='filtered'
'debezium.slot.name' = 'xxx',
'debezium.snapshot.mode' = 'initial',
'debezium.plugin.name' = 'pgoutput'
5. The error :no

**Additional Description**
![Snipaste_2022-04-25_18-55-55](https://user-images.githubusercontent.com/100289093/165077430-018e5c59-5a67-46f0-8d06-558091114217.png)

**Comment by PatrickRen** [comment] 2024-02-28 15:08
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:08 UTC
Labels: bug
