### ISSUE TITLE
2.0无法支持K8S session 模式

### ISSUE THREAD

**Issue by a120610114** [ververica/flink-cdc-connectors#310] opened 2021-08-12 07:16 UTC
我在使用flink1.13.0和flink1.13.1的时候 。 我把flink-sql-connector-mysql-cdc-2.0.0 .jar 放到flink lib包中以后 启动k8s session 模式 就报错了
![lALPBFuNehqWEP3NAkfNByE_1825_583](https://user-images.githubusercontent.com/26463863/129154203-3c804ee3-e520-4757-a85e-1c793fc62e14.png)

当我删除它，并使用其他版本之后，程序 正常启动了 
![lALPGSyfh5Wpgj3NA2TNB14_1886_868](https://user-images.githubusercontent.com/26463863/129154243-2d5000b8-78ab-44db-aa33-858fb59139d3.png)

所以我怀疑是有冲突或缺陷

**Comment by PatrickRen** [comment] 2024-02-28 15:41
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:41 UTC
Labels: question
