### ISSUE TITLE
VariableScaleDecimal is no longer emitted

### ISSUE THREAD

**Issue by sap1ens** [ververica/flink-cdc-connectors#1705] opened 2022-11-07 04:05 UTC
**Describe the bug**

[This commit](https://github.com/ververica/flink-cdc-connectors/commit/fcbed913116d92de606eacca064ae9a0a650c79e) has upgraded Postgres driver to version `42.2.26` without upgrading Debezium. However, I believe it's introduced a regression: 

- Postgres driver `42.2.23` has changed the way the numeric fields are presented, check the [changelog](https://jdbc.postgresql.org/changelogs/2021-07-06-42.2.23-release/)
- Debezium needs [this change](https://github.com/debezium/debezium/pull/2743/files#diff-df44a4cf2af87f5f56a89290e8d27525df242605aaa04c6565256c4376a83903) in order to accommodate the new logic 
- As a result, this project doesn't emit numeric types without scale as `VariableScaleDecimal` values anymore, which violates Debezium docs

**Environment :**
 - Flink version :  1.15
 - Flink CDC version: 2.3-SNAPSHOT (built based on [this commit](https://github.com/ververica/flink-cdc-connectors/commit/da5b3228904460b5ecc78d97bbb93239bca87bb2))
 - Database and version: Postgres 13

**To Reproduce**
Steps to reproduce the behaviour:
1. The test data : create a Postgres table with numeric type but no scale/precision
2. The test code : use the DataStream API source to consume and check the raw data: it now emits data using the Bytes type instead of a `VariableScaleDecimal` encoded as a Struct

**Comment by PatrickRen** [comment] 2024-02-28 14:57
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 14:57 UTC
Labels: bug
