### ISSUE TITLE
org.apache.kafka.connect.errors.ConnectException: tried to access field com.mysql.cj.CharsetMapping.COLLATION_INDEX_TO_COLLATION_NAME from class io.debezium.connector.mysql.antlr.MySqlAntlrDdlParser

### ISSUE THREAD

**Issue by overcls** [ververica/flink-cdc-connectors#302] opened 2021-08-10 02:23 UTC
21-08-10 10:22:14.690 ERROR 63716 --- [source-snapshot] i.d.connector.mysql.SnapshotReader       : Failed due to error: Aborting snapshot due to error when last running 'UNLOCK TABLES': tried to access field com.mysql.cj.CharsetMapping.COLLATION_INDEX_TO_COLLATION_NAME from class io.debezium.connector.mysql.antlr.MySqlAntlrDdlParser

**Comment by huojiajin** [comment] 2021-08-25 03:14
Have you resolved the problem? I met the same one

**Comment by Shilpa-Sareen** [comment] 2021-12-23 13:29
This is happening due to incompatibility of debezium maven dependecies with your DB (my-sql) version. For example I am using mysql-8.0 and debezium-connector-mysql 1.4.2. It was throwing same exception for me. Then I upgraded debezium-connector-mysql to 1.7.0.Final. It solved my problem. Try to use different version of debezium dependecies.

**Comment by PatrickRen** [comment] 2024-02-28 15:32
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:32 UTC
Labels: question
