### ISSUE TITLE
checkpoint failed

### ISSUE THREAD

**Issue by nayoaixgnat** [ververica/flink-cdc-connectors#955] opened 2022-03-16 08:03 UTC
after the first checkpoint cpmplated ,the second checkpoint is failed:
java.lang.NullPointerException
	at com.ververica.cdc.debezium.internal.FlinkOffsetBackingStore.configure(FlinkOffsetBackingStore.java:129)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:690)
	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:188)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by nayoaixgnat** [comment] 2022-03-16 08:08
cancel job and try to restore from the complated checkpoint ,can not restore ,the error is same.

**Comment by leonardBang** [comment] 2022-03-17 02:26
@nayoaixgnat Could you offer your flink cdc version and usage?

**Comment by nayoaixgnat** [comment] 2022-03-22 03:19
> @nayoaixgnat Could you offer your flink cdc version and usage?

stream cdc version: 2.0.2
checkpoint: 
StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
        env.disableOperatorChaining();
        env.enableCheckpointing(1000*60*5, CheckpointingMode.EXACTLY_ONCE);
        env.getCheckpointConfig().setTolerableCheckpointFailureNumber(100);
        env.getCheckpointConfig().setCheckpointTimeout(1000*60*10);
        env.getCheckpointConfig().enableExternalizedCheckpoints(CheckpointConfig.ExternalizedCheckpointCleanup.RETAIN_ON_CANCELLATION);
        env.getCheckpointConfig().enableUnalignedCheckpoints();
        env.setStateBackend(new HashMapStateBackend());
        env.getCheckpointConfig().setCheckpointStorage("hdfs:///user/fycmb/flink-checkpoints/readBinlog");
        env.setRestartStrategy(RestartStrategies.fixedDelayRestart(Integer.MAX_VALUE, 3 * 1000));
        
usage:
MySqlSource.<String>builder()
                .hostname(url)
                .port(port)
                .username(username)
                .password(password)
                .databaseList(databaseList)//所监控的数据库列表
                .tableList(tableList)//所监控的表的列表，支持正则，但是只支持(xxx_.*)方式即以xxx_开头的所有表
                .deserializer(new JsonDebeziumDeserializationSchema())
                .debeziumProperties(properties)
                .serverId(serverId)
                .startupOptions(startupOptions) 
                .build();

**Comment by nayoaixgnat** [comment] 2022-03-22 07:13
> @nayoaixgnat Could you offer your flink cdc version and usage?
I have observed the tasks for a period of time and found that the checkpoints are normal, but when the task fails for some reasons and recovers from the previous checkpoint, an error will be reported.

**Comment by nayoaixgnat** [comment] 2022-03-22 07:15
> @nayoaixgnat Could you offer your flink cdc version and usage?



> @leonardBang  Could you offer your flink cdc version and usage?

I have observed the tasks for a period of time and found that the checkpoints are normal, but when the task fails for some reasons and recovers from the previous checkpoint, an error will be reported.

**Comment by PatrickRen** [comment] 2024-02-28 15:09
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:09 UTC
Labels: bug
