### ISSUE TITLE
Flink Table/SQL API使用Flink CDC

### ISSUE THREAD

**Issue by ghost** [ververica/flink-cdc-connectors#259] opened 2021-07-18 06:28 UTC
请问使用Flink Table/SQL API定义一个CDC作为源的表，每定义一张表都会生产一个job吗

**Comment by leonardBang** [comment] 2021-08-20 09:03
不会，和其他flink sql作业一样，CDC 项目里我们尽量讨论CDC相关的issue, 如果是Flink 相关的，比如 sql 的运行机制，flink 原理等，我们可以去flink社区讨论

**Comment by PatrickRen** [comment] 2024-02-28 15:33
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:33 UTC
Labels: question
