### ISSUE TITLE
Flink CDC设置为specificOffset，当pod重启导致代码挂掉后，无法从checkpoint重启

### ISSUE THREAD

**Issue by Alexandereagle** [ververica/flink-cdc-connectors#1673] opened 2022-10-30 10:37 UTC
**Describe the bug(Please use English)**

**Environment :** K8s
 - Flink version :  1.13.2
 - Flink CDC version: 2.2.0
 - Database and version: mysql-5.6 / 5.7

**To Reproduce**
1. The test data :
2. The test code :
3. The error :When the pod is restarted, it cannot be restarted from the checkpoint。

**Additional Description**
the error is: the connector is trying to read binlog starting at SourceInfo[currentGtid=null .......], but this is no longer available on the server. reconfigure the connector to use a snapshot when need.
but when we config the  snapshot.mode is when_need. We can't start the program normally。

**Comment by dua01** [comment] 2022-11-09 08:45
This problem exists in cdc 1.2 version,
It seems that  the latest option also could not resume tasks from ck now.
The direct cause is ：gtidSetToReplicate.equals(nonPurgedGtidSetToReplicate）is always false in _'com.ververica.cdc.connectors.mysql.debezium.task.context.StatefulTaskContext.java'_ if the master purged some binlog.

If I force change this to true，it will throw ：
`ERROR io.debezium.pipeline.ErrorHandler - Producer failure
io.debezium.DebeziumException: The slave is connecting using CHANGE MASTER TO MASTER_AUTO_POSITION = 1, but the master has purged binary logs containing GTIDs that the slave requires. Replicate the missing transactions from elsewhere, or provision a new slave from backup. Consider increasing the master's binary log expiration period. The GTID set sent by the slave is 'be3f98c9-8ae2-11eb-bec3-080027a6a84c:268760-279776', and the missing transactions are 'be3f98c9-8ae2-11eb-bec3-080027a6a84c:1-268759'. Error code: 1236; SQLSTATE: HY000.
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.wrap(MySqlStreamingChangeEventSource.java:1383) ~[classes/:1.6.4.Final]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$ReaderThreadLifecycleListener.onCommunicationFailure(MySqlStreamingChangeEventSource.java:1439) [classes/:1.6.4.Final]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:980) [mysql-binlog-connector-java-0.25.3.jar:0.25.3]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:599) [mysql-binlog-connector-java-0.25.3.jar:0.25.3]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:857) [mysql-binlog-connector-java-0.25.3.jar:0.25.3]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: com.github.shyiko.mysql.binlog.network.ServerException: The slave is connecting using CHANGE MASTER TO MASTER_AUTO_POSITION = 1, but the master has purged binary logs containing GTIDs that the slave requires. Replicate the missing transactions from elsewhere, or provision a new slave from backup. Consider increasing the master's binary log expiration period. The GTID set sent by the slave is 'be3f98c9-8ae2-11eb-bec3-080027a6a84c:268760-279776', and the missing transactions are 'be3f98c9-8ae2-11eb-bec3-080027a6a84c:1-268759'.
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:944) ~[mysql-binlog-connector-java-0.25.3.jar:0.25.3]
	... 3 more`

**Comment by dua01** [comment] 2022-11-09 09:48
**Temporary solution**：
I modify the restored gtidSet in com.ververica.cdc.connectors.mysql.source.split.MySqlSplitSerializer， it works.

![image](https://user-images.githubusercontent.com/75104806/200797302-7f0105f6-8001-436c-a358-e618258ae177.png)

**Comment by lufzhangzitao** [comment] 2023-02-23 07:54
@dua01 hello,请教下，这样是不是貌似只能解决gtids只有一个的情况，如果我有多个从库实例gtids就会有多个，应该还是会报错：
我show master status的gtids：106a4bb6-ec0d-11ec-a2d4-00163e279211:1-204376424,
7aec1281-719c-11eb-afcf-00163e06a35c:1-147359662

**Comment by PatrickRen** [comment] 2024-02-28 15:02
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:02 UTC
Labels: bug
