### ISSUE TITLE
[question] best practice of timezone setting for mysql timestamp fields in both snapshot and binlog phases

### ISSUE THREAD

**Issue by ldwnt** [ververica/flink-cdc-connectors#1614] opened 2022-10-14 07:12 UTC
**Describe the bug(Please use English)**
The scenario is to use flink streaming api and flink cdc to poll data from mysql and write to kafka. A field value of timestamp field is expected to be in UTC timezone.

1. In snapshot phase of mysql flink cdc, UTC is used as default value for paramter serverTimezone. However, the mysql global timezone is +08:00, which means the sessionTimezone of jdbc connection is also +08:00. So a timestamp value 2000-01-01T16:00:00Z+08:00 in mysql is converted to 2001-01-01T16:00:00Z by cdc and in JsonDebeziumDeserializationSchema.deserialize, a string value "2001-01-01T16:00:00Z" is observed, while the correct value should be 2001-01-01T08:00:00Z.

My question is:
a) Is it the best practice to set serverTimezone to the same value of sessionTimezone of mysql? sessionTimezone could be queried from mysql when creating MySqlSource and set to serverTimezone , but the actual sessionTimezone may be different when the jdbc connection is established and the global timezone of mysql is changed at that time (small chance though).

b) In flink cdc 2.2, the default value of serverTimezone is removed, so a default value of jvm timezone is implicitly applied to paramter serverTimezone. If it's different to the mysql sessionTimezone, the output value of timestamp is incorrect. It would be great if the sessionTimezone could be configured in flink cdc. Maybe allow users to change MySqlConnection.URL_PATTERN and add parameter like "serverTimezone=UTC&useLegacyDatetimeCode=false&sessionVariables=time_zone='UTC'"? For mysql driver 8.0.23 and later, "preserveInstants=true&connectionTimeZone=SERVER" may be a better idea?

2. In binlog phase, a correct value of 2001-01-01T08:00:00Z is observed. I guess it's because of the same value of serverTimezone (defaults to my jvm timezone +08:00) and sessionTimezone (mysql global timezone +08:00). If these two values are different, how can I configure them?

3. In flink cdc code, I also find a class PooledDataSourceFactory. The createPooledDataSource is invoked and a datasource is created, but it seems not used to read records from mysql in snapshot/binlog phases (I change the serverTimezone/sessionTimezone of JDBC_URL_PATTERN in this class and the output value of timestamp fields are not changed). What's the purpose of this datasource?

**Environment :**
 - Flink CDC version: 2.1.1
 - Database and version: mysql 8

**Comment by PatrickRen** [comment] 2024-02-28 15:27
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:28 UTC
Labels: bug
