### ISSUE TITLE
snapshot and continues binlog read question,the same data will be consumed twice

### ISSUE THREAD

**Issue by luxuebao** [ververica/flink-cdc-connectors#717] opened 2021-12-14 02:32 UTC
**Describe the bug**
when using flink-mysql-cdc-connector to consume mysql data in incremental mode,i found some data is consumed more than once.Some datas are consumed as inserted data in snapshot stage and will be consumed again as insert,-update,+update data,that leads to one data will be compute twice.

**Environment :**
 - Flink version :  1.13.1
 - Flink CDC version: 2.1.0
 - Database and version: mysql & 5.7

**To Reproduce**
CREATE TABLE test1 (
loan_no varchar(10),
value varchar(10)
primary key(id) not enforced)
with(
'connector' = 'mysql-cdc',
'hostname' = 'XXXX',
'port' = '4417',
'username' = 'bigdata_r',
'password' = 'XXXXX',
'database-name' = 'test',
'table-name' = 'test1',
'scan.incremental.snapshot.enabled'='true',
'scan.incremental.snapshot.chunk.size' = '10240',
'scan.snapshot.fetch.size' = '1024',
'scan.startup.mode'='initial'
);

select loan_no,count(*) from test1 group by id having count()>1;

![image](https://user-images.githubusercontent.com/20124259/145922297-aa89507c-e801-4059-b467-427462fa6ba4.png)

**Additional Description**

**Comment by luxuebao** [comment] 2021-12-14 07:12
CREATE TABLE test1 (
loan_no varchar(10),
value varchar(10)
primary key(loan_no) not enforced)
with(
'connector' = 'mysql-cdc',
'hostname' = 'XXXX',
'port' = '4417',
'username' = 'bigdata_r',
'password' = 'XXXXX',
'database-name' = 'test',
'table-name' = 'test1',
'scan.incremental.snapshot.enabled'='true',
'scan.incremental.snapshot.chunk.size' = '10240',
'scan.snapshot.fetch.size' = '1024',
'scan.startup.mode'='initial'
);

**Comment by PatrickRen** [comment] 2024-02-28 15:32
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:32 UTC
Labels: bug
