### ISSUE TITLE
oracle中获取BLOB字段报错

### ISSUE THREAD

**Issue by JuchangGit** [ververica/flink-cdc-connectors#1576] opened 2022-09-23 09:43 UTC
请问oracle中获取BLOB字段报错怎么处理？
2022-09-16 16:54:36,972 ERROR io.debezium.relational.TableSchemaBuilder [] - Failed to properly convert data value for 'JWDB.ACADEMIC.STUDENT.PHOTO' of type BLOB for row [10427, 3200, , null, oracle.sql.BLOB@2c86cd16, 0, 0, 0, null, null, null]:
io.debezium.DebeziumException: Couldn't convert value for column PHOTO
        at io.debezium.connector.oracle.OracleValueConverters.convertBinary(OracleValueConverters.java:298) ~[flink-sql-connector-oracle-cdc-2.2.1.jar:2.2.1]
        at io.debezium.connector.oracle.OracleValueConverters.lambda$converter$1(OracleValueConverters.java:188) ~[flink-sql-connector-oracle-cdc-2.2.1.jar:2.2.1]
        at io.debezium.relational.TableSchemaBuilder.lambda$createValueGenerator$5(TableSchemaBuilder.java:264) ~[flink-sql-connector-mysql-cdc-2.2.1.jar:2.2.1]
        at io.debezium.relational.TableSchema.valueFromColumnData(TableSchema.java:141) ~[flink-sql-connector-mysql-cdc-2.2.1.jar:2.2.1]
        at io.debezium.relational.RelationalChangeRecordEmitter.emitReadRecord(RelationalChangeRecordEmitter.java:85) ~[flink-sql-connector-mysql-cdc-2.2.1.jar:2.2.1]
        at io.debezium.relational.RelationalChangeRecordEmitter.emitChangeRecords(RelationalChangeRecordEmitter.java:48) ~[flink-sql-connector-mysql-cdc-2.2.1.jar:2.2.1]
        at io.debezium.pipeline.EventDispatcher.dispatchSnapshotEvent(EventDispatcher.java:155) ~[flink-sql-connector-mysql-cdc-2.2.1.jar:2.2.1]
        at io.debezium.relational.RelationalSnapshotChangeEventSource.createDataEventsForTable(RelationalSnapshotChangeEventSource.java:377) ~[flink-sql-connector-mysql-cdc-2.2.1.jar:2.2.1]
        at io.debezium.relational.RelationalSnapshotChangeEventSource.createDataEvents(RelationalSnapshotChangeEventSource.java:305) ~[flink-sql-connector-mysql-cdc-2.2.1.jar:2.2.1]
        at io.debezium.relational.RelationalSnapshotChangeEventSource.doExecute(RelationalSnapshotChangeEventSource.java:138) ~[flink-sql-connector-mysql-cdc-2.2.1.jar:2.2.1]
        at io.debezium.pipeline.source.AbstractSnapshotChangeEventSource.execute(AbstractSnapshotChangeEventSource.java:71) ~[flink-sql-connector-mysql-cdc-2.2.1.jar:2.2.1]
        at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:110) ~[flink-sql-connector-mysql-cdc-2.2.1.jar:2.2.1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.sql.SQLException: Invalid argument(s) in call: getBytes()
        at oracle.jdbc.driver.OracleBlob.getBytes(OracleBlob.java:238) ~[flink-sql-connector-oracle-cdc-2.2.1.jar:2.2.1]
        at oracle.sql.BLOB.getBytes(BLOB.java:304) ~[flink-sql-connector-oracle-cdc-2.2.1.jar:2.2.1]
        at io.debezium.connector.oracle.OracleValueConverters.convertBinary(OracleValueConverters.java:295) ~[flink-sql-connector-oracle-cdc-2.2.1.jar:2.2.1]
        ... 16 more

**Comment by gong** [comment] 2024-02-03 05:29
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you! cc @GOODBOY008

**Comment by PatrickRen** [comment] 2024-02-28 15:29
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:29 UTC
