### ISSUE TITLE
Failed to deserialize data of EventHeaderV4

### ISSUE THREAD

**Issue by l1183479157** [ververica/flink-cdc-connectors#1437] opened 2022-08-01 09:33 UTC
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  1.13.6
 - Flink CDC version:  2.2.1
 - Database and version: mysql 8.0.26

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :

**Additional Description**

![image](https://user-images.githubusercontent.com/2595351/182119060-23d72343-6f49-4657-b9f6-3b3c41ed20eb.png)

**Comment by ruanhang1993** [comment] 2022-08-08 09:54
Duplicated to #432.

**Comment by PatrickRen** [comment] 2024-02-28 15:36
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:36 UTC
Labels: bug
