### ISSUE TITLE
Metrics exposure from Deserialisation layer.

### ISSUE THREAD

**Issue by debjeetsarkar** [ververica/flink-cdc-connectors#1210] opened 2022-05-21 11:01 UTC
In case of data being deserialised after receiving a SourceRecord from Debezium layer, what is the suggested way to gather metrics at that layer. More needed in case a custom deserialiser is being implemented to gather metrics. At the moment none of the implemented deserialisers expose metrics [counters, gauges].

**Describe the solution you'd like**
Being able to have a open method which gives an initialisation context [Similar to the serialiser layer]. This is possible only if the interface DebeziumDeserializationSchema has a default open method which has an runtime context being passed to it. 

**Describe alternatives you've considered**
Tried creating a custom metrics class and using that in the custom deserialiser but however, the way flink topology works, the custom metrics class doesn't get initialised from the deserialiser class.

**Comment by debjeetsarkar** [comment] 2022-05-21 11:05
This can also be correlated to : https://github.com/ververica/flink-cdc-connectors/issues/1078

**Comment by PatrickRen** [comment] 2024-02-28 15:30
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:30 UTC
Labels: enhancement
