### ISSUE TITLE
[mysql] Move table discovery logic to enumerator

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#492] opened 2021-10-11 06:45 UTC
The discovery logic should move to {@link MySqlSourceEnumerator} from {@link MySqlSnapshotSplitAssigner} so that the captured tables is correct when restore happens.

**Comment by PatrickRen** [comment] 2024-02-28 15:11
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed as not planned by PatrickRen** 2024-02-28 15:11 UTC
Labels: enhancement
