### ISSUE TITLE
Inefficient batch event handling

### ISSUE THREAD

**Issue by SmirAlex** [ververica/flink-cdc-connectors#109] opened 2021-02-24 07:01 UTC
Currently in master branch in [handleBatch](https://github.com/ververica/flink-cdc-connectors/blob/05a28a44287c10bb769530e7538c7cbe14763ed1/flink-connector-debezium/src/main/java/com/alibaba/ververica/cdc/debezium/internal/DebeziumChangeConsumer.java#L91) method of DebeziumChangeConsumer records are being passed to method [emitRecordsUnderCheckpointLock](https://github.com/ververica/flink-cdc-connectors/blob/e2d4ff735c7a94fa5073622260a78e5c0229ee97/flink-connector-debezium/src/main/java/com/alibaba/ververica/cdc/debezium/internal/DebeziumChangeConsumer.java#L134) one by one (because there are only 1 element in [queue](https://github.com/ververica/flink-cdc-connectors/blob/e2d4ff735c7a94fa5073622260a78e5c0229ee97/flink-connector-debezium/src/main/java/com/alibaba/ververica/cdc/debezium/internal/DebeziumChangeConsumer.java#L182) at any given time), which is not efficient especially considering that locks are taken there. To support truly batch event handling I suggest to accumulate records in a queue and then process them as a batch. Offset of the batch will be the last record offset of the  `List<SourceRecord>`.

**Comment by PatrickRen** [comment] 2024-02-28 15:41
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:41 UTC
Labels: enhancement
