### ISSUE TITLE
[mysql-cdc] decrease the distribution factor upper-bound

### ISSUE THREAD

**Issue by luoyajun10** [ververica/flink-cdc-connectors#1278] opened 2022-06-12 14:07 UTC
#### _description_

As known to us, mysql cdc connector supports dynamic chunk size since v2.1. The connector will adjust the chunk size through the distribution factor, if it's between lower-bound and upper-bound. The distribution factor is calculated by formula `(max - min + 1) / rowCount`, which is max/min of the split column. Now the issue is that the dynamic chunk size is fairly large in some scenarios, such as a few millions, which can cause GC problems and impact the job. I think it may be related to the upper-bound option with default 1000.0d, which enlarged the condition of even distribution.

For instance:

```
max: 20220101000001
min: 20220601000001
approximate row count: 1,000,000
```

In this case, the distribution factor will be 500.0d, which is less than the upper-bound 1000.0d. Then the connector will consider data as evenly distributed. But the chunk size will be 500 * 8096(default) = 4048000, and there is only one chunk in the connector. Obviously it's unreasonable.

We can decrease the default value of `split-key.even-distribution.factor.upper-bound` option, may be 10.0d is reasonable. If so, the number of chunks may be fairly large sometimes. However, we can define the chunk size to keep it reasonable.

#### _related code snippet_

https://github.com/ververica/flink-cdc-connectors/blob/c06fd64c50fd7583b24bd969a14d7bc49e4ffdf1/flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/assigners/ChunkSplitter.java#L139-L163

**Comment by luoyajun10** [comment] 2022-06-14 03:14
@leonardBang what do you think of it?

**Comment by PatrickRen** [comment] 2024-02-28 15:06
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:06 UTC
Labels: enhancement
