### ISSUE TITLE
[mysql]binlog file validation error when switch mysql cluster

### ISSUE THREAD

**Issue by xiaoyu19950911** [ververica/flink-cdc-connectors#1001] opened 2022-03-24 09:53 UTC
**Describe the bug(Please use English)**
During binlogReader phase, it will checks whether the binlog file exists first.In master/slave mode,If I switch from cluster A to cluster B and restore from checkpoint,It will continue to run in GTID mode but valid binlog file error!

**Environment :**
 - Flink version :  1.13
 - Flink CDC version: 2.1
 - Database and version: 5.7

**To Reproduce**
1. Thes test data :cluster A(file = mysql-bin.000001)    cluster B(file = mysql-bin.000002)
2. The test code :switch from cluster A to cluster B and restore from checkpoint
3. The error :Caused by: java.lang.IllegalStateException: The connector is trying to read binlog starting at Struct{version=1.5.0-LANCER-SNAPSHOT,connector=mysql,name=mysql_binlog_source,ts_ms=1648112699084,db=,server_id=0,file=mysql-bin.000001,pos=3311,row=0}, but this is no longer available on the server. Reconfigure the connector to use a snapshot when needed.

**Additional Description**
<img width="829" alt="image" src="https://user-images.githubusercontent.com/31729765/159889835-e5e44135-113c-45a7-b230-a0e89cff6d4b.png">

**Comment by rcf666** [comment] 2022-08-25 03:21
> is the problem solved,bro

**Comment by PatrickRen** [comment] 2024-02-28 15:31
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:31 UTC
Labels: bug
