### ISSUE TITLE
[MySql] not to throw an exception when bin log format changed from row to others to stop job from endless restarting. 

### ISSUE THREAD

**Issue by Fisher666** [ververica/flink-cdc-connectors#1453] opened 2022-08-07 15:02 UTC
issue:

flink job get restarted and stuck at an exception  when bin log format changed from row to others 

  exception : 
    Caused by: io.debezium.DebeziumException: Received DML
  
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/45913164/183297520-069b7cb1-e9f8-44e6-9b69-be3bf29f1963.png">

   versions:
        flink 1.13
        cdc 2.2.1
        mysql  5.6

suggested solution: 
     not to throw an exception when bin log format changed from row to others
     and increase the  bin log offset by one until the bin log format changes back to row

**Comment by ruanhang1993** [comment] 2022-08-15 02:25
duplicated to #1017

**Comment by ruanhang1993** [comment] 2022-08-15 02:26
Debezium has a issue to fix this [DBZ-3949](https://issues.redhat.com/browse/DBZ-3949). We could set [event.deserialization.failure.handling.mode](https://debezium.io/documentation/reference/1.6/connectors/mysql.html#mysql-property-event-deserialization-failure-handling-mode) to `warn` to skip this failure.

**Comment by PatrickRen** [comment] 2024-02-28 15:36
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:36 UTC
Labels: enhancement
