### ISSUE TITLE
PostgreSQL data synchronization, io error occurs in incremental synchronization after snapshot execution

### ISSUE THREAD

**Issue by PengMinghui973** [ververica/flink-cdc-connectors#1175] opened 2022-05-12 03:36 UTC
**Describe the bug(Please use English)**
Synchronize a piece of 130W data to redis. Whenever the data is fully synchronized, that is, the snapshot is read, an io error occurs in flink synchronization when the first batch of data changes.

**Environment :**
 - Flink version :  flink1.13.1
 - Flink CDC version: 2.2.1
 - Database and version: aws rds postgresql-11
 - Database parameters:
![image](https://user-images.githubusercontent.com/62225711/167986906-534f98ba-cd61-45f2-b61d-b1bf4f0e3509.png)

**To Reproduce**
1. Thes test data : 130W data synchronization
2. The test code :  
![image](https://user-images.githubusercontent.com/62225711/167985798-f3e5598d-45b1-423c-b93f-264400dcec08.png)
![image](https://user-images.githubusercontent.com/62225711/167985857-17f93036-5c4f-4783-b943-a3aa99602da6.png)

4. The error :
![image](https://user-images.githubusercontent.com/62225711/167985924-e4d06e96-0cde-46e6-8a3f-f2eda580bc2e.png)
![image](https://user-images.githubusercontent.com/62225711/167985955-fd9c3ffd-c380-44c3-acba-9c61580bc363.png)

**Additional Description**
Server and database network latency
![image](https://user-images.githubusercontent.com/62225711/167986157-74f7da17-777f-48b8-9caa-0bfc56a55929.png)
Is it because cdc switches to incremental synchronization data after the snapshot is executed, and cannot process a large amount of data? At present, this problem is almost inevitable

**Comment by fsk119** [comment] 2022-05-16 02:00
Thanks for your report. Could you also share the logs in the task manager?

**Comment by PengMinghui973** [comment] 2022-05-16 04:26
> 感谢您的举报。您能否在任务管理器中共享日志？
[flink-root-taskexecutor-0-flinktest.log](https://github.com/ververica/flink-cdc-connectors/files/8697146/flink-root-taskexecutor-0-flinktest.log)
[flink-root-taskexecutor-1-flinktest.log](https://github.com/ververica/flink-cdc-connectors/files/8697148/flink-root-taskexecutor-1-flinktest.log)

**Comment by PatrickRen** [comment] 2024-02-28 15:30
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:30 UTC
Labels: bug
