### ISSUE TITLE
Using the mysql-cdc 2.2, and using latest-offset mode during caused add newly table not to be capture.

### ISSUE THREAD

**Issue by minchowang** [ververica/flink-cdc-connectors#1184] opened 2022-05-16 09:23 UTC
**Describe the bug(Please use English)**
Using the mysql-cdc 2.2, and using latest-offset mode during caused newly table  not to be capture.
**Environment :**
 - Flink version :  
 - Flink CDC version: 2.2
 - Database and version: MYSQL-5.7

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :

**Additional Description**
<img width="478" alt="image" src="https://user-images.githubusercontent.com/33626973/168561096-16d33533-4065-4869-a423-123017707d55.png">

**Comment by PatrickRen** [comment] 2024-02-28 15:30
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:30 UTC
Labels: bug
