### ISSUE TITLE
Unique key conflict when updating the unique key in the process of reading the new split

### ISSUE THREAD

**Issue by zhaomin1423** [ververica/flink-cdc-connectors#760] opened 2021-12-30 06:05 UTC
**Describe the bug**
When a mysql table with unique key, there are some splits. When a split read was complete, other split is reading，at this point,  a row of previous split was updated, next to, a row of current split update a unique key to the value same with last row. After the split snapshot complete, the binlog file was used to update the batch, so the unique key of the row is same with a row of previous split. So, when write to mysql table with same unique key, there is an exception.

**Environment :**
 - Flink version :  1.13.0
 - Flink CDC version: 2.1.0
 - Database and version: 5.7

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :

**Additional Description**
![image](https://user-images.githubusercontent.com/49054376/147725956-177173e9-cc04-459f-8dc9-bca04a92018b.png)

**Comment by PatrickRen** [comment] 2024-02-28 15:31
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:31 UTC
Labels: bug
