### ISSUE TITLE
[mysql] MysqlParallelSource Stability Improvement

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#373] opened 2021-08-29 05:16 UTC
- [x] 1. Skip binlog reading, if low == high
- [x] 2. If concurrency=1, there is no need to wait with checkpoint. (done)  #365
- [x] 3. Improve the log and clean up debezium logs
- [x] 4. Investigate rds master/standby switching scenarios can works or not
- [ ] 5. Bind the DebeziumReader life circle with split
- [ ] 6. Investigate MySqlParallelSource could use single serverId or not

**Comment by PatrickRen** [comment] 2024-02-28 15:40
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:40 UTC
Labels: category, task
