### ISSUE TITLE
Stop job with savepoint. restarted with savepoint but some table is re-export.

### ISSUE THREAD

**Issue by MyLanPangzi** [ververica/flink-cdc-connectors#1637] opened 2022-10-20 08:04 UTC
**Describe the bug(Please use English)**
I hava a job running for 3 months. Today i stopped the job with savepoint. Then i started the job with savepoint.
After i find some table re-export...
This is a bug?

**Environment :**
 - Flink version :  1.14.2
 - Flink CDC version: 2.2.1
 - Database and version:  5.7

**To Reproduce**
My code: https://github.com/ververica/flink-cdc-connectors/issues/1486
My sql 
```
SET database-name=a;
SET server-id=9101-9200;
SET scan.incremental.snapshot.chunk.size=409600;
SET split-key.even-distribution.factor.upper-bound=2.0;
SET scan.newly-added-table.enabled=true;
SET debezium.bigint.unsigned.handling.mode=long;

SET table-topic-mapping.a.t_kline_.*=ods_a_t_kline_cdc_realtime;

call com.phemex.flink.cdc.function.MysqlCdcSourceRegister;

CREATE TABLE ods_binlog_default
(
    `key`   STRING,
    `value` STRING,
    `topic` STRING METADATA FROM 'topic'
) WITH (
    'connector' = 'route-kafka',
    'topic' = 'ods_binlog_default',
    'properties.bootstrap.servers' = '',
    'key.format' = 'raw',
    'key.fields' = 'key',
    'value.format' = 'raw',
    'value.fields-include' = 'EXCEPT_KEY',
    'properties.compression.type' = 'gzip',
    'properties.linger.ms' = '1000',
    'properties.batch.size' = '163840'
 );

INSERT INTO ods_binlog_default
SELECT `key`, `value`, get_topic(`db`, `table`)
FROM cdc;

```
**Additional Description**
Some log 
<img width="1379" alt="image" src="https://user-images.githubusercontent.com/46845236/196891694-6b6c1567-c972-45c1-931a-d64aea24bd02.png">

**Comment by MyLanPangzi** [comment] 2022-10-20 08:14
Same id data have two recoreds.
<img width="536" alt="image" src="https://user-images.githubusercontent.com/46845236/196894214-2f569691-19bb-45ff-8a36-0a0fca907493.png">

**Comment by MyLanPangzi** [comment] 2022-10-20 08:17
My job is started from savepoint.
<img width="819" alt="image" src="https://user-images.githubusercontent.com/46845236/196894656-df656f74-a576-4e6b-8fe6-eef52c2d4182.png">

savepoint timestamp:
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/46845236/196894799-c46781cf-ffd7-4e52-a2a8-3e8cea8a779f.png">

**Comment by PatrickRen** [comment] 2024-02-28 15:03
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:03 UTC
Labels: bug
