### ISSUE TITLE
[MySql] The specific offset mode failed when enable GTID mode

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#433] opened 2021-09-16 15:39 UTC
**Describe the bug**
The specific offset mode failed when enable GTID mode

**Environment :**
 - Flink version :  1.13.2
 - Flink CDC version: 1.x 
 - Database and version: MySQL 5.7 

**To Reproduce**
`MySqlSourTest#testStartupFromSpecificOffset` will failed if we enable GTID mode

**Comment by PatrickRen** [comment] 2024-02-28 15:12
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:12 UTC
Labels: bug
