### ISSUE TITLE
报错 com.alibaba.ververica.cdc.connectors.mysql.table.MySQLTableSource.$deserializeLambda$方法找不到

### ISSUE THREAD

**Issue by zhouyu328** [ververica/flink-cdc-connectors#280] opened 2021-08-01 01:18 UTC
![image](https://user-images.githubusercontent.com/46194040/127756091-7a56556f-5a3d-4da3-a0de-b536b74921ff.png)

connector的jar包也是1.4.0

flink版本1.13，在另外一台flink版本1.12的机器上似乎没有问题，感觉是flink版本的问题哇

**Comment by PatrickRen** [comment] 2024-02-28 15:33
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:33 UTC
Labels: question
