### ISSUE TITLE
Flink job will not stop when the mysql database becomes unavailable.

### ISSUE THREAD

**Issue by ruanhang1993** [ververica/flink-cdc-connectors#1372] opened 2022-07-14 06:05 UTC
**Is your feature request related to a problem? Please describe.**
I submit a flink job that reads from a mysql database and writes to a kafka cluster by mysql cdc connector. This mysql database offline after a month, but this flink job does not exit. And the BinnaryLogClient will continue to retry endlessly.

**Describe the solution you'd like**
I think mysql cdc connector should react to this error instead of endlessly retrying. Maybe the job should fail after retrying a few times.

**Comment by Jiabao-Sun** [comment] 2022-07-15 07:58
Hi @ruanhang1993,

Do you configure the restart strategy like below?  The `attempts` option can limit the max attempts of restarts.
```
restart-strategy fixed-delay
restart-strategy.fixed-delay.delay: 15s
restart-strategy.fixed-delay.attempts: 10
```

**Comment by hezhenghongmail** [comment] 2022-07-22 03:30
2022-07-21 19:20:04.021 INFO  io.debezium.util.Threads                                     - Creating thread debezium-mysqlconnector-mysql_binlog_source-binlog-client
2022-07-21 19:20:34.046 ERROR System.err                                                   - Jul 21, 2022 7:20:34 PM com.github.shyiko.mysql.binlog.BinaryLogClient$5 run
WARNING: Failed to restore connection to 10.136.140.44:13114. Next attempt in 60000ms

2022-07-21 19:21:34.046 ERROR System.err                                                   - Jul 21, 2022 7:21:34 PM com.github.shyiko.mysql.binlog.BinaryLogClient$5 run
INFO: Trying to restore lost connection to 10.136.140.44:13114

2022-07-21 19:21:34.046 INFO  io.debezium.util.Threads                                     - Creating thread debezium-mysqlconnector-mysql_binlog_source-binlog-client
2022-07-21 19:22:04.054 ERROR System.err                                                   - Jul 21, 2022 7:22:04 PM com.github.shyiko.mysql.binlog.BinaryLogClient$5 run
WARNING: Failed to restore connection to 10.136.140.44:13114. Next attempt in 60000ms

2022-07-21 19:23:04.055 ERROR System.err                                                   - Jul 21, 2022 7:23:04 PM com.github.shyiko.mysql.binlog.BinaryLogClient$5 run
INFO: Trying to restore lost connection to 10.136.140.44:13114

2022-07-21 19:23:04.055 INFO  io.debezium.util.Threads                                     - Creating thread debezium-mysqlconnector-mysql_binlog_source-binlog-client
2022-07-21 19:23:34.081 ERROR System.err                                                   - Jul 21, 2022 7:23:34 PM com.github.shyiko.mysql.binlog.BinaryLogClient$5 run
WARNING: Failed to restore connection to 10.136.140.44:13114. Next attempt in 60000ms

2022-07-21 19:23:51.247 INFO  org.apache.flink.metrics.lcs.shaded.com.xiaomi.infra.galaxy.lcs.common.file.DiskManager - datadir: /home/work/app/lcs-agent/data, usableSpace: 488  GB
2022-07-21 19:24:34.081 ERROR System.err                                                   - Jul 21, 2022 7:24:34 PM com.github.shyiko.mysql.binlog.BinaryLogClient$5 run
INFO: Trying to restore lost connection to 10.136.140.44:13114

2022-07-21 19:24:34.081 INFO  io.debezium.util.Threads                                     - Creating thread debezium-mysqlconnector-mysql_binlog_source-binlog-client
2022-07-21 19:24:34.982 INFO  org.apache.flink.streaming.runtime.tasks.StreamTask          - Starting checkpoint 2079 CHECKPOINT on task Source: Custom Source -> Filter -> Flat Map -> Sink: Unnamed(cnbj4-talos:binlog_topic_mysql_10609_13114_xm_pss) (1/1)#0
2022-07-21 19:24:35.182 INFO  com.xiaomi.infra.galaxy.talos.producer.TalosProducer         - Flush finish for topic:binlog_topic_mysql_10609_13114_xm_pss
2022-07-21 19:24:35.182 INFO  org.apache.flink.runtime.state.SnapshotStrategyRunner        - DefaultOperatorStateBackend snapshot (FsCheckpointStorageLocation {fileSystem=org.apache.flink.core.fs.SafetyNetWrapperFileSystem@3fbfb827, checkpointDirectory=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/chk-2079, sharedStateDirectory=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/shared, taskOwnedStateDirectory=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/taskowned, metadataFilePath=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/chk-2079/_metadata, reference=(default), fileStateSizeThreshold=20480, writeBufferSize=20480}, synchronous part) in thread Thread[Source: Custom Source -> Filter -> Flat Map -> Sink: Unnamed(cnbj4-talos:binlog_topic_mysql_10609_13114_xm_pss) (1/1)#0,5,Flink Task Threads] took 0 ms.
2022-07-21 19:24:35.182 INFO  org.apache.flink.runtime.state.SnapshotStrategyRunner        - DefaultOperatorStateBackend snapshot (FsCheckpointStorageLocation {fileSystem=org.apache.flink.core.fs.SafetyNetWrapperFileSystem@3fbfb827, checkpointDirectory=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/chk-2079, sharedStateDirectory=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/shared, taskOwnedStateDirectory=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/taskowned, metadataFilePath=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/chk-2079/_metadata, reference=(default), fileStateSizeThreshold=20480, writeBufferSize=20480}, synchronous part) in thread Thread[Source: Custom Source -> Filter -> Flat Map -> Sink: Unnamed(cnbj4-talos:binlog_topic_mysql_10609_13114_xm_pss) (1/1)#0,5,Flink Task Threads] took 0 ms.
2022-07-21 19:24:35.183 INFO  org.apache.flink.runtime.state.SnapshotStrategyRunner        - DefaultOperatorStateBackend snapshot (FsCheckpointStorageLocation {fileSystem=org.apache.flink.core.fs.SafetyNetWrapperFileSystem@3fbfb827, checkpointDirectory=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/chk-2079, sharedStateDirectory=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/shared, taskOwnedStateDirectory=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/taskowned, metadataFilePath=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/chk-2079/_metadata, reference=(default), fileStateSizeThreshold=20480, writeBufferSize=20480}, synchronous part) in thread Thread[Source: Custom Source -> Filter -> Flat Map -> Sink: Unnamed(cnbj4-talos:binlog_topic_mysql_10609_13114_xm_pss) (1/1)#0,5,Flink Task Threads] took 0 ms.
2022-07-21 19:24:35.184 INFO  org.apache.flink.runtime.state.SnapshotStrategyRunner        - DefaultOperatorStateBackend snapshot (FsCheckpointStorageLocation {fileSystem=org.apache.flink.core.fs.SafetyNetWrapperFileSystem@3fbfb827, checkpointDirectory=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/chk-2079, sharedStateDirectory=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/shared, taskOwnedStateDirectory=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/taskowned, metadataFilePath=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/chk-2079/_metadata, reference=(default), fileStateSizeThreshold=20480, writeBufferSize=20480}, synchronous part) in thread Thread[Source: Custom Source -> Filter -> Flat Map -> Sink: Unnamed(cnbj4-talos:binlog_topic_mysql_10609_13114_xm_pss) (1/1)#0,5,Flink Task Threads] took 0 ms.
2022-07-21 19:24:35.186 INFO  org.apache.flink.runtime.state.SnapshotStrategyRunner        - DefaultOperatorStateBackend snapshot (FsCheckpointStorageLocation {fileSystem=org.apache.flink.core.fs.SafetyNetWrapperFileSystem@3fbfb827, checkpointDirectory=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/chk-2079, sharedStateDirectory=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/shared, taskOwnedStateDirectory=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/taskowned, metadataFilePath=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/chk-2079/_metadata, reference=(default), fileStateSizeThreshold=20480, writeBufferSize=20480}, asynchronous part) in thread Thread[AsyncOperations-thread-2017,5,Flink Task Threads] took 0 ms.
2022-07-21 19:24:35.217 INFO  org.apache.flink.runtime.state.SnapshotStrategyRunner        - DefaultOperatorStateBackend snapshot (FsCheckpointStorageLocation {fileSystem=org.apache.flink.core.fs.SafetyNetWrapperFileSystem@3fbfb827, checkpointDirectory=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/chk-2079, sharedStateDirectory=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/shared, taskOwnedStateDirectory=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/taskowned, metadataFilePath=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/chk-2079/_metadata, reference=(default), fileStateSizeThreshold=20480, writeBufferSize=20480}, asynchronous part) in thread Thread[AsyncOperations-thread-2017,5,Flink Task Threads] took 30 ms.
2022-07-21 19:24:35.217 INFO  org.apache.flink.runtime.state.SnapshotStrategyRunner        - DefaultOperatorStateBackend snapshot (FsCheckpointStorageLocation {fileSystem=org.apache.flink.core.fs.SafetyNetWrapperFileSystem@3fbfb827, checkpointDirectory=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/chk-2079, sharedStateDirectory=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/shared, taskOwnedStateDirectory=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/taskowned, metadataFilePath=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/chk-2079/_metadata, reference=(default), fileStateSizeThreshold=20480, writeBufferSize=20480}, asynchronous part) in thread Thread[AsyncOperations-thread-2017,5,Flink Task Threads] took 0 ms.
2022-07-21 19:24:35.217 INFO  org.apache.flink.runtime.state.SnapshotStrategyRunner        - DefaultOperatorStateBackend snapshot (FsCheckpointStorageLocation {fileSystem=org.apache.flink.core.fs.SafetyNetWrapperFileSystem@3fbfb827, checkpointDirectory=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/chk-2079, sharedStateDirectory=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/shared, taskOwnedStateDirectory=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/taskowned, metadataFilePath=hdfs://zjyprc-streaming/checkpoint/flink/h_data_platform/kolibre/814987/a386d1e21c827313a623de92415b88d2/chk-2079/_metadata, reference=(default), fileStateSizeThreshold=20480, writeBufferSize=20480}, asynchronous part) in thread Thread[AsyncOperations-thread-2017,5,Flink Task Threads] took 0 ms.
2022-07-21 19:25:04.113 ERROR System.err                                                   - Jul 21, 2022 7:25:04 PM com.github.shyiko.mysql.binlog.BinaryLogClient$5 run
WARNING: Failed to restore connection to 10.136.140.44:13114. Next attempt in 60000ms

2022-07-21 19:26:04.114 ERROR System.err                                                   - Jul 21, 2022 7:26:04 PM com.github.shyiko.mysql.binlog.BinaryLogClient$5 run
INFO: Trying to restore lost connection to 10.136.140.44:13114

2022-07-21 19:26:04.114 INFO  io.debezium.util.Threads                                     - Creating thread debezium-mysqlconnector-mysql_binlog_source-binlog-client
2022-07-21 19:26:34.137 ERROR System.err                                                   - Jul 21, 2022 7:26:34 PM com.github.shyiko.mysql.binlog.BinaryLogClient$5 run
WARNING: Failed to restore connection to 10.136.140.44:13114. Next attempt in 60000ms

2022-07-21 19:27:34.137 ERROR System.err                                                   - Jul 21, 2022 7:27:34 PM com.github.shyiko.mysql.binlog.BinaryLogClient$5 run
INFO: Trying to restore lost connection to 10.136.140.44:13114

2022-07-21 19:27:34.137 INFO  io.debezium.util.Threads                                     - Creating thread debezium-mysqlconnector-mysql_binlog_source-binlog-client
2022-07-21 19:28:04.140 ERROR System.err                                                   - Jul 21, 2022 7:28:04 PM com.github.shyiko.mysql.binlog.BinaryLogClient$5 run
WARNING: Failed to restore connection to 10.136.140.44:13114. Next attempt in 60000ms

2022-07-21 19:28:51.247 INFO  org.apache.flink.metrics.lcs.shaded.com.xiaomi.infra.galaxy.lcs.common.file.DiskManager - datadir: /home/work/app/lcs-agent/data, usableSpace: 488  GB
2022-07-21 19:29:04.140 ERROR System.err                                                   - Jul 21, 2022 7:29:04 PM com.github.shyiko.mysql.binlog.BinaryLogClient$5 run
INFO: Trying to restore lost connection to 10.136.140.44:13114

2022-07-21 19:29:04.141 INFO  io.debezium.util.Threads                                     - Creating thread debezium-mysqlconnector-mysql_binlog_source-binlog-client
2022-07-21 19:29:34.173 ERROR System.err                                                   - Jul 21, 2022 7:29:34 PM com.github.shyiko.mysql.binlog.BinaryLogClient$5 run
WARNING: Failed to restore connection to 10.136.140.44:13114. Next attempt in 60000ms

**Comment by hezhenghongmail** [comment] 2022-07-22 03:34
The task doesn't exit, it's just that debezium keeps retrying.

**Comment by hezhenghongmail** [comment] 2022-07-22 03:35
![image](https://user-images.githubusercontent.com/109778487/180357212-e07b9996-691c-485d-a89b-c96bb83f6e86.png)

**Comment by Jiabao-Sun** [comment] 2022-07-22 03:36
Thanks @ruanhang1993 @hezhenghongmail to report this.

**Comment by lufzhangzitao** [comment] 2023-01-30 06:22
> ![image](https://user-images.githubusercontent.com/109778487/180357212-e07b9996-691c-485d-a89b-c96bb83f6e86.png)

if i set connect.keep.alive = false ，cloud  solve this problem？

**Comment by PatrickRen** [comment] 2024-02-28 15:36
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:36 UTC
Labels: enhancement
