### ISSUE TITLE
[Improvment] Add a labeler github action to triage PRs

### ISSUE THREAD

**Issue by yangrong688** [ververica/flink-cdc-connectors#1024] opened 2022-03-30 01:20 UTC
**Is your feature request related to a problem? Please describe.**
Using https://github.com/marketplace/actions/label-actions to triage PRs roughly to get reviewers' attention easier

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/70557521/160731807-69866cdc-5c42-41c1-92ca-3cb446cec553.png)
Add a label.yml related to our codebase, and an action to trigger this flow will be needed.
Labels shown above maybe easily tagged by robot.

**Describe alternatives you've considered**

**Comment by PatrickRen** [comment] 2024-02-28 15:30
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:30 UTC
Labels: enhancement
