### ISSUE TITLE
Does flink-cdc support dynamic table addition

### ISSUE THREAD

**Issue by ClareGuoBin** [ververica/flink-cdc-connectors#1226] opened 2022-05-26 14:11 UTC
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  flink-1.13.0
 - Flink CDC version: 2.2.0
 - Database and version: mysql-5.7(dev enviorment) and 8.0.28(for local test)

**To Reproduce**
1. Thes test data : Dynamic table addtition according to MySqlSource#tableList(String) api through nacos
2. The test code :
```java
MySqlSource<String> mySqlSource = MySqlSource.<String>builder()
                .hostname("localhost")
                .port(3306)
                .databaseList("test")
                .tableList(tables)
                .username("cdc-test")
                .password("12345abc")
                // serverId，可用于高并发全量读取时起作用，默认5600-6400之间随机值
                .serverId("5600-6400")
                // 支持扫描新表，默认值为true
                .scanNewlyAddedTableEnabled(true)
                .startupOptions(StartupOptions.latest())
                // 全量读时每个chunk的值
                .splitSize(8096)
                // 全量读时每个批次拉取数据量
                .fetchSize(1024)
                // 时区，默认上海时区
                .serverTimeZone("Asia/Shanghai")
                // 连接超时时间，默认30s
                .connectTimeout(Duration.ofSeconds(120))
                .connectMaxRetries(3)
                .connectionPoolSize(20)
                .heartbeatInterval(Duration.ofSeconds(30))
//                .includeSchemaChanges(true)
                .deserializer(new CustomDebeziumDeserialization())
                .jdbcProperties(jdbcProperties)
                .debeziumProperties(debeziumProperties)
                .build();
```
In order to dynamically capture the change of `tableList`, I use nacos' listener, but it does not take effect.

```java
for (String group : GROUPS) {
                for (String dataId : DATA_IDS) {
                    content = configService.getConfig(dataId, group, TIMEOUT);
                    if (content != null) {
                        NACOS_CONFIG_MAP.load(new StringReader(content));
                        configService.addListener(dataId, group, new PropertiesListener() {
                            @Override
                            public void innerReceive(Properties properties) {
                                log.info("config file {}:{} refreshed", group, dataId);
                                NACOS_CONFIG_MAP.putAll(properties);
                            }
                        });
                    }
                }
            }
```

3. The error :
It must restart my job and use savepoint to help us capture the change of mysql.

Is it a bug or what should i do? 

I had a similar problem with this blog.
`https://blog.csdn.net/weixin_52918377/article/details/123826662`

**Additional Description**

**Comment by PatrickRen** [comment] 2024-02-28 15:30
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:30 UTC
Labels: bug
