### ISSUE TITLE
Flink-CDC  在同步字段为timestamp类型的数据时，初始化数据和增量数据时区不一致

### ISSUE THREAD

**Issue by ghost** [ververica/flink-cdc-connectors#317] opened 2021-08-13 07:38 UTC
在使用flinkcdc stream处理时，字段类型为timestamp的字段，初始化的数据和增量binlog的数据里的timestamp类型数据时区不一致。我是临时通过isSnapshot这个字段处理了一下，希望可以修复一下这个bug。flink版本1.2.0，flinkcdc1.4.0

**Comment by leonardBang** [comment] 2021-08-13 07:56
@xiaoshijiang523  Could you post a simple demo to reproduce the issue? thanks

**Comment by wuqingquan-github** [comment] 2021-08-23 07:59
env.addSource(getCDC(DATABASE, TABLE)).print();

mysql中数据：start_time和end_time都是datetime类型
{"id_card":"362324","end_time":2021-08-14 08:55:11,"start_time":2021-08-14 08:44:08,"id":72}

不管是否添加配置：mysql.serverTimezone=Asia/Shanghai，结果都一样
"data":{"id_card":"362324","end_time":1628931311000,"start_time":1628930648000,"id":72}
打印的结果转换为LocalDateTime分别是2021-08-14 16:44:08和2021-08-14 16:55:11

 public static DebeziumSourceFunction<JSONObject> getCDC(String databaseList, String tableList) {
        return MySQLSource.<JSONObject>builder()
                .hostname(HOSTNAME)
                .port(3306)
                .username(USERNAME)
                .password(PASSWORD)
                .databaseList(databaseList)
                .tableList(tableList)
                .deserializer(new MyDeserializer())
                .build();
}

**Comment by wuqingquan-github** [comment] 2021-08-23 08:14
env.addSource(getCDC(DATABASE, TABLE)).print();

mysql中数据：start_time和end_time都是datetime类型
{"id_card":"362324","end_time":2021-08-14 08:55:11,"start_time":2021-08-14 08:44:08,"id":72}

不管是否添加配置：SERVER_TIME_ZONE=Asia/Shanghai，结果都一样
"data":{"id_card":"362324","end_time":1628931311000,"start_time":1628930648000,"id":72}
打印的结果转换为LocalDateTime分别是2021-08-14 16:44:08和2021-08-14 16:55:11

    public static DebeziumSourceFunction<JSONObject> getCDC(String databaseList, String tableList) {
        return MySQLSource.<JSONObject>builder()
                .hostname(HOSTNAME)
                .port(3306)
                .username(USERNAME)
                .password(PASSWORD)
                .databaseList(databaseList)
                .tableList(tableList)
//                .serverTimeZone(SERVER_TIME_ZONE)
                .deserializer(new MyDeserializer())
                .build();
    }

**Comment by wuqingquan-github** [comment] 2021-08-23 08:15
env.addSource(getCDC(DATABASE, TABLE)).print();

mysql中数据：start_time和end_time都是datetime类型
{"id_card":"362324","end_time":2021-08-14 08:55:11,"start_time":2021-08-14 08:44:08,"id":72}

不管是否添加配置：SERVER_TIME_ZONE=Asia/Shanghai，结果都一样
"data":{"id_card":"362324","end_time":1628931311000,"start_time":1628930648000,"id":72}
打印的结果转换为LocalDateTime分别是2021-08-14 16:44:08和2021-08-14 16:55:11

    public static DebeziumSourceFunction<JSONObject> getCDC(String databaseList, String tableList) {
        return MySQLSource.<JSONObject>builder()
                .hostname(HOSTNAME)
                .port(3306)
                .username(USERNAME)
                .password(PASSWORD)
                .databaseList(databaseList)
                .tableList(tableList)
                .serverTimeZone(SERVER_TIME_ZONE)
                .deserializer(new MyDeserializer())
                .build();
    }

**Comment by ZhuJiang121** [comment] 2021-08-24 09:08
我遇到了类似的问题，我的现象是这样的，首先我的 mysql 本地库的时区是 UTC +8 时区，当我配置server-time-zone为 Asia/Shanghai 时 我的 datetime 类型与 timestamp 类型字段都比原字段时间多了 8 小时，当我配置 server-time-zone 为 UTC 时，我的 datetime 类型时间显示与原字段一致，但timestamp 字段比原字段时间多了 8 小时。 flink 1.13.1， flink cdc 2.0.0

> CREATE TABLE source_user_info (  `UserId` INT, `UserName` STRING, `IsAdmin` TINYINT, `LastLogin` TIMESTAMP(3), `TestTime` TIMESTAMP(3),PRIMARY KEY( UserId ) NOT ENFORCED ) WITH (
  'connector' = 'mysql-cdc',
  'scan.startup.mode' = 'initial',
  'hostname' = '172.16.10.138',
  'port' = '3306',
  'username' = 'root',
  'password' = 'root',
  'database-name' = 'hcdsj',
  'table-name' = 'user_info',
  'server-time-zone' = 'Asia/Shanghai',
  'debezium.snapshot.locking.mode' = 'none'

**当我使用 flink 1.12.2 flink cdc 1.2.0 时，可以通过指定'debezium.database.serverTimezone' = 'Asia/Shanghai' 来使 timestamp 类型字段显示正常，但那时 datetime 不正常**

**Comment by ZhuJiang121** [comment] 2021-08-24 09:27
我遇到了类似的问题，我的现象是这样的，首先我的 mysql 本地库的时区是 UTC +8 时区， flink 1.13.1， flink cdc 2.0.0

> CREATE TABLE source_user_info (  `UserId` INT, `UserName` STRING, `IsAdmin` TINYINT, `LastLogin` TIMESTAMP(3), `TestTime` TIMESTAMP(3),PRIMARY KEY( UserId ) NOT ENFORCED ) WITH (
  'connector' = 'mysql-cdc',
  'scan.startup.mode' = 'initial',
  'hostname' = '172.16.10.138',
  'port' = '3306',
  'username' = 'root',
  'password' = 'root',
  'database-name' = 'hcdsj',
  'table-name' = 'user_info',
  'server-time-zone' = 'Asia/Shanghai',
  'debezium.snapshot.locking.mode' = 'none'

**当我使用 flink 1.12.2 flink cdc 1.2.0 时，可以通过指定'debezium.database.serverTimezone' = 'Asia/Shanghai' 来使 timestamp 类型字段显示正常，但 datetime 依旧不正常； 当我升级到 2.0.0 后无法通过 debezium.database.serverTimezone 来改变 timestamp 类型的值**

**Comment by luckes-yang** [comment] 2021-11-08 07:01
为什么RowDataDebeziumDeserializeSchema中的convertToTime方法返回的是一个int类型的值，这个怎么转换成java.sql.Time类型呢

**Comment by leonardBang** [comment] 2022-06-24 08:08
I'll open a PR to fix the server timezone issue.

**Comment by PatrickRen** [comment] 2024-02-28 15:40
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:40 UTC
Labels: discussion, resolved
