### ISSUE TITLE
[mysql] Add a option to emit heartbeatEvent to downstream

### ISSUE THREAD

**Issue by zhjwpku** [ververica/flink-cdc-connectors#990] opened 2022-03-23 09:43 UTC
**Is your feature request related to a problem? Please describe.**

This feature is only needed by stream API, table API must not enable this option.

In our use case, we want sourceReader to emit *heartbeat* to downstream, so 
we can extract the `ts_ms` and do some calulation on sink side.  

I'm not sure whether this feature is a general one, so feedback needed, thanks ;)

**Comment by PatrickRen** [comment] 2024-02-28 15:31
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:31 UTC
Labels: enhancement
