### ISSUE TITLE
Support user-defined character sets to match database

### ISSUE THREAD

**Issue by young2633** [ververica/flink-cdc-connectors#1645] opened 2022-10-23 09:32 UTC
**Is your feature request related to a problem? Please describe.**
When i read the mysql database with GBK charset encoding, Chinese garbled characters appeared.

**Describe the solution you'd like**
add configuration to define charset to march database.

**Describe alternatives you've considered**
modify the method "patternBasedFactory" in io.debezium.jdbc.JdbcConnection, eg: modify the jdbc url by passing user-defined configuration

**Comment by PatrickRen** [comment] 2024-02-28 15:03
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:03 UTC
Labels: enhancement
