### ISSUE TITLE
cdc  includeSchemaChanges(true)  无法获取历史ddl 

### ISSUE THREAD

**Issue by fengfuli** [ververica/flink-cdc-connectors#1045] opened 2022-04-04 02:34 UTC
MySqlSource<String> mySqlSource = MySqlSource.<String>builder()
                .hostname("host")
                .port(3306)
                .databaseList("xx") 
                .tableList("xxx")
                .username("root")
                .password("xxxx")
                .deserializer(new JsonDebeziumDeserializationSchema()) 
                .startupOptions(StartupOptions.initial())
                .includeSchemaChanges(true)
                .build();
按照官方例子 对存量数据进行消费，并开启schema  ,能获取到历史的数据  但是无法捕获到历史的ddl, 只能获取增量的schema变化

场景：通过cdc 捕获到用户填写的数据源，获取该数据源历史的ddl 元数据信息到平台

**Comment by smdxdxd** [comment] 2022-06-16 12:51
我遇到了同样的问题，无法获取历史数据的建表DDL，只能借助Druid来获取所有create table scripts

**Comment by hqbhoho** [comment] 2022-10-10 09:37
+1

**Comment by PatrickRen** [comment] 2024-02-28 15:37
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:37 UTC
Labels: enhancement
