### ISSUE TITLE
flink-cdc读取pgsql数据，延迟几个小时，任务启动后会关闭连接debezium.jdbc.JdbcConnection   Connection gracefully closed

### ISSUE THREAD

**Issue by xiongmozhou** [ververica/flink-cdc-connectors#178] opened 2021-05-11 06:46 UTC
看了下日志，会报异常postgresql.util.PSQLException: Database connection failed when reading from copy，请问这个需要怎么解决呢

**Comment by PatrickRen** [comment] 2024-02-28 15:14
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:14 UTC
Labels: discussion
