### ISSUE TITLE
Awesome Flink CDC with Data Lake/Data WareHosue

### ISSUE THREAD

**Issue by luoyuxia** [ververica/flink-cdc-connectors#524] opened 2021-10-26 04:29 UTC
In here, I would like to collect some artices about the practice that intergrate with some popular datalakes like  Iceberg/ Hudi and data warehouse like Doris/Clickhouse.

Welcome everyone to help enrich it.

**Comment by luoyuxia** [comment] 2021-11-29 06:16
A demo for Flink MySQL -> ES && Kafka && Hudi  based on Docker enviroment

https://www.yuque.com/docs/share/271a9165-02f9-4dbb-8e70-13a5e547bb6c?#MnFiJ

**Comment by PatrickRen** [comment] 2024-02-28 15:11
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:11 UTC
