### ISSUE TITLE
Support multiple parallelism to read binglog

### ISSUE THREAD

**Issue by lugela** [ververica/flink-cdc-connectors#428] opened 2021-09-15 09:12 UTC
Is there any plan to support multiple parallelism reading binlog?

**Comment by leonardBang** [comment] 2021-09-15 09:39
Could you share your motivation why we need to support parallelism reading?

**Comment by lugela** [comment] 2021-09-16 01:06
When the business system has a large number of insert, delete, update, synchronization will be delayed. At the same time, in the later stage, roadmap supports the synchronization of the whole database, and the delay will increase if the degree of parallelism is single. Personally immature proposal。

**Comment by wuchong** [comment] 2021-09-18 11:50
@lugela , did you hit a bottleneck in binlog phase? Usually, this shouldn't be a bottleneck in reader, because MySQL don't support too much writing throughput.

**Comment by PatrickRen** [comment] 2024-02-28 15:12
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:12 UTC
Labels: enhancement, discussion
