### ISSUE TITLE
sql server2008 企业版是支持cdc的，但是代码提示版本过低

### ISSUE THREAD

**Issue by JackTianZhao** [ververica/flink-cdc-connectors#1490] opened 2022-08-19 03:41 UTC
尝试自己用源码编译后可以通过
![图片](https://user-images.githubusercontent.com/40516297/185538091-4066e959-23ee-4acc-972f-04bb4e96b396.png)

**Comment by GOODBOY008** [comment] 2022-08-19 14:45
@JackTianZhao Hi, sql server 2008 cann't pass all unit test and version is too old. I don't suggest you to do this , maybe cause production accident.

**Comment by yasz** [comment] 2022-11-26 16:34
hope ur great team can support this version!

**Comment by 1lo0** [comment] 2023-01-31 14:36
希望能尽快支持，现在依然有不少老版本的在跑，这会让flink-cdc更宽容！！

**Comment by switlen** [comment] 2023-03-17 06:33
hope flink can support this version!

**Comment by PatrickRen** [comment] 2024-02-28 15:04
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:04 UTC
Labels: bug
