### ISSUE TITLE
How to deal the "Failed to deserialize data of EventHeaderV4"?

### ISSUE THREAD

**Issue by onefeng** [ververica/flink-cdc-connectors#1096] opened 2022-04-20 13:26 UTC
org.apache.kafka.connect.errors.ConnectException: com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1650449053000, eventType=WRITE_ROWS, serverId=21150363, headerLength=19, dataLength=8022, nextPosition=419757365, flags=0}
	at io.debezium.connector.mysql.AbstractReader.wrap(AbstractReader.java:241) ~[blob_p-c04644864cea94e1416c7464511a98e6a4a537da-b73d0c5056484cc7352e1cc0c5b69def:?]
	at io.debezium.connector.mysql.AbstractReader.failed(AbstractReader.java:218) ~[blob_p-c04644864cea94e1416c7464511a98e6a4a537da-b73d0c5056484cc7352e1cc0c5b69def:?]
	at io.debezium.connector.mysql.BinlogReader.handleEvent(BinlogReader.java:607) ~[blob_p-c04644864cea94e1416c7464511a98e6a4a537da-b73d0c5056484cc7352e1cc0c5b69def:?]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.notifyEventListeners(BinaryLogClient.java:1104) [blob_p-c04644864cea94e1416c7464511a98e6a4a537da-b73d0c5056484cc7352e1cc0c5b69def:?]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:955) [blob_p-c04644864cea94e1416c7464511a98e6a4a537da-b73d0c5056484cc7352e1cc0c5b69def:?]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:595) [blob_p-c04644864cea94e1416c7464511a98e6a4a537da-b73d0c5056484cc7352e1cc0c5b69def:?]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:839) [blob_p-c04644864cea94e1416c7464511a98e6a4a537da-b73d0c5056484cc7352e1cc0c5b69def:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.RuntimeException: com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1650449053000, eventType=WRITE_ROWS, serverId=21150363, headerLength=19, dataLength=8022, nextPosition=419757365, flags=0}
	at io.debezium.connector.mysql.BinlogReader.handleServerIncident(BinlogReader.java:675) ~[blob_p-c04644864cea94e1416c7464511a98e6a4a537da-b73d0c5056484cc7352e1cc0c5b69def:?]
	at io.debezium.connector.mysql.BinlogReader.handleEvent(BinlogReader.java:590) ~[blob_p-c04644864cea94e1416c7464511a98e6a4a537da-b73d0c5056484cc7352e1cc0c5b69def:?]
	... 5 more
Caused by: com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1650449053000, eventType=WRITE_ROWS, serverId=21150363, headerLength=19, dataLength=8022, nextPosition=419757365, flags=0}
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:304) ~[blob_p-c04644864cea94e1416c7464511a98e6a4a537da-b73d0c5056484cc7352e1cc0c5b69def:?]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:227) ~[blob_p-c04644864cea94e1416c7464511a98e6a4a537da-b73d0c5056484cc7352e1cc0c5b69def:?]
	at io.debezium.connector.mysql.BinlogReader$1.nextEvent(BinlogReader.java:252) ~[blob_p-c04644864cea94e1416c7464511a98e6a4a537da-b73d0c5056484cc7352e1cc0c5b69def:?]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:934) ~[blob_p-c04644864cea94e1416c7464511a98e6a4a537da-b73d0c5056484cc7352e1cc0c5b69def:?]
	... 3 more
Caused by: java.io.EOFException
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.read(ByteArrayInputStream.java:192) ~[blob_p-c04644864cea94e1416c7464511a98e6a4a537da-b73d0c5056484cc7352e1cc0c5b69def:?]
	at java.io.InputStream.read(InputStream.java:170) ~[?:1.8.0_181]
	at java.io.InputStream.skip(InputStream.java:224) ~[?:1.8.0_181]
	at com.github.shyiko.mysql.binlog.io.ByteArrayInputStream.skipToTheEndOfTheBlock(ByteArrayInputStream.java:219) ~[blob_p-c04644864cea94e1416c7464511a98e6a4a537da-b73d0c5056484cc7352e1cc0c5b69def:?]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:300) ~[blob_p-c04644864cea94e1416c7464511a98e6a4a537da-b73d0c5056484cc7352e1cc0c5b69def:?]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:227) ~[blob_p-c04644864cea94e1416c7464511a98e6a4a537da-b73d0c5056484cc7352e1cc0c5b69def:?]
	at io.debezium.connector.mysql.BinlogReader$1.nextEvent(BinlogReader.java:252) ~[blob_p-c04644864cea94e1416c7464511a98e6a4a537da-b73d0c5056484cc7352e1cc0c5b69def:?]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:934) ~[blob_p-c04644864cea94e1416c7464511a98e6a4a537da-b73d0c5056484cc7352e1cc0c5b69def:?]
	... 3 more

**Comment by zhilinli123** [comment] 2022-05-06 07:21
How did you solve the problem at last?
@onefeng

**Comment by li57598** [comment] 2022-10-26 03:26
I encountered the same problem in version 2.2. How did you solve it at last？ @onefeng

**Comment by PatrickRen** [comment] 2024-02-28 15:08
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:08 UTC
Labels: bug
