### ISSUE TITLE
[docs] Translate the FAQ documentation to English

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#725] opened 2021-12-15 07:46 UTC
We collected some user feedbacks and FAQ from Flink CDC Chinese DingTalk Group and make them documented on Github wiki.

We should also translate the documentation to English which can help more users.

**Comment by leonardBang** [comment] 2021-12-15 07:46
https://github.com/ververica/flink-cdc-connectors/wiki/FAQ(%E4%B8%AD%E6%96%87)

**Comment by rookiegao** [comment] 2021-12-15 09:06
Can I try to solve this issue?

This is an example I have tried:

For Oracle version 11, debezium will set tableidcasesensitive to true by default, resulting in the table name being updated to lowercase. Therefore, the table completion log setting cannot be queried in Oracle, resulting in the false alarm of "supplementary logging not configured for table error".

If it is the datastream API, add the configuration item of debezium 'database. tablename. case. insensitive' = 'false'. If the SQL method is used, add the configuration item 'debezium. database. tablename. case. insensitive' = 'false' in the option of the table

对于 oracle11 版本，debezium 会默认把 tableIdCaseInsensitive 设置为true, 导致表名被更新为小写，因此在oracle中查询不到 这个表补全日志设置，导致误报这个Supplemental logging not configured for table 错误”。 添加 debezium 的配置项 'database.tablename.case.insensitive' = 'false'， 如果使用 SQL 的方式，则在表的 option 中添加配置项 'debezium.database.tablename.case.insensitive' = 'false'

**Comment by leonardBang** [comment] 2021-12-16 03:02
@rookiegao 
Thanks for picking this, only the maintainer can create the wiki, but I can help do this after the translation finished.
I think we can 
(1) Translate the FAQ(中文) document to English documentation in markdown format firstly
(2) Merge the Connectors FAQ e.g. [MySQL FAQ](https://ververica.github.io/flink-cdc-connectors/release-2.1/content/connectors/mysql-cdc.html#faq ) into the FAQ(中文) document
(3) Remove the Connectors FAQ document with the  FAQ(中文) document link
How do you think ?

**Comment by leonardBang** [comment] 2021-12-16 03:02
@rookiegao 
Thanks for picking this, only the maintainer can create the wiki, but I can help do this after the translation finished.
I think we can 
(1) Translate the FAQ(中文) document to English documentation in markdown format firstly
(2) Merge the Connectors FAQ e.g. [MySQL FAQ](https://ververica.github.io/flink-cdc-connectors/release-2.1/content/connectors/mysql-cdc.html#faq ) into the FAQ(中文) document
(3) Remove the Connectors FAQ document with the  FAQ(中文) document link
How do you think ?

**Comment by leonardBang** [comment] 2021-12-16 03:02
@rookiegao 
Thanks for picking this, only the maintainer can create the wiki, but I can help do this after the translation finished.
I think we can 
(1) Translate the FAQ(中文) document to English documentation in markdown format firstly
(2) Merge the Connectors FAQ e.g. [MySQL FAQ](https://ververica.github.io/flink-cdc-connectors/release-2.1/content/connectors/mysql-cdc.html#faq ) into the FAQ(中文) document
(3) Remove the Connectors FAQ document with the  FAQ(中文) document link
How do you think ?

**Comment by rookiegao** [comment] 2021-12-16 04:47
That's a good idea. I'll finish it soon

**Comment by PatrickRen** [comment] 2024-02-28 15:32
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:32 UTC
Labels: docs, enhancement
