### ISSUE TITLE
 insert into mysql by stream api

### ISSUE THREAD

**Issue by linmingze** [ververica/flink-cdc-connectors#1595] opened 2022-09-29 07:33 UTC
Is there any case that deserialize debezium SourceRecord to sql or other for insert mysql.
Table Api change SourceRecord to RowData,but it do not suppot multi table.

**Comment by PatrickRen** [comment] 2024-02-28 15:28
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:28 UTC
Labels: enhancement
