### ISSUE TITLE
SqlServer 的TIMESTAMP类型无法转换为合法的flinkSQL的数据类型

### ISSUE THREAD

**Issue by Adiao512** [ververica/flink-cdc-connectors#1485] opened 2022-08-18 02:00 UTC
The value type of XDBMASK field is TIMESTAMP in SqlServer (this field data is binary in SqlServer), but the value type of XDBMASK field is BIGint in mysql，When data is synchronized from SqlServer to mysql via Flink-CDC, the data is converted to FlinkSQL's data type as a bunch of Java objects (java.nio.heapByteBuffer [pos=0 lim=8 cap=8])，Unable to write to mysql
![ea8b1f76e95da94d3223e3d0d98c8e1](https://user-images.githubusercontent.com/111474159/185275546-b3fc7118-4b47-4ba6-94d9-bad7692b5c30.jpg)

**Comment by GOODBOY008** [comment] 2022-08-19 01:17
Hi @Adiao512 , Can you supply sql script and data to reproduce the issue ?

**Comment by PatrickRen** [comment] 2024-02-28 15:05
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:05 UTC
Labels: bug
