### ISSUE TITLE
flinkcdc 同步kafka的数据到pg数据重启任务，库丢数据的问题

### ISSUE THREAD

**Issue by lg4546** [ververica/flink-cdc-connectors#245] opened 2021-07-13 02:42 UTC
Flink SQL> CREATE TABLE flink_ub_pv_uv(
> cip String,t String,ua String,
> data ROW<appId int,sysId int,vs String,fid String,et int,uid String,vid  String,pid String,body ROW<vo String,net String,ci String,bs String>>
> )WITH(
> 'connector' = 'kafka'
> ,'topic' = 'topic-1'
> ,'properties.bootstrap.servers' = '17.16.16.210:9092,17.16.16.211:9092'
> ,'properties.group.id' = 'pv_uv-group'
> ,'properties.enable.auto.commit' = 'true'
> ,'scan.startup.mode' = 'group-offsets'
> ,'format' = 'json'
> ,'json.fail-on-missing-field' = 'false'
> ,'json.ignore-parse-errors' = 'true'
> );

Flink SQL> CREATE TABLE ods_t_ub_pv_uv(
> appid INTEGER NULL,  
> sysid INTEGER NULL, 
> fid String NULL,  
> et Integer NULL,  
> uid String NULL, 
> vid String NULL, 
> pid String NULL,  
> vs String NULL,  
> vo String NULL,
> net String NULL,
> ci String NULL,
> cn String NULL,
> co String NULL,
> bs String NULL,
> ua String NULL,
> cip String NULL, -- 客户端ip
> t String NULL -- 服务器端接收时间
> )with(
> 'connector' = 'jdbc'
> ,'url' = 'jdbc:postgresql://17.16.16.213:5432/hua?currentSchema=hua_ods'
> ,'username' = 'postgres'
> ,'password' = 'postgres'
> ,'table-name' = 'ods_t_ub_pv_uv'
> ,'driver' = 'org.postgresql.Driver');
[INFO] Table has been created.

Flink SQL> insert into ods_t_ub_pv_uv
> select data.appId,data.sysId,data.fid,data.et,data.uid,data.vid,data.pid,data.vs,body.vo,body.net,body.ci,'cn','co',body.bs,ua,cip,t from flink_ub_pv_uv;

我用这种方式同步kafka的数据到pg数据库，但是如果这个任务失败了，重新启动任务后，这个期间kafka新生成的数据就丢失了，不会插入到数据库，如果修改成 ,'scan.startup.mode' = 'earliest-offset' 就又会把之前所有的数据全部同步过来了，有人遇到相同的问题？

**Comment by ZhangChaoming** [comment] 2021-07-13 09:07
@lg4546 Did you enbale periodic checkpoint ?

**Comment by lg4546** [comment] 2021-08-24 09:52
![image](https://user-images.githubusercontent.com/7876402/130596216-c7a8f0ca-6717-4a9b-8dfb-bd79d05a673f.png)
我已经在flink-conf.yaml文件修改了增加了配置项。
![image](https://user-images.githubusercontent.com/7876402/130596366-f501f24e-8f26-4c7c-aa5c-8816b01b8d14.png)
ling'w另外在flink的界面也能看到point的信息，但是就是没有生效

**Comment by PatrickRen** [comment] 2024-02-28 15:33
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:33 UTC
Labels: question
