### ISSUE TITLE
Postgres CDC connnector - custom query 

### ISSUE THREAD

**Issue by SwapnilKhante** [ververica/flink-cdc-connectors#1051] opened 2022-04-06 13:21 UTC
Hello Team,

I was wondering if is there a way to use customer query (with joins) instead of providing a table name or list of tables.
My requirement is to use Flink CDC connector to get a source from the Postgres database but needs to watch multiple tables with a join condition.
If this is not possible is it possible to pass the View name instead of the table name in the PostgresTableSource builder.

thanks,
Swapnil

**Comment by PatrickRen** [comment] 2024-02-28 15:37
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:37 UTC
Labels: enhancement
