### ISSUE TITLE
[mysql]  if colunm defined default value and nullable,when column value is null. flink-cdc catch field value is default

### ISSUE THREAD

**Issue by GOODBOY008** [ververica/flink-cdc-connectors#516] opened 2021-10-21 09:45 UTC
**Describe the bug**

**Environment :**
 - Flink version :  1.12
 - Flink CDC version:  release-2.0
 - Database and version:  mysql 5.7

**To Reproduce**
1. Thes test data :
<img width="926" alt="1634809289(1)" src="https://user-images.githubusercontent.com/13617900/138252730-5192d551-7a5a-4e81-9797-a4f34a8cfa4e.png">

2. The test code and error :
<img width="1242" alt="lALPDhYBRlulJ9_NBkHNCbQ_2484_1601" src="https://user-images.githubusercontent.com/13617900/138252612-7ef6a1f4-4ab2-4f44-a91f-7c7e7b49c2df.png">

**Additional Description**
I found problem is here.
<img width="1105" alt="1634797330662_10D29C1C-6D0D-4c64-9BBC-4DD02FC76DC2" src="https://user-images.githubusercontent.com/13617900/138253151-1760efe1-d306-4808-ada4-f223721b2eb0.png">
<img width="1189" alt="1634797387199_3A5A0AC5-1856-4cc3-AE4A-06BBE77613F8" src="https://user-images.githubusercontent.com/13617900/138253182-16be77b2-87b7-4a97-bfe7-c335b93a4fff.png">

I will submit a pr to fix this.

**Comment by GOODBOY008** [comment] 2021-11-04 15:20
This issue maybe discuss  at kafka [issuse](https://issues.apache.org/jira/browse/KAFKA-13433?jql=labels%20%3D%20connect-api).

**Comment by coalchan** [comment] 2023-11-30 02:21
补充下，如果使用了 `JsonDebeziumDeserializationSchema`
将 connect-json 版本升级到 3.5，并且配置 JsonConverterConfig.REPLACE_NULL_WITH_DEFAULT_CONFIG 为 false 即可。

具体如下：其中 kafka.version 为 3.5.0
```xml
<dependency>
    <groupId>com.ververica</groupId>
    <artifactId>flink-connector-mysql-cdc</artifactId>
    <version>2.4.2</version>
    <exclusions>
        <exclusion>
            <groupId>org.apache.kafka</groupId>
            <artifactId>connect-api</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.apache.kafka</groupId>
            <artifactId>connect-runtime</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.apache.kafka</groupId>
            <artifactId>connect-json</artifactId>
        </exclusion>
        <exclusion>
            <groupId>org.apache.kafka</groupId>
            <artifactId>connect-file</artifactId>
        </exclusion>
    </exclusions>
</dependency>

<dependency>
    <groupId>org.apache.kafka</groupId>
    <artifactId>connect-runtime</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-log4j-appender</artifactId>
        </exclusion>
        <exclusion>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
        </exclusion>
    </exclusions>
    <version>${kafka.version}</version>
</dependency>
<dependency>
    <groupId>org.apache.kafka</groupId>
    <artifactId>connect-json</artifactId>
    <version>${kafka.version}</version>
</dependency>
<dependency>
    <groupId>org.apache.kafka</groupId>
    <artifactId>connect-file</artifactId>
    <version>${kafka.version}</version>
</dependency>
```

使用时：

```java
Map<String, Object> config = new HashMap<>(1);
config.put(JsonConverterConfig.REPLACE_NULL_WITH_DEFAULT_CONFIG, false);
JsonDebeziumDeserializationSchema schema = new JsonDebeziumDeserializationSchema(false, config);
```

**Comment by PatrickRen** [comment] 2024-02-28 15:11
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:11 UTC
Labels: bug
