### ISSUE TITLE
使用mysql同步至starrocks，如果上游mysql停止生产数据后，如何判断flink是否已经消费完mysql最新的数据

### ISSUE THREAD

**Issue by hellolilyliuyi** [ververica/flink-cdc-connectors#1708] opened 2022-11-07 06:02 UTC
**Describe the bug(Please use English)**

使用mysql同步至sr，如果上游mysql停止生产数据后，如何确定flink已经消费完mysql最新的数据 @leonardBang

**Environment :**
 - Flink version :  
 - Flink CDC version: 
 - Database and version: 

**To Reproduce**
1. The test data :
2. The test code :
3. The error :

**Additional Description**

**Comment by Jiabao-Sun** [comment] 2022-11-07 09:43
Maybe we can check the max last modified time of records.
By the way, there's `op_ts` metadata indicates the time that the change was made in the database.
Refers to https://ververica.github.io/flink-cdc-connectors/master/content/connectors/mysql-cdc.html#available-metadata for detail.

Hope it helps you.

**Comment by PatrickRen** [comment] 2024-02-28 14:50
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 14:50 UTC
Labels: question
