### ISSUE TITLE
kafka changelog json 数据没写进去。

### ISSUE THREAD

**Issue by Lswx2017** [ververica/flink-cdc-connectors#56] opened 2020-11-13 06:27 UTC
按照https://github.com/ververica/flink-cdc-connectors/wiki/%E4%B8%AD%E6%96%87%E6%95%99%E7%A8%8B 方法，执行到
第7步
--Flink SQL
CREATE TABLE kafka_gmv (
  day_str STRING,
  gmv DECIMAL(10, 5)
) WITH (
    'connector' = 'kafka',
    'topic' = 'kafka_gmv',
    'scan.startup.mode' = 'earliest-offset',
    'properties.bootstrap.servers' = 'localhost:9092',
    'format' = 'changelog-json'
);

INSERT INTO kafka_gmv
SELECT DATE_FORMAT(order_date, 'yyyy-MM-dd') as day_str, SUM(price) as gmv
FROM orders
WHERE order_status = true
GROUP BY DATE_FORMAT(order_date, 'yyyy-MM-dd');

-- 读取 Kafka 的 changelog 数据，观察 materialize 后的结果
SELECT * FROM kafka_gmv;

kafka中topic也创建了，但是一直没有消息进去。但是单独执行
SELECT DATE_FORMAT(order_date, 'yyyy-MM-dd') as day_str, SUM(price) as gmv
FROM orders
WHERE order_status = true
GROUP BY DATE_FORMAT(order_date, 'yyyy-MM-dd');

又是有结果的。

**Comment by Lswx2017** [comment] 2020-11-13 06:28
补充一下，lib下的jar包如下
drwxr-xr-x. 1 flink flink      4096 Nov 13 13:46 .
drwxr-xr-x. 1 flink flink        40 Sep 17 06:52 ..
-rw-r--r--. 1 flink flink     90785 Sep 10 11:44 flink-csv-1.11.2.jar
-rw-r--r--. 1 flink flink 108356096 Sep 10 11:48 flink-dist_2.11-1.11.2.jar
-rw-r--r--. 1 flink flink     19301 Sep  2 16:30 flink-format-changelog-json-1.1.0.jar
-rw-r--r--. 1 flink flink     95092 Sep 10 11:44 flink-json-1.11.2.jar
-rw-r--r--. 1 flink flink   7712156 Jun 18 10:42 flink-shaded-zookeeper-3.4.14.jar
-rw-r--r--. 1 flink flink  26053432 Sep 10 01:18 flink-sql-connector-elasticsearch7_2.11-1.11.2.jar
-rw-r--r--. 1 flink flink   3541819 Sep 10 01:19 flink-sql-connector-kafka_2.11-1.11.2.jar
-rw-r--r--. 1 flink flink  26598279 Sep  2 16:29 flink-sql-connector-mysql-cdc-1.1.0.jar
-rw-r--r--. 1 flink flink  23696488 Sep  2 16:29 flink-sql-connector-postgres-cdc-1.1.0.jar
-rw-r--r--. 1 flink flink  37339075 Sep 10 11:47 flink-table-blink_2.11-1.11.2.jar
-rw-r--r--. 1 flink flink  33327320 Sep 10 11:47 flink-table_2.11-1.11.2.jar
-rw-r--r--. 1 flink flink     67114 Apr 20  2020 log4j-1.2-api-2.12.1.jar
-rw-r--r--. 1 flink flink    276771 Apr 20  2020 log4j-api-2.12.1.jar
-rw-r--r--. 1 flink flink   1674433 Apr 20  2020 log4j-core-2.12.1.jar
-rw-r--r--. 1 flink flink     23518 Apr 20  2020 log4j-slf4j-impl-2.12.1.jar

**Comment by SinyoWong** [comment] 2020-11-26 13:54
我和你的情况相反，kafka 消费者能够正常获取数据，但是 select * from kafka_gmv 为空。

**Comment by jinguangyu** [comment] 2021-02-22 11:29
我是只有kafka里有log，flink sql client查询kafka_gmv没数据

**Comment by PatrickRen** [comment] 2024-02-28 15:38
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:38 UTC
Labels: discussion
