### ISSUE TITLE
mysql cdc job faild com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool

### ISSUE THREAD

**Issue by Matrix42** [ververica/flink-cdc-connectors#1272] opened 2022-06-10 08:58 UTC
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  1.14.2
 - Flink CDC version: 2.2
 - Database and version: mysql 5.7 

**To Reproduce**

start  mysql cdc job repeatedly with different source, there will some connection connect to mysql not closed.

 
![f8ea76e49d6716e04b16ff5e2912b37](https://user-images.githubusercontent.com/13606692/173029542-5bd8e1b1-f3ea-44ee-a5e5-285746c89a14.png)

> flink host is 192.168.10.22

I think this because the `HikariDataSource` was not closed properly.

![image](https://user-images.githubusercontent.com/13606692/173030090-8272edb5-6039-4fab-85d0-2ed920821905.png)

There isn't any code to close the `HikariDataSource`.

**Comment by PatrickRen** [comment] 2024-02-28 15:06
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:06 UTC
Labels: bug
