### ISSUE TITLE
为过程或函数 cdc.fn_cdc_get_all_changes_ ...  提供的参数数目不足

### ISSUE THREAD

**Issue by murongpingtian** [ververica/flink-cdc-connectors#1083] opened 2022-04-18 09:58 UTC
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  1.13.5
 - Flink CDC version: 2.3
 - Database and version: sqlserver2016

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :
2022-04-17 19:05:36
com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.
	at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:42)
	at io.debezium.connector.sqlserver.SqlServerStreamingChangeEventSource.execute(SqlServerStreamingChangeEventSource.java:292)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:152)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: 为过程或函数 cdc.fn_cdc_get_all_changes_ ...  提供的参数数目不足。
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet$FetchBuffer.nextRow(SQLServerResultSet.java:5427)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.fetchBufferNext(SQLServerResultSet.java:1758)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.next(SQLServerResultSet.java:1016)
	at io.debezium.pipeline.source.spi.ChangeTableResultSet.next(ChangeTableResultSet.java:63)
	at io.debezium.connector.sqlserver.SqlServerStreamingChangeEventSource.lambda$execute$1(SqlServerStreamingChangeEventSource.java:181)
	at io.debezium.jdbc.JdbcConnection.prepareQuery(JdbcConnection.java:608)
	at io.debezium.connector.sqlserver.SqlServerConnection.getChangesForTables(SqlServerConnection.java:226)
	at io.debezium.connector.sqlserver.SqlServerStreamingChangeEventSource.execute(SqlServerStreamingChangeEventSource.java:171)
	... 7 more
**Additional Description**

**Comment by PatrickRen** [comment] 2022-04-19 09:30
@murongpingtian Could you provide more details about your case like SQL statement, config and logs?

**Comment by murongpingtian** [comment] 2022-04-25 03:00
get sqlserver cdc ,insert into postgresql

**Comment by Xiaojun-Pan** [comment] 2022-06-25 10:38
Has this problem been solved, and if so, can you share it? Thanks!

**Comment by PatrickRen** [comment] 2024-02-28 15:09
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:09 UTC
Labels: bug
