### ISSUE TITLE
Error in inserting data into es on Flink SQL CLI

### ISSUE THREAD

**Issue by OxYGC** [ververica/flink-cdc-connectors#1353] opened 2022-07-06 09:37 UTC
**Describe the bug(Please use English)**
Error in inserting data into es on Flink SQL CLI

```
[INFO] Submitting SQL update statement to the cluster...
[ERROR] Could not execute SQL statement. Reason:
java.lang.ClassNotFoundException: org.apache.http.HttpHost
```

**Environment :**
 - Flink version :  1.15.0
 - Flink CDC version: 1.15.0
 - Database and version:  MYSQL 5.7 AND ES 7.0

**To Reproduce**

Official documents are used：

ververica.github.io/flink-cdc-connectors/release-2.1/content/%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B/mysql-postgres-tutorial-zh.html#elasticsearch

**Additional Description**

**Comment by zhongyiio** [comment] 2022-08-09 10:02
+1

### Environment :

Flink version : 1.14.5

flink-sql-connector-mysql-cdc-2.1.1.jar
flink-connector-elasticsearch7_2.12-1.14.5.jar
flink-connector-elasticsearch-base_2.12-1.14.5.jar

**Comment by PatrickRen** [comment] 2024-02-28 15:05
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:05 UTC
Labels: bug
