### ISSUE TITLE
Incorrect information in file: './sys/tdsql.frm' Error code: 1033; SQLSTATE: HY000.

### ISSUE THREAD

**Issue by MyLanPangzi** [ververica/flink-cdc-connectors#156] opened 2021-04-12 06:43 UTC
mysql: 5.7.17-11-V2.0R530D002-20190816-1203-log
java: 1.8
flink: 1.12.0
flink-connector-mysql-cdc.version: 1.2 1.3

**when i downgrade to 1.1 . it's ok.**

startup throw exception: 
[ERROR] 2021-04-12 14:39:29.433 [debezium-engine] DebeziumSourceFunction - Reporting error:
org.apache.kafka.connect.errors.ConnectException: Incorrect information in file: './sys/tdsql.frm' Error code: 1033; SQLSTATE: HY000.
	at io.debezium.connector.mysql.AbstractReader.wrap(AbstractReader.java:241) ~[flink-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at io.debezium.connector.mysql.AbstractReader.failed(AbstractReader.java:218) ~[flink-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at io.debezium.connector.mysql.SnapshotReader.execute(SnapshotReader.java:857) ~[flink-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.sql.SQLException: Incorrect information in file: './sys/tdsql.frm'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[flink-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[flink-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[flink-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1200) ~[flink-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at io.debezium.jdbc.JdbcConnection.query(JdbcConnection.java:554) ~[flink-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at io.debezium.jdbc.JdbcConnection.query(JdbcConnection.java:497) ~[flink-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at io.debezium.connector.mysql.SnapshotReader.readTableSchema(SnapshotReader.java:888) ~[flink-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at io.debezium.connector.mysql.SnapshotReader.execute(SnapshotReader.java:550) ~[flink-connector-mysql-cdc-1.2.0.jar:1.2.0]
	... 3 more

**Comment by PatrickRen** [comment] 2024-02-28 15:15
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:15 UTC
Labels: question
