### ISSUE TITLE
Correct Usage for DataStream API 

### ISSUE THREAD

**Issue by minchowang** [ververica/flink-cdc-connectors#414] opened 2021-09-09 08:45 UTC
**Is your feature request related to a problem? Please describe.**
When users use the DataStream API, they often encounter the following problems:
1. Incorrect use of `no lock mode`. 
e.g. `debeziumProperties.put("debezium.snapshot.locking.mode", "none")`
2. The captured table could not be set up correctly..
e.g. `tableList("tableName")`
3. Unable to get json output.
e.g. `deserializer(new StringDebeziumDeserializationSchema())`

**Describe the solution you'd like**
Correct usage for DataStream API:
```java
Properties debeziumProperties = new Properties();
      debeziumProperties.put("snapshot.locking.mode", "none");// do not use lock
      SourceFunction<String> sourceFunction = MySQLSource.<String>builder()
      .hostname("yourHostname")
      .port(yourPort)
      .databaseList("yourDatabaseName") // set captured database
      .tableList("yourDatabaseName.yourTableName") // set captured table
      .username("yourUsername")
      .password("yourPassword")
      .deserializer(new JsonDebeziumDeserializationSchema()) // converts SourceRecord to JSON String
      .debeziumProperties(debeziumProperties)
      .build();
```

**Comment by PatrickRen** [comment] 2024-02-28 15:12
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:12 UTC
Labels: docs, enhancement
