### ISSUE TITLE
flink-cdc-connectors-master  源码编译失败了,

### ISSUE THREAD

**Issue by ithjz** [ververica/flink-cdc-connectors#131] opened 2021-03-20 07:38 UTC
com.alibaba.ververica.cdc.debezium.internal .DebeziumChangeConsumer  这个类有方法找不到,,

 
第 101 行的 MemoryUtils.UNSAFE.monitorEnter(checkpointLock);     monitorExit方法找不到,是不是漏提交代码?
monitorExit

**Comment by MichaelXucf** [comment] 2021-03-22 02:15
you can use jdk 1.8 to compile the project.

**Comment by EllenAdams** [comment] 2021-06-01 06:25
`[INFO] /Users/xueersi/IdeaProjects/study/flink-cdc-connectors/flink-connector-debezium/src/main/java/com/alibaba/ververica/cdc/debezium/utils/TemporalConversions.java: /Users/xueersi/IdeaProjects/study/flink-cdc-connectors/flink-connector-debezium/src/main/java/com/alibaba/ververica/cdc/debezium/utils/TemporalConversions.java使用或覆盖了已过时的 API。
[INFO] /Users/xueersi/IdeaProjects/study/flink-cdc-connectors/flink-connector-debezium/src/main/java/com/alibaba/ververica/cdc/debezium/utils/TemporalConversions.java: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/xueersi/IdeaProjects/study/flink-cdc-connectors/flink-connector-debezium/src/main/java/com/alibaba/ververica/cdc/debezium/internal/DebeziumChangeConsumer.java:[154,43] 找不到符号
  符号:   方法 monitorEnter(java.lang.Object)
  位置: 类型为sun.misc.Unsafe的变量 UNSAFE
[ERROR] /Users/xueersi/IdeaProjects/study/flink-cdc-connectors/flink-connector-debezium/src/main/java/com/alibaba/ververica/cdc/debezium/internal/DebeziumChangeConsumer.java:[160,43] 找不到符号
  符号:   方法 monitorExit(java.lang.Object)
  位置: 类型为sun.misc.Unsafe的变量 UNSAFE
[INFO] 2 errors 
`

![image](https://user-images.githubusercontent.com/30849347/120276329-20e35200-c2e5-11eb-8c58-cce04a1f59e8.png)

想问下1.3  编译这个问题能否跳过呢？

**Comment by EllenAdams** [comment] 2021-06-01 06:26
> you can use jdk 1.8 to compile the project.

![image](https://user-images.githubusercontent.com/30849347/120276464-4b350f80-c2e5-11eb-910c-f69f8ecce018.png)
emmm???

**Comment by PatrickRen** [comment] 2024-02-28 15:34
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:34 UTC
Labels: question
