### ISSUE TITLE
Fix the behaviour when the data precision is larger than the specified precision

### ISSUE THREAD

**Issue by fsk119** [ververica/flink-cdc-connectors#663] opened 2021-11-29 02:14 UTC
If the specified precision is smaller than the data precision in `RowDataDebeziumDeserializeSchema`, the `DecimalData#fromBigDecimal` will return null. I think it's better if we just lose the precision rather than lose the whole data.

**Comment by PatrickRen** [comment] 2024-02-28 15:37
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:37 UTC
Labels: enhancement
