### ISSUE TITLE
java.sql.SQLSyntaxErrorException: SHOW command denied to user 'xxx'@'xxxxx' for table 'slave_master_info'

### ISSUE THREAD

**Issue by xpower1984** [ververica/flink-cdc-connectors#180] opened 2021-05-13 08:18 UTC
When debezium start to do snapshot, it will execute 'show databases, show tables ' first, and then execute ' show create table ' for each table .
But the privileges for users on some system databases(eg: mysql) is limited by Cloud Database suppliers. The account can not perform the execution. Such as "SHOW command denied to user 'xxxx'@'xxxx' for table 'slave_master_info'".
Is there any idea to aviod to perform the excuetion on "mysql" database?

**Comment by doudou06180618** [comment] 2021-06-10 06:17
Did you solve it

**Comment by PatrickRen** [comment] 2024-02-28 15:14
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:14 UTC
Labels: discussion
