### ISSUE TITLE
MySQL CDC Connector option 'debezium.snapshot.fetch.size' trap

### ISSUE THREAD

**Issue by jjiey** [ververica/flink-cdc-connectors#98] opened 2021-02-09 07:17 UTC
**This is debezium‘s problem.**

Specify option ``debezium.snapshot.fetch.size``  for MySQL CDC Connector is invalid. The MySQL connection will still pull all results into memory while reading snapshot data, it will cause OOM for very large tables!

reasons as follows:

1) debezium version is 1.2.1.Final in flink-cdc-connectors repo. In Debezium 1.2.1.Final, the version of mysql-connector-java is 8.0.16.

For MySQL Connector/J 8.0, how to tell the driver to stream the results? 

There are two ways:

```java
stmt = conn.createStatement(java.sql.ResultSet.TYPE_FORWARD_ONLY,
              java.sql.ResultSet.CONCUR_READ_ONLY);
stmt.setFetchSize(Integer.MIN_VALUE); // it must be Integer.MIN_VALUE
```

or

```java
conn = DriverManager.getConnection("jdbc:mysql://localhost/?useCursorFetch=true", "user", "s3cr3t"); // set the connection property useCursorFetch to true
stmt = conn.createStatement();
stmt.setFetchSize(100);
```

(see: https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-implementation-notes.html)

2) The value of option ``debezium.snapshot.fetch.size`` will be set to FetchSize in the Debezium source code.

(see: io.debezium.connector.mysql.SnapshotReader#createStatementWithLargeResultSet)

```java
private Statement createStatementWithLargeResultSet(Connection connection) throws SQLException {
        int fetchSize = context.getConnectorConfig().getSnapshotFetchSize();
        Statement stmt = connection.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY);
        stmt.setFetchSize(fetchSize);
        return stmt;
    }
```

But, connection property ``useCursorFetch=true`` is not set in the JDBC url.

(see: io.debezium.connector.mysql.MySqlJdbcContext#MYSQL_CONNECTION_URL)

So, it is invalid.

3)  On the other hand, we can not specify 'debezium.snapshot.fetch.size' = 'Integer.MIN_VALUE' or 'debezium.snapshot.fetch.size' = '-2147483648' in DML. Because an non-negative integer is expected.

(see: io.debezium.config.CommonConnectorConfig#SNAPSHOT_FETCH_SIZE)

4) Actually, if we do not specify ``debezium.snapshot.fetch.size``, it has a default value, Integer.MIN_VALUE.

(see: io.debezium.connector.mysql.MySqlConnectorConfig#DEFAULT_SNAPSHOT_FETCH_SIZE)

**That is, it will stream results default while reading snapshot data if we do not specify ``debezium.snapshot.fetch.size``.**

**Comment by jjiey** [comment] 2021-02-09 07:18
Just to remind everyone.

**Comment by wuchong** [comment] 2021-02-24 07:17
Thanks for the reminder @jjiey . Is this bug been fixed in later Debezium versions?  Is there any ways to workaround from our side?

**Comment by jjiey** [comment] 2021-03-27 05:23
@wuchong Sorry for the late response. And sorry that this is not debezium‘s problem, it's my misunderstanding.

If you want to use 'stream results' in MySQL CDC Connector, first, you must specify the value of option `'debezium.min.row.count.to.stream.results'` is 0 or a value greater than the total count of table. And second, as mentioned above, there are two ways to tell the driver to stream the results.

From our side, we should:
1) For the first case, we must not specify option `'debezium.snapshot.fetch.size'`.
By default, it will stream results because default fetchSize is 'Integer.MIN_VALUE'.
2) For the second case, we should specify option `'debezium.snapshot.fetch.size'` and `'debezium.database.useCursorFetch' = 'true'`.
The config option 'useCursorFetch' is not passed in the JDBC URL but in the connection properties, it also works.(My previous misunderstanding. I think it must be passed in the JDBC URL before..)

Note that in the first case, the MySQL protocol is `Text Protocol`. In the second case, when you set `useCursorFetch=true`, then `useServerPrepStmts` is consequently also set to `true`, setting `useServerPrepStmts=true` internally causes the MySQL protocol to change from `Text Protocol` to `Binary Protocol`. Consult [MySQL Text Protocol](https://dev.mysql.com/doc/internals/en/text-protocol.html) and [MySQL Binary Protocol](https://dev.mysql.com/doc/internals/en/prepared-statements.html) for more details.

For MySQL Binary Protocol, the current version of debezium will cause ***Snapshot fails*** when parsing TIME, DATE, DATETIME fields in mysql. It has already opened a [#2245](https://github.com/debezium/debezium/pull/2245) for this bug, you can also refer to [DBZ-3238](https://issues.redhat.com/browse/DBZ-3238). It is expected to be fixed in version 1.6.

So for the current version, I recommend the first way, and only the first way is safe.

**Comment by yangliuyu** [comment] 2021-05-10 05:06
@jjiey how to check wheather flink cdc is feching data via streaming the result?
I created table in flink sql client
```
Flink SQL> CREATE TABLE users (
>   user_id BIGINT,
>   user_name STRING,
>   region STRING
> ) WITH (
>   'connector' = 'mysql-cdc',
>   'hostname' = 'localhost',
>   'database-name' = 'flink',
>   'table-name' = 'users',
>   'username' = 'root',
>   'password' = '123456',
>   'debezium.snapshot.fetch.size' = '100'
> );
```
and have 100006 rows in table uses in MySQL 5.7. When I launch `select * from users` in flink sql client, got log from MySQL:
```
2021-05-10T04:50:43.704622Z	   32 Quit
2021-05-10T04:50:58.708048Z	   34 Connect	root@172.19.0.1 on  using TCP/IP
2021-05-10T04:50:58.709999Z	   34 Query	/* mysql-connector-java-8.0.21 (Revision: 33f65445a1bcc544eb0120491926484da168f199) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@collation_server AS collation_server, @@collation_connection AS collation_connection, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_write_timeout AS net_write_timeout, @@performance_schema AS performance_schema, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@transaction_isolation AS transaction_isolation, @@wait_timeout AS wait_timeout
2021-05-10T04:50:58.711140Z	   34 Query	SHOW WARNINGS
2021-05-10T04:50:58.712784Z	   34 Query	SET NAMES utf8mb4
2021-05-10T04:50:58.713941Z	   34 Query	SET autocommit=1
2021-05-10T04:50:58.714859Z	   34 Query	SHOW VARIABLES
2021-05-10T04:50:58.718699Z	   34 Query	SHOW GLOBAL VARIABLES LIKE 'binlog_format'
2021-05-10T04:50:58.720614Z	   34 Query	SHOW GLOBAL VARIABLES LIKE 'binlog_row_image'
2021-05-10T04:50:58.723379Z	   34 Query	SHOW GRANTS FOR CURRENT_USER
2021-05-10T04:50:58.724129Z	   34 Query	SHOW VARIABLES WHERE Variable_name REGEXP 'version|binlog|tx_|gtid|character_set|collation|time_zone'
2021-05-10T04:50:58.727766Z	   34 Query	SET autocommit=0
2021-05-10T04:50:58.728447Z	   34 Query	SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
2021-05-10T04:50:58.729109Z	   34 Query	SET SESSION lock_wait_timeout=10
2021-05-10T04:50:58.729900Z	   34 Query	SET SESSION innodb_lock_wait_timeout=10
2021-05-10T04:50:58.730599Z	   34 Query	SHOW VARIABLES WHERE Variable_name IN ('character_set_server','collation_server')
2021-05-10T04:50:58.732684Z	   34 Query	SELECT @@session.transaction_read_only
2021-05-10T04:50:58.733852Z	   34 Query	FLUSH TABLES WITH READ LOCK
2021-05-10T04:50:58.739690Z	   34 Query	SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
2021-05-10T04:50:58.741283Z	   34 Query	START TRANSACTION WITH CONSISTENT SNAPSHOT
2021-05-10T04:50:58.742118Z	   34 Query	SHOW MASTER STATUS
2021-05-10T04:50:58.742807Z	   34 Query	SHOW DATABASES
2021-05-10T04:50:58.744013Z	   34 Query	SHOW FULL TABLES IN `information_schema` where Table_Type = 'BASE TABLE'
2021-05-10T04:50:58.744885Z	   34 Query	SHOW FULL TABLES IN `flink` where Table_Type = 'BASE TABLE'
2021-05-10T04:50:58.745734Z	   34 Query	SHOW FULL TABLES IN `inventory` where Table_Type = 'BASE TABLE'
2021-05-10T04:50:58.746992Z	   34 Query	SHOW FULL TABLES IN `mydb` where Table_Type = 'BASE TABLE'
2021-05-10T04:50:58.747913Z	   34 Query	SHOW FULL TABLES IN `mysql` where Table_Type = 'BASE TABLE'
2021-05-10T04:50:58.749996Z	   34 Query	SHOW FULL TABLES IN `performance_schema` where Table_Type = 'BASE TABLE'
2021-05-10T04:50:58.754024Z	   34 Query	SHOW FULL TABLES IN `sys` where Table_Type = 'BASE TABLE'
2021-05-10T04:50:58.773773Z	   34 Query	SELECT schema_name, default_character_set_name, default_collation_name FROM information_schema.schemata
2021-05-10T04:50:58.775285Z	   34 Query	SHOW CREATE TABLE `flink`.`users`
2021-05-10T04:50:58.777311Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`accounts`
2021-05-10T04:50:58.778988Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`cond_instances`
2021-05-10T04:50:58.780035Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_stages_current`
2021-05-10T04:50:58.781402Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_stages_history`
2021-05-10T04:50:58.782846Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_stages_history_long`
2021-05-10T04:50:58.784426Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_stages_summary_by_account_by_event_name`
2021-05-10T04:50:58.785731Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_stages_summary_by_host_by_event_name`
2021-05-10T04:50:58.786888Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_stages_summary_by_thread_by_event_name`
2021-05-10T04:50:58.787922Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_stages_summary_by_user_by_event_name`
2021-05-10T04:50:58.789118Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_stages_summary_global_by_event_name`
2021-05-10T04:50:58.790110Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_statements_current`
2021-05-10T04:50:58.792537Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_statements_history`
2021-05-10T04:50:58.795246Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_statements_history_long`
2021-05-10T04:50:58.797965Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_statements_summary_by_account_by_event_name`
2021-05-10T04:50:58.802848Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_statements_summary_by_digest`
2021-05-10T04:50:58.805405Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_statements_summary_by_host_by_event_name`
2021-05-10T04:50:58.807662Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_statements_summary_by_program`
2021-05-10T04:50:58.810292Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_statements_summary_by_thread_by_event_name`
2021-05-10T04:50:58.812488Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_statements_summary_by_user_by_event_name`
2021-05-10T04:50:58.815267Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_statements_summary_global_by_event_name`
2021-05-10T04:50:58.817285Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_transactions_current`
2021-05-10T04:50:58.819455Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_transactions_history`
2021-05-10T04:50:58.821775Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_transactions_history_long`
2021-05-10T04:50:58.824165Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_transactions_summary_by_account_by_event_name`
2021-05-10T04:50:58.826124Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_transactions_summary_by_host_by_event_name`
2021-05-10T04:50:58.827851Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_transactions_summary_by_thread_by_event_name`
2021-05-10T04:50:58.829409Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_transactions_summary_by_user_by_event_name`
2021-05-10T04:50:58.831076Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_transactions_summary_global_by_event_name`
2021-05-10T04:50:58.832726Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_waits_current`
2021-05-10T04:50:58.834562Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_waits_history`
2021-05-10T04:50:58.836389Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_waits_history_long`
2021-05-10T04:50:58.838311Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_waits_summary_by_account_by_event_name`
2021-05-10T04:50:58.839650Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_waits_summary_by_host_by_event_name`
2021-05-10T04:50:58.840757Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_waits_summary_by_instance`
2021-05-10T04:50:58.841835Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_waits_summary_by_thread_by_event_name`
2021-05-10T04:50:58.843169Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_waits_summary_by_user_by_event_name`
2021-05-10T04:50:58.844502Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`events_waits_summary_global_by_event_name`
2021-05-10T04:50:58.845621Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`file_instances`
2021-05-10T04:50:58.846643Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`file_summary_by_event_name`
2021-05-10T04:50:58.850799Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`file_summary_by_instance`
2021-05-10T04:50:58.852965Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`global_status`
2021-05-10T04:50:58.854008Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`global_variables`
2021-05-10T04:50:58.854912Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`host_cache`
2021-05-10T04:50:58.856973Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`hosts`
2021-05-10T04:50:58.858085Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`memory_summary_by_account_by_event_name`
2021-05-10T04:50:58.859552Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`memory_summary_by_host_by_event_name`
2021-05-10T04:50:58.860901Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`memory_summary_by_thread_by_event_name`
2021-05-10T04:50:58.862216Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`memory_summary_by_user_by_event_name`
2021-05-10T04:50:58.863959Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`memory_summary_global_by_event_name`
2021-05-10T04:50:58.865285Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`metadata_locks`
2021-05-10T04:50:58.866616Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`mutex_instances`
2021-05-10T04:50:58.867625Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`objects_summary_global_by_type`
2021-05-10T04:50:58.868965Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`performance_timers`
2021-05-10T04:50:58.870074Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`prepared_statements_instances`
2021-05-10T04:50:58.872290Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`replication_applier_configuration`
2021-05-10T04:50:58.873282Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`replication_applier_status`
2021-05-10T04:50:58.874472Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`replication_applier_status_by_coordinator`
2021-05-10T04:50:58.875832Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`replication_applier_status_by_worker`
2021-05-10T04:50:58.877436Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`replication_connection_configuration`
2021-05-10T04:50:58.879333Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`replication_connection_status`
2021-05-10T04:50:58.881149Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`replication_group_member_stats`
2021-05-10T04:50:58.882725Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`replication_group_members`
2021-05-10T04:50:58.884023Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`rwlock_instances`
2021-05-10T04:50:58.885271Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`session_account_connect_attrs`
2021-05-10T04:50:58.886519Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`session_connect_attrs`
2021-05-10T04:50:58.887755Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`session_status`
2021-05-10T04:50:58.888745Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`session_variables`
2021-05-10T04:50:58.889813Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`setup_actors`
2021-05-10T04:50:58.891668Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`setup_consumers`
2021-05-10T04:50:58.892948Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`setup_instruments`
2021-05-10T04:50:58.894060Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`setup_objects`
2021-05-10T04:50:58.895527Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`setup_timers`
2021-05-10T04:50:58.896649Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`socket_instances`
2021-05-10T04:50:58.898037Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`socket_summary_by_event_name`
2021-05-10T04:50:58.899907Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`socket_summary_by_instance`
2021-05-10T04:50:58.902972Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`status_by_account`
2021-05-10T04:50:58.904224Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`status_by_host`
2021-05-10T04:50:58.905309Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`status_by_thread`
2021-05-10T04:50:58.906655Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`status_by_user`
2021-05-10T04:50:58.908118Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`table_handles`
2021-05-10T04:50:58.909502Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`table_io_waits_summary_by_index_usage`
2021-05-10T04:50:58.912175Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`table_io_waits_summary_by_table`
2021-05-10T04:50:58.914775Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`table_lock_waits_summary_by_table`
2021-05-10T04:50:58.918535Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`threads`
2021-05-10T04:50:58.920573Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`user_variables_by_thread`
2021-05-10T04:50:58.922198Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`users`
2021-05-10T04:50:58.923843Z	   34 Query	SHOW CREATE TABLE `performance_schema`.`variables_by_thread`
2021-05-10T04:50:58.925978Z	   34 Query	SHOW CREATE TABLE `mydb`.`orders`
2021-05-10T04:50:58.928003Z	   34 Query	SHOW CREATE TABLE `mydb`.`products`
2021-05-10T04:50:58.930153Z	   34 Query	SHOW CREATE TABLE `mysql`.`columns_priv`
2021-05-10T04:50:58.932240Z	   34 Query	SHOW CREATE TABLE `mysql`.`db`
2021-05-10T04:50:58.934824Z	   34 Query	SHOW CREATE TABLE `mysql`.`engine_cost`
2021-05-10T04:50:58.936360Z	   34 Query	SHOW CREATE TABLE `mysql`.`event`
2021-05-10T04:50:58.939208Z	   34 Query	SHOW CREATE TABLE `mysql`.`func`
2021-05-10T04:50:58.940609Z	   34 Query	SHOW CREATE TABLE `mysql`.`general_log`
2021-05-10T04:50:58.941996Z	   34 Query	SHOW CREATE TABLE `mysql`.`gtid_executed`
2021-05-10T04:50:58.943605Z	   34 Query	SHOW CREATE TABLE `mysql`.`help_category`
2021-05-10T04:50:58.944971Z	   34 Query	SHOW CREATE TABLE `mysql`.`help_keyword`
2021-05-10T04:50:58.946407Z	   34 Query	SHOW CREATE TABLE `mysql`.`help_relation`
2021-05-10T04:50:58.947609Z	   34 Query	SHOW CREATE TABLE `mysql`.`help_topic`
2021-05-10T04:50:58.949335Z	   34 Query	SHOW CREATE TABLE `mysql`.`innodb_index_stats`
2021-05-10T04:50:58.951312Z	   34 Query	SHOW CREATE TABLE `mysql`.`innodb_table_stats`
2021-05-10T04:50:58.952810Z	   34 Query	SHOW CREATE TABLE `mysql`.`ndb_binlog_index`
2021-05-10T04:50:58.954234Z	   34 Query	SHOW CREATE TABLE `mysql`.`plugin`
2021-05-10T04:50:58.955277Z	   34 Query	SHOW CREATE TABLE `mysql`.`proc`
2021-05-10T04:50:58.958029Z	   34 Query	SHOW CREATE TABLE `mysql`.`procs_priv`
2021-05-10T04:50:58.960334Z	   34 Query	SHOW CREATE TABLE `mysql`.`proxies_priv`
2021-05-10T04:50:58.962235Z	   34 Query	SHOW CREATE TABLE `mysql`.`server_cost`
2021-05-10T04:50:58.963509Z	   34 Query	SHOW CREATE TABLE `mysql`.`servers`
2021-05-10T04:50:58.965128Z	   34 Query	SHOW CREATE TABLE `mysql`.`slave_master_info`
2021-05-10T04:50:58.967988Z	   34 Query	SHOW CREATE TABLE `mysql`.`slave_relay_log_info`
2021-05-10T04:50:58.969801Z	   34 Query	SHOW CREATE TABLE `mysql`.`slave_worker_info`
2021-05-10T04:50:58.971625Z	   34 Query	SHOW CREATE TABLE `mysql`.`slow_log`
2021-05-10T04:50:58.973336Z	   34 Query	SHOW CREATE TABLE `mysql`.`tables_priv`
2021-05-10T04:50:58.975463Z	   34 Query	SHOW CREATE TABLE `mysql`.`time_zone`
2021-05-10T04:50:58.976758Z	   34 Query	SHOW CREATE TABLE `mysql`.`time_zone_leap_second`
2021-05-10T04:50:58.977840Z	   34 Query	SHOW CREATE TABLE `mysql`.`time_zone_name`
2021-05-10T04:50:58.978863Z	   34 Query	SHOW CREATE TABLE `mysql`.`time_zone_transition`
2021-05-10T04:50:58.979947Z	   34 Query	SHOW CREATE TABLE `mysql`.`time_zone_transition_type`
2021-05-10T04:50:58.981307Z	   34 Query	SHOW CREATE TABLE `mysql`.`user`
2021-05-10T04:50:58.985636Z	   34 Query	SHOW CREATE TABLE `sys`.`sys_config`
2021-05-10T04:50:58.987806Z	   34 Query	SHOW CREATE TABLE `inventory`.`addresses`
2021-05-10T04:50:58.989320Z	   34 Query	SHOW CREATE TABLE `inventory`.`customers`
2021-05-10T04:50:58.990503Z	   34 Query	SHOW CREATE TABLE `inventory`.`geom`
2021-05-10T04:50:58.991812Z	   34 Query	SHOW CREATE TABLE `inventory`.`orders`
2021-05-10T04:50:58.993245Z	   34 Query	SHOW CREATE TABLE `inventory`.`products`
2021-05-10T04:50:58.994465Z	   34 Query	SHOW CREATE TABLE `inventory`.`products_on_hand`
2021-05-10T04:50:58.995898Z	   34 Query	SELECT @@session.transaction_read_only
2021-05-10T04:50:58.996573Z	   34 Query	UNLOCK TABLES
2021-05-10T04:50:58.997395Z	   34 Query	SELECT @@session.transaction_read_only
2021-05-10T04:50:58.997992Z	   34 Query	USE `flink`
2021-05-10T04:50:58.998613Z	   34 Query	SHOW TABLE STATUS LIKE 'users'
2021-05-10T04:50:58.999565Z	   34 Query	SELECT * FROM `flink`.`users`
2021-05-10T04:51:00.442572Z	   34 Query	commit
2021-05-10T04:51:00.443785Z	   34 Query	rollback
2021-05-10T04:51:00.444605Z	   34 Quit
```
Just want to know wheather `SELECT * FROM flink.users` may cause performance problem.

**Comment by jjiey** [comment] 2021-05-11 09:51
Hi, @yangliuyu, maybe you need to debug the JDBC source code to check..
As I said, for current version, do not specify options 'debezium.snapshot.fetch.size' for streaming reading.

**Comment by PatrickRen** [comment] 2024-02-28 15:41
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:41 UTC
Labels: bug
