### ISSUE TITLE
e2e-tests optimize for arm

### ISSUE THREAD

**Issue by deemogsw** [ververica/flink-cdc-connectors#1558] opened 2022-09-16 07:19 UTC
I want to debug the code with module flink-cdc-e2e-tests in IDE.
While,although I have run the docker desktop in my mac.An exception still been throwed like this
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/48081481/190575322-457a51ba-341b-4a3c-b676-804560786c48.png">
The current code can't work in Mac with apple silicon chip. 

Besides teste moudle use docker container to run JM & TM,testContainer would assign  a random port for the exposed Port.So when I run the test case,I must find out which port is currently bound to 8081.so that I can visit flink web.
This is not friendly for those people who has less idea with docker.

**Comment by deemogsw** [comment] 2022-09-27 14:55
@leonardBang May you have a look.

**Comment by PatrickRen** [comment] 2024-02-28 15:03
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:03 UTC
Labels: enhancement
