### ISSUE TITLE
[Deserialization]  JsonDebeziumDeserializationSchema will get default value,if colunm defined default value and nullable,when column value is null

### ISSUE THREAD

**Issue by GOODBOY008** [ververica/flink-cdc-connectors#604] opened 2021-11-13 13:41 UTC
**Describe the bug**

**Environment :**
 - Flink CDC version: 2.0.2

**To Reproduce**
1. Thes test data : when a table with optinal column with default value and set this column with 'null' value.
2. The error : use JsonDebeziumDeserializationSchema will get default value of column.

**Additional Description**
<img width="1556" alt="image-2021-11-04-16-25-18-975" src="https://user-images.githubusercontent.com/13617900/141645948-c7cbcabd-c999-4aa4-b554-bc52dfc85988.png">
<img width="1215" alt="image-2021-11-04-16-25-18-890" src="https://user-images.githubusercontent.com/13617900/141645961-cc60e194-9f79-4ed3-8179-79f729f8556c.png">

I had submit a issue for kafka. [KAFKA-13433](https://issues.apache.org/jira/browse/KAFKA-13433) Welcome to discuss about this.

**Comment by lvyanquan** [comment] 2023-10-18 06:04
Looks like it was resolved in https://issues.apache.org/jira/browse/KAFKA-8713.
We may need to update Kafka dependency in the future.

**Comment by GOODBOY008** [comment] 2023-10-18 06:19
> Looks like it was resolved in https://issues.apache.org/jira/browse/KAFKA-8713. We may need to update Kafka dependency in the future.

Yes , kafka had fixed it in 3.5.0 .

**Comment by PatrickRen** [comment] 2024-02-28 15:38
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:38 UTC
Labels: bug
