### ISSUE TITLE
[mysql] fix binlog purge

### ISSUE THREAD

**Issue by happylin0x29a** [ververica/flink-cdc-connectors#1101] opened 2022-04-21 00:52 UTC
**mysql source binlog disappear very fast ，can not fix it to change binlog Strategy**

![efda3c13fc16c75e1b600698e1ae22c](https://user-images.githubusercontent.com/30915794/164349731-83cc8b30-eb2e-42e8-8fef-e6e7ee060243.png)

**When the full amount of MySQL data is read, the binlog data is asynchronously cached until the split data is read, and the merge is performed.**

**Comment by leonardBang** [comment] 2022-04-21 01:46
@happylin0x29a could you share your mysql binlog setting? how long do you keep in mysql server?

**Comment by happylin0x29a** [comment] 2022-04-21 07:40
> @happylin0x29a could you share your mysql binlog setting? how long do you keep in mysql server?

![image](https://user-images.githubusercontent.com/30915794/164403793-c532b9d5-def2-4ff4-a4e6-95eb78b2b1eb.png)
The time policy is 18 hours, but the remaining 30% of the disk policy will clean up the data. The hardware resources are limited and there is no way to expand the capacity, so the binlog disappears quickly

**Comment by PatrickRen** [comment] 2024-02-28 15:08
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:08 UTC
Labels: enhancement
