### ISSUE TITLE
com.esotericsoftware.kryo.KryoException: java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by squning123** [ververica/flink-cdc-connectors#462] opened 2021-09-24 05:38 UTC
SourceFunction自定义deserializer , ForwardDeserializeSchema是复制的源码.

private static class ForwardDeserializeSchema implements DebeziumDeserializationSchema<SourceRecord> {

        private static final long serialVersionUID = 2975058057832211228L;

        @Override
        public void deserialize(SourceRecord record, Collector<SourceRecord> out) throws Exception {
            out.collect(record);
        }

        @Override
        public TypeInformation<SourceRecord> getProducedType() {
            return TypeInformation.of(SourceRecord.class);
        }
    }

**Comment by PatrickRen** [comment] 2024-02-28 15:12
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:12 UTC
Labels: bug
