### ISSUE TITLE
 Encountered change event for table `db`.`table` whose schema isn't known to this connector

### ISSUE THREAD

**Issue by minchowang** [ververica/flink-cdc-connectors#567] opened 2021-11-05 07:17 UTC
**Describe the bug**
Multiple table synchronization errors when using ParallelSource
**Environment :**
 - Flink version :  flink 1.13.3
 - Flink CDC version:  2.1-snapshot (issues create time)
 - Database and version: 5.7

**To Reproduce**
1. Thes test data : 
2. The test code : parallel=4 serverId=5001-5004
3. The error :
```
2021-11-05 15:06:37,201 INFO  com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator [] - Assign split MySqlSnapshotSplit{tableId=dev_erp2.fba_daily_inventory_history_report_mws, splitId='dev_erp2.fba_daily_inventory_history_report_mws:1941', splitKeyType=[`id` BIGINT NOT NULL], splitStart=[19256322], splitEnd=[19264418], highWatermark=null} to subtask 0
2021-11-05 15:06:37,721 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph       [] - Source: mysqlcdc-source -> Sink: kafka-sink (1/4) (fd1bb6e5970e2bc80a3a95b527dc3a65) switched from RUNNING to FAILED on container_e08_1635325297403_13921_01_000002 @ 10.49.1.51 (dataPort=38629).
java.lang.RuntimeException: One or more fetchers have encountered exception
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcherManager.checkErrors(SplitFetcherManager.java:223) ~[flink-table-blink_2.12-1.13.3.jar:1.13.3]
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.getNextFetch(SourceReaderBase.java:154) ~[flink-table-blink_2.12-1.13.3.jar:1.13.3]
	at org.apache.flink.connector.base.source.reader.SourceReaderBase.pollNext(SourceReaderBase.java:116) ~[flink-table-blink_2.12-1.13.3.jar:1.13.3]
	at org.apache.flink.streaming.api.operators.SourceOperator.emitNext(SourceOperator.java:294) ~[flink-dist_2.12-1.13.3.jar:1.13.3]
	at org.apache.flink.streaming.runtime.io.StreamTaskSourceInput.emitNext(StreamTaskSourceInput.java:69) ~[flink-dist_2.12-1.13.3.jar:1.13.3]
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:66) ~[flink-dist_2.12-1.13.3.jar:1.13.3]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:423) ~[flink-dist_2.12-1.13.3.jar:1.13.3]
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:204) ~[flink-dist_2.12-1.13.3.jar:1.13.3]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:684) ~[flink-dist_2.12-1.13.3.jar:1.13.3]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.executeInvoke(StreamTask.java:639) ~[flink-dist_2.12-1.13.3.jar:1.13.3]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runWithCleanUpOnFail(StreamTask.java:650) ~[flink-dist_2.12-1.13.3.jar:1.13.3]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:623) ~[flink-dist_2.12-1.13.3.jar:1.13.3]
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:779) ~[flink-dist_2.12-1.13.3.jar:1.13.3]
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:566) ~[flink-dist_2.12-1.13.3.jar:1.13.3]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_191]
Caused by: java.lang.RuntimeException: SplitFetcher thread 289 received unexpected exception while polling the records
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.runOnce(SplitFetcher.java:148) ~[flink-table-blink_2.12-1.13.3.jar:1.13.3]
	at org.apache.flink.connector.base.source.reader.fetcher.SplitFetcher.run(SplitFetcher.java:103) ~[flink-table-blink_2.12-1.13.3.jar:1.13.3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_191]
	... 1 more
Caused by: com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.
	at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:42) ~[flink-sql-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleEvent(MySqlStreamingChangeEventSource.java:369) ~[flink-sql-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlBinlogSplitReadTask.handleEvent(MySqlBinlogSplitReadTask.java:94) ~[flink-sql-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.notifyEventListeners(BinaryLogClient.java:1118) ~[flink-sql-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:966) ~[flink-sql-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:606) ~[flink-sql-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:850) ~[flink-sql-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
	... 1 more
Caused by: io.debezium.DebeziumException: Error processing binlog event
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleEvent(MySqlStreamingChangeEventSource.java:369) ~[flink-sql-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlBinlogSplitReadTask.handleEvent(MySqlBinlogSplitReadTask.java:94) ~[flink-sql-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.notifyEventListeners(BinaryLogClient.java:1118) ~[flink-sql-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:966) ~[flink-sql-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:606) ~[flink-sql-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:850) ~[flink-sql-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
	... 1 more
Caused by: io.debezium.DebeziumException: Encountered change event for table dev_erp2.fba_sug_msku whose schema isn't known to this connector
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.informAboutUnknownTableIfRequired(MySqlStreamingChangeEventSource.java:651) ~[flink-sql-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleUpdateTableMetadata(MySqlStreamingChangeEventSource.java:631) ~[flink-sql-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleEvent(MySqlStreamingChangeEventSource.java:352) ~[flink-sql-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
	at com.ververica.cdc.connectors.mysql.debezium.task.MySqlBinlogSplitReadTask.handleEvent(MySqlBinlogSplitReadTask.java:94) ~[flink-sql-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.notifyEventListeners(BinaryLogClient.java:1118) ~[flink-sql-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:966) ~[flink-sql-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:606) ~[flink-sql-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:850) ~[flink-sql-connector-mysql-cdc-2.1-SNAPSHOT.jar:2.1-SNAPSHOT]
	... 1 more```
**Additional Description**
If applicable, add screenshots to help explain your problem.

**Comment by PatrickRen** [comment] 2024-02-28 15:38
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:38 UTC
Labels: bug
