### ISSUE TITLE
Flinkcdc monitors oracle19c lost fields and data and it is very slow

### ISSUE THREAD

**Issue by lcystart** [ververica/flink-cdc-connectors#762] opened 2021-12-30 16:55 UTC
**Describe the bug**

**Environment :**
 - Flink version :  flink1.13.3
 - Flink CDC version: 2.1.1
 - Database and version: oracle 19C 

**To Reproduce**
1. Thes test data : The Millions
2. The test code :
Properties properties = new Properties();
properties.setProperty("debezium.log.mining.strategy","online_catalog");
properties.setProperty("debezium.log.mining.continuous.mine","true");

SourceFunction<String> sourceFunction = OracleSource.<String>builder()
		.hostname("ip")
		.port(1521)
		.database("db_name")
		.schemaList("schema_name")
		.tableList("schema_name.tb_name")
		.username("uName")
		.password("pwd")
		.deserializer(new MyStringDeserializationSchema())
		.startupOptions(StartupOptions.latest())
		.debeziumProperties(properties)
		.build();

StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
env.setParallelism(1);

//1.1 设置CK&状态后端
env.setStateBackend(new FsStateBackend(PropertyUtils.getString("hdfsAlibaba")));
3. The error :
3.1）
[debezium-engine] ERROR com.ververica.cdc.debezium.internal.Handover - Reporting error:
org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.
	at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:42)
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:208)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:152)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: ORA-01327: 无法按构建的要求锁定系统字典 (锁为独占锁)
ORA-06512: 在 "SYS.DBMS_LOGMNR_INTERNAL", line 8651
ORA-06512: 在 "SYS.DBMS_LOGMNR_INTERNAL", line 4519
ORA-06512: 在 "SYS.DBMS_LOGMNR_INTERNAL", line 4082
ORA-06512: 在 "SYS.DBMS_LOGMNR_INTERNAL", line 4447
ORA-06512: 在 "SYS.DBMS_LOGMNR_INTERNAL", line 8429
ORA-06512: 在 "SYS.DBMS_LOGMNR_INTERNAL", line 8665
ORA-06512: 在 "SYS.DBMS_LOGMNR_INTERNAL", line 8821
ORA-06512: 在 "SYS.DBMS_LOGMNR_D", line 61
ORA-06512: 在 line 1

3.2）
[debezium-engine] INFO io.debezium.embedded.EmbeddedEngine - Retrieable exception thrown, connector will be restarted
org.apache.kafka.connect.errors.RetriableException: An exception occurred in the change event producer. This connector will be restarted.
	at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:38)
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:208)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:152)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: ORA-01291: 缺少日志文件
ORA-06512: 在 "SYS.DBMS_LOGMNR", line 72
ORA-06512: 在 line 1

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:550)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
	at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:265)
	at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:86)
	at oracle.jdbc.driver.T4CCallableStatement.executeForRows(T4CCallableStatement.java:965)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1205)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3666)
	at oracle.jdbc.driver.T4CCallableStatement.executeInternal(T4CCallableStatement.java:1358)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3778)
	at oracle.jdbc.driver.OracleCallableStatement.execute(OracleCallableStatement.java:4251)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1081)
	at io.debezium.connector.oracle.logminer.LogMinerHelper.executeCallableStatement(LogMinerHelper.java:693)
	at io.debezium.connector.oracle.logminer.LogMinerHelper.startLogMining(LogMinerHelper.java:236)
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:177)
	... 7 more
Caused by: Error : 1291, Position : 0, Sql = BEGIN sys.dbms_logmnr.start_logmnr(startScn => '13390410406826', endScn => '13390410426826', OPTIONS => DBMS_LOGMNR.DICT_FROM_REDO_LOGS + DBMS_LOGMNR.DDL_DICT_TRACKING  + DBMS_LOGMNR.NO_ROWID_IN_STMT);END;, OriginalSql = BEGIN sys.dbms_logmnr.start_logmnr(startScn => '13390410406826', endScn => '13390410426826', OPTIONS => DBMS_LOGMNR.DICT_FROM_REDO_LOGS + DBMS_LOGMNR.DDL_DICT_TRACKING  + DBMS_LOGMNR.NO_ROWID_IN_STMT);END;, Error Msg = ORA-01291: 缺少日志文件
ORA-06512: 在 "SYS.DBMS_LOGMNR", line 72
ORA-06512: 在 line 1

3.3）
java.lang.Exception: Could not perform checkpoint 949 for operator Source: Custom Source -> Filter -> filter-cdc -> (Sink: Print to Std. Out, Sink: cdc-sink-topic) (1/1)#19.
	at org.apache.flink.streaming.runtime.tasks.StreamTask.triggerCheckpointAsyncInMailbox(StreamTask.java:1006)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$triggerCheckpointAsync$7(StreamTask.java:958)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.runThrowing(StreamTaskActionExecutor.java:93)
	at org.apache.flink.streaming.runtime.tasks.mailbox.Mail.run(Mail.java:90)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.processMailsWhenDefaultActionUnavailable(MailboxProcessor.java:344)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.processMail(MailboxProcessor.java:330)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:202)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:684)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.executeInvoke(StreamTask.java:639)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runWithCleanUpOnFail(StreamTask.java:650)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:623)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:779)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:566)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.flink.runtime.checkpoint.CheckpointException: Could not complete snapshot 949 for operator Source: Custom Source -> Filter -> filter-cdc -> (Sink: Print to Std. Out, Sink: cdc-sink-topic) (1/1)#19. Failure reason: Checkpoint was declined.
	at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.snapshotState(StreamOperatorStateHandler.java:264)
	at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.snapshotState(StreamOperatorStateHandler.java:169)
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator.snapshotState(AbstractStreamOperator.java:371)
	at org.apache.flink.streaming.runtime.tasks.SubtaskCheckpointCoordinatorImpl.checkpointStreamOperator(SubtaskCheckpointCoordinatorImpl.java:706)
	at org.apache.flink.streaming.runtime.tasks.SubtaskCheckpointCoordinatorImpl.buildOperatorSnapshotFutures(SubtaskCheckpointCoordinatorImpl.java:627)
	at org.apache.flink.streaming.runtime.tasks.SubtaskCheckpointCoordinatorImpl.takeSnapshotSync(SubtaskCheckpointCoordinatorImpl.java:590)
	at org.apache.flink.streaming.runtime.tasks.SubtaskCheckpointCoordinatorImpl.checkpointState(SubtaskCheckpointCoordinatorImpl.java:312)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$performCheckpoint$8(StreamTask.java:1092)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.runThrowing(StreamTaskActionExecutor.java:93)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.performCheckpoint(StreamTask.java:1076)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.triggerCheckpointAsyncInMailbox(StreamTask.java:994)
	... 13 more
Caused by: java.lang.IllegalStateException: Retrieve schema history failed, the schema records for engine 62bf987b-5fae-4ba4-92f0-2fc680ecad6e has been removed, this might because the debezium engine has been shutdown due to other errors.
	at com.ververica.cdc.debezium.utils.DatabaseHistoryUtil.retrieveHistory(DatabaseHistoryUtil.java:77)
	at com.ververica.cdc.debezium.DebeziumSourceFunction.snapshotHistoryRecordsState(DebeziumSourceFunction.java:357)
	at com.ververica.cdc.debezium.DebeziumSourceFunction.snapshotState(DebeziumSourceFunction.java:312)
	at org.apache.flink.streaming.util.functions.StreamingFunctionUtils.trySnapshotFunctionState(StreamingFunctionUtils.java:118)
	at org.apache.flink.streaming.util.functions.StreamingFunctionUtils.snapshotFunctionState(StreamingFunctionUtils.java:99)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.snapshotState(AbstractUdfStreamOperator.java:89)
	at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.snapshotState(StreamOperatorStateHandler.java:218)
	... 23 more

3.4）
[debezium-engine] ERROR com.ververica.cdc.debezium.internal.Handover - Reporting error:
org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.
	at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:42)
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:208)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:152)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: ORA-01289: 无法添加重复的日志文件 +DATAC1/HBCNPLDM/ONLINELOG/group_3.318.1040549997
ORA-06512: 在 "SYS.DBMS_LOGMNR", line 82
ORA-06512: 在 line 1

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:550)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
	at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:265)
	at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:86)
	at oracle.jdbc.driver.T4CCallableStatement.executeForRows(T4CCallableStatement.java:965)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1205)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3666)
	at oracle.jdbc.driver.T4CCallableStatement.executeInternal(T4CCallableStatement.java:1358)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3778)
	at oracle.jdbc.driver.OracleCallableStatement.execute(OracleCallableStatement.java:4251)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1081)
	at io.debezium.connector.oracle.logminer.LogMinerHelper.executeCallableStatement(LogMinerHelper.java:693)
	at io.debezium.connector.oracle.logminer.LogMinerHelper.setRedoLogFilesForMining(LogMinerHelper.java:491)
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.initializeRedoLogsForMining(LogMinerStreamingChangeEventSource.java:245)
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:168)
	... 7 more
Caused by: Error : 1289, Position : 0, Sql = BEGIN sys.dbms_logmnr.add_logfile(LOGFILENAME => '+DATAC1/HBCNPLDM/ONLINELOG/group_3.318.1040549997', OPTIONS => DBMS_LOGMNR.ADDFILE);END;, OriginalSql = BEGIN sys.dbms_logmnr.add_logfile(LOGFILENAME => '+DATAC1/HBCNPLDM/ONLINELOG/group_3.318.1040549997', OPTIONS => DBMS_LOGMNR.ADDFILE);END;, Error Msg = ORA-01289: 无法添加重复的日志文件 +DATAC1/HBCNPLDM/ONLINELOG/group_3.318.1040549997
ORA-06512: 在 "SYS.DBMS_LOGMNR", line 82
ORA-06512: 在 line 1

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:513)
	... 25 more

3.5）
[debezium-engine] ERROR com.ververica.cdc.debezium.internal.Handover - Reporting error:
org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.
	at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:42)
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:208)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:152)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: ORA-00308: 无法打开归档日志 '+RECOC1/HBCNPLDM/ARCHIVELOG/2021_12_30/thread_2_seq_98818.438.1092669143'
ORA-17503: ksfdopn: 2 未能打开文件 +RECOC1/HBCNPLDM/ARCHIVELOG/2021_12_30/thread_2_seq_98818.438.1092669143
ORA-15012: ASM file '+RECOC1/HBCNPLDM/ARCHIVELOG/2021_12_30/thread_2_seq_98818.438.1092669143' does not exist
ORA-06512: 在 "SYS.DBMS_LOGMNR", line 72
ORA-06512: 在 line 1

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:550)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:268)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
	at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:265)
	at oracle.jdbc.driver.T4CCallableStatement.doOall8(T4CCallableStatement.java:86)
	at oracle.jdbc.driver.T4CCallableStatement.executeForRows(T4CCallableStatement.java:965)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1205)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3666)
	at oracle.jdbc.driver.T4CCallableStatement.executeInternal(T4CCallableStatement.java:1358)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3778)
	at oracle.jdbc.driver.OracleCallableStatement.execute(OracleCallableStatement.java:4251)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1081)
	at io.debezium.connector.oracle.logminer.LogMinerHelper.executeCallableStatement(LogMinerHelper.java:693)
	at io.debezium.connector.oracle.logminer.LogMinerHelper.startLogMining(LogMinerHelper.java:236)
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:177)
	... 7 more
Caused by: Error : 308, Position : 0, Sql = BEGIN sys.dbms_logmnr.start_logmnr(startScn => '13391615195178', endScn => '13391615225178', OPTIONS => DBMS_LOGMNR.DICT_FROM_REDO_LOGS + DBMS_LOGMNR.DDL_DICT_TRACKING  + DBMS_LOGMNR.NO_ROWID_IN_STMT);END;, OriginalSql = BEGIN sys.dbms_logmnr.start_logmnr(startScn => '13391615195178', endScn => '13391615225178', OPTIONS => DBMS_LOGMNR.DICT_FROM_REDO_LOGS + DBMS_LOGMNR.DDL_DICT_TRACKING  + DBMS_LOGMNR.NO_ROWID_IN_STMT);END;, Error Msg = ORA-00308: 无法打开归档日志 '+RECOC1/HBCNPLDM/ARCHIVELOG/2021_12_30/thread_2_seq_98818.438.1092669143'
ORA-17503: ksfdopn: 2 未能打开文件 +RECOC1/HBCNPLDM/ARCHIVELOG/2021_12_30/thread_2_seq_98818.438.1092669143
ORA-15012: ASM file '+RECOC1/HBCNPLDM/ARCHIVELOG/2021_12_30/thread_2_seq_98818.438.1092669143' does not exist
ORA-06512: 在 "SYS.DBMS_LOGMNR", line 72
ORA-06512: 在 line 1

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:513)
	... 24 more

3.6)
org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.
	at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:42)
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:208)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:152)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.debezium.DebeziumException: Online REDO LOG files or archive log files do not contain the offset scn 13391615245298.  Please perform a new snapshot.
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:127)
	... 7 more

3.7)
[debezium-engine] ERROR com.ververica.cdc.debezium.internal.Handover - Reporting error:
org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.
	at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:42)
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:208)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:152)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.debezium.DebeziumException: Online REDO LOG files or archive log files do not contain the offset scn 13391650921640.  Please perform a new snapshot.
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:127)
	... 7 more
[Source: Custom Source -> Filter -> filter-cdc -> Sink: Print to Std. Out (1/1)#461] INFO io.debezium.embedded.EmbeddedEngine - Stopping the embedded engine
[Source: Custom Source -> Filter -> filter-cdc -> Sink: Print to Std. Out (1/1)#461] INFO io.debezium.embedded.EmbeddedEngine - Stopping the embedded engine
[Source: Custom Source -> Filter -> filter-cdc -> Sink: Print to Std. Out (1/1)#461] WARN org.apache.flink.runtime.taskmanager.Task - Source: Custom Source -> Filter -> filter-cdc -> Sink: Print to Std. Out (1/1)#461 (098964e65de97af6688182b79fb48184) switched from RUNNING to FAILED with failure cause: org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.
	at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:42)
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:208)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:152)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.debezium.DebeziumException: Online REDO LOG files or archive log files do not contain the offset scn 13391650921640.  Please perform a new snapshot.
	at io.debezium.connector.oracle.logminer.LogMinerStreamingChangeEventSource.execute(LogMinerStreamingChangeEventSource.java:127)
	... 7 more

**Additional Description**
    The above is the error that I have reported in the test these days，we have access to two shema and more than ten tables in the oracle database, with a data volume of nearly one million；I found two very unsolvable problems：1. Occasionally there are missing fields in the data of a certain record of a table, for example, the fields of the table have a, b, c, d field, and sometimes only a, b, d are coming.   2. The data came quickly when two or three tables were first connected, but after more than a dozen tables were connected, the changed data did not arrive until half an hour later.     
    We are now using FlinkCDC to simulate the poc scene, I am very helpless now, I hope to get your answers and help, thank you！

**Comment by hellochueng** [comment] 2022-03-04 02:23
so do i

**Comment by zhujian86** [comment] 2022-03-19 08:03
have you solved this problem?

**Comment by szhengshuai** [comment] 2022-05-11 03:20
我也碰到了， 社区什么时候解决呢

**Comment by dongkelun** [comment] 2023-03-22 06:32
没人处理这个问题吗？

**Comment by jasonhewg** [comment] 2023-11-03 08:35
我也遇到了此问题：

Failed to start Oracle LogMiner after '5' attempts.

Caused by: oracle.jdbc.OracleDatabaseException: ORA-01291: missing log file
ORA-06512: at "SYS.DBMS_LOGMNR", line 72
ORA-06512: at line 1

社区有人处理或解决这个问题吗？

**Comment by Naros** [comment] 2023-11-15 16:34
Hi, Debezium Oracle maintainer here, hopefully I can provide some insights.

**ORA-01327**
This error occurs because the data dictionary cannot be locked to write its contents to the redo logs.  This most often happens if you have a very volatile system undergoing high volumes of DDL changes.  If this is normal for your database, you may be unable to use the default mining strategy used by Debezium OOTB. Instead, you may use the `online_catalog` strategy by setting `log.mining.strategy` accordingly.  Be aware with this mode, there are restrictions around handling table schema changes, so only make this adjustment if the structure of your captured tables generally do not change.

**ORA-01291**
This can happen because of aggressive log retention policies and a connector bug.  The easiest way to determine whether it's the former or the latter is if the connector restarts successfully, then it's due to the connector bug.  The former is because the DBA team has a retention policy for archive logs in place where a log the connector requires has been removed.   If that's the case, please work with your DBA team to increase the retention period for logs.   The latter bug was fixed in Debezium 2.4.1.Final and 2.5.0.Alpha2 of Debezium.

**Comment by PatrickRen** [comment] 2024-02-28 15:31
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:31 UTC
Labels: bug
