### ISSUE TITLE
support ingesting  changes from tables with different schemas

### ISSUE THREAD

**Issue by wangxiangyu** [ververica/flink-cdc-connectors#1158] opened 2022-05-08 13:26 UTC
Currently when using SQL API,  we must define table schema in the source table. So the tables in one flink cdc sql job must be with the same schema. Is there any way to `ingest  changes from tables with different schemas in one flink job`? Thank you.

**Comment by PatrickRen** [comment] 2024-02-28 15:40
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:40 UTC
Labels: enhancement
