### ISSUE TITLE
无法指定链接参数 AllowPublicKeyRetrieval=True

### ISSUE THREAD

**Issue by springMoon** [ververica/flink-cdc-connectors#173] opened 2021-04-26 06:05 UTC
在使用 mysql 8.0 的时候报下面的，需要指定链接参数 AllowPublicKeyRetrieval=True，但是没有找到配置的地方
`Caused by: java.sql.SQLNonTransientConnectionException: Public Key Retrieval is not allowed
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197)
	at io.debezium.jdbc.JdbcConnection.lambda$patternBasedFactory$1(JdbcConnection.java:230)
	at io.debezium.jdbc.JdbcConnection.connection(JdbcConnection.java:871)
	at io.debezium.jdbc.JdbcConnection.connection(JdbcConnection.java:866)
	at io.debezium.jdbc.JdbcConnection.connect(JdbcConnection.java:412)
	at io.debezium.connector.mysql.MySqlJdbcContext.querySystemVariables(MySqlJdbcContext.java:328)
	... 11 more
`

**Comment by xiaohui1227** [comment] 2021-05-14 04:00
我也遇到了同样的问题

**Comment by springMoon** [comment] 2021-05-19 11:26
> 我也遇到了同样的问题

如果只是自己开发，可以先用cdc的账号先登录一下

**Comment by afghl** [comment] 2021-07-29 14:17
> > 我也遇到了同样的问题
> 
> 如果只是自己开发，可以先用cdc的账号先登录一下

没懂，是这样？还是不行呢。

--FlinkSQL
CREATE TABLE products (
  id INT,
  name STRING,
  description STRING
) WITH (
  'connector' = 'mysql-cdc',
  'hostname' = 'localhost',
  'port' = '3306',
  'username' = 'mysqluser',
  'password' = 'mysqlpw',
  'database-name' = 'mydb',
  'table-name' = 'products'
);

**Comment by lea21st** [comment] 2021-11-01 11:08
有人解决了这个问题吗

**Comment by MaoYiKun12138** [comment] 2021-11-11 09:53
指定参数
`'debezium.database.allowPublicKeyRetrieval' = 'true'`
[Debezium & MySQL v8 : Public Key Retrieval Is Not Allowed](https://rmoff.net/2019/10/23/debezium-mysql-v8-public-key-retrieval-is-not-allowed/)

**Comment by lea21st** [comment] 2021-11-11 10:06
我的密码策略时mysql_native_password，我的原因找到了，是因为用户名和密码错了（没有这个用户），提示也是 Public Key Retrieval Is Not Allowed

**Comment by saLeox** [comment] 2022-08-29 11:00
For Datastram API(Scala), the config for `useSSL` and `allowPublicKeyRetrieval` can be added as below:
```
    val jdbcProperties = new Properties
    jdbcProperties.setProperty("useSSL", "false")
    jdbcProperties.setProperty("allowPublicKeyRetrieval", "true")

    val debeziumProperties = new Properties
    debeziumProperties.setProperty("debezium.database.allowPublicKeyRetrieval", "true")

...
    val mySqlSource = MySqlSource.builder[String]
      .jdbcProperties(jdbcProperties)
      .debeziumProperties(debeziumProperties)

```

**Comment by liushuaihang** [comment] 2022-11-18 05:50
Properties jdbcProperties = new Properties
    jdbcProperties.setProperty("useSSL", "false")
    jdbcProperties.setProperty("allowPublicKeyRetrieval", "true")
添加这两个参数之后不报错了，但是我监听两个mysql表，只能监听到一张表的binlog，而且只能是第一全量，之后无法动态获取到这张表的binlog日志。另外一张表从flink日志看到监听sql，不知道为什么有过滤条件。

**Comment by PatrickRen** [comment] 2024-02-28 15:14
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:14 UTC
Labels: discussion

**Comment by gobgm** [comment] 2026-06-11 06:44
现在是cdc 3.0版本，不支持yaml文件传入useSSL=false&allowPublicKeyRetrieval=true参数吗
