### ISSUE TITLE
[Bug]  Unsupported table metadata field type 216 when parsing binlog event

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#2192] opened 2023-06-08 08:59 UTC
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.15.2

### Flink CDC version

2.3.0

### Database and its version

mysql version = 8.0.18

### Minimal reproduce step

This error occurs when parsing the binlog.

### What did you expect to see?

Support this kind of even type.

### What did you see instead?

Caused by: io.debezium.DebeziumException: Failed to deserialize data of EventHeaderV4{timestamp=1679640836000, eventType=TABLE_MAP, serverId=1704062425, headerLength=19, dataLength=89, nextPosition=359034816, flags=0}
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.wrap(MySqlStreamingChangeEventSource.java:1154)
	... 5 more
Caused by: com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1679640836000, eventType=TABLE_MAP, serverId=1704062425, headerLength=19, dataLength=89, nextPosition=359034816, flags=0}
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:309)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeTableMapEventData(EventDeserializer.java:281)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:228)
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$1.nextEvent(MySqlStreamingChangeEventSource.java:230)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:952)
	... 3 more
Caused by: java.io.IOException: Unsupported table metadata field type 216
	at com.github.shyiko.mysql.binlog.event.deserialization.TableMapEventMetadataDeserializer.deserialize(TableMapEventMetadataDeserializer.java:52)
	at com.github.shyiko.mysql.binlog.event.deserialization.TableMapEventDataDeserializer.deserialize(TableMapEventDataDeserializer.java:59)
	at com.github.shyiko.mysql.binlog.event.deserialization.TableMapEventDataDeserializer.deserialize(TableMapEventDataDeserializer.java:37)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:303)
	... 7 more

https://github.com/ververica/flink-cdc-connectors/issues/2001#issuecomment-1482349231

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ruanhang1993** [comment] 2023-06-08 10:14
I add a test, but cannot reproduce the error.

MySQL : docker mysql:8.0
Table sql :
```sql
CREATE TABLE multi_value_index (
    id bigint NOT NULL,
    f1 json,
    PRIMARY KEY (id)
);

insert into multi_value_index(id, f1)
values (1, cast('{"inner":[1,3]}' as json)),
       (2, cast('{"inner":[1,3,9,8]}' as json));
```
Test:
```java
@Test
    public void testMultiValueIndex() throws Throwable {
        fullTypesMySql8Database.createAndInitialize();
        String sourceDDL =
                String.format(
                        "CREATE TABLE multi_value_index (\n"
                                + "    `id` INT NOT NULL,\n"
                                + "    f1 STRING,\n"
                                + "    primary key (`id`) not enforced"
                                + ") WITH ("
                                + " 'connector' = 'mysql-cdc',"
                                + " 'hostname' = '%s',"
                                + " 'port' = '%s',"
                                + " 'username' = '%s',"
                                + " 'password' = '%s',"
                                + " 'database-name' = '%s',"
                                + " 'table-name' = '%s',"
                                + " 'scan.incremental.snapshot.enabled' = '%s',"
                                + " 'server-id' = '%s',"
                                + " 'server-time-zone' = 'UTC',"
                                + " 'scan.incremental.snapshot.chunk.size' = '%s'"
                                + ")",
                        MYSQL8_CONTAINER.getHost(),
                        MYSQL8_CONTAINER.getDatabasePort(),
                        fullTypesMySql8Database.getUsername(),
                        fullTypesMySql8Database.getPassword(),
                        fullTypesMySql8Database.getDatabaseName(),
                        "multi_value_index",
                        incrementalSnapshot,
                        getServerId(),
                        getSplitSize());
        tEnv.executeSql(sourceDDL);

        // async submit job
        TableResult result = tEnv.executeSql("SELECT id, f1 FROM multi_value_index");

        CloseableIterator<Row> iterator = result.collect();
        waitForSnapshotStarted(iterator);
        Thread.sleep(10000L);

        try (Connection connection = fullTypesMySql8Database.getJdbcConnection();
             Statement statement = connection.createStatement()) {
            statement.execute(
                    "ALTER TABLE `multi_value_index` ADD INDEX `k_source`  ( (CAST(f1->'$.inner' AS UNSIGNED ARRAY)) );");
            statement.execute(
                    "insert into multi_value_index(id, f1) values (3, cast('{\"inner\":[1,4,5,8]}' as json));");
        }

        while (true) {

        }
//        assertEqualsInAnyOrder(Arrays.asList(), fetchRows(iterator, 2));
//        result.getJobClient().get().cancel().get();
    }
```

**Comment by ruanhang1993** [comment] 2023-06-08 10:18
Debug 

![截屏2023-06-08 下午6 16 55](https://github.com/ververica/flink-cdc-connectors/assets/17610579/505efc91-08f1-4cf5-821f-cf7535df440e)

The value is:
```json
{"source":{"file":"mysql-bin.000005","pos":1001,"server_id":223344},"position":{"transaction_id":null,"ts_sec":1686219039,"file":"mysql-bin.000005","pos":1240,"gtids":"9444d53c-05e4-11ee-b649-0242ac110004:1-17","server_id":223344},"databaseName":"column_type_test_mysql8_1gppbph","ddl":"ALTER TABLE `multi_value_index` ADD INDEX `k_source`  ( (CAST(f1->'$.inner' AS UNSIGNED ARRAY)) )","tableChanges":[]}
```

**Comment by racoon945** [comment] 2023-06-09 02:44
I noticed that you are using docker mysql:8.0
Can you try with mysql:8.0.18 ?
`docker pull mysql:8.0.18`
The problem occurred again recently, reproducible in MySQL 8.0.18 but not in 8.0.22-13.

**Comment by ruanhang1993** [comment] 2023-06-13 06:31
Hi, @racoon945 .
I change the version to mysql:8.0.18, but the error does not occur.
<img width="976" alt="截屏2023-06-13 下午2 30 25" src="https://github.com/ververica/flink-cdc-connectors/assets/17610579/2c525385-e1d5-4c27-be3a-010ef404f8a0">
![截屏2023-06-13 下午2 27 02](https://github.com/ververica/flink-cdc-connectors/assets/17610579/6bce22e8-ce62-413f-9c8a-4c82bd3e33af)

**Comment by hanpi14** [comment] 2023-08-16 09:06
I was using flink1.16.2 and mysql 5.6 for data capture, and such errors also occurred,cdc versions 2.4.0 and 2.4.1 have the same error
![image](https://github.com/ververica/flink-cdc-connectors/assets/90750932/af8e1fca-07f4-41fd-b39b-43e1693a3d09)

**Comment by ruanhang1993** [comment] 2023-08-21 03:00
Hi, @hanpi14.
Which MySQL version are you using when the error occurs?
And do you know what sql will cause this error ? Thanks.

**Comment by ruanhang1993** [comment] 2024-02-04 12:17
Close this issue as no reply received. 

If the problem still exists, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project Flink with component tag Flink CDC. Thank you!

**Closed by ruanhang1993** 2024-02-04 12:17 UTC
Labels: bug
