### ISSUE TITLE
当使用bigint承载时间戳字段时没有时区校正？

### ISSUE THREAD

**Issue by eriendeng** [ververica/flink-cdc-connectors#1070] opened 2022-04-12 05:17 UTC
flink-connector-cdc-mysql-2.2
我们的链路是mysql -> flink-cdc -> iceberg，因为想忽略时区对timestamp的影响，所以在解析数据库timestamp字段时使用了bigint来读取，写入到iceberg的long字段，表现上转出来的ts总会比真实时间多8小时，我看Debezium中似乎对于时间类字段本身就是用ts来传输的，在flink-cdc源码中.serverTimeZone()只是对flink中的timestamp类字段进行调整，直接使用bigint似乎没法调整这个时差，是我忽略了什么地方吗？
<img width="761" alt="image" src="https://user-images.githubusercontent.com/30573371/162885477-ad84d33c-d048-4e46-aeac-eaaaf65115b6.png">
<img width="324" alt="image" src="https://user-images.githubusercontent.com/30573371/162885528-aa25a36e-9cac-406d-b409-31db55f4ddbe.png">
<img width="259" alt="image" src="https://user-images.githubusercontent.com/30573371/162885560-6a491405-93a4-411b-a5d2-25b39add9c31.png">

**Comment by PatrickRen** [comment] 2024-02-28 15:36
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:36 UTC
