### ISSUE TITLE
initial  mode don't  get data when new create db and table and restart job

### ISSUE THREAD

**Issue by deepthinkin** [ververica/flink-cdc-connectors#1357] opened 2022-07-10 03:11 UTC
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :   1.13.5
 - Flink CDC version:  2.2.0
 - Database and version:  mysql 5.7.38

**To Reproduce**
1. Thes test data :  
2. The test code :
   MySqlSource<String> mysqlSource = MySqlSource.<String>builder()
                .hostname("192.168.XX.XX")
                .port(3306)
                .username("root")
                .password("root")
             
                .databaseList("db01")
                .tablList(".*")
                .startupOptions(StartupOptions.initial())
                .deserializer(new JsonDebeziumDeserializationSchema())           
                .build();
4. The error :
10 mins later error comes:
2022-07-10 10:54:17.402 [main] INFO  java.lang.Class - 4.开始执行同步任务...
2022-07-10 11:05:23.372 [SourceCoordinator-Source: MySQL-Cdc-Source] ERROR org.apache.flink.runtime.source.coordinator.SourceCoordinator - Uncaught exception in the SplitEnumerator for Source Source: MySQL-Cdc-Source while handling operator event RequestSplitEvent (host='') from subtask 0. Triggering job failover.
org.apache.flink.util.FlinkRuntimeException: InterruptedException while waiting for asynchronously snapshot split
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlSnapshotSplitAssigner.getNext(MySqlSnapshotSplitAssigner.java:235) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlHybridSplitAssigner.getNext(MySqlHybridSplitAssigner.java:125) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator.assignSplits(MySqlSourceEnumerator.java:193) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator.handleSplitRequest(MySqlSourceEnumerator.java:109) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$handleEventFromOperator$1(SourceCoordinator.java:172) ~[flink-runtime_2.12-1.13.5.jar:1.13.5]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:331) ~[flink-runtime_2.12-1.13.5.jar:1.13.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2022-07-10 11:05:23.372 [SourceCoordinator-Source: MySQL-Cdc-Source] ERROR org.apache.flink.runtime.source.coordinator.SourceCoordinator - Uncaught exception in the SplitEnumerator for Source Source: MySQL-Cdc-Source while handling operator event RequestSplitEvent (host='') from subtask 0. Triggering job failover.
org.apache.flink.util.FlinkRuntimeException: InterruptedException while waiting for asynchronously snapshot split
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlSnapshotSplitAssigner.getNext(MySqlSnapshotSplitAssigner.java:235) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlHybridSplitAssigner.getNext(MySqlHybridSplitAssigner.java:125) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator.assignSplits(MySqlSourceEnumerator.java:193) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator.handleSplitRequest(MySqlSourceEnumerator.java:109) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$handleEventFromOperator$1(SourceCoordinator.java:172) ~[flink-runtime_2.12-1.13.5.jar:1.13.5]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:331) ~[flink-runtime_2.12-1.13.5.jar:1.13.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2022-07-10 11:06:24.407 [SourceCoordinator-Source: MySQL-Cdc-Source] ERROR org.apache.flink.runtime.source.coordinator.SourceCoordinator - Uncaught exception in the SplitEnumerator for Source Source: MySQL-Cdc-Source while handling operator event RequestSplitEvent (host='') from subtask 0. Triggering job failover.
org.apache.flink.util.FlinkRuntimeException: InterruptedException while waiting for asynchronously snapshot split
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlSnapshotSplitAssigner.getNext(MySqlSnapshotSplitAssigner.java:235) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlHybridSplitAssigner.getNext(MySqlHybridSplitAssigner.java:125) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator.assignSplits(MySqlSourceEnumerator.java:193) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator.handleSplitRequest(MySqlSourceEnumerator.java:109) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$handleEventFromOperator$1(SourceCoordinator.java:172) ~[flink-runtime_2.12-1.13.5.jar:1.13.5]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:331) ~[flink-runtime_2.12-1.13.5.jar:1.13.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2022-07-10 11:06:24.407 [SourceCoordinator-Source: MySQL-Cdc-Source] ERROR org.apache.flink.runtime.source.coordinator.SourceCoordinator - Uncaught exception in the SplitEnumerator for Source Source: MySQL-Cdc-Source while handling operator event RequestSplitEvent (host='') from subtask 0. Triggering job failover.
org.apache.flink.util.FlinkRuntimeException: InterruptedException while waiting for asynchronously snapshot split
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlSnapshotSplitAssigner.getNext(MySqlSnapshotSplitAssigner.java:235) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlHybridSplitAssigner.getNext(MySqlHybridSplitAssigner.java:125) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator.assignSplits(MySqlSourceEnumerator.java:193) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator.handleSplitRequest(MySqlSourceEnumerator.java:109) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$handleEventFromOperator$1(SourceCoordinator.java:172) ~[flink-runtime_2.12-1.13.5.jar:1.13.5]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:331) ~[flink-runtime_2.12-1.13.5.jar:1.13.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2022-07-10 11:07:25.420 [SourceCoordinator-Source: MySQL-Cdc-Source] ERROR org.apache.flink.runtime.source.coordinator.SourceCoordinator - Uncaught exception in the SplitEnumerator for Source Source: MySQL-Cdc-Source while handling operator event RequestSplitEvent (host='') from subtask 0. Triggering job failover.
org.apache.flink.util.FlinkRuntimeException: InterruptedException while waiting for asynchronously snapshot split
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlSnapshotSplitAssigner.getNext(MySqlSnapshotSplitAssigner.java:235) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlHybridSplitAssigner.getNext(MySqlHybridSplitAssigner.java:125) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator.assignSplits(MySqlSourceEnumerator.java:193) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator.handleSplitRequest(MySqlSourceEnumerator.java:109) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$handleEventFromOperator$1(SourceCoordinator.java:172) ~[flink-runtime_2.12-1.13.5.jar:1.13.5]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:331) ~[flink-runtime_2.12-1.13.5.jar:1.13.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2022-07-10 11:07:25.420 [SourceCoordinator-Source: MySQL-Cdc-Source] ERROR org.apache.flink.runtime.source.coordinator.SourceCoordinator - Uncaught exception in the SplitEnumerator for Source Source: MySQL-Cdc-Source while handling operator event RequestSplitEvent (host='') from subtask 0. Triggering job failover.
org.apache.flink.util.FlinkRuntimeException: InterruptedException while waiting for asynchronously snapshot split
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlSnapshotSplitAssigner.getNext(MySqlSnapshotSplitAssigner.java:235) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlHybridSplitAssigner.getNext(MySqlHybridSplitAssigner.java:125) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator.assignSplits(MySqlSourceEnumerator.java:193) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator.handleSplitRequest(MySqlSourceEnumerator.java:109) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$handleEventFromOperator$1(SourceCoordinator.java:172) ~[flink-runtime_2.12-1.13.5.jar:1.13.5]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:331) ~[flink-runtime_2.12-1.13.5.jar:1.13.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2022-07-10 11:08:26.430 [SourceCoordinator-Source: MySQL-Cdc-Source] ERROR org.apache.flink.runtime.source.coordinator.SourceCoordinator - Uncaught exception in the SplitEnumerator for Source Source: MySQL-Cdc-Source while handling operator event RequestSplitEvent (host='') from subtask 0. Triggering job failover.
org.apache.flink.util.FlinkRuntimeException: InterruptedException while waiting for asynchronously snapshot split
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlSnapshotSplitAssigner.getNext(MySqlSnapshotSplitAssigner.java:235) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlHybridSplitAssigner.getNext(MySqlHybridSplitAssigner.java:125) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator.assignSplits(MySqlSourceEnumerator.java:193) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator.handleSplitRequest(MySqlSourceEnumerator.java:109) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$handleEventFromOperator$1(SourceCoordinator.java:172) ~[flink-runtime_2.12-1.13.5.jar:1.13.5]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:331) ~[flink-runtime_2.12-1.13.5.jar:1.13.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2022-07-10 11:08:26.430 [SourceCoordinator-Source: MySQL-Cdc-Source] ERROR org.apache.flink.runtime.source.coordinator.SourceCoordinator - Uncaught exception in the SplitEnumerator for Source Source: MySQL-Cdc-Source while handling operator event RequestSplitEvent (host='') from subtask 0. Triggering job failover.
org.apache.flink.util.FlinkRuntimeException: InterruptedException while waiting for asynchronously snapshot split
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlSnapshotSplitAssigner.getNext(MySqlSnapshotSplitAssigner.java:235) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlHybridSplitAssigner.getNext(MySqlHybridSplitAssigner.java:125) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator.assignSplits(MySqlSourceEnumerator.java:193) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator.handleSplitRequest(MySqlSourceEnumerator.java:109) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$handleEventFromOperator$1(SourceCoordinator.java:172) ~[flink-runtime_2.12-1.13.5.jar:1.13.5]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:331) ~[flink-runtime_2.12-1.13.5.jar:1.13.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2022-07-10 11:09:27.460 [SourceCoordinator-Source: MySQL-Cdc-Source] ERROR org.apache.flink.runtime.source.coordinator.SourceCoordinator - Uncaught exception in the SplitEnumerator for Source Source: MySQL-Cdc-Source while handling operator event RequestSplitEvent (host='') from subtask 0. Triggering job failover.
org.apache.flink.util.FlinkRuntimeException: InterruptedException while waiting for asynchronously snapshot split
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlSnapshotSplitAssigner.getNext(MySqlSnapshotSplitAssigner.java:235) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlHybridSplitAssigner.getNext(MySqlHybridSplitAssigner.java:125) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator.assignSplits(MySqlSourceEnumerator.java:193) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator.handleSplitRequest(MySqlSourceEnumerator.java:109) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$handleEventFromOperator$1(SourceCoordinator.java:172) ~[flink-runtime_2.12-1.13.5.jar:1.13.5]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:331) ~[flink-runtime_2.12-1.13.5.jar:1.13.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2022-07-10 11:09:27.460 [SourceCoordinator-Source: MySQL-Cdc-Source] ERROR org.apache.flink.runtime.source.coordinator.SourceCoordinator - Uncaught exception in the SplitEnumerator for Source Source: MySQL-Cdc-Source while handling operator event RequestSplitEvent (host='') from subtask 0. Triggering job failover.
org.apache.flink.util.FlinkRuntimeException: InterruptedException while waiting for asynchronously snapshot split
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlSnapshotSplitAssigner.getNext(MySqlSnapshotSplitAssigner.java:235) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlHybridSplitAssigner.getNext(MySqlHybridSplitAssigner.java:125) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator.assignSplits(MySqlSourceEnumerator.java:193) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator.handleSplitRequest(MySqlSourceEnumerator.java:109) ~[flink-connector-mysql-cdc-2.2.0.jar:2.2.0]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$handleEventFromOperator$1(SourceCoordinator.java:172) ~[flink-runtime_2.12-1.13.5.jar:1.13.5]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:331) ~[flink-runtime_2.12-1.13.5.jar:1.13.5]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by deepthinkin** [comment] 2022-07-11 00:37
later, i use the way of  remote debug found the error that dbs  contains  all table no primary key.  but it is not friendly, why not throws errors.

**Comment by geosmart** [comment] 2023-01-11 04:06
@deepthinkin  thank you for save my life.

the consume table should has primary key for  buildSplitQuery . the error message is not friendly.

**Comment by EGitDeveloper** [comment] 2023-09-18 21:19
> @deepthinkin thank you for save my life.
> 
> the consume table should has primary key for buildSplitQuery . the error message is not friendly.

Could you please clarify exactly what buildSplitQuery is and where you configure it?

**Comment by geosmart** [comment] 2023-10-24 02:31
> > @deepthinkin thank you for save my life.
> > the consume table should has primary key for buildSplitQuery . the error message is not friendly.
> 
> Could you please clarify exactly what buildSplitQuery is and where you configure it?

first the consume table should has primary key.
[buildSplitQuery](https://github.com/ververica/flink-cdc-connectors/blob/e0fd6f965b702cc2876372dc068379dafe066277/flink-connector-mysql-cdc/src/main/java/com/ververica/cdc/connectors/mysql/source/utils/StatementUtils.java#L137) is the internal function of cdc :

**Comment by PatrickRen** [comment] 2024-02-28 15:29
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:29 UTC
Labels: bug
