### ISSUE TITLE
[mysql][improvement] support assign splits lazily

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#240] opened 2021-07-08 15:03 UTC
New feature, when the table primary key is not numeric or the primary key is combined key, the split analyzing may take much time, in this case, we can assign splits lazily to improve the total time.

**Comment by PatrickRen** [comment] 2024-02-28 15:33
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:33 UTC
Labels: task
