### ISSUE TITLE
Flink Connector  TiDB CDC throws exception  java.lang.NullPointerException at org.tikv.cdc.CDCClient.getMinResolvedTs

### ISSUE THREAD

**Issue by adam3asy** [ververica/flink-cdc-connectors#1598] opened 2022-09-30 07:16 UTC
**the bug**
I use Rancher to deploy a k8s cluster (3 node), then deploy a TiDB database on K8s use TiDB Operator， and then use Flink Operator to deploy a flink job service, its bussiness code as follows:

```
SourceFunction<String> tidbSource =
                TiDBSource.<String>builder()
                        .database("xxx") // set captured database
                        .tableName("xxx") // set captured table
                        .tiConf(
                                TDBSourceOptions.getTiConfiguration(
                                        "xx.xx.xx.xx:2379", new HashMap<>()))
                        .snapshotEventDeserializer(
                                new TiKVSnapshotEventDeserializationSchema<String>() {
                                    @Override
                                    public void deserialize(
                                            Kvrpcpb.KvPair record, Collector<String> out)
                                            throws Exception {
                                        out.collect(record.toString());
                                    }

                                    @Override
                                    public TypeInformation<String> getProducedType() {
                                        return BasicTypeInfo.STRING_TYPE_INFO;
                                    }
                                })
                        .changeEventDeserializer(
                                new TiKVChangeEventDeserializationSchema<String>() {
                                    @Override
                                    public void deserialize(
                                            Cdcpb.Event.Row record, Collector<String> out)
                                            throws Exception {
                                        out.collect(record.toString());
                                    }

                                    @Override
                                    public TypeInformation<String> getProducedType() {
                                        return BasicTypeInfo.STRING_TYPE_INFO;
                                    }
                                })
                        .build();

        StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();

        // enable checkpoint
        env.enableCheckpointing(3000);
        env.addSource(tidbSource).print().setParallelism(1);

        env.execute("Print TiDB Snapshot + Binlog");
```

the flink job  throws NullPointerException at org.tikv.cdc.CDCClient.getMinResolvedTs.  Details logs in the end. Can anybody knows why?

**Environment :**
 - Flink version :  1.14.4
 - Flink CDC version:  2.2.0
 - Database and version: TiDB v5.4.0
 - Rancher version: 2.5.8
 - K8s version: v1.20.11
 - Flink Kubernetes Operator: v1.1.0
 - TiDB Operator & TiDB Cluster: v1.3.7

**Additional Description**
these are error logs in flink-job-manager
```
2022-09-30 06:45:24,631 INFO  com.ververica.cdc.connectors.tidb.TiKVRichParallelSourceFunction [] - initialize checkpoint
2022-09-30 06:45:24,637 INFO  com.ververica.cdc.connectors.tidb.TiKVRichParallelSourceFunction [] - Initialize State from resolvedTs: 0
2022-09-30 06:45:24,639 INFO  org.tikv.common.TiSession                                    [] - Welcome to TiKV Java Client 3.2.0@cc3ec5f4e3349a50c335eace1ebd49e238cb3c7a
2022-09-30 06:45:24,656 INFO  org.tikv.common.PDClient                                     [] - init cluster: start
2022-09-30 06:45:24,793 INFO  org.tikv.common.PDClient                                     [] - init host mapping: start
2022-09-30 06:45:24,794 INFO  org.tikv.common.PDClient                                     [] - init host mapping: end
2022-09-30 06:45:24,794 INFO  org.tikv.common.PDClient                                     [] - get members with pd http://10.43.225.142:2379: start
2022-09-30 06:45:25,231 INFO  org.tikv.common.PDClient                                     [] - get members with pd http://10.43.225.142:2379: end
2022-09-30 06:45:25,234 INFO  org.tikv.common.PDClient                                     [] - init cluster with address: [http://tidb-cluster-pd-2.tidb-cluster-pd-peer.tidb-cluster.svc:2379, http://tidb-cluster-pd-1.tidb-cluster-pd-peer.tidb-cluster.svc:2379, http://tidb-cluster-pd-0.tidb-cluster-pd-peer.tidb-cluster.svc:2379]
2022-09-30 06:45:25,234 INFO  org.tikv.common.PDClient                                     [] - createLeaderClientWrapper with leader tidb-cluster-pd-0.tidb-cluster-pd-peer.tidb-cluster.svc:2379: start
2022-09-30 06:45:25,235 INFO  org.tikv.common.PDClient                                     [] - Switched to new leader: [leaderInfo: tidb-cluster-pd-0.tidb-cluster-pd-peer.tidb-cluster.svc:2379, storeAddress: tidb-cluster-pd-0.tidb-cluster-pd-peer.tidb-cluster.svc:2379]
2022-09-30 06:45:25,235 INFO  org.tikv.common.PDClient                                     [] - createLeaderClientWrapper with leader tidb-cluster-pd-0.tidb-cluster-pd-peer.tidb-cluster.svc:2379: end
2022-09-30 06:45:25,236 INFO  org.tikv.common.PDClient                                     [] - init cluster: finish
2022-09-30 06:45:25,236 INFO  org.tikv.common.TiSession                                    [] - enable grpc forward for high available
2022-09-30 06:45:25,237 INFO  org.tikv.common.TiSession                                    [] - TiSession initialized in TXN mode
2022-09-30 06:45:28,520 INFO  org.apache.flink.runtime.taskmanager.Task                    [] - Source: Custom Source -> Sink: Print to Std. Out (1/1)#0 (e1d8e53e687e909ccf15849379e66881) switched from INITIALIZING to RUNNING.
2022-09-30 06:45:28,629 INFO  com.ververica.cdc.connectors.tidb.TiKVRichParallelSourceFunction [] - read snapshot events
2022-09-30 06:45:29,443 INFO  com.ververica.cdc.connectors.tidb.TiKVRichParallelSourceFunction [] - start read change events
2022-09-30 06:45:29,449 INFO  org.tikv.cdc.CDCClient                                       [] - remove regions: []
2022-09-30 06:45:29,449 INFO  org.tikv.cdc.CDCClient                                       [] - add regions: [{Region[39500023] ConfVer[65] Version[88] Store[4] KeyRange[]:[]}], timestamp: 436344017234427906
2022-09-30 06:45:29,450 INFO  com.ververica.cdc.connectors.tidb.TiKVRichParallelSourceFunction [] - snapshotState checkpoint: 1 at resolvedTs: 436344017234427906
2022-09-30 06:45:29,449 ERROR org.tikv.cdc.CDCClient                                       [] - failed to start:
java.lang.IllegalArgumentException: Invalid range: [+INF..{116,128,0,0,0,0,0,0,119,95,115,0,0,0,0,0,0,0,0})
	at org.tikv.shade.com.google.common.collect.Range.<init>(Range.java:358) ~[blob_p-9da03a33ba463125e7b0b07eb8b2cac1fbae0e73-d287f17e452763d358f08629a252b5f2:?]
	at org.tikv.shade.com.google.common.collect.Range.create(Range.java:156) ~[blob_p-9da03a33ba463125e7b0b07eb8b2cac1fbae0e73-d287f17e452763d358f08629a252b5f2:?]
	at org.tikv.shade.com.google.common.collect.Range.intersection(Range.java:558) ~[blob_p-9da03a33ba463125e7b0b07eb8b2cac1fbae0e73-d287f17e452763d358f08629a252b5f2:?]
	at org.tikv.cdc.CDCClient.overlapWithRegion(CDCClient.java:214) ~[blob_p-9da03a33ba463125e7b0b07eb8b2cac1fbae0e73-d287f17e452763d358f08629a252b5f2:?]
	at org.tikv.cdc.CDCClient.addRegions(CDCClient.java:167) ~[blob_p-9da03a33ba463125e7b0b07eb8b2cac1fbae0e73-d287f17e452763d358f08629a252b5f2:?]
	at org.tikv.cdc.CDCClient.applyKeyRange(CDCClient.java:160) ~[blob_p-9da03a33ba463125e7b0b07eb8b2cac1fbae0e73-d287f17e452763d358f08629a252b5f2:?]
	at org.tikv.cdc.CDCClient.start(CDCClient.java:75) [blob_p-9da03a33ba463125e7b0b07eb8b2cac1fbae0e73-d287f17e452763d358f08629a252b5f2:?]
	at com.ververica.cdc.connectors.tidb.TiKVRichParallelSourceFunction.run(TiKVRichParallelSourceFunction.java:135) [blob_p-9da03a33ba463125e7b0b07eb8b2cac1fbae0e73-d287f17e452763d358f08629a252b5f2:?]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110) [flink-dist_2.12-1.14.4.jar:1.14.4]
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:67) [flink-dist_2.12-1.14.4.jar:1.14.4]
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:323) [flink-dist_2.12-1.14.4.jar:1.14.4]
2022-09-30 06:45:29,452 INFO  com.ververica.cdc.connectors.tidb.TiKVRichParallelSourceFunction [] - read change event from resolvedTs:436344017234427906
2022-09-30 06:45:29,557 INFO  org.tikv.cdc.CDCClient                                       [] - remove regions: []
2022-09-30 06:45:29,569 WARN  org.apache.flink.runtime.taskmanager.Task                    [] - Source: Custom Source -> Sink: Print to Std. Out (1/1)#0 (e1d8e53e687e909ccf15849379e66881) switched from RUNNING to FAILED with failure cause: java.lang.NullPointerException
	at org.tikv.cdc.CDCClient.getMinResolvedTs(CDCClient.java:100)
	at com.ververica.cdc.connectors.tidb.TiKVRichParallelSourceFunction.readChangeEvents(TiKVRichParallelSourceFunction.java:205)
	at com.ververica.cdc.connectors.tidb.TiKVRichParallelSourceFunction.run(TiKVRichParallelSourceFunction.java:136)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:110)
	at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:67)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:323)
```

**Comment by zhangzhaohuazai** [comment] 2023-05-08 01:13
How is it going now？

**Comment by PatrickRen** [comment] 2024-02-28 15:28
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:28 UTC
Labels: bug
