### ISSUE TITLE
Is there a problem with our license selection?

### ISSUE THREAD

**Issue by JesseAtSZ** [ververica/flink-cdc-connectors#884] opened 2022-02-23 07:17 UTC
mysql-connector-java, which flink-sql-connector-mysql-cdc relies on, is a GPL license, so should flink-cdc-connectors also be a GPL license?

![image](https://user-images.githubusercontent.com/35264598/155646142-63e413cf-73a9-49f0-a7d1-489bfc906ae0.png)

**Comment by JesseAtSZ** [comment] 2022-02-24 01:37
In fact, I mentioned this issue because I was confused about the GPL license, because I found that debezium also relies on mysql, but it is still Apache 2.0 externally. I don't know whether debezium is also wrong to use it in this way.
![image](https://user-images.githubusercontent.com/35264598/155440565-e851f7d5-8cd8-4658-a304-14fdb825a5bf.png)

**Comment by whhe** [comment] 2022-02-24 03:06
There are FOSS License Exception and Universal FOSS Exception for MySQL Client Libraries. I'm not sure if it applies here.
 https://www.mysql.com/cn/about/legal/licensing/foss-exception/

**Comment by wuchong** [comment] 2022-02-24 09:36
I opened an issue in Debezium community as well https://issues.redhat.com/browse/DBZ-4793

**Comment by JesseAtSZ** [comment] 2022-02-25 01:57
> I opened an issue in Debezium community as well https://issues.redhat.com/browse/DBZ-4793

Can you tell me the relationship between FOSS and GPL, does he mean that this library complies with two licenses at the same time? 

It is used in the way of jar package, which only involves the interface, not the source code, so it is allowed to use Apache license externally?

**Comment by wuchong** [comment] 2022-02-25 02:26
FOSS is the short of `Free Open Source Software`. The Universal FOSS Exception says it grants the additional permission to the projects under a license that is OSI-approved and/or categorized by the FSF as free. ASLv2 is of course one of the licenses.

**Comment by whhe** [comment] 2022-02-25 03:27
No one takes a look at the link in my reply, sad.

**Comment by wuchong** [comment] 2022-02-25 03:55
Thanks for the link @whhe , I was just not sure and confirmed with Debezium community.

**Comment by PatrickRen** [comment] 2024-02-28 15:09
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:09 UTC
