### ISSUE TITLE
Flink 1.14.4+Flink CDC 2.2.1 dependency problem

### ISSUE THREAD

**Issue by hunter-cloud09** [ververica/flink-cdc-connectors#1259] opened 2022-06-09 03:07 UTC
When I am using flink1.14+flink cdc 2.2.1, because the flink version depends on the source code is 1.13.5, it will prompt that the dependency org.apache.flink:flink-shaded-guava:18.0-13.0 is missing, if you refer to flink-sql-connector-mysql-cdc, these problems will not appear

**Comment by KWIGNIS** [comment] 2022-06-13 05:29
Why does this happen? Why does datastream API appear, but SQL API does not? Please take me with you

**Comment by nyingping** [comment] 2022-06-13 07:01
mark
It doesn't seem to be a matter of jar conflict

**Comment by PatrickRen** [comment] 2024-02-28 15:07
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:07 UTC
Labels: bug
