### ISSUE TITLE
Support DaMeng DB 8.X

### ISSUE THREAD

**Issue by yequanzhuo** [ververica/flink-cdc-connectors#1589] opened 2022-09-28 09:16 UTC
Hi, Are there any plans in the near future to support version 8.x of DaMeng DB?

**Comment by PatrickRen** [comment] 2024-02-28 15:28
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:28 UTC
Labels: enhancement
