### ISSUE TITLE
OracleDG Support

### ISSUE THREAD

**Issue by rekichan** [ververica/flink-cdc-connectors#683] opened 2021-12-02 14:45 UTC
![QQ图片20211202224502](https://user-images.githubusercontent.com/56336716/144444080-35166b50-2174-402a-847d-4cb5b6c7f30b.png)

**Comment by rekichan** [comment] 2021-12-02 14:48
开发者你们好：
最近我的项目中遇到了一个问题，我们的DBA要求只能从主库中写入数据，从备库（不能写，分配了只读权限）中读取数据。而OracleCDC只能读写同一个库，这导致了程序在运行中必然会报权限不足的异常。
请问一下我应该如何解决这个问题？或者说这个问题在后续版本能否得到优化？谢谢！

**Comment by PatrickRen** [comment] 2024-02-28 15:37
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:37 UTC
Labels: enhancement
