### ISSUE TITLE
After the task runs for a period of time, no exception is thrown, but no data is synchronized

### ISSUE THREAD

**Issue by qianchutao** [ververica/flink-cdc-connectors#1467] opened 2022-08-10 10:27 UTC
**Environment :**
 - Flink version :  1.14.0
 - Flink CDC version:  2.2.3-snaphot
 - Database and version: mysql5.7

**Additional Description**
Using flinkCDC 2.3-Snaphot to synchronize mysql data, multiple tables were synchronized at a time. After the task ran for a period of time, no data was synchronized, and the task was not thrown. After checking the log, it was found that the full synchronization was stuck

![lQLPJxaT3WUYwu7NAa3NBSuwtXCjv2ixCG4C81P56gCEAA_1323_429](https://user-images.githubusercontent.com/72595723/183879562-aa8c4963-57f3-4f15-98f9-368c8bbd7abc.png)

**Comment by PatrickRen** [comment] 2024-02-28 15:05
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:05 UTC
Labels: bug
