### ISSUE TITLE
Debezium automatically changes Oracle 11g Tables to lowercase

### ISSUE THREAD

**Issue by dingyang0519** [ververica/flink-cdc-connectors#702] opened 2021-12-08 13:00 UTC
Debezium automatically changes the table names in Oracle 11g to lowercase, which will make it fail to find the tables as belows:

[ERROR] Could not execute SQL statement. Reason:
io.debezium.DebeziumException: Supplemental logging not configured for table MY_SERVICE_NAME.MY_SCHEMA.test.  Use command: ALTER TABLE MY_SCHEMA.test ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS

In the Wiki, suggestions is to add the 'debezium.database.tablename.case.insensitive'='false' option. So it is suggested to Flink CDC to automatically add the option in the future version.

**Comment by luoyuxia** [comment] 2022-01-10 09:40
@dingyang0519 Thanks very much for reporting it. Would you like to open a pr for it? We'll really appreciate that.

**Comment by PatrickRen** [comment] 2024-02-28 15:37
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:37 UTC
Labels: enhancement
