### ISSUE TITLE
Flink Connector mysql CDC sql-client模式下全库扫描，直到capturing到目标表，如果实例下库表比较多，会影响任务启动时效

### ISSUE THREAD

**Issue by EvanSole** [ververica/flink-cdc-connectors#82] opened 2021-01-11 10:34 UTC
CREATE TABLE mysql_company_cdc (
 id bigint NOT NULL,
 company STRING
) WITH (
 'connector' = 'mysql-cdc',
 'hostname' = 'localhost',
 'port' = '3306',
 'username' = 'root',
 'password' = '123456',
 'database-name' = 'inventory',
 'table-name' = 'company'
);

select id,UPPER(company) from mysql_company_cdc;

启动任务后会创建一个，会全库扫描，capture目标表，如果实例下库表比较多，会影响任务启动时效
<img width="1111" alt="1" src="https://user-images.githubusercontent.com/6367452/104170117-97b5a680-543b-11eb-967b-ffcad5d61409.png">
<img width="1111" alt="2" src="https://user-images.githubusercontent.com/6367452/104170153-a3a16880-543b-11eb-888a-f3a5bae442fa.png">

2021-01-07 20:23:11,794 INFO  io.debezium.util.Threads                                     [] - Creating thread debezium-mysqlconnector-mysql_binlog_source-snapshot
2021-01-07 20:23:11,798 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - Starting snapshot for jdbc:mysql://localhost:3306/?useInformationSchema=true&nullCatalogMeansCurrent=false&useSSL=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&connectTimeout=30000 with user 'root' with locking mode 'minimal'
2021-01-07 20:23:11,800 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - Starting snapshot for jdbc:mysql://localhost:3306/?useInformationSchema=true&nullCatalogMeansCurrent=false&useSSL=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&connectTimeout=30000 with user 'root' with locking mode 'minimal'
2021-01-07 20:23:11,803 INFO  org.apache.flink.runtime.state.heap.HeapKeyedStateBackend    [] - Initializing heap keyed state backend with stream factory.
2021-01-07 20:23:11,807 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - Snapshot is using user 'root' with these MySQL grants:
2021-01-07 20:23:11,808 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - 	GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION
2021-01-07 20:23:11,808 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - 	GRANT PROXY ON ''@'' TO 'root'@'localhost' WITH GRANT OPTION
2021-01-07 20:23:11,808 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - MySQL server variables related to change data capture:
2021-01-07 20:23:11,809 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - Snapshot is using user 'root' with these MySQL grants:
2021-01-07 20:23:11,810 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - 	GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION
2021-01-07 20:23:11,810 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - 	GRANT PROXY ON ''@'' TO 'root'@'localhost' WITH GRANT OPTION
2021-01-07 20:23:11,810 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - MySQL server variables related to change data capture:
2021-01-07 20:23:11,812 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - 	binlog_cache_size                             = 32768                                        
2021-01-07 20:23:11,813 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - 	binlog_checksum                               = CRC32                                        
2021-01-07 20:23:11,813 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - 	binlog_direct_non_transactional_updates       = OFF                                          
2021-01-07 20:23:11,813 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - 	binlog_error_action                           = ABORT_SERVER                                 
2021-01-07 20:23:11,813 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - 	binlog_format                                 = ROW                                          
2021-01-07 20:23:11,813 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - 	binlog_group_commit_sync_delay                = 0                                            
2021-01-07 20:23:11,813 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - 	binlog_group_commit_sync_no_delay_count       = 0                                            
2021-01-07 20:23:11,813 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - 	binlog_gtid_simple_recovery                   = ON                                           
2021-01-07 20:23:11,813 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - 	binlog_max_flush_queue_time                   = 0                                            
2021-01-07 20:23:11,813 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - 	binlog_order_commits                          = ON                                           
2021-01-07 20:23:11,813 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - 	binlog_row_image                              = FULL                                         
2021-01-07 20:23:11,813 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - 	binlog_rows_query_log_events                  = OFF                                          
2021-01-07 20:23:11,813 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - 	binlog_stmt_cache_size                        = 32768                                        
2021-01-07 20:23:11,813 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - 	binlog_transaction_dependency_history_size    = 25000                                        
2021-01-07 20:23:11,813 INFO  io.debezium.connector.mysql.SnapshotReader                   [] - 	binlog_transaction_dependency_tracking

**Comment by leewaiho** [comment] 2021-02-04 04:17
可以通过缩小数据库权限避免扫描全库

```sql
-- 授予REPLICATION Slave权限
GRANT RELOAD,REPLICATION SLAVE, REPLICATION CLIENT on *.* to 'username';

-- 授予目标库的访问权限
GRANT SELECT ON `your_single_database`.* TO 'username'@'%';

-- 刷新权限
FLUSH PRIVILEGES;
```

**Comment by PatrickRen** [comment] 2024-02-28 15:41
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:41 UTC
Labels: enhancement, task
