### ISSUE TITLE
Oracle CDC Whether the dynamic discovery of new tables is supported

### ISSUE THREAD

**Issue by Rowen110** [ververica/flink-cdc-connectors#1379] opened 2022-07-15 09:48 UTC
Flink CDC Orcale Source Whether can support automatic scanning new table functions, like mysql CDC scanNewlyAddedTableEnabled feature function.

**Comment by hbk671104** [comment] 2022-12-30 09:26
Need this so bad. +1

**Comment by e-mhui** [comment] 2023-04-13 02:26
Oracle now supports automatically detecting newly added tables. What is the scenario of you?

**Comment by e-mhui** [comment] 2023-04-13 02:54
@Rowen110 @hbk671104 pls review it https://github.com/ververica/flink-cdc-connectors/pull/2078 .

**Comment by PatrickRen** [comment] 2024-02-28 15:36
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:36 UTC
Labels: enhancement
