### ISSUE TITLE
this no longer available on the server

### ISSUE THREAD

**Issue by 1105220927** [ververica/flink-cdc-connectors#1117] opened 2022-04-25 07:43 UTC
**Environment :**
 - Flink version :  1.13.3
 - Flink CDC version:  2.1.1
 - Database and version:  mysql 

如果接入的数据表长时间不更新(超过binlog文件滚动时间)，通过checkpoint重启时，会报错binlog文件找不到。

![image](https://user-images.githubusercontent.com/95424327/165042751-fb7af7d1-b5d4-4000-b64b-b7f7282e96eb.png)

**Comment by PatrickRen** [comment] 2024-02-28 15:08
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:08 UTC
Labels: bug
