### ISSUE TITLE
DataStream api need support close incremental snapshot

### ISSUE THREAD

**Issue by Kyofin** [ververica/flink-cdc-connectors#1337] opened 2022-07-01 10:00 UTC
**Is your feature request related to a problem? Please describe.**
When i use Datastream Api to Collect Mysql Binlog to Kafka , I find it will error when some table don't have primary key.
Error message is below:
```
Incremental snapshot for tables requires primary key, but table ssb.customer doesn't have primary key
```

**Describe the solution you'd like**
flink 1.13.6  , flinkcdc 2.2.1
my code :
```
  MySqlSource<String> mySqlSource = MySqlSource.<String>builder()
                .hostname("xxx")
                .port(3306)
                .databaseList("ssb") // set captured database
                .tableList("ssb.*") // set captured table
                .username("xxx")
                .password("xxx")
                .startupOptions(StartupOptions.initial())
                .deserializer(new JsonDebeziumDeserializationSchema()) 
                .build();
```

How can i close  Incremental snapshot  when i use datastream api?

**Describe alternatives you've considered**

**Comment by killyouall** [comment] 2022-07-28 01:11
I also encountered this problem. Which God can solve it

**Comment by JavaKingCr** [comment] 2022-08-23 08:40
How did you solve the problem

**Comment by JavaKingCr** [comment] 2022-08-23 08:50
hellp

**Comment by PatrickRen** [comment] 2024-02-28 15:05
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:05 UTC
Labels: enhancement
