### ISSUE TITLE
Elasticsearch SQL Connector with ssl 

### ISSUE THREAD

**Issue by bulolo** [ververica/flink-cdc-connectors#958] opened 2022-03-17 09:10 UTC
when i use [Elasticsearch SQL Connector](https://nightlies.apache.org/flink/flink-docs-release-1.14/zh/docs/connectors/table/elasticsearch/)

i found that my es secret by ssl  and use Self-Sign Certificate, i can not connect elasticsearch as sink,because there is no option   to set cert

```
CREATE TABLE enriched_orders (
  order_id INT,
  order_date TIMESTAMP_LTZ(3),
  customer_id INT,
  price DECIMAL(10, 5),
  product ROW<name STRING, description STRING>,
  order_status BOOLEAN,
  customer_name STRING,
  customer_address STRING,
  PRIMARY KEY (order_id) NOT ENFORCED
) WITH (
 'connector' = 'elasticsearch-7',
 'hosts' = 'http://localhost:9200',
 'index' = 'enriched_orders',
 'username' = 'root',
 'password' = 'password'
);
```
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/10026498/158776322-89f2ee77-0a3a-47a1-9f29-7e4b51e374d7.png">

when i use `kibana` to connect to es i had to set `elasticsearch.ssl.verificationMode: none` to let ssl connect to es successful
when i use `filebeat` to connect to es i had to set `ssl.verification_mode: none` to let ssl connect to es successful
any other client want to connect to es also nedd to set  ssl config to connect es with ssl.

but i found no idea how to connect to es as a sink with ssl

this is my es config
```
cluster.name: "docker-cluster"
network.host: 0.0.0.0

http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-headers: Authorization,X-Requested-With,Content-Length,Content-Type


xpack.license.self_generated.type: basic


xpack.security.enabled: true

xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: certs/elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: certs/elastic-certificates.p12


xpack.security.http.ssl.enabled: true
xpack.security.authc.api_key.enabled: true
xpack.security.http.ssl.keystore.path: certs/elastic-certificates.p12
xpack.security.http.ssl.truststore.path: certs/elastic-certificates.p12
xpack.security.http.ssl.verification_mode: none
xpack.security.http.ssl.client_authentication: none


xpack.monitoring.collection.enabled: false

```

**Comment by rookiegao** [comment] 2022-03-18 03:45
This is the Flink CDC community. The CDC connector runs as a source. Please feed back to the Flink community about the sink connector

**Comment by PatrickRen** [comment] 2024-02-28 15:09
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:09 UTC
Labels: enhancement
