### ISSUE TITLE
[jdk-support] Flink will deprecate jdk8 in feature.

### ISSUE THREAD

**Issue by GOODBOY008** [ververica/flink-cdc-connectors#891] opened 2022-02-24 09:43 UTC
**Is your feature request related to a problem? Please describe.**
 Flink will deprecate jdk8 in feature.

**Describe the solution you'd like**
When flink release next version,follow flink's step to support jdk11 and bump debezium version to lastest,because of  debezium 1.5 later verison only support jdk11+.Also we will maintain multi branches for user,because we will support multi flink version.

**Comment by GOODBOY008** [comment] 2022-02-24 09:44
@leonardBang What do you think about this?

**Comment by PatrickRen** [comment] 2024-02-28 15:09
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:09 UTC
Labels: enhancement
