### ISSUE TITLE
对应订单es模型（orderitems使用nested object），如何把 orderitem 构造成 ARRAY<ROW< id INT, orderid INT, productid INT, price INT, >>写入elasticsearch

### ISSUE THREAD

**Issue by caozhiyuan** [ververica/flink-cdc-connectors#1484] opened 2022-08-17 03:11 UTC
**Is your feature request related to a problem? Please describe.**

对应订单es模型（orderitem使用nested object），如何把 orderitems 构造成 ARRAY<ROW< id INT, orderid INT, productid INT, price INT, >>写入elasticsearch

**Describe the solution you'd like**
使用易配置的方式实现，无须java代码定义UDF。

**Comment by caozhiyuan** [comment] 2022-08-17 03:14
like this https://github.com/ververica/flink-cdc-connectors/issues/151 , now have better sloution?

**Comment by yilongchuan** [comment] 2023-02-07 01:54
Ask the same question, How to simply define data of type es nested？
同样的问题，如何简单定义一个es 的 nested 嵌套类型字段？
顺便问下，父子文档类型 （join） 类型如何处理?

**Comment by PatrickRen** [comment] 2024-02-28 15:05
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:05 UTC
Labels: enhancement
