### ISSUE TITLE
flinkcdc 拿不到数据库数据

### ISSUE THREAD

**Issue by PengMinghui973** [ververica/flink-cdc-connectors#1059] opened 2022-04-08 07:12 UTC
启动flink连接pg数据库 ，请问怎么解决 一直提示这些io.debezium.connector.postgresql.connection.PostgresConnection [] - Cannot obtain valid replication slot 'h_appstore_new_slot_6' for plugin 'pgoutput' and database 'h_appstore_new' [during attempt 23 out of 900, concurrent tx probably blocks taking snapshot.

![EPG`9WB V@JR7QX A9VU797](https://user-images.githubusercontent.com/62225711/162383406-7e511871-d432-4ed0-8b80-ba4730521792.png)

**Comment by PatrickRen** [comment] 2022-04-19 09:09
@PengMinghui973 Could you check if the privilege of the user connecting to the DB is correctly configured? There's [a detailed description](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-permissions) about permissions required for using Postgres CDC.

**Comment by PatrickRen** [comment] 2024-02-28 15:37
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:37 UTC
Labels: bug
