### ISSUE TITLE
PostgreSQL(12.0) replication slot消费完后restart_lsn不变导致PG的WAL日志不被清理

### ISSUE THREAD

**Issue by tiyh** [ververica/flink-cdc-connectors#106] opened 2021-02-22 13:33 UTC
Debezium消费了WAL restart_lsn不会变化，PostgreSQL数据update后，确认CDC成功同步后，restart_lsn不变
重启Flink任务restart_lsn也不会前进，WAL占用空间一直增长

select pg_size_pretty(pg_wal_lsn_diff(pg_current_wal_lsn(),'5B/270B2568'));
95 GB

slot_name,plugin,slot_type,datoid,database,temporary,active,active_pid,xmin,catalog_xmin,restart_lsn,confirmed_flush_lsn
"debezium","pgoutput","logical","16393","test","f","t","4822",null,"983310","5B/270B2568","5B/270B25A0"

**Comment by eric3zhao** [comment] 2021-02-23 08:28
已知bug #92 ，今天我提交了一个PR #107 可以参考一下

**Comment by tiyh** [comment] 2021-02-23 09:50
> 已知bug #92 ，今天我提交了一个PR #107 可以参考一下

@eric3zhao 
请教下，您是否清楚这里为啥把默认commit offset关闭

//flink-connector-debezium/src/main/java/com/alibaba/ververica/cdc/debezium/DebeziumSourceFunction.java
		// disable the offset flush totally
		properties.setProperty("offset.flush.interval.ms", String.valueOf(Long.MAX_VALUE));
		
		offset.flush.interval.ms | 60000 | Interval at which to try committing offsets. The default is 1 minute.

**Comment by tiyh** [comment] 2021-02-23 13:02
offset.flush.interval.ms这个参数依赖 kafka，flink-cdc-connector 是不依赖 kafka 的

**Comment by eric3zhao** [comment] 2021-02-24 05:37
flink的容错是通过checkpoint去做的，所以提交offset应该是当snapshot中去做。如果是用task中的commit逻辑去做有可能导致wal中的lsn和checkpoint中的对应不上，从而导致丢数据

**Comment by wuchong** [comment] 2021-02-24 06:19
Closes this issue as a duplicate of #92

**Closed by wuchong** 2021-02-24 06:19 UTC
