### ISSUE TITLE
debezium 执行sql对数据库压力太大

### ISSUE THREAD

**Issue by PengMinghui973** [ververica/flink-cdc-connectors#969] opened 2022-03-21 07:08 UTC
在flink-connector-postgres-cdc版本为2.0.2中
类路径io/debezium/connector/postgresql/connection/PostgresReplicationConnection.class
PostgresReplicationConnection类中initPublication方法 有条sql:SELECT COUNT(1) FROM pg_publication WHERE pubname = '%s'
每分钟对数据库执行 这个每分钟执行sql时间间隔太小 是否可以调大？如果可以 怎么解决？ 谢谢！
![image](https://user-images.githubusercontent.com/62225711/159217661-316ad80c-ad19-453b-ac42-8644400e823d.png)

**Comment by GOODBOY008** [comment] 2022-03-21 07:19
@PengMinghui973 Have you set config property [publication.autocreate.mode](https://debezium.io/documentation/reference/1.5/connectors/postgresql.html#postgresql-publication-autocreate-mode) ?

**Comment by PengMinghui973** [comment] 2022-03-21 07:23
> @PengMinghui973是否设置了配置属性 [publication.autocreate.mode](https://debezium.io/documentation/reference/1.5/connectors/postgresql.html#postgresql-publication-autocreate-mode) ？

publication.autocreate.mode属性值 怎么设置呢 是设置可以关闭 还是可以扩大查询间隔时间

**Comment by GOODBOY008** [comment] 2022-03-21 07:32
> 

You can use follow config property to pass debezium configuration. Just set tables which you want to monitor.
![企业微信截图_16478477964278](https://user-images.githubusercontent.com/13617900/159219826-daeb6f9a-273c-4644-8434-59251f000963.png)

**Comment by PengMinghui973** [comment] 2022-03-21 07:45
> > 
> 
> 您可以使用 follow 配置属性来传递 debezium 配置。只需设置要监视的表即可。 ![企业微信截图_16478477964278](https://user-images.githubusercontent.com/13617900/159219826-daeb6f9a-273c-4644-8434-59251f000963.png)

如果我想调整5分钟查询一次sql 可以吗 该怎么设置呀 谢谢

**Comment by GOODBOY008** [comment] 2022-03-21 07:47
> 如果我想调整5分钟查询一次sql 可以吗 该怎么设置呀 谢谢

Set configuration [poll.interval.ms](https://debezium.io/documentation/reference/1.5/connectors/postgresql.html#postgresql-property-poll-interval-ms) .

**Comment by PengMinghui973** [comment] 2022-03-22 01:29
![lQLPDhtCAi6Ex0bNA0nNBuewv3By6UA4X00CPNJRb8BsAA_1767_841](https://user-images.githubusercontent.com/62225711/159389194-47f688b5-7a5b-46dd-8c89-be88adfc5d01.png)
这个频率是秒级轮询，昨天加了配置不起效果
![lQLPDhtCAi6Ex2bNArHNAzKwMkrWkyWGRYYCPNJRcwBaAA_818_689](https://user-images.githubusercontent.com/62225711/159389353-fef6648f-f6be-4866-b0ee-a03065ae89fb.png)

**Comment by wuchong** [comment] 2022-03-22 02:30
@PengMinghui973 are your jobs keep failing or do you have many jobs? In theory, this query should only be executed only once on startup.

**Comment by PengMinghui973** [comment] 2022-03-22 02:40
> @PengMinghui973你的工作不断失败，还是你有很多工作？从理论上讲，此查询只应在启动时执行一次。
目前只同步一张表 但是查询间隔还是秒级的，如果只启动时执行一次 是我这边有啥设置忽略了吗

**Comment by PengMinghui973** [comment] 2022-03-22 04:27
核心dai代码![image](https://user-images.githubusercontent.com/62225711/159408089-d08eda97-6155-4add-833d-b0ae2d77de31.png)
![image](https://user-images.githubusercontent.com/62225711/159408143-39f923d9-3709-4d1b-a179-c33616a4c789.png)

**Comment by GOODBOY008** [comment] 2022-03-22 04:45
> @PengMinghui973 are your jobs keep failing or do you have many jobs? In theory, this query should only be executed only once on startup.

Yes,I have test in my local with pg connector unit test .Just execute once.

**Comment by PatrickRen** [comment] 2024-02-28 15:31
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:31 UTC
Labels: bug
