### ISSUE TITLE
[tidb-cdc] Monitor tidb table lose data, which table has one more regions.

### ISSUE THREAD

**Issue by GOODBOY008** [ververica/flink-cdc-connectors#1159] opened 2022-05-09 15:11 UTC
**Describe the bug(Please use English)**

**Environment :**
 - Flink CDC version:  2.2.1

Link [issue](https://github.com/tikv/client-java/issues/600).

**Comment by xieyi888** [comment] 2022-05-10 06:43
I found the bug when using tidb-cdc https://github.com/tikv/client-java/issues/600
I think here are two ways to solve this problem in TiDB-CDC：
(1) fix the bug https://github.com/tikv/client-java/issues/600
(2) change code of com.ververica.cdc.connectors.tidb.TiKVRichParallelSourceFunction.readSnapshotEvents
before scan each region, getEndKey  of each region.  set the endKey, then scanClient.scan(startKey, endKey, startTs).  roughly as follows：
Howerer, in this way, startKey、endKey  devide become complex when flink job parallelism>1 (the following code did not consider this situation)
```java
    protected void readSnapshotEvents() throws Exception {
        LOG.info("read snapshot events");
        final KVClient scanClient = session.createKVClient();
        long startTs = session.getTimestamp().getVersion();
        long tableId = session.getCatalog().getTable(database, tableName).getId();
        ByteString startKey = RowKey.toRowKey(tableId, Long.MIN_VALUE).toByteString();
        TiRegion regionByKey = session.getRegionManager().getRegionByKey(startKey);
        ByteString endKey = regionByKey.getEndKey();
        try {
            while (true) {
                final List<Kvrpcpb.KvPair> segment =
                        scanClient.scan(startKey, endKey, startTs);

                if (segment.isEmpty()) {
                    resolvedTs = startTs;
                    break;
                }

                for (final Kvrpcpb.KvPair pair : segment) {
                    if (TableKeyRangeUtils.isRecordKey(pair.getKey().toByteArray())) {
                        snapshotEventDeserializationSchema.deserialize(pair, outputCollector);
                    }
                }

                startKey =
                        RowKey.toRawKey(segment.get(segment.size() - 1).getKey())
                                .next()
                                .toByteString();

                endKey = regionByKey.getEndKey();
                if(Key.toRawKey(endKey).getInfFlag()==1) {
                    endKey = RowKey.toRowKey(tableId, Long.MAX_VALUE).toByteString();
                }else{
                    if(segment.size()<10240L){
                        startKey = regionByKey.getEndKey();
                        regionByKey = session.getRegionManager().getRegionByKey(startKey);
                        endKey = regionByKey.getEndKey();
                    }
                }
            }
        } finally {
            scanClient.close();
        }
    }
```

which way do you think is better?

**Comment by zengqinchris** [comment] 2022-05-18 06:10
应该是cdc的bug，我也遇到了，tidb表数据量大，全量拉取数据丢时问题

**Comment by xieyi888** [comment] 2022-05-18 06:40
hi,data loss is caused by tikv-cient-java.
I had fix the bug in tikv-client-java:https://github.com/tikv/client-java/issues/600.
to avoid data loss in tidb-cdc snapshot, we can build  tikv-java-client from master branch source code, and change the   dependency in [tidb-cdc ](https://github.com/ververica/flink-cdc-connectors/blob/master/flink-connector-tidb-cdc/pom.xml)      
```
<dependency>
            <groupId>org.tikv</groupId>
            <artifactId>tikv-client-java</artifactId>
            <version>${tikv.version}</version>
        </dependency>
```
I had test, and no data loss in snapshot.

**Comment by GOODBOY008** [comment] 2022-05-18 06:52
@xieyi888 @zengqinchris I have copy class `ScanIterator` to tidb cdc to fix this issue.

**Comment by zengqinchris** [comment] 2022-05-18 07:03
> hi,data loss is caused by tikv-cient-java. I had fix the bug in tikv-client-java:[tikv/client-java#600](https://github.com/tikv/client-java/issues/600). to avoid data loss in tidb-cdc snapshot, we can build tikv-java-client from master branch source code, and change the dependency in [tidb-cdc ](https://github.com/ververica/flink-cdc-connectors/blob/master/flink-connector-tidb-cdc/pom.xml)
> 
> ```
> <dependency>
>             <groupId>org.tikv</groupId>
>             <artifactId>tikv-client-java</artifactId>
>             <version>${tikv.version}</version>
>         </dependency>
> ```
> 
> I had test, and then no data loss in tidb-cdc snapshot.

用的是什么版本的jar

![image](https://user-images.githubusercontent.com/44901627/168977110-40a41f29-e193-4a3c-8a91-29879cdd872d.png)
![image](https://user-images.githubusercontent.com/44901627/168977155-d149c74d-afa4-4de9-95db-4c48ecc4fd59.png)

我的是最新版本 3.2.0

**Comment by zengqinchris** [comment] 2022-05-18 07:09
@xieyi888 Do you have a packaged flink-cdc code package, please share

**Comment by xieyi888** [comment] 2022-05-18 07:11
> > hi,data loss is caused by tikv-cient-java. I had fix the bug in tikv-client-java:[tikv/client-java#600](https://github.com/tikv/client-java/issues/600). to avoid data loss in tidb-cdc snapshot, we can build tikv-java-client from master branch source code, and change the dependency in [tidb-cdc ](https://github.com/ververica/flink-cdc-connectors/blob/master/flink-connector-tidb-cdc/pom.xml)
> > ```
> > <dependency>
> >             <groupId>org.tikv</groupId>
> >             <artifactId>tikv-client-java</artifactId>
> >             <version>${tikv.version}</version>
> >         </dependency>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I had test, and then no data loss in tidb-cdc snapshot.
> 
> 用的是什么版本的jar
> 
> ![image](https://user-images.githubusercontent.com/44901627/168977110-40a41f29-e193-4a3c-8a91-29879cdd872d.png) ![image](https://user-images.githubusercontent.com/44901627/168977155-d149c74d-afa4-4de9-95db-4c48ecc4fd59.png)
> 
> 我的是最新版本 3.2.0

The master had not releases .Here are steps for short fix:

1. clone https://github.com/tikv/client-java and checkout master branch
```git clone https://github.com/tikv/client-java.git
     git checkout master
````
2. build tikv-client-java in local repository
`mvn clean install -Dmaven.test.skip=true`
version:
`<version>3.3.0-SNAPSHOT</version>`
3.  change pom in tidb-cdc  and build
https://github.com/ververica/flink-cdc-connectors/blob/master/flink-connector-tidb-cdc/pom.xml

**Comment by xieyi888** [comment] 2022-05-18 07:12
> please

ok , I will upload the fix tidb-cdc jar here ,wait a minute please

**Comment by xieyi888** [comment] 2022-05-18 07:13
> @xieyi888 Do you have a packaged flink-cdc code package, please share

ok , I will upload the fix tidb-cdc jar here ,wait a minute please

**Comment by zengqinchris** [comment] 2022-05-18 07:25
感谢大佬分享，谢谢了

**Comment by xieyi888** [comment] 2022-05-18 07:42
> @xieyi888 Do you have a packaged flink-cdc code package, please share



> @xieyi888 Do you have a packaged flink-cdc code package, please share

hi, jar 和依赖版本见 : https://github.com/xieyi888/flink-tidb-cdc-SNAPSHOT-jar/tree/master
如果有问题，可以再联系我哈～

**Comment by zengqinchris** [comment] 2022-05-18 08:09
> > @xieyi888 Do you have a packaged flink-cdc code package, please share
> 
> > @xieyi888 Do you have a packaged flink-cdc code package, please share
> 
> hi, jar 和依赖版本见 : https://github.com/xieyi888/flink-tidb-cdc-SNAPSHOT-jar/tree/master 如果有问题，可以再联系我哈～

感谢大佬，膜拜

**Comment by PatrickRen** [comment] 2024-02-28 15:40
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:40 UTC
Labels: bug
