### ISSUE TITLE
oracle using redo_log_catalog default Slow query

### ISSUE THREAD

**Issue by yuangjiang** [ververica/flink-cdc-connectors#558] opened 2021-11-04 01:15 UTC
- Flink version :  1.13.0
 - Flink CDC version: 2.0
 - Database and version:  oracle 11g

When testing oralce cdc, I found that it is very slow when using the default **redo_log_catalog** query, but by changing the log.mining.strategy option to **online_catalog**, it is significantly faster. 
The redo_log_catalog query time is about **1 minute and 10 seconds**, and the online_catalog query time is 5s. It is about 10s, but snapshot.fetch.size needs to be configured to reduce database pressure. The value tested here is 1000. 
The oracle IO overhead is about 15%, and the data is 1 million. The consumption time is about 6 minutes

**Comment by leonardBang** [comment] 2021-11-04 01:36
@yuangjiang Thanks for your report, could you share your sql and data scale as well?

**Comment by yuangjiang** [comment] 2021-11-04 01:54
Sorry the company business table used in the data table cannot be made public @leonardBang

**Comment by leonardBang** [comment] 2021-11-04 01:58
@yuangjiang It's okay, could your share your table's  with parameters(except your private information) and the row count of your table?

**Comment by yuangjiang** [comment] 2021-11-04 08:03
This is 100,000 rows of data in my test table:
CREATE TABLE "PRODUCER"."ts_user_info" 
   (	"id" VARCHAR2(255), 
	"name" VARCHAR2(255), 
	"sex" VARCHAR2(255), 
	"city" VARCHAR2(255), 
	"occupation" VARCHAR2(255), 
	"tel" VARCHAR2(255), 
	"fixphonenum" VARCHAR2(255), 
	"bankname" VARCHAR2(255), 
	"address" VARCHAR2(255), 
	"marriage" VARCHAR2(255), 
	"childnum" VARCHAR2(255), 
        "fundaccount "  VARCHAR2(255)
	 CONSTRAINT "TS_USER_INFO_PK" PRIMARY KEY ("id")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";

CREATE UNIQUE INDEX "PRODUCER"."TS_USER_INFO_PK" ON "PRODUCER"."ts_user_info" ("id") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";

**Comment by slashchenxiaojun** [comment] 2022-01-12 08:17
@yuangjiang Dear my friend, according to your description there's not a bug.
according to dbz doc, your will see the paramter
![image](https://user-images.githubusercontent.com/10084320/149088651-985927c1-8534-4788-abff-635646fa71e9.png)
when log.mining.strategy = online_catalog that means the logminer will capture faster but at the expense that DDL changes cannot be tracked, and I tested as same as yours except table ddl. there's no google functions to resolving it, if you have any ideas, pleases tell me

**Comment by PatrickRen** [comment] 2024-02-28 15:11
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:11 UTC
Labels: bug
