### ISSUE TITLE
No TableMapEventData has been found for table id:816. Usually that means that you have started reading binary log 'within the logical event group' (e.g. from WRITE_ROWS and not proceeding TABLE_MAP

### ISSUE THREAD

**Issue by obobj** [ververica/flink-cdc-connectors#830] opened 2022-01-24 09:18 UTC
**Describe the bug**
```
2022-01-24 16:54:04.259  ERROR io.debezium.connector.mysql.MySqlStreamingChangeEventSource  - Error during binlog processing. Last offset stored = null, binlog reader near position = mysql-bin.011464/75452818
2022-01-24 16:54:04.259  ERROR io.debezium.pipeline.ErrorHandler  - Producer failure
io.debezium.DebeziumException: Failed to deserialize data of EventHeaderV4{timestamp=1643014443000, eventType=EXT_WRITE_ROWS, serverId=3746666141, headerLength=19, dataLength=967, nextPosition=75461633, flags=0}
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.wrap(MySqlStreamingChangeEventSource.java:1146)
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$ReaderThreadLifecycleListener.onEventDeserializationFailure(MySqlStreamingChangeEventSource.java:1193)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:958)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:606)
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:850)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1643014443000, eventType=EXT_WRITE_ROWS, serverId=3746666141, headerLength=19, dataLength=967, nextPosition=75461633, flags=0}
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:309)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:232)
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$1.nextEvent(MySqlStreamingChangeEventSource.java:233)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:945)
	... 3 common frames omitted
Caused by: com.github.shyiko.mysql.binlog.event.deserialization.MissingTableMapEventException: No TableMapEventData has been found for table id:277. Usually that means that you have started reading binary log 'within the logical event group' (e.g. from WRITE_ROWS and not proceeding TABLE_MAP
	at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeRow(AbstractRowsEventDataDeserializer.java:109)
	at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserializeRows(WriteRowsEventDataDeserializer.java:64)
	at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserialize(WriteRowsEventDataDeserializer.java:56)
	at com.github.shyiko.mysql.binlog.event.deserialization.WriteRowsEventDataDeserializer.deserialize(WriteRowsEventDataDeserializer.java:32)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:303)
	... 6 common frames omitted
2022-01-24 16:54:04.259  ERROR io.debezium.connector.mysql.MySqlStreamingChangeEventSource  - Error during binlog processing. Last offset stored = null, binlog reader near position = mysql-bin.011464/75452818
2022-01-24 16:54:04.259  ERROR io.debezium.pipeline.ErrorHandler  - Producer failure
io.debezium.DebeziumException: null
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.wrap(MySqlStreamingChangeEventSource.java:1146)
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$ReaderThreadLifecycleListener.onEventDeserializationFailure(MySqlStreamingChangeEventSource.java:1193)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:958)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:606)
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:850)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at com.github.shyiko.mysql.binlog.event.deserialization.TableMapEventMetadataDeserializer.deserialize(TableMapEventMetadataDeserializer.java:50)
	at com.github.shyiko.mysql.binlog.event.deserialization.TableMapEventDataDeserializer.deserialize(TableMapEventDataDeserializer.java:47)
	at com.github.shyiko.mysql.binlog.event.deserialization.TableMapEventDataDeserializer.deserialize(TableMapEventDataDeserializer.java:27)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:303)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeTableMapEventData(EventDeserializer.java:281)
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:228)
	at io.debezium.connector.mysql.MySqlStreamingChangeEventSource$1.nextEvent(MySqlStreamingChangeEventSource.java:233)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:945)
	... 3 common frames omitted
```
![image](https://user-images.githubusercontent.com/15715341/150754637-09a94e84-d0ee-4a73-9a9a-5b3a96683126.png)
Flink程序不停的重启但是数据仍然在读取，发现好像有修复过[#432](https://github.com/ververica/flink-cdc-connectors/issues/432)，但是不太清楚是不是同样的问题

**Environment :**
 - Flink version :  1.13.5
 - Flink CDC version:  2.2-SNAPSHOT
 - Database and version: Mysql 5.6

**Comment by hnjincan** [comment] 2022-03-22 02:55
![image](https://user-images.githubusercontent.com/39942725/159398626-d85977e3-a4c6-43c8-83df-3912a59c24cb.png)
flink-version 1.13.2 
flink-cdc 2.2-SNAPSHOT
mysql-version 5.7

**Comment by z070204z** [comment] 2022-03-30 09:35
2.2-release也遇到了同样的问题

**Comment by Goplatforms** [comment] 2023-02-09 08:36
flink-version 1.13.0
flink-cdc 2.0.0
mysql-version 8.0

**Comment by HideonBushz** [comment] 2023-11-19 18:00
这个问题有人解决了吗

**Comment by PatrickRen** [comment] 2024-02-28 15:10
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:10 UTC
Labels: bug
