### ISSUE TITLE
在tidb建立一张分区表，使用tidb connector 配置 source table 的时候，flink sql client查不出结果。

### ISSUE THREAD

**Issue by otjoy** [ververica/flink-cdc-connectors#1027] opened 2022-03-30 08:33 UTC
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  1.13
 - Flink CDC version: 2.2.0
 - Database and version:  tidb 5.3

**To Reproduce**
1. tidb ddl :
CREATE TABLE `transaction_order` (
  `id` VARCHAR(64) COLLATE utf8mb4_general_ci NOT NULL  ,
  `merchant_info_id` BIGINT(20) UNSIGNED NOT NULL  ,
  `merchant_id` VARCHAR(64) COLLATE utf8mb4_general_ci NOT NULL  ,
  `channel_merchant_id` VARCHAR(64) COLLATE utf8mb4_general_ci NOT NULL  ,
  `merchant_name` VARCHAR(255) COLLATE utf8mb4_general_ci DEFAULT NULL  ,
  `order_no` VARCHAR(128) COLLATE utf8mb4_general_ci NOT NULL  ,
  `trans_amount` DECIMAL(24,2) DEFAULT NULL  ,
  `charge_amount` DECIMAL(24,2) DEFAULT NULL  ,
  `trans_rate` DECIMAL(24,2) DEFAULT NULL  ,
  `channel_src` VARCHAR(20) COLLATE utf8mb4_general_ci NOT NULL  ,
  `trans_type` INT(4) DEFAULT NULL  ,
  `pay_type` INT(4) ,
  `pay_time` DATETIME(3) DEFAULT NULL,
  `order_status` INT(4) DEFAULT '1' ,
  `device_type` TINYINT(1) DEFAULT NULL ,
  `settle_type` TINYINT(1) DEFAULT NULL ,
  `cancel_status` TINYINT(1) UNSIGNED DEFAULT '0' ,
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ,
  PRIMARY KEY (`id`,`create_time`) /*T![clustered_index] NONCLUSTERED */,
  KEY `idx_pay_time` (`pay_time`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci /*T! SHARD_ROW_ID_BITS=4 PRE_SPLIT_REGIONS=3 */
PARTITION BY RANGE ( YEAR(`create_time`) ) (
  PARTITION `p2021` VALUES LESS THAN (2022),
  PARTITION `p2022` VALUES LESS THAN (2023),
  PARTITION `p2023` VALUES LESS THAN (2024)
)

2. flink ddl source :
CREATE TABLE `transaction_order_source` (
  `id` STRING  NOT NULL ,
  `merchant_info_id` BIGINT ,
  `merchant_id` STRING,
  `channel_merchant_id` STRING ,
  `merchant_name` STRING ,
  `order_no`STRING ,
  `trans_amount` DECIMAL(24,2) ,
  `charge_amount` DECIMAL(24,2) ,
  `trans_rate` DECIMAL(24,2) ,
  `channel_src` STRING ,
  `trans_type` INT,
  `pay_type` INT ,
  `pay_time` TIMESTAMP(3) ,
  `order_status` INT ,
  `device_type` TINYINT ,
  `settle_type` TINYINT ,
  `cancel_status` TINYINT ,
  `create_time` TIMESTAMP(3)  ,
  PRIMARY KEY (`id`) 
  NOT ENFORCED
) WITH (
     'connector' = 'tidb-cdc',
     'tikv.grpc.timeout_in_ms' = '20000', 
     'pd-addresses' = '192.168.1.xxx:2379',
     'database-name' = 'test',
     'table-name' = 'transaction_order'
);

5. The error 
select * from transaction_order_source; 

**Additional Description**
从flink sql client 执行select语句查看source table，但是查不出数据。对应的tidb数据库里的表是有数据的。

**Comment by GOODBOY008** [comment] 2022-04-01 03:41
@otjoy  Yes, Partion table do not work currently.

**Comment by luozb** [comment] 2022-11-23 06:30
> @otjoy Yes, Partion table do not work currently.

有计划什么时候支持吗？

**Comment by fuxishuyuan** [comment] 2023-07-06 12:14
> @otjoy Yes, Partion table do not work currently.

Any progress or plan on this fix?

**Comment by PatrickRen** [comment] 2024-02-28 15:30
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:30 UTC
Labels: bug
