### ISSUE TITLE
Question about flink-connector-tidb-cdc, please help me!

### ISSUE THREAD

**Issue by MengXiangDing** [ververica/flink-cdc-connectors#1525] opened 2022-08-30 12:33 UTC
Can each flink-cdc task only subscribe to one table? 
After reading the source code, I found that CDCClient can only pull the change log of one table.

Can each CDCClient only pull one table? 
Then if there are many tables, it will lead to many connections and cause TiKV to be overwhelmed?

**Comment by PatrickRen** [comment] 2024-02-28 15:04
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:04 UTC
