### ISSUE TITLE
flink-sql-connector-oracle-cdc-2.2.0 report  ORA-01292

### ISSUE THREAD

**Issue by xiemingjin** [ververica/flink-cdc-connectors#1036] opened 2022-04-01 02:36 UTC
**Describe the bug(Please use English)**
The following error occurs when restarting the Flink cluster

**Caused by: java.sql.SQLException: ORA-01292: no log file has been specified for the current LogMiner session**

**Environment :**
 - Flink version :  flink-1.13.6
 - Flink CDC version: 2.2.0
 - Database and version: oracle11g

**To Reproduce**
    1、Oracle archive logs are deleted every 4 hours
    2、Checkpoint every 10 minutes
    3、The database table has not been operated on for more than 8 hours 
    4、restarting the Flink cluster
    5、The error :
**Caused by: java.sql.SQLException: ORA-01292: no log file has been specified for the current LogMiner session**
**Additional Description**

**Comment by jtsunxp** [comment] 2022-04-05 15:04
The bug also occured when Oracle user is runing backup command with RMAN tool. Connector configed as following parameters:
    'debezium.log.mining.strategy' = 'online_catalog',
    'debezium.log.mining.continuous.mine' = 'true',

**Comment by PatrickRen** [comment] 2022-04-19 08:54
@luoyuxia Could you take a look on this issue? Thanks

**Comment by cocojiejie** [comment] 2022-07-26 07:46
i have the same questions，and the code running after  many days  occured this question，and the code has already add 'debezium.log.mining.strategy' = 'online_catalog',
'debezium.log.mining.continuous.mine' = 'true',

**Comment by cocojiejie** [comment] 2022-07-26 07:50
6147

t java. lang. Thread . run( Thread. java: 748) ~l ! :1.8.0_ _191]

6148 Caused by: java. sql. SQLException: ORA-01292: no log file has been specified for the current LogMiner session

6149

ORA-06512: at "SYS .DBMS_ _LOGMNR", line 5;

6150

ORA-06512: at line 1

6151

6152

at oracle. jdbc. driver . T4CTTIoer11. processError(T4CTTIoer11. java:509) ~[flink-sql-connector-oracle-cdc-2.2.1.jar:2.2.1]

6153

at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11. java:461) ~[flink-sql-connector-oracle-cdc-2.2.1.jar:2.2.1]

6154

at oracle . jdbc . driver . T4C80all. processError(T4C80all. java:1104) ~[flink-sql-connector-oracle-cdc-2.2.1.jar:2.2.1]

e Tct

6155

at oracle. jdbc. driver. T4CTTIfun. receive( T4CTTIfun. java:550) ~[ flink-sql -connector -oracle-cdc-2.2.1.jar:2.2.1]

6156

at oracle. jdbc . driver . T4CTTIfun. doRPC(T4CTTIfun.java:268) ~[flink-sql -connector-oracle-cdc-2.2.1. jar:2.2.1]

6157

at oracle. jdbc . driver. T4C80all. doOALL(T4C80all. java:655) ~[flink-sql -connector-oracle-cdc-2.2.1.jar:2.2.1]

6158

at oracle.jdbc.driver .T4CCallableStatement . do0all8(T4CCallableStatement .java:265) ~[flink-sql-connector-oracle-cdc-2.2.1.jar:2.2.1]

6159

at oracle. jdbc. driver. T4CCallableStatement . do0all8(T4CCallableStatement . java:86) ~[ flink-sql-connector-oracle-cdc-2.2.1.jar:2.2.1]

6160

at oracle. jdbc. driver . T4CCallableStatement . executeForRows (T4CCallableStatement. java:965) ~[flink-sql -connector-oracle-cdc-2.2.1. jar:2.2.1]

6161

at oracle. jdbc . driver . OracleStatement . doExecuteWithTimeout (OracleStatement. java : 1205) ~[ flink-sql-connector-oracle-cdc-2.2.1.jar:2.2.1]

6162

at oracle.jdbc.driver.0raclePreparedStatement. executeInternal(0raclePreparedStatement.java:3666) ~[flink-sql-connector-oracle-cdc-2.2.1.jar:2.2.1]

6163

at oracle. jdbc . driver . T4CCallableStatement . executeInternal(T4CCallableStatement . java:1358) ~[flink-sql-connector-oracle-cdlc-2.2.1.jar:2.2.1]

6164

at oracle. jdbc.driver . OraclePreparedStatement . execute (OraclePreparedStatement. java :3778) ~[flink-sql-connector-oracle-cdc-2.2.1.jar:2.2.1]

6165

at oracle. jdbc. driver . OracleCallableStatement . execute(OracleCallableStatement . java :4251) ~[ flink-sql- connector-oracle-cdc-2.2.1. jar:2.2.1]

6166

at oracle.jdbc.driver.0raclePr

ementWrapper . execute(OraclePreparedStatementWrapper . java:1081) ~[flink-sql-connector-oracle-cdc-2.2.1.jar:2.2.1]

6167

at io. debezium. connector . oracle. logminer . LogMinerHe lper . executeCallableStatement(LogMinerHelper . java:693) ~[flink-sql - connector-oracle-cdc-2.2.1. jar:2.2.1]

6168

at io.debezium. connector . oracle. logminer. LogMinerHe lper. startLogMining( LogMi nerHelper. java:236) ~[flink-sql-connector-oracle-cdc-2.2.1.jar:2.2.1]

6169

at io. debezium. connector . oracle . logminer. LogMinerStreamingChangeEventSource. execute(LogMinerStreamingChangeEventSource. java:177) ~[flink-sql-connector-oracle-cdc-2.2.1. jar:2.2.1]

6170

more

6171 Caused by: oracle . jdbc .OracleDatabaseException: ORA-01292: no log file has been specified for the current LogMiner session

6172 ORA-06512: at "SYS .DBMS_ LOGMNR", line 5

6173 ORA-06512: at line 1

**Comment by wdzhanghao** [comment] 2022-08-10 01:29
i have the same questions，and the code running after many days occured this question，and the code has already add 'debezium.log.mining.strategy' = 'online_catalog',
'debezium.log.mining.continuous.mine' = 'true',
but my flink version is 1.13.1 and cdc version is 2.1.1

**Comment by 1105748319** [comment] 2022-08-10 05:54
i have the same questions，and the code running after many days occured this question，and the code has already add 'debezium.log.mining.strategy' = 'online_catalog',
'debezium.log.mining.continuous.mine' = 'true',
but my flink version is 1.13.0 and cdc version is 2.1.0

**Comment by wl3207601** [comment] 2022-08-23 08:24
i have the same questions，and the code running after many days occured this question，and the code has already add 'debezium.log.mining.strategy' = 'online_catalog',
'debezium.log.mining.continuous.mine' = 'true',
but my flink version is 1.13.6 and cdc version is 2.2.1

**Comment by wl3207601** [comment] 2022-08-23 15:13
@leonardBang  Could you take a look on this issue? Thanks

**Comment by MadaoRyan** [comment] 2022-09-26 02:18
i have the same questions，and the code running after many days occured this question，and the code has already add 'debezium.log.mining.strategy' = 'online_catalog',
'debezium.log.mining.continuous.mine' = 'true',
but my flink version is 1.14.5 and cdc version is 2.2.1

**Comment by yuandajn578** [comment] 2023-07-16 03:38
I have the same questions，and the code running after some days occured this question，and the code has already add 'debezium.log.mining.strategy' = 'online_catalog',
'debezium.log.mining.continuous.mine' = 'true',
but my flink version is 1.17.1 and cdc version is 2.4.0

**Comment by ighack** [comment] 2023-07-24 01:39
i have the same questions
 'debezium.log.mining.strategy' = 'online_catalog',
'debezium.log.mining.continuous.mine' = 'true',

Oracle archive logs are deleted every 12 hours

**Comment by wsczm** [comment] 2023-08-17 06:27
@wuchong I hope you can give us some suggestions to solve this problem

**Comment by xiongxsong** [comment] 2023-08-18 08:17
i meet same error

**Comment by huanzui** [comment] 2023-08-30 02:59
i meet same error flink version is 1.17.1 and oracle-cdc version is 2.2.1

**Comment by spaceice123** [comment] 2023-11-21 01:51
i meet same error after the task running a little while

**Comment by PatrickRen** [comment] 2024-02-28 15:37
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:37 UTC
Labels: bug
