### ISSUE TITLE
After mysql use the truncate statement, one data will be lost

### ISSUE THREAD

**Issue by lykpass** [ververica/flink-cdc-connectors#467] opened 2021-09-27 07:01 UTC
**Describe the bug**
After mysql use the truncate statement ,I insert an original data,then delete this data,the result table will lose this data
**Environment :**
 - Flink version :  1.13.1
 - Flink CDC version: 1.14.0
 - Database and version: 8.0.26

**To Reproduce**

------------------------mysql

create table a (
	id int,
	name varchar(5),
	primary key(id)
)

insert into a (id,name) values(1,'lyk')

insert into a (id,name) values(2,'lyk2')

insert into a (id,name) values(3,'lyk3')

insert into a (id,name) values(4,'lyk4')

create table b (
	id int,
	name varchar(5),
	age int,
	score int,
	primary key(id)	
)

insert into b (id,name,age,score) values(1,'lyk',1,1)

insert into b (id,name,age,score) values(2,'lyk',2,2)

insert into b (id,name,age,score) values(3,'lyk',3,3)

insert into b (id,name,age,score) values(4,'lyk',4,4)

create table c (
	id int,
	name varchar(5),
	age int,
	primary key(id)	
)

-------------idea 

        tableEnv.executeSql("CREATE TABLE a (\n" +
                "  `id` int,\n" +
                "  `name` varchar,\n" +
                "  PRIMARY KEY (id) NOT ENFORCED\n" +
                ") WITH (\n" +
                "  'connector' = 'mysql-cdc',\n" +
                "  'hostname' = 'localhost',\n" +
                "  'port' = '3306',\n" +
                "  'username' = 'root',\n" +
                "  'password' = '139976',\n" +
                "  'database-name' = 'lyk',\n" +
                "  'debezium.snapshot.locking.mode' = 'none',\n" +
                "  'debezium.snapshot.mode' = 'when_needed',\n" +
                "  'table-name' = 'a'\n" +
                "  )  \n");

        tableEnv.executeSql("CREATE TABLE b (\n" +
                "  `id` int,\n" +
                "  `name` varchar,\n" +
                "  `age` int,\n" +
                "  `score` int,\n" +
                "  PRIMARY KEY (id) NOT ENFORCED\n" +
                ") WITH (\n" +
                "  'connector' = 'mysql-cdc',\n" +
                "  'hostname' = 'localhost',\n" +
                "  'port' = '3306',\n" +
                "  'username' = 'root',\n" +
                "  'password' = '139976',\n" +
                "  'database-name' = 'lyk',\n" +
                "  'debezium.snapshot.locking.mode' = 'none',\n" +
                "  'debezium.snapshot.mode' = 'when_needed',\n" +
                "  'table-name' = 'b'\n" +
                "  )  \n");

        tableEnv.executeSql("CREATE TABLE c (\n" +
                "  `id` int,\n" +
                "  `name` varchar,\n" +
                "  `age` int,\n" +
                "  PRIMARY KEY (id) NOT ENFORCED\n" +
                "  )WITH (\n" +
                "    'connector' = 'jdbc',\n" +
                "    'url' = 'jdbc:mysql://localhost"+"/lyk?serverTimezone=Asia/Shanghai',\n" +
                "    'table-name' = 'c',\n" +
                "    'driver' = 'com.mysql.cj.jdbc.Driver',\n" +
                "    'sink.parallelism' = '1',\n" +
                "    'username' = 'root',\n" +
                "    'password' = '139976'\n" +
                "  )");

        tableEnv.executeSql("insert into c select a.id,a.name,b.age from a left join b on a.id = b.id");

----------------------------mysql

truncate table b

insert into b (id,name,age,score) values(1,'lyk',1,1)

delete from b where id = 1

the result should be 

![image](https://user-images.githubusercontent.com/48595535/134859715-d6ebe429-1a40-48f4-a882-aeadab5250aa.png)

but  the result is
![image](https://user-images.githubusercontent.com/48595535/134859524-a4c62852-1608-4131-b8d5-40648a737265.png)

**Comment by reven404** [comment] 2021-09-27 19:08
https://dev.mysql.com/doc/refman/5.7/en/replication-features-truncate.html
> TRUNCATE TABLE is treated for purposes of logging and replication as DDL rather than DML so that it can be logged and replicated as a statement. However, the effects of the statement as applicable to InnoDB and other transactional tables on replicas still follow the rules described in Section 13.1.34, “TRUNCATE TABLE Statement” governing such tables. (Bug #36763)

**Comment by PatrickRen** [comment] 2024-02-28 15:12
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:12 UTC
Labels: bug
