### ISSUE TITLE
Easy to contribute

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#340] opened 2021-08-20 07:59 UTC
## Good For Newcomers 
* [x] #356 
* [x] #345 
* [x] #346
* [x] #370 
* [x] #381 
* [x] #343
* [x] #249
* [x] #162 
* [x] #342
* [x] #322  
* [x] #301  

## Contribution guidance
- (1) Left comment under the issue that you want to take
* (2) Clone and compile your Flink CDC project
```
git clone https://github.com/your_name/flink-cdc-connectors.git
cd flink-cdc-connectors
mvn clean install -DskipTests
```
* (3) Check to a new branch and start your work
```
git checkout -b my_feature
-- develop and commit
```
* (4) Push your branch to your github 
```
git push origin my_feature
```
* (5) Open a PR to https://github.com/ververica/flink-cdc-connectors
![image](https://user-images.githubusercontent.com/5163645/131132668-d958c766-43cf-471b-8caf-bab136384717.png)

**Comment by PatrickRen** [comment] 2024-02-28 15:40
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:40 UTC
Labels: good first issue, category
