### ISSUE TITLE
cdc for mongo support startupOptions.specificOffset(_id)

### ISSUE THREAD

**Issue by lanse-li** [ververica/flink-cdc-connectors#1584] opened 2022-09-27 07:00 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by lanse-li** [comment] 2022-09-27 07:07
如果是多库多表， 希望能够支持map参数，设置多表的数据回溯功能

**Comment by PatrickRen** [comment] 2024-02-28 15:28
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:28 UTC
Labels: enhancement
