### ISSUE TITLE
use StartupOptions.earliest() model get binlog error

### ISSUE THREAD

**Issue by hzh2955** [ververica/flink-cdc-connectors#289] opened 2021-08-05 07:50 UTC
hi,
when use mysql cdc get binlog info，set  StartupOptions.earliest() model。
get this error ： Encountered change event for table a.b whose schema isn't known to this connector。

reason is debuzuim snapshot model: 
never - the connector never uses snapshots. Upon first startup with a logical server name, the connector reads from the beginning of the binlog. Configure this behavior with care. It is valid only when the binlog is guaranteed to contain the entire history of the database.

as binlog not contain the entire history of the database.  

how to use StartupOptions.earliest() in this case?

**Comment by PatrickRen** [comment] 2024-02-28 15:32
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:32 UTC
Labels: bug
