### ISSUE TITLE
changelog-json序列化数字时，将10.000000序列化为科学计数法 1E+1 了

### ISSUE THREAD

**Issue by liaooo** [ververica/flink-cdc-connectors#527] opened 2021-10-27 07:04 UTC
changelog-json内部也是依赖flink-json组件，可否把flink-json的json.encode.decimal-as-plain-number属性在changelog-json也支持？

**Comment by PatrickRen** [comment] 2024-02-28 15:11
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:11 UTC
