### ISSUE TITLE
Question: Does Flink-CDC support Oracle Real Application Clusters (RAC) ?

### ISSUE THREAD

**Issue by sty945** [ververica/flink-cdc-connectors#664] opened 2021-11-29 03:19 UTC
Dear developer，

- I want to ask a question: Does Flink-CDC support Oracle Real Application Clusters (RAC) ?
    - If support. How to use it?
    - If not support. When is the plan available?

**Comment by szs903** [comment] 2021-12-07 09:50
我目前测试是不支持的 ， 要么报不知道SID ， 要么报不知道service name , 你也是吗

**Comment by sty945** [comment] 2021-12-22 16:04
> 我目前测试是不支持的 ， 要么报不知道SID ， 要么报不知道service name , 你也是吗

是的，我当前测试就是报不知道SID，不怎么应该怎么解决的，你解决了么？

**Comment by PatrickRen** [comment] 2024-02-28 15:37
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:37 UTC
Labels: enhancement
