### ISSUE TITLE
FlinkCDC 在 insert 部分 支持 where 条件过滤

### ISSUE THREAD

**Issue by sakinsun** [ververica/flink-cdc-connectors#1665] opened 2022-10-28 01:32 UTC
CDCmysql 表：A（startup_mode:initial)
目标表：B

insert into B
select *
from A 
where id >10000

运行之后，我看日志，FLINK依然会把 表A 全表进行 切分操作，而不是 按照 id>10000 做快照进行同步，请问有什么方法可以不要A表全量快照切分吗？很慢的。

**Comment by ruanhang1993** [comment] 2022-10-31 03:54
I think we need a filtering logic for the chunk key column in the snapshot phase.

**Comment by Oloong** [comment] 2022-12-16 10:54
CDC 中 WHERE 条件不能下推，什么时候能解决呢，感觉很二！

**Comment by PatrickRen** [comment] 2024-02-28 15:02
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:02 UTC
Labels: enhancement
