### ISSUE TITLE
postgres cdc ,restore from checkpoint failed

### ISSUE THREAD

**Issue by heiren93** [ververica/flink-cdc-connectors#1105] opened 2022-04-21 09:24 UTC
my checkpoint settings are as below :

     configuration.setString("execution.checkpointing.interval", "10 s");
    configuration.setString("execution.checkpointing.externalized-checkpoint-retention","RETAIN_ON_CANCELLATION");
    configuration.setString("execution.checkpointing.mode","EXACTLY_ONCE");  

the checkpoint are created in  path "hdfs://HermesServices/flink-checkpoints/f9bf57fe21994d663851d3b07cf4dd34/chk-20"

when I canceled  the flink cdc job and restart from  the  checkpoint .my setting is :

 configuration.setString("execution.savepoint.path","hdfs://HermesServices/flink-checkpoints/f9bf57fe21994d663851d3b07cf4dd34/chk-20");

it do not work.

![image](https://user-images.githubusercontent.com/23006307/164423988-7c078a3c-2e7a-479a-ab1e-f9b063296ad7.png)

**Comment by heiren93** [comment] 2022-05-11 03:29
I solved the problem. my job mode is  yarn application.The  checkpoints configuration  is  supposed to set before "yarnClusterDescriptor
        .deployApplicationCluster"  and should not setting in pipeline.jars.
 configuration.setString("execution.savepoint.path","hdfs://HermesServices/flink-checkpoints/f9bf57fe21994d663851d3b07cf4dd34/chk-20");

**Comment by PatrickRen** [comment] 2024-02-28 15:08
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:08 UTC
