### ISSUE TITLE
Retrieve schema history failed

### ISSUE THREAD

**Issue by hehetown** [ververica/flink-cdc-connectors#1182] opened 2022-05-13 07:16 UTC
**Describe the bug(Please use English)** 
           Retrieve schema history failed, the schema records for engine e573d667-c5e4-4df8-b55a-1686860bd2f0 has been removed, this might because the debezium engine has been shutdown due to other errors.
**Environment :**
 - Flink version :  1.13.5
 - Flink CDC version:  2.2.1
 - Database and version:  Oracle 19.7

**To Reproduce**
1. Thes test data :
2. The test code :
DROP TABLE IF EXISTS sourceorders;
CREATE TABLE source_orders (
    ORDERID INT,
    BM STRING,
    PRIMARY KEY (ORDERID) NOT ENFORCED
  ) WITH (
    'connector' = 'oracle-cdc',
    'hostname' = '10.10.10.17',
    'port' = '1521',
    'username' = 'flinkuser',
    'password' = 'flinknowd',
    'database-name' = 'orclpdb',
    'schema-name' = 'flinkuser',
    'table-name' = 'orders',
    'debezium.database.hostname' = '10.10.10.17',
    'debezium.database.port' = '1521',
    'debezium.database.server.name' = 'server1',  
    'debezium.database.dbname' = 'orclbdc',
    'debezium.database.pdb.name' = 'orclpdb',
    'debezium.database.user' = 'C##LOGMINER',
    'debezium.database.password' = 'dbz',
    'debezium.database.connection.adapter' = 'logminer', 
    'debezium.rac.nodes' = '10.10.18.11,10.10.10.19',
    'debezium.log.mining.strategy' = 'online_catalog'
  );
4. The error :
Caused by: java.lang.IllegalStateException: Retrieve schema history failed, the schema records for engine e573d667-c5e4-4df8-b55a-1686860bd2f0 has been removed, this might because the debezium engine has been shutdown due to other errors.
	at com.ververica.cdc.debezium.utils.DatabaseHistoryUtil.retrieveHistory(DatabaseHistoryUtil.java:77)
	at com.ververica.cdc.debezium.internal.FlinkDatabaseSchemaHistory.configure(FlinkDatabaseSchemaHistory.java:82)
	at io.debezium.relational.HistorizedRelationalDatabaseConnectorConfig.getDatabaseHistory(HistorizedRelationalDatabaseConnectorConfig.java:105)
	at io.debezium.relational.HistorizedRelationalDatabaseSchema.<init>(HistorizedRelationalDatabaseSchema.java:39)
	at io.debezium.connector.oracle.OracleDatabaseSchema.<init>(OracleDatabaseSchema.java:35)
	at io.debezium.connector.oracle.OracleConnectorTask.start(OracleConnectorTask.java:54)
	at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:130)
	at io.debezium.connector.common.BaseSourceTask.startIfNeededAndPossible(BaseSourceTask.java:207)
	at io.debezium.connector.common.BaseSourceTask.poll(BaseSourceTask.java:148)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:788)
	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:188)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
**Additional Description**

**Comment by lexiaoer** [comment] 2023-04-13 10:09
我也出现这个错误，现在解决了吗？

**Comment by gong** [comment] 2024-02-03 06:04
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
cc @GOODBOY008

**Closed** 2024-02-03 09:56 UTC
Labels: bug
