### ISSUE TITLE
[mysql] support read snapshot only 

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#1687] opened 2022-11-01 12:29 UTC
we can support read snapshot only mode to unlock more user cases.

**Comment by PatrickRen** [comment] 2022-11-01 12:53
Also we need to log the current offset once the binlog split reader reaches highest watermarks among snapshot splits (pure binlog reading mode)

**Comment by SML0127** [comment] 2023-08-10 11:34
I also need this feature..

**Comment by waitingF** [comment] 2023-08-28 10:49
hihihi, any news?

**Comment by leonardBang** [comment] 2023-08-28 12:23
@PatrickRen Could you kindly look at this request ?

**Comment by punish-yh** [comment] 2023-11-07 07:20
I am very looking forward to this new feature

**Comment by PatrickRen** [comment] 2024-02-28 15:02
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:02 UTC
Labels: enhancement
