### ISSUE TITLE
[SUPPORT]  insert into select statement is abnormal

### ISSUE THREAD

**Issue by Tandoy** [ververica/flink-cdc-connectors#219] opened 2021-06-22 04:38 UTC
**Steps to reproduce the behavior:**
Use cdc as the data source to associate, and then insert the mysql result table

**Environment Description:**
Flink version : 1.12.2
cdc-connector version : flink-sql-connector-mysql-cdc-1.2.0
jdbc-connector version : flink-connector-jdbc_2.11-1.12.2
Storage (HDFS/S3/GCS..) : HDFS
Running on Docker? (yes/no) :no

**code:**
`CREATE TABLE activity_records (
  record_id STRING NOT NULL
  ,created_at STRING
  ,updated_at STRING
  ,activity_id STRING
  ,activity_name STRING 
  ,cust_id STRING
  ,reward_id STRING
  ,activity_type_id STRING
  ,activity_type_name STRING
  ,current_progress STRING
  ,status STRING
  ,attribute STRING
  ,repeat_time STRING
  ,repeat_begin_time STRING
  ,repeat_end_time STRING
  ,meet_date STRING
  ,meet_date_str STRING
  ,done_date STRING
  ,give_date STRING
  ,meet_timeout_date STRING
  ,last_give_date STRING
  ,real_give_date STRING
  ,web_show STRING
  ,txn_seq STRING
  ,activity_timeout_date STRING
  ,active_receive STRING
  ,is_delete STRING
) WITH (
 'connector' = 'mysql-cdc',
 'hostname' = 'xxxxxx',
 'port' = '3306',
 'username' = 'xxx',
 'password' = 'xxxxx',
 'database-name' = 'flinkcdc',
 'table-name' = 'activity_records',
 'debezium.snapshot.locking.mode' = 'none'
);

CREATE TABLE interactive_events (
  weixin_event_id  STRING NOT NULL
  ,created_at STRING 
  ,updated_at STRING 
  ,cust_id STRING 
  ,event_key STRING 
  ,content STRING  
  ,record_date STRING 
) WITH (
 'connector' = 'mysql-cdc',
 'hostname' = 'xxxxxx',
 'port' = '3306',
 'username' = 'xxxx',
 'password' = 'xxxxx',
 'database-name' = 'flinkcdc',
 'table-name' = 'interactive_events',
 'debezium.snapshot.locking.mode' = 'none'
);

CREATE TABLE reslut (
  cust_id STRING NOT NULL
  ,setquery_cnt BIGINT 
  ,cipher_cnt BIGINT 
  ,openapp_day BIGINT 
  ,openapp_cnt BIGINT 
  ,thumbsup_day BIGINT 
  ,thumbsup_cnt BIGINT 
  ,save_cnt BIGINT 
  ,save_day BIGINT 
  ,setup_cnt BIGINT 
  ,novicedone_cnt BIGINT 
  ,dailydone_cnt BIGINT 
  ,flashdone_cnt BIGINT 
  ,passivedone_cnt BIGINT 
  ,elsedone_cnt BIGINT 
  ,done_cnt BIGINT 
  ,app_cnt BIGINT 
  ,PRIMARY KEY (cust_id) NOT ENFORCED
) WITH (
  'connector' = 'jdbc',
  'url' = 'jdbc:mysql://xxxxxxx:3306/flinkcdc?useSSL=false&autoReconnect=true',
  'driver' = 'com.mysql.cj.jdbc.Driver',
  'table-name' = 'reslut',
  'username' = 'xxx',
  'password' = 'xxx',
  'lookup.cache.max-rows' = '3000',
  'lookup.cache.ttl' = '10s',
  'lookup.max-retries' = '3'
);

INSERT INTO reslut
select 
t1.cust_id
,sum(case when t1.event_key = '6' then 1 else 0 end) as setquery_cnt
,sum(case when t1.event_key = '7' then 1 else 0 end) as cipher_cnt
,count(DISTINCT case when t1.event_key = '2' then t1.record_date else null end) as openapp_day
,sum(case when t1.event_key = '2' then 1 else 0 end) as openapp_cnt
,count(DISTINCT case when t1.event_key = '3' then t1.record_date else null end) as thumbsup_day
,sum(case when t1.event_key = '3' then 1 else 0 end) as thumbsup_cnt
,sum(case when t1.event_key = '4' then 1 else 0 end) as save_cnt
,count(DISTINCT case when t1.event_key = '4' then t1.record_date else null end) as save_day
,sum(case when t1.event_key = '5' then 1 else 0 end) as setup_cnt
,COALESCE(max(t2.novicedone_cnt),0) as novicedone_cnt
,COALESCE(max(t2.dailydone_cnt),0) as dailydone_cnt
,COALESCE(max(t2.flashdone_cnt),0) as flashdone_cnt
,COALESCE(max(t2.passivedone_cnt),0) as passivedone_cnt
,COALESCE(max(t2.elsedone_cnt),0) as elsedone_cnt
,COALESCE(max(t2.done_cnt),0) as done_cnt
,sum(case when t1.event_key = '0' then 1 else 0 end) as app_cnt
from interactive_events t1
left join (
SELECT
tmp.cust_id
,sum(case when tmp.attribute='0' and (tmp.status=3 or tmp.status=2) then 1 else 0 end) as novicedone_cnt
,sum(case when tmp.attribute='1' and (tmp.status=3 or tmp.status=2) then 1 else 0 end) as dailydone_cnt
,sum(case when tmp.attribute='2' and (tmp.status=3 or tmp.status=2) then 1 else 0 end) as flashdone_cnt
,sum(case when tmp.attribute='3' and (tmp.status=3 or tmp.status=2) then 1 else 0 end) as passivedone_cnt
,sum(case when tmp.attribute='4' and (tmp.status=3 or tmp.status=2) then 1 else 0 end) as elsedone_cnt
,sum(case when tmp.status in ('1','2') then 1 else 0 end) as done_cnt
from activity_records tmp
group by tmp.cust_id
) t2
on t2.cust_id = t1.cust_id
group by t1.cust_id;`

**Stacktrace:**
[ERROR] Could not execute SQL statement. Reason:
org.apache.flink.table.planner.codegen.CodeGenException: Unable to find common type of GeneratedExpression(field$206,isNull$205,,STRING,None) and ArrayBuffer(GeneratedExpression(((int) 0),false,,INT NOT NULL,Some(0))).

**Additional context:**
But I used the following code without error,When the table is created, event_key and status are of type STRING.

INSERT INTO reslut
select 
t1.cust_id
,sum(case when t1.event_key = 6 then 1 else 0 end) as setquery_cnt
,sum(case when t1.event_key = 7 then 1 else 0 end) as cipher_cnt
,count(DISTINCT case when t1.event_key = 2 then t1.record_date else null end) as openapp_day
,sum(case when t1.event_key = 2 then 1 else 0 end) as openapp_cnt
,count(DISTINCT case when t1.event_key = 3 then t1.record_date else null end) as thumbsup_day
,sum(case when t1.event_key = 3 then 1 else 0 end) as thumbsup_cnt
,sum(case when t1.event_key = 4 then 1 else 0 end) as save_cnt
,count(DISTINCT case when t1.event_key = 4 then t1.record_date else null end) as save_day
,sum(case when t1.event_key = 5 then 1 else 0 end) as setup_cnt
,COALESCE(max(t2.novicedone_cnt),0) as novicedone_cnt
,COALESCE(max(t2.dailydone_cnt),0) as dailydone_cnt
,COALESCE(max(t2.flashdone_cnt),0) as flashdone_cnt
,COALESCE(max(t2.passivedone_cnt),0) as passivedone_cnt
,COALESCE(max(t2.elsedone_cnt),0) as elsedone_cnt
,COALESCE(max(t2.done_cnt),0) as done_cnt
,sum(case when t1.event_key = 0 then 1 else 0 end) as app_cnt
from interactive_events t1
left join (
SELECT
tmp.cust_id
,sum(case when tmp.attribute='0' and (tmp.status='3' or tmp.status='2') then 1 else 0 end) as novicedone_cnt
,sum(case when tmp.attribute='1' and (tmp.status='3' or tmp.status='2') then 1 else 0 end) as dailydone_cnt
,sum(case when tmp.attribute='2' and (tmp.status='3' or tmp.status='2') then 1 else 0 end) as flashdone_cnt
,sum(case when tmp.attribute='3' and (tmp.status='3' or tmp.status='2') then 1 else 0 end) as passivedone_cnt
,sum(case when tmp.attribute='4' and (tmp.status='3' or tmp.status='2') then 1 else 0 end) as elsedone_cnt
,sum(case when tmp.status in ('1','2') then 1 else 0 end) as done_cnt
from activity_records tmp
group by tmp.cust_id
) t2
on t2.cust_id = t1.cust_id
group by t1.cust_id;

**Comment by PatrickRen** [comment] 2024-02-28 15:13
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:13 UTC
Labels: enhancement
