### ISSUE TITLE
flink sql使用flink cdc的原理

### ISSUE THREAD

**Issue by ghost** [ververica/flink-cdc-connectors#255] opened 2021-07-15 13:29 UTC
CREATE TABLE products (
  id INT,
  name STRING,
  description STRING
) WITH (
  'connector' = 'mysql-cdc',
  'hostname' = 'localhost',
  'port' = '3306',
  'username' = 'root',
  'password' = '123456',
  'database-name' = 'mydb',
  'table-name' = 'products'
);

CREATE TABLE orders (
  order_id INT,
  order_date TIMESTAMP(0),
  customer_name STRING,
  price DECIMAL(10, 5),
  product_id INT,
  order_status BOOLEAN
) WITH (
  'connector' = 'mysql-cdc',
  'hostname' = 'localhost',
  'port' = '3306',
  'username' = 'root',
  'password' = '123456',
  'database-name' = 'mydb',
  'table-name' = 'orders'
);

CREATE TABLE shipments (
  shipment_id INT,
  order_id INT,
  origin STRING,
  destination STRING,
  is_arrived BOOLEAN
) WITH (
  'connector' = 'postgres-cdc',
  'hostname' = 'localhost',
  'port' = '5432',
  'username' = 'postgres',
  'password' = 'postgres',
  'database-name' = 'postgres',
  'schema-name' = 'public',
  'table-name' = 'shipments'
);

使用flink SQL的cdc方式读取多张表，是每张表都会产生一个流吗，流表join的时候是怎样一个过程。上面使用cdc source方式建了3张表，order、products、shipments，order和product表进行join，由于数据是一直过来的，然后处理了流向下游，如10分的时候，product表中的一条数据可以关联上order表中的一条数据，之后到20分的时候，product表中的这条数据又可以关联到order表中的新产生的一条数据，flink是怎么处理的呢。
由于flink是不存储数据的，是把order和product表中到来的数据一直缓存在状态里吗，那随着程序一直运行，状态不是会越来越大，最后处理不了了吗。如果是3张flink的流表关联，情况不是更复杂吗，底层是怎么一回事呢

**Comment by leonardBang** [comment] 2021-07-15 14:09
@LiangXiam https://github.com/ververica/flink-cdc-connectors/issues/239 中回复你了

**Comment by PatrickRen** [comment] 2024-02-28 15:33
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:33 UTC
