### ISSUE TITLE
there are T and  Z in the value of column of timestamp type

### ISSUE THREAD

**Issue by foobarrer** [ververica/flink-cdc-connectors#1250] opened 2022-06-06 14:11 UTC
![image](https://user-images.githubusercontent.com/46312795/172177383-99c3d541-c219-4d3d-a41b-b364bc9cfac0.png)
can not use the value like ##2022-06-06T10:30:00Z## to insert in to another column of timestamp type.
So is there any way to avoid ? thanks ahead

**Comment by PatrickRen** [comment] 2024-02-28 15:07
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:07 UTC
