### ISSUE TITLE
Supports partial table rescan for full data

### ISSUE THREAD

**Issue by walk-in-cloud** [ververica/flink-cdc-connectors#1638] opened 2022-10-20 09:58 UTC
Currently, the scanning of newly added tables is supported, but in my daily use, I often need to perform a full scan of some tables again. Is there any way to achieve this requirement?

**Comment by GOODBOY008** [comment] 2022-10-20 11:32
@walk-in-cloud  Common method is start new batch jobs or excute sqls with snapshot-only model.

**Comment by walk-in-cloud** [comment] 2022-10-21 01:47
@GOODBOY008 thanks for your advice!
It is possible to use a batch task for processing, but I don't want to have to suspend the current running stream task in order to ensure data accuracy.
I tried to remove the information about the full table to be re-executed when recovering the task from the checkpoint, but the task would get stuck on several chunks.
what i did like this:
`@Override
    public SplitEnumerator<MySqlSplit, PendingSplitsState> restoreEnumerator(
            SplitEnumeratorContext<MySqlSplit> enumContext, PendingSplitsState checkpoint) {
        MySqlSourceConfig sourceConfig = configFactory.createConfig(0);

        final MySqlSplitAssigner splitAssigner;
        log.info("从ck中恢复，checkpoint class:{}", checkpoint.getClass());
        if (checkpoint instanceof HybridPendingSplitsState) {

            List<String> reScanTableList = sourceConfig.getReScanTableList();
            List<String> tableList = sourceConfig.getTableList();

            SnapshotPendingSplitsState snapshotPendingSplits =
                    ((HybridPendingSplitsState) checkpoint).getSnapshotPendingSplits();
            //删除 alreadyProcessedTables
            List<TableId> alreadyProcessedTables = snapshotPendingSplits.getAlreadyProcessedTables();
            if (CollectionUtils.isNotEmpty(alreadyProcessedTables)) {
                Iterator<TableId> it1 = alreadyProcessedTables.iterator();
                while (it1.hasNext()) {
                    TableId tableId = it1.next();
                    String table = tableId.toString();
                    if (reScanTableList.contains(table) || !tableList.contains(table)) {
                        it1.remove();
                    }
                }
            }
            //删除 remainingTables
            List<TableId> remainingTables = snapshotPendingSplits.getRemainingTables();
            log.info("remainingTables:{}", remainingTables);
            if (CollectionUtils.isNotEmpty(remainingTables)) {
                Iterator<TableId> it2 = remainingTables.iterator();
                while (it2.hasNext()) {
                    TableId tableId = it2.next();
                    String table = tableId.toString();
                    if (reScanTableList.contains(table) || !tableList.contains(table)) {
                        it2.remove();
                    }
                }
            }
            //删除 remainingSplits
            List<MySqlSnapshotSplit> remainingSplits = snapshotPendingSplits.getRemainingSplits();
            if (CollectionUtils.isNotEmpty(remainingSplits)) {
                Iterator<MySqlSnapshotSplit> it3 = remainingSplits.iterator();
                while (it3.hasNext()) {
                    MySqlSnapshotSplit snapshotSplit = it3.next();
                    String table = snapshotSplit.getTableId().toString();
                    if (reScanTableList.contains(table) || !tableList.contains(table)) {
                        it3.remove();
                    }
                }
            }
            //删除 assignedSplits
            Map<String, MySqlSnapshotSplit> assignedSplits = snapshotPendingSplits.getAssignedSplits();
            if (assignedSplits != null) {
                List<String> keysToBeRemove = new ArrayList<>();
                for (Map.Entry<String, MySqlSnapshotSplit> entry : assignedSplits.entrySet()) {
                    MySqlSnapshotSplit value = entry.getValue();
                    String table = value.getTableId().toString();
                    if (reScanTableList.contains(table) || !tableList.contains(table)) {
                        keysToBeRemove.add(entry.getKey());
                    }
                }
                for (String table : keysToBeRemove) {
                    assignedSplits.remove(table);
                }
            }
            //删除 splitFinishedOffsets
            Map<String, BinlogOffset> splitFinishedOffsets = snapshotPendingSplits.getSplitFinishedOffsets();
            if (splitFinishedOffsets != null) {
                List<String> keysToBeRemove = new ArrayList<>();
                for (Map.Entry<String, BinlogOffset> entry : splitFinishedOffsets.entrySet()) {
                    String key = entry.getKey();
                    String[] split = StringUtils.split(key, ":");
                    if (reScanTableList.contains(split[0]) || !tableList.contains(split[0])) {
                        keysToBeRemove.add(key);
                    }
                }
                for (String table : keysToBeRemove) {
                    splitFinishedOffsets.remove(table);
                }
            }
            splitAssigner =
                    new MySqlHybridSplitAssigner(
                            sourceConfig,
                            enumContext.currentParallelism(),
                            (HybridPendingSplitsState) checkpoint);
        } else if (checkpoint instanceof BinlogPendingSplitsState) {
            splitAssigner =
                    new MySqlBinlogSplitAssigner(
                            sourceConfig, (BinlogPendingSplitsState) checkpoint);
        } else {
            throw new UnsupportedOperationException(
                    "Unsupported restored PendingSplitsState: " + checkpoint);
        }
        return new MySqlSourceEnumerator(enumContext, sourceConfig, splitAssigner);
    }
`

**Comment by PatrickRen** [comment] 2024-02-28 15:03
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:03 UTC
Labels: enhancement
