### ISSUE TITLE
idea package failed

### ISSUE THREAD

**Issue by wcc1433** [ververica/flink-cdc-connectors#1238] opened 2022-05-31 04:18 UTC
**Describe the bug(Please use English)**
When i use flink cdc stream api for cdc mysql data, is successed in local. but when build package,  is error and message "程序包com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.data不存在". 
The package "com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.data" used in deserializer function. Below is my deserialization code.

**Environment :**
 - Flink version :  1.14.0
 - Flink CDC version: 2.2.0
 - Database and version: mysql8

Code:
import com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.data.Struct;
import com.ververica.cdc.connectors.shaded.org.apache.kafka.connect.source.SourceRecord;
import com.ververica.cdc.debezium.DebeziumDeserializationSchema;
import com.zanxiangnet.flink.cdc.platform.pojo.entity.platform.PlatformOrder;
import com.zanxiangnet.flink.cdc.platform.serialization.transform.TransformPlatformOrder;
import com.zanxiangnet.flink.cdc.platform.util.CDCStructToBeanUtil;
import io.debezium.data.Envelope;
import org.apache.flink.api.common.typeinfo.TypeInformation;
import org.apache.flink.api.common.typeinfo.Types;
import org.apache.flink.util.Collector;

/**
 * 自定义序列化方式
 */
public class PlatformOrderDebeziumDeserializationSchema implements DebeziumDeserializationSchema<TransformPlatformOrder> {

    @Override
    public void deserialize(SourceRecord sourceRecord, Collector<TransformPlatformOrder> collector) throws Exception {
        Struct struct = (Struct) sourceRecord.value();
        Struct after = struct.getStruct("after");
        Struct before = struct.getStruct("before");
        //获取操作类型
        Envelope.Operation operation = Envelope.operationFor(sourceRecord);

        PlatformOrder beforeBean = null;
        if (before != null) {
            beforeBean = CDCStructToBeanUtil.structToBean(before, PlatformOrder.class);
        }
        PlatformOrder afterBean = null;
        if (after != null) {
            afterBean = CDCStructToBeanUtil.structToBean(after, PlatformOrder.class);
        }
        collector.collect(TransformPlatformOrder.builder()
                .operation(operation)
                .before(beforeBean)
                .after(afterBean)
                .build()
        );
    }

    @Override
    public TypeInformation<TransformPlatformOrder> getProducedType() {
        return Types.POJO(TransformPlatformOrder.class);
    }
}

**Comment by PatrickRen** [comment] 2024-02-28 15:29
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:29 UTC
Labels: bug
