### ISSUE TITLE
[question]the error of connection with mariadb

### ISSUE THREAD

**Issue by CoconuterTATA** [ververica/flink-cdc-connectors#1628] opened 2022-10-19 16:00 UTC
When I use the flink-cdc to connect the mariadb, the result shows:`java.sql.SQLException: Access denied for user`
Environment :
 - Flink version :  1.13.0
 - Flink CDC version: 2.2.1
 - Database and version: [5.5.5-10.5.11-MariaDB(modified)](https://github.com/edgelesssys/edgelessdb)

**To Reproduce**
2. The test code :
CREATE TABLE user_source3 (
      `id` int,
      name STRING,
      age int,
      PRIMARY KEY (`id`) NOT ENFORCED
    ) WITH (
      'connector' = 'mysql-cdc',
      'hostname' = '<server ip addr>',
      'port' = '3307',
      'username' = 'test',
      'password' = '123',	
      'database-name' = 'demo',
      'table-name' = 'student1',
      'jdbc.properties.enabledTLSProtocols' = 'TLSv1.2',
      'jdbc.properties.useSSL' = 'true', 
      'jdbc.properties.trustServerCertificate' = 'true',
 );

**Comment by PatrickRen** [comment] 2024-02-28 15:03
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:03 UTC
Labels: bug
