### ISSUE TITLE
Flink CDC 有支持 SAP-Hana 的计划吗

### ISSUE THREAD

**Issue by JanCong** [ververica/flink-cdc-connectors#1301] opened 2022-06-22 03:15 UTC
Flink CDC 有支持 SAP-Hana 的计划吗

**Comment by Liugh2020** [comment] 2022-07-01 01:38
+1

**Comment by Shoham-Yamin** [comment] 2022-10-30 20:49
+1

**Comment by LegendOfGod** [comment] 2023-02-15 09:15
+10086

**Comment by zqsgithub2023** [comment] 2023-02-17 07:47
+1

**Comment by SinyoWong** [comment] 2023-04-03 12:34
+1

**Comment by fly-shark** [comment] 2024-01-15 10:51
+1

**Comment by PatrickRen** [comment] 2024-02-28 15:06
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:06 UTC
Labels: enhancement
