### ISSUE TITLE
matadata op_ts insert into mysql error(read from snapshot)

### ISSUE THREAD

**Issue by rcf666** [ververica/flink-cdc-connectors#1370] opened 2022-07-14 01:57 UTC
**Describe the bug(Please use English)**
use flink-cdc  mysql to mysql . insert  matadata  op_ts (read from snapshot)   error ： Data truncation: Incorrect datetime value: '1970-01-01 00:00:00.0' for column 'operation_ts' at row 1
binlog is normal

**Environment :**
 - Flink version :  13.1
 - Flink CDC version: 2.2.0
 - Database and version:  mysql:8.0

**To Reproduce**
1. Thes test data :
2. The test code :
`    public static final String  TABLE=" create table if not exists student\n" +
            "(\n" +
            "    id       integer not null,\n" +
            "    name     string,\n" +
            "    sex      string,\n" +
            "    pwd      string,\n" +
            "    birthday TIMESTAMP(3),\n" +
            "    address  string,\n" +
            "    email    string,\n" +
            "    operation_ts TIMESTAMP_LTZ(3) metadata from 'op_ts' VIRTUAL,\n" +
            "    primary key (id) not enforced\n" +
            ") with (\n" +
            "                   'connector' = 'mysql-cdc',\n" +
            "                    'hostname' = '127.0.0.1',\n" +
            "                   'port' = '33306',\n" +
            "                    'username' = 'root',\n" +
            "                    'password' = '123456',\n" +
            "                    'database-name' = 'test',\n" +
            "                    'table-name' = 'student',\n" +
            "                    'server-time-zone'='Asia/Shanghai',\n" +
            "                    'scan.startup.mode' = 'initial'\n" +
            "                )";

    public static final String  SINK="CREATE TABLE  if not exists student1 (\n" +
            "                            id       integer,\n" +
            "                            name    string,\n" +
            "                            sex     string,\n" +
            "                            pwd     string,\n" +
            "                            birthday  timestamp,\n" +
            "                            address  string,\n" +
            "                            email    string,\n" +
            "                            operation_ts timestamp,\n" +
            " PRIMARY KEY (id) NOT ENFORCED\n" +
            ") WITH (\n" +
            "'connector' = 'jdbc',\n" +
            "'url' = 'jdbc:mysql://127.0.0.1:33306/test',\n" +
            "'table-name' = 'student1',\n" +
            "'username'='root',\n" +
            "'password'='123456'\n" +
            ")";
    public static final String  INSERT="insert into student1 select id,name,sex,pwd,birthday,address,email,operation_ts  from student";` 
4. The error :
`java.sql.BatchUpdateException: Data truncation: Incorrect datetime value: '1970-01-01 00:00:00.0' for column 'operation_ts' at row 1
	at sun.reflect.GeneratedConstructorAccessor55.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_152]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_152]
	at com.mysql.cj.util.Util.handleNewInstance(Util.java:192) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.util.Util.getInstance(Util.java:167) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.util.Util.getInstance(Util.java:174) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:855) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:437) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:814) ~[mysql-connector-java-8.0.16.jar:8.0.16]
	at org.apache.flink.connector.jdbc.statement.FieldNamedPreparedStatementImpl.executeBatch(FieldNamedPreparedStatementImpl.java:65) ~[flink-connector-jdbc_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.connector.jdbc.internal.executor.TableSimpleStatementExecutor.executeBatch(TableSimpleStatementExecutor.java:64) ~[flink-connector-jdbc_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.connector.jdbc.internal.executor.TableBufferReducedStatementExecutor.executeBatch(TableBufferReducedStatementExecutor.java:101) ~[flink-connector-jdbc_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.connector.jdbc.internal.JdbcBatchingOutputFormat.attemptFlush(JdbcBatchingOutputFormat.java:213) ~[flink-connector-jdbc_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.connector.jdbc.internal.JdbcBatchingOutputFormat.flush(JdbcBatchingOutputFormat.java:183) ~[flink-connector-jdbc_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.connector.jdbc.internal.GenericJdbcSinkFunction.snapshotState(GenericJdbcSinkFunction.java:62) ~[flink-connector-jdbc_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.util.functions.StreamingFunctionUtils.trySnapshotFunctionState(StreamingFunctionUtils.java:118) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.util.functions.StreamingFunctionUtils.snapshotFunctionState(StreamingFunctionUtils.java:99) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.snapshotState(AbstractUdfStreamOperator.java:89) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.snapshotState(StreamOperatorStateHandler.java:218) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.snapshotState(StreamOperatorStateHandler.java:169) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.api.operators.AbstractStreamOperator.snapshotState(AbstractStreamOperator.java:371) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.runtime.tasks.SubtaskCheckpointCoordinatorImpl.checkpointStreamOperator(SubtaskCheckpointCoordinatorImpl.java:706) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.runtime.tasks.SubtaskCheckpointCoordinatorImpl.buildOperatorSnapshotFutures(SubtaskCheckpointCoordinatorImpl.java:627) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.runtime.tasks.SubtaskCheckpointCoordinatorImpl.takeSnapshotSync(SubtaskCheckpointCoordinatorImpl.java:590) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.runtime.tasks.SubtaskCheckpointCoordinatorImpl.checkpointState(SubtaskCheckpointCoordinatorImpl.java:312) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$performCheckpoint$8(StreamTask.java:1086) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.runThrowing(StreamTaskActionExecutor.java:50) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.performCheckpoint(StreamTask.java:1070) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.triggerCheckpoint(StreamTask.java:988) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$triggerCheckpointAsync$7(StreamTask.java:960) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.runThrowing(StreamTaskActionExecutor.java:50) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.runtime.tasks.mailbox.Mail.run(Mail.java:90) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.processMailsWhenDefaultActionUnavailable(MailboxProcessor.java:344) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.processMail(MailboxProcessor.java:330) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:202) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:681) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.executeInvoke(StreamTask.java:636) ~[flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runWithCleanUpOnFail(StreamTask.java:647) [flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:620) [flink-streaming-java_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:779) [flink-runtime_2.11-1.13.1.jar:1.13.1]
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:566) [flink-runtime_2.11-1.13.1.jar:1.13.1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]`

**Additional Description**

**Temporary Solution**
mysql  not support  timestamp_ltz=0  ,so i use `if(DATE_FORMAT(operation_ts, 'yyyy-MM-dd HH:mm:ss') < '1970-01-02 00:00:00', to_timestamp_ltz(1, 0), operation_ts) as operation_time `   it  take effect

**Comment by PatrickRen** [comment] 2024-02-28 15:29
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:29 UTC
Labels: bug
