### ISSUE TITLE
[bug][tidb-connector]checkpoint is not updated long after a task has been running

### ISSUE THREAD

**Issue by wangxiaojing** [ververica/flink-cdc-connectors#1685] opened 2022-11-01 03:03 UTC
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  1.14
 - Flink CDC version: 2.3
 - Database and version: 5.1

**To Reproduce**
1. The error :
``2022-10-27 12:48:34,981 INFO  org.tikv.cdc.CDCClient                                       [] - handle resolvedTs: 436953707961122840, regionId: 1721083
2022-10-27 12:48:35,469 INFO  org.tikv.cdc.CDCClient                                       [] - handle resolvedTs: 436953708092194817, regionId: 10236245
2022-10-27 12:48:35,469 INFO  org.tikv.cdc.CDCClient                                       [] - handle resolvedTs: 436953708092194817, regionId: 10237829
2022-10-27 12:48:35,469 INFO  org.tikv.cdc.CDCClient                                       [] - handle resolvedTs: 436953708092194817, regionId: 8419115
2022-10-27 12:48:35,477 INFO  org.tikv.cdc.CDCClient                                       [] - handle resolvedTs: 436953708092194820, regionId: 7318373
2022-10-27 12:48:35,477 INFO  org.tikv.cdc.CDCClient                                       [] - handle resolvedTs: 436953708092194820, regionId: 11085331
2022-10-27 12:48:35,631 INFO  com.ververica.cdc.connectors.tidb.TiKVRichParallelSourceFunction [] - snapshotState checkpoint: 9 at resolvedTs: 436952756312866827`

`2022-10-27 12:58:35,594 INFO  org.tikv.cdc.CDCClient                                       [] - handle resolvedTs: 436953865404809241, regionId: 8684959
2022-10-27 12:58:35,594 INFO  org.tikv.cdc.CDCClient                                       [] - handle resolvedTs: 436953865404809241, regionId: 8309437
2022-10-27 12:58:35,594 INFO  org.tikv.cdc.CDCClient                                       [] - handle resolvedTs: 436953865404809241, regionId: 1721083
2022-10-27 12:58:35,594 INFO  org.tikv.cdc.CDCClient                                       [] - handle resolvedTs: 436953865404809241, regionId: 11090547
2022-10-27 12:58:35,635 INFO  com.ververica.cdc.connectors.tidb.TiKVRichParallelSourceFunction [] - snapshotState checkpoint: 10 at resolvedTs: 436952756312866827`
`

`
2022-10-27 13:08:35,197 INFO  org.tikv.cdc.CDCClient                                       [] - handle resolvedTs: 436954022586351623, regionId: 8424191
2022-10-27 13:08:35,197 INFO  org.tikv.cdc.CDCClient                                       [] - handle resolvedTs: 436954022586351623, regionId: 8343109
2022-10-27 13:08:35,197 INFO  org.tikv.cdc.CDCClient                                       [] - handle resolvedTs: 436954022586351623, regionId: 3287795
2022-10-27 13:08:35,197 INFO  org.tikv.cdc.CDCClient                                       [] - handle resolvedTs: 436954022586351623, regionId: 8221803
2022-10-27 13:08:35,197 INFO  org.tikv.cdc.CDCClient                                       [] - handle resolvedTs: 436954022586351623, regionId: 11120919
2022-10-27 13:08:35,197 INFO  org.tikv.cdc.CDCClient                                       [] - handle resolvedTs: 436954022586351623, regionId: 10296761
2022-10-2
7 13:08:35,197 INFO  org.tikv.cdc.CDCClient                                       [] - handle resolvedTs: 436954022586351623, regionId: 8309437
2022-10-27 13:08:35,197 INFO  org.tikv.cdc.CDCClient                                       [] - handle resolvedTs: 436954022586351623, regionId: 8684959
2022-10-27 13:08:35,197 INFO  org.tikv.cdc.CDCClient                                       [] - handle resolvedTs: 436954022586351623, regionId: 11090547
2022-10-27 13:08:35,197 INFO  org.tikv.cdc.CDCClient                                       [] - handle resolvedTs: 436954022586351623, regionId: 1721083
2022-10-27 13:08:35,632 INFO  com.ververica.cdc.connectors.tidb.TiKVRichParallelSourceFunction [] - snapshotState checkpoint: 11 at resolvedTs: 436952756312866827
`

**Additional Description**

**Comment by wangxiaojing** [comment] 2022-11-02 02:12
https://github.com/ververica/flink-cdc-connectors/pull/1686

**Comment by PatrickRen** [comment] 2024-02-28 15:02
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:02 UTC
Labels: bug
