### ISSUE TITLE
Flink CDC是否支持读阿里的DRDS的全局binlog，报错如下

### ISSUE THREAD

**Issue by qingfengKnight** [ververica/flink-cdc-connectors#144] opened 2021-03-29 01:42 UTC
2021-03-24 19:36:03,520 INFO  io.debezium.connector.mysql.BinlogReader                     [] - Waiting for keepalive thread to start
2021-03-24 19:36:03,521 INFO  io.debezium.util.Threads                                     [] - Creating thread debezium-mysqlconnector-mysql_binlog_source-binlog-client
2021-03-24 19:36:03,522 ERROR io.debezium.connector.mysql.BinlogReader                     [] - Error during binlog processing. Last offset stored = null, binlog reader near position = /4
2021-03-24 19:36:03,527 INFO  io.debezium.connector.mysql.BinlogReader                     [] - Stopped reading binlog after 0 events, no new offset was recorded
2021-03-24 19:36:08,521 INFO  io.debezium.connector.common.BaseSourceTask                  [] - Stopping down connector
2021-03-24 19:36:08,521 INFO  io.debezium.connector.mysql.MySqlConnectorTask               [] - Stopping MySQL connector task
2021-03-24 19:36:08,521 INFO  io.debezium.connector.mysql.ChainedReader                    [] - ChainedReader: Stopping the binlog reader
2021-03-24 19:36:08,521 INFO  io.debezium.connector.mysql.BinlogReader                     [] - Discarding 0 unsent record(s) due to the connector shutting down
2021-03-24 19:36:08,522 INFO  io.debezium.connector.mysql.BinlogReader                     [] - Discarding 0 unsent record(s) due to the connector shutting down
2021-03-24 19:36:08,531 INFO  io.debezium.jdbc.JdbcConnection                              [] - Connection gracefully closed
2021-03-24 19:36:08,534 INFO  io.debezium.connector.mysql.MySqlConnectorTask               [] - Connector task finished all work and is now shutdown
2021-03-24 19:36:08,545 ERROR com.alibaba.ververica.cdc.debezium.DebeziumSourceFunction    [] - Reporting error:
org.apache.kafka.connect.errors.ConnectException: [12337214b6ce6000][172.16.176.72:3306][sdm]Unknown command Error code: 1047; SQLSTATE: HY000.
	at io.debezium.connector.mysql.AbstractReader.wrap(AbstractReader.java:241) ~[flink-sql-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at io.debezium.connector.mysql.AbstractReader.failed(AbstractReader.java:207) ~[flink-sql-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at io.debezium.connector.mysql.BinlogReader$ReaderThreadLifecycleListener.onCommunicationFailure(BinlogReader.java:1142) ~[flink-sql-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:962) ~[flink-sql-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:595) ~[flink-sql-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:839) ~[flink-sql-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: com.github.shyiko.mysql.binlog.network.ServerException: [12337214b6ce6000][172.16.176.72:3306][sdm]Unknown command
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:926) ~[flink-sql-connector-mysql-cdc-1.2.0.jar:1.2.0]
	... 3 more
2021-03-24 19:36:09,564 INFO  io.debezium.embedded.EmbeddedEngine                          [] - Stopping the embedded engine
2021-03-24 19:36:09,578 INFO  io.debezium.embedded.EmbeddedEngine                          [] - Stopping the embedded engine
2021-03-24 19:36:09,584 WARN  org.apache.flink.runtime.taskmanager.Task                    [] - Source: Custom Source (1/1)#0 (6bf35819d2cc9bfadfbda675ca5e1234) switched from RUNNING to FAILED.
org.apache.kafka.connect.errors.ConnectException: [12337214b6ce6000][172.16.176.72:3306][sdm]Unknown command Error code: 1047; SQLSTATE: HY000.
	at io.debezium.connector.mysql.AbstractReader.wrap(AbstractReader.java:241) ~[flink-sql-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at io.debezium.connector.mysql.AbstractReader.failed(AbstractReader.java:207) ~[flink-sql-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at io.debezium.connector.mysql.BinlogReader$ReaderThreadLifecycleListener.onCommunicationFailure(BinlogReader.java:1142) ~[flink-sql-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:962) ~[flink-sql-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:595) ~[flink-sql-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:839) ~[flink-sql-connector-mysql-cdc-1.2.0.jar:1.2.0]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: com.github.shyiko.mysql.binlog.network.ServerException: [12337214b6ce6000][172.16.176.72:3306][sdm]Unknown command
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:926) ~[flink-sql-connector-mysql-cdc-1.2.0.jar:1.2.0]
	... 3 more

**Comment by wuchong** [comment] 2021-04-07 02:13
目前还没有对接 DRDS。

**Comment by PatrickRen** [comment] 2024-02-28 15:33
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:33 UTC
Labels: enhancement
