### ISSUE TITLE
[mysql] expose MySqlSnapshotSplitAssigner metrics

### ISSUE THREAD

**Issue by zhjwpku** [ververica/flink-cdc-connectors#731] opened 2021-12-16 09:34 UTC
Flink cdc mysql now expose some metrics for SourceReader, which are `fetchDelay`, `emitDelay` and `idleTime`,
but this is not enough, user may want to know the process of the snapshot phase.

MySqlSnapshotSplitAssigner maintains some states which are very valuable to user:

- alreadyProcessedTables
- remainingTables
- assignedSplits
- splitFinishedOffsets

We can infer total table number from `alreadyProcessedTables.size() + remainingTables.size()`,
if remainingTables is empty, the job enters the binlog phase, users may roughly know the processing
percentage by calulate `alreadyProcessedTables.size() / alreadyProcessedTables.size() + remainingTables.size()`.

`assignedSplits` and `splitFinishedOffsets` are not grouped by SourceReader, but if they are,
we can infer the work load of each SourceReader.

### Solution

It will be great if we can expose the above status directly throw `SplitEnumeratorContext.metricGroup()`,
unfortunately we can't due to `metricGroup()` returns null, and that's because Enumerator runs on JobMaster.

So we might use the RPC Gateway, a.k.a SourceEvent to transfer the above mentioned metrics to each SourceReader.

I implement this idea using `FinishedSnapshotSplitsAckEvent` to pass those data to SourceReader,  see #720, there
are chances that a SourceReader will not get the metrics if parallism > totalSplits, but I think that's not a big
problem. In order to get `assignedSplits` and `splitFinishedOffsets` for each SourceReader,  I changed some 
data structures:

```
-    private final Map<String, MySqlSnapshotSplit> assignedSplits;
-    private final Map<String, BinlogOffset> splitFinishedOffsets;
+    private final Map<Integer, Map<String, MySqlSnapshotSplit>> assignedSplits;
+    private final Map<Integer, Map<String, BinlogOffset>> splitFinishedOffsets;
```

*The Integer key reflect the subtaskId of each SourceReader.*

Thoughts?

**Comment by zhjwpku** [comment] 2022-02-08 02:37
After some investigation, I found `assignedSplits` and `splitFinishedOffsets ` data structure should not be changed, because if the parallism changes,  the number of SourceReader is different, thus the subtaskId may not reflect the previous SourceReader.

**Comment by PatrickRen** [comment] 2024-02-28 15:32
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:32 UTC
Labels: enhancement
