### ISSUE TITLE
Client requested master to start replication from impossible position

### ISSUE THREAD

**Issue by 1105220927** [ververica/flink-cdc-connectors#962] opened 2022-03-18 06:44 UTC
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  1.13.2
 - Flink CDC version: master (2.2-Snapshot)
 - Database and version: 10.1.9-Mariadb (slave)

**To Reproduce**
I use  flink-cdc(version 2.2-snapshot) com.ververica.cdc.connectors.mysql.source.MySqlSource build binlogSource, and  i'll got this exception when I start the job,:
![image](https://user-images.githubusercontent.com/95424327/158949474-3f1f40d7-7205-4cae-8a02-79247cda1a22.png)
 
when  i use flink-cdc(version  2.1.1) com.ververica.cdc.connectors.mysql.MySqlSource build binlogSource , the job can running normally

is there some bugs of com.ververica.cdc.connectors.mysql.source.MySqlSource? or bugs of  branch-master(2.2-snapshot)

**Comment by PatrickRen** [comment] 2024-02-28 15:09
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:09 UTC
Labels: bug
