### ISSUE TITLE
tidb cdc connectors classNotFoundException: org.tikv.shade.io.grpc.internal.ManagedChannelImpl$LbHelperImpl$1LoadBalancerRefreshNameResolution

### ISSUE THREAD

**Issue by milkdrink** [ververica/flink-cdc-connectors#1113] opened 2022-04-25 02:00 UTC
Apr 25, 2022 6:16:00 AM org.tikv.shade.io.grpc.internal.ManagedChannelImpl$2 uncaughtException
SEVERE: [Channel<3>: (192.168.31.189:2379)] Uncaught exception in the SynchronizationContext. Panic!
java.lang.NoClassDefFoundError: org/tikv/shade/io/grpc/internal/ManagedChannelImpl$LbHelperImpl$1LoadBalancerRefreshNameResolution
	at org.tikv.shade.io.grpc.internal.ManagedChannelImpl$LbHelperImpl.refreshNameResolution(ManagedChannelImpl.java:1492)
	at org.tikv.shade.io.grpc.internal.PickFirstLoadBalancer.processSubchannelState(PickFirstLoadBalancer.java:89)
	at org.tikv.shade.io.grpc.internal.PickFirstLoadBalancer.access$000(PickFirstLoadBalancer.java:39)
	at org.tikv.shade.io.grpc.internal.PickFirstLoadBalancer$1.onSubchannelState(PickFirstLoadBalancer.java:58)
	at org.tikv.shade.io.grpc.internal.ManagedChannelImpl$SubchannelImpl$1ManagedInternalSubchannelCallback.onStateChange(ManagedChannelImpl.java:1966)
	at org.tikv.shade.io.grpc.internal.InternalSubchannel.gotoState(InternalSubchannel.java:333)
	at org.tikv.shade.io.grpc.internal.InternalSubchannel.gotoNonErrorState(InternalSubchannel.java:323)
	at org.tikv.shade.io.grpc.internal.InternalSubchannel.access$300(InternalSubchannel.java:65)
	at org.tikv.shade.io.grpc.internal.InternalSubchannel$TransportListener$2.run(InternalSubchannel.java:583)
	at org.tikv.shade.io.grpc.SynchronizationContext.drain(SynchronizationContext.java:95)
	at org.tikv.shade.io.grpc.SynchronizationContext.execute(SynchronizationContext.java:127)
	at org.tikv.shade.io.grpc.internal.InternalSubchannel$TransportListener.transportShutdown(InternalSubchannel.java:574)
	at org.tikv.shade.io.grpc.netty.ClientTransportLifecycleManager.notifyGracefulShutdown(ClientTransportLifecycleManager.java:56)
	at org.tikv.shade.io.grpc.netty.ClientTransportLifecycleManager.notifyShutdown(ClientTransportLifecycleManager.java:62)
	at org.tikv.shade.io.grpc.netty.NettyClientHandler.onConnectionError(NettyClientHandler.java:541)
	at org.tikv.shade.io.netty.handler.codec.http2.Http2ConnectionHandler.onError(Http2ConnectionHandler.java:715)
	at org.tikv.shade.io.grpc.netty.AbstractNettyHandler.exceptionCaught(AbstractNettyHandler.java:94)
	at org.tikv.shade.io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
	at org.tikv.shade.io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
	at org.tikv.shade.io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
	at org.tikv.shade.io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377)
	at org.tikv.shade.io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
	at org.tikv.shade.io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
	at org.tikv.shade.io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907)
	at org.tikv.shade.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.handleReadException(AbstractNioByteChannel.java:125)
	at org.tikv.shade.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:177)
	at org.tikv.shade.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at org.tikv.shade.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at org.tikv.shade.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at org.tikv.shade.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at org.tikv.shade.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at org.tikv.shade.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at org.tikv.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.tikv.shade.io.grpc.internal.ManagedChannelImpl$LbHelperImpl$1LoadBalancerRefreshNameResolution
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClassWithoutExceptionHandling(FlinkUserCodeClassLoader.java:64)
	at org.apache.flink.util.ChildFirstClassLoader.loadClassWithoutExceptionHandling(ChildFirstClassLoader.java:74)
	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClass(FlinkUserCodeClassLoader.java:48)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 34 more

**Comment by PatrickRen** [comment] 2024-02-28 15:08
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:08 UTC
Labels: bug
