### ISSUE TITLE
InterruptedException while waiting for asynchronously snapshot split

### ISSUE THREAD

**Issue by kangshisen** [ververica/flink-cdc-connectors#1612] opened 2022-10-12 02:08 UTC
**Environment :**
 - Flink version :  1.14.5
 - Flink CDC version: 2.2.1
 - Database and version: Mysql5.6.39

**To Reproduce**
Flinkcdc同步Mysql数据的时候出现个别数据库不采集数据也不报错的问题，提交方式采用的yarn per-job。
这是我测试的flinksql：
<img width="963" alt="image" src="https://user-images.githubusercontent.com/38653300/195232136-6518687f-fb1e-4f40-82f2-aaf631ffdf56.png">
这是提交后的flinkweb界面
![image](https://user-images.githubusercontent.com/38653300/195232233-51d508e9-5f64-43c0-8c82-ddbd01d3acb1.png)
cancel job后去yarn log日志查看发现如下错误：
![image](https://user-images.githubusercontent.com/38653300/195232415-dcef0b23-3cd5-4fae-a2ac-cd95d3be9a9f.png)

**Additional Description**
大部分数据库都可以采集到，不知道是数据库的原因还是什么

**Comment by fuyun2024** [comment] 2022-10-12 03:22
The real mistake is not here. Can you check TM log

**Comment by kangshisen** [comment] 2022-10-12 05:06
No error information is displayed in the TM log. Procedure

**Comment by kangshisen** [comment] 2022-10-12 05:57
[taskmanager_container_1661934954992_5903_01_000002_log.txt](https://github.com/ververica/flink-cdc-connectors/files/9761947/taskmanager_container_1661934954992_5903_01_000002_log.txt)

**Comment by geosmart** [comment] 2023-01-11 03:47
the same issue . consume  same event and interupt .
throw a `org.apache.flink.util.FlinkRuntimeException: InterruptedException while waiting for asynchronously snapshot split`
and no more binglog event is emit.

```java
2023-01-10 11:59:23,044 INFO  io.debezium.jdbc.JdbcConnection                              [] - Connection gracefully closed
2023-01-10 11:59:23,045 ERROR org.apache.flink.runtime.source.coordinator.SourceCoordinator [] - Uncaught exception in the SplitEnumerator for Source Source: BotKnowledge_BinLog -> (Filter, Filter -> Map) while handling operator event RequestSplitEvent (host='hz-hadoop-flink-98-20-7') from subtask 0. Triggering job failover.
org.apache.flink.util.FlinkRuntimeException: InterruptedException while waiting for asynchronously snapshot split
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlSnapshotSplitAssigner.getNext(MySqlSnapshotSplitAssigner.java:235) ~[qa-xiaoxin-question_0.1_flink_1.13.2_bstag.jar:?]
	at com.ververica.cdc.connectors.mysql.source.assigners.MySqlHybridSplitAssigner.getNext(MySqlHybridSplitAssigner.java:125) ~[qa-xiaoxin-question_0.1_flink_1.13.2_bstag.jar:?]
	at com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator.assignSplits(MySqlSourceEnumerator.java:193) ~[qa-xiaoxin-question_0.1_flink_1.13.2_bstag.jar:?]
	at com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator.handleSplitRequest(MySqlSourceEnumerator.java:109) ~[qa-xiaoxin-question_0.1_flink_1.13.2_bstag.jar:?]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$handleEventFromOperator$1(SourceCoordinator.java:164) ~[flink-dist_2.11-1.13.2.jar:1.13.2]
	at org.apache.flink.runtime.source.coordinator.SourceCoordinator.lambda$runInEventLoop$8(SourceCoordinator.java:315) ~[flink-dist_2.11-1.13.2.jar:1.13.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
2023-01-10 11:59:23,047 WARN  io.debezium.relational.history.DatabaseHistoryMetrics        [] - Unable to register the MBean 'debezium.mysql:type=connector-metrics,context=schema-history,server=mysql_binlog_source': debezium.mysql:type=connector-metrics,context=schema-history,server=mysql_binlog_source
2023-01-10 11:59:23,047 INFO  com.ververica.cdc.connectors.mysql.source.assigners.ChunkSplitter [] - Start splitting table bot_knowledge_pre.hf_chat_question into chunks...
2023-01-10 11:59:23,055 INFO  com.ververica.cdc.connectors.mysql.source.assigners.ChunkSplitter [] - Use unevenly-sized chunks for table bot_knowledge_pre.hf_chat_question, the chunk size is 8096
2023-01-10 11:59:23,063 INFO  com.ververica.cdc.connectors.mysql.source.assigners.ChunkSplitter [] - Split table bot_knowledge_pre.hf_chat_question into 1 chunks, time cost: 16ms.
2023-01-10 11:59:23,064 INFO  io.debezium.jdbc.JdbcConnection                              [] - Connection gracefully closed
2023-01-10 11:59:23,065 INFO  com.ververica.cdc.connectors.mysql.source.assigners.ChunkSplitter [] - Start splitting table bot_knowledge_pre.hf_question into chunks...
2023-01-10 11:59:23,067 INFO  com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator [] - Assign split MySqlSnapshotSplit{tableId=bot_knowledge_pre.hf_chat_question, splitId='bot_knowledge_pre.hf_chat_question:0', splitKeyType=[`hf_id` VARCHAR(32) NOT NULL], splitStart=null, splitEnd=null, highWatermark=null} to subtask 0
2023-01-10 11:59:23,067 INFO  org.apache.flink.runtime.source.coordinator.SourceCoordinator [] - Removing registered reader after failure for subtask 0 of source Source: BotKnowledge_BinLog -> (Filter, Filter -> Map).
2023-01-10 11:59:23,070 INFO  io.debezium.jdbc.JdbcConnection                              [] - Connection gracefully closed
2023-01-10 11:59:23,178 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph       [] - Source: BinLog-xiaoxin_question_v0 -> Map -> Sink: Sync2ES-jrsyb-qabot-xiaoxin_question_v0 (1/1) (2b914c470b1af6c0b55338fb6844fb02) switched from CANCELING to CANCELED.
2023-01-10 11:59:23,179 INFO  org.apache.flink.runtime.resourcemanager.slotmanager.DeclarativeSlotManager [] - Clearing resource requirements of job e74067ea3b618b8c17b83df98ad32b62
2023-01-10 11:59:23,546 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph       [] - Job [bstag]Sync-XiaoxinQuestion[v0] (e74067ea3b618b8c17b83df98ad32b62) switched from state RESTARTING to RUNNING.
2023-01-10 11:59:23,547 INFO  org.apache.flink.runtime.checkpoint.CheckpointCoordinator    [] - No checkpoint found during restore.
2023-01-10 11:59:23,547 INFO  org.apache.flink.runtime.checkpoint.CheckpointCoordinator    [] - Resetting the Operator Coordinators to an empty state.
2023-01-10 11:59:23,547 INFO  org.apache.flink.runtime.operators.coordination.RecreateOnResetOperatorCoordinator [] - Resetting coordinator to checkpoint.
2023-01-10 11:59:23,547 INFO  org.apache.flink.runtime.operators.coordination.RecreateOnResetOperatorCoordinator [] - Resetting coordinator to checkpoint.
2023-01-10 11:59:23,547 INFO  org.apache.flink.runtime.source.coordinator.SourceCoordinator [] - Closing SourceCoordinator for source Source: BotKnowledge_BinLog -> (Filter, Filter -> Map).
2023-01-10 11:59:23,547 INFO  org.apache.flink.runtime.source.coordinator.SourceCoordinator [] - Closing SourceCoordinator for source Source: BinLog-xiaoxin_question_v0 -> Map -> Sink: Sync2ES-jrsyb-qabot-xiaoxin_question_v0.
2023-01-10 11:59:23,548 INFO  com.ververica.cdc.connectors.mysql.source.enumerator.MySqlSourceEnumerator [] - Closing enumerator...
2023-01-10 11:59:23,548 INFO  org.apache.flink.runtime.source.coordinator.SourceCoordinator [] - Source coordinator for source Source: BotKnowledge_BinLog -> (Filter, Filter -> Map) closed.
2023-01-10 11:59:23,548 INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph       [] - Source: BotKnowledge_BinLog -> (Filter, Filter -> Map) (1/1) (a59be92692d470d83825585374684d4d) switched from CREATED to SCHEDULED.
```

**Comment by geosmart** [comment] 2023-01-11 04:07
just as  issue #1537 . you need to add primary key for consume table

**Comment by PatrickRen** [comment] 2024-02-28 15:28
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:28 UTC
Labels: bug
