### ISSUE TITLE
mysql connector order by primary key in each chunk during  snapshot read

### ISSUE THREAD

**Issue by yujiaxinlong** [ververica/flink-cdc-connectors#1074] opened 2022-04-13 10:36 UTC
**Is your feature request related to a problem? Please describe.**
I am trying to export one table from mysql to data warehouse, and need to store some information in Flink state, and need the stream is handled in order on some level.
But I find that the data read from mysql is totally out-of-order in each chunk, even when I set parallel to 1.

Currently I am using a tumbling window  to reorder data, but this lead to some other problems.

I am curious why these data is not order by primary key , since it has been splited by the order primary key, or did I miss some configuration.

**Describe the solution you'd like**
A new configuration that can keep the data in chunk in order will be great.

**Comment by PatrickRen** [comment] 2024-02-28 15:09
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:09 UTC
Labels: enhancement
