### ISSUE TITLE
[Bug] io.debezium.connector.oracle.logminer.parser.DmlParserException: DML statement couldn't be parsed

### ISSUE THREAD

**Issue by szhengshuai** [ververica/flink-cdc-connectors#1965] opened 2023-03-07 06:56 UTC
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

1.16.1

### Flink CDC version

2.3.0

### Database and its version

ORACLE 19c

### Minimal reproduce step

1、The following is an example of the running code：
 tableEnv.executeSql( "CREATE TABLE ORACLE_TEST (" +
				" ID STRING," +
				" NAME STRING," +
				" ADDR STRING," +
				" CUR_TIME AS LOCALTIMESTAMP, "+
				" CREATE_TIME TIMESTAMP(3), "+
				" PRIMARY KEY(ID) NOT ENFORCED " +
				") WITH (" +
				"  'connector' = 'oracle-cdc'," +
				"  'hostname' = '12.0.217.02'," +
				"  'port' = '1521'," +
				"  'username' = 'XXX'," +
				"  'password' = 'Oracle_123'," +
				"  'database-name' = 'test'," +
				"  'schema-name' = 'SCOTT'," +
				"  'table-name' = 'TEST3'," +       
				" 'scan.startup.mode' = 'initial'," +
				" 'debezium.log.mining.strategy'='online_catalog'," +    
				" 'scan.incremental.snapshot.enabled' = 'true'"+
				")" )
String sql = "SELECT ID,NAME,ADDR,DATE_FORMAT(CREATE_TIME,'yyyy-MM-dd HH:mm:ss'),'' from ORACLE_TEST  WHERE NAME <> 'aaa'";
TableResult tableResult = tableEnv.executeSql(sql);
  tableResult.print();

### What did you expect to see?

Incremental data changes can be captured smoothly

+I 1 ,szs, beijing, 2022-03-07 00:00:00
+I 2 ,tom, beijing, 2022-03-07 00:00:00
+I 3 ,jim, beijing, 2022-03-07 00:00:00
-U 3 ,jim, beijing, 2022-03-07 00:00:00
+U 3 ,tom, beijing, 2022-03-07 00:00:00

### What did you see instead?

1、The snapshot data is obtained successfully
+I 1 ,szs, beijing, 2022-03-07 00:00:00
+I 2 ,tom, beijing, 2022-03-07 00:00:00
+I 3 ,jim, beijing, 2022-03-07 00:00:00

2、But the incremental datagram has the following error:
Caused by: io.debezium.connector.oracle.logminer.parser.DmlParserException: DML statement couldn't be parsed. Please open a Jira issue with the statement 'update "SCOTT"."TEST3" set "NAME" = 'tom' where "ID" = '3' and "NAME" = 'jim' and "ADDR" = 'beijing' and "CREATE_TIME" = TO_DATE('2023-03-07 00:00:00', 'YYYY-MM-DD HH24:MI:SS');'. You can set internal.log.mining.dml.parser='legacy' as a workaround until the parse error is fixed.

3、 I added the ”internal.log.mining.dml.parser='legacy'“ configuration and still reported the same error

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by ora-mayadong** [comment] 2023-03-15 07:19
i also met this bug,it cannot parse insert sql ,some errros is  as fllows: 
 orace-cdc versions is 2.3.0
 flink-version: 1.15.0
erorr:

Caused by: io.debezium.connector.oracle.logminer.parser.DmlParserException: Failed to parse insert DML: 'insert into "HL40"." BUFFER"("POSNO","FLOWNO","CASHIER","FILDATE","STDTOTAL","SCRTOTAL","REALAMT","CARDNO","RECCNT","MEMO","SCRFAVMODE","SCRFAVVALUE","DEALER","SCORE","RCVTIME","CLASSDATE","CLASSNO","BUSDATE","CONTINUOUSFLOWNO","ACTIONSTAMP","ACTION","VOUCHERCODE","VOUCHERTYPE","SERVICETYPE","SRCFLOWNO","ISKILLALLSALE","CURRENCYGID","EXGRATE","SRCSTDTOTAL","SRCSCRTOTAL","SRCREALAMT","SRCSCRFAVVALUE","TAKEOUTFOODORDNO","MEMBERID","UUID","TERMINAL","EXGRATETYPE","PAYNO","FLAG","SRCPOSNO","BUSITYPE","TAXNO","ELEINVOICECODE","SRCCLS","DATASRC","INVOICENO","CUSTOMERINFO","UNIONPAYFLOWNO","BCKREASON","FOODPROCSTAT","ASSISTANT","REMARK","TMPRCVTIME","FLOWNOFLAG","TOKENTOTAL","MEMBERGRADE") values ('J246C2','202303150001','1004480',TO_TIMESTAMP('2023-03-15 05:05:11.'),'8.03','8.03','5.69',NULL,'2',NULL,'0','100','0','0',TO_TIMESTAMP('2023-03-15 05:05:12.'),NULL,NULL,TO_TIMESTAMP('2023-03-15 05:05:11.'),'000000098676',TO_TIMESTAMP('2023-03-15 05:05:12.'),'1',NULL,'0',NULL,NULL,'0','2','1','8.03','8.03','5.69','100',NULL,NULL,'9100fe7d4a2f0f6c262c94141',NULL,'0','null|7969f2d239b14248b131431414541','0',NULL,'0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);'
	at io.debezium.connector.oracle.logminer.parser.LogMinerDmlParser.parseInsert(LogMinerDmlParser.java:111)
	at io.debezium.connector.oracle.logminer.parser.LogMinerDmlParser.parse(LogMinerDmlParser.java:75)
	at io.debezium.connector.oracle.logminer.LogMinerQueryResultProcessor.parse(LogMinerQueryResultProcessor.java:397)
	... 14 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 55

**Comment by ora-mayadong** [comment] 2023-03-15 07:20
i wanna ask when the bug will be fixed, or provide a temporary solution

**Comment by ora-mayadong** [comment] 2023-03-15 07:47
@szhengshuai how do you set parameter ' internal.log.mining.dml.parser' ?   my opertion is right ?
![image](https://user-images.githubusercontent.com/7436455/225241153-43f641f4-65a7-472f-b582-686d57f0a771.png)

**Comment by szhengshuai** [comment] 2023-03-16 04:09
> @szhengshuai how do you set parameter ' internal.log.mining.dml.parser' ? my opertion is right ? ![image](https://user-images.githubusercontent.com/7436455/225241153-43f641f4-65a7-472f-b582-686d57f0a771.png)
tableEnv.executeSql( "CREATE TABLE ORACLE_TEST (" +
" ID STRING," +
" NAME STRING," +
" ADDR STRING," +
" CUR_TIME AS LOCALTIMESTAMP, "+
" CREATE_TIME TIMESTAMP(3), "+
" PRIMARY KEY(ID) NOT ENFORCED " +
") WITH (" +
" 'connector' = 'oracle-cdc'," +
" 'hostname' = '12.0.217.02'," +
" 'port' = '1521'," +
" 'username' = 'XXX'," +
" 'password' = 'Oracle_123'," +
" 'database-name' = 'test'," +
" 'schema-name' = 'SCOTT'," +
" 'table-name' = 'TEST3'," +
" 'scan.startup.mode' = 'initial'," +
" 'debezium.log.mining.strategy'='online_catalog'," +
" 'scan.incremental.snapshot.enabled' = 'true',"+
" 'internal.log.mining.dml.parser'='legacy'"
")" )

**Comment by szhengshuai** [comment] 2023-03-16 04:14
> 



>

**Comment by ora-mayadong** [comment] 2023-03-16 07:10
@szhengshuai I don't know which cdc version you use , my cdc vesion is 2.3.0, it illustrates that oracle-cdc cannot support this opition "'internal.log.mining.dml.parser' = 'legacy'"

![Uploading image.png…]()


i can set this option in sql cli ,but i don't know whether the operation  works or not

**Comment by ora-mayadong** [comment] 2023-03-16 07:10
@szhengshuai I don't know which cdc version you use , my cdc vesion is 2.3.0, it illustrates that oracle-cdc cannot support this opition "'internal.log.mining.dml.parser' = 'legacy'"
 
![image](https://user-images.githubusercontent.com/7436455/225541226-b387477f-3c91-4f01-939c-f896b1241300.png)



i can set this option in sql cli ,but i don't know whether the operation  works or not

**Comment by ora-mayadong** [comment] 2023-03-16 07:16
@szhengshuai  I think you connector option "'internal.log.mining.dml.parser' = 'legacy'"  probably don't solve  the problem.

**Comment by ora-mayadong** [comment] 2023-03-16 07:18
@szhengshuai I think you connector option "'internal.log.mining.dml.parser' = 'legacy'" probably don't solve the problem. Could we exchage wechat  to talk about this question deeply ？

**Comment by ora-mayadong** [comment] 2023-03-16 08:02
Maybe theres is serious problem about the option，i use this option today，it occurs that some data is missing in cdc collection.

**Comment by ora-mayadong** [comment] 2023-03-16 08:02
Maybe theres is serious problem about the option，i use this option today，it occurs that some data is missing in cdc collection.

**Comment by szhengshuai** [comment] 2023-03-27 07:57
>  Ok, I've been busy these days and haven't had time to check github

**Comment by szhengshuai** [comment] 2023-03-27 08:03
ok, I have been busy these days and have no time to check github. I think this is a bug and I haven't solved it yet, but we can add the contact  to communicate with other problems. @ora-mayadong

**Comment by ruanhang1993** [comment] 2023-06-30 08:02
Maybe we could test is with 2.4.0. The debezium is updated to 1.9.7.Final. It fixed some bugs for DDL.

**Comment by gong** [comment] 2024-02-03 07:56
https://issues.redhat.com/browse/DBZ-3892 Maybe debezium fix this problem you can try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you! cc @GOODBOY008

**Closed** 2024-02-03 09:54 UTC
Labels: bug
