### ISSUE TITLE
关于使用flinkcdc拉取double类型数据转为了科学计数法

### ISSUE THREAD

**Issue by YUZU-wq** [ververica/flink-cdc-connectors#1227] opened 2022-05-27 08:03 UTC
当使用flink mysql cdc进行数据同步时，出现了数字转换异常，原因是较长的double转为了科学计数法的字符串。针对这个问题该如何通过配置来解决。

**Comment by yanghuaiGit** [comment] 2022-06-06 02:40
有测试数据吗 我这边试了都是double类型的 基于master分支验证的

**Comment by PatrickRen** [comment] 2024-02-28 15:30
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed as not planned by PatrickRen** 2024-02-28 15:30 UTC
