### ISSUE TITLE
flink-cdc2.2.1 同步任务启动时提示io.debezium.DebeziumException: User does not have the 'LOCK TABLES' privilege required 报错

### ISSUE THREAD

**Issue by HermzaDawn** [ververica/flink-cdc-connectors#1242] opened 2022-06-02 02:19 UTC
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/104486083/171534554-62f5b4d4-a1f1-45f2-93e2-043794529e23.png)
即使在已经开启数据库全局权限的情况下，启动flink2.2.1任务有时会产生无lock table权限的问题导致job启动失败

**Describe alternatives you've considered**
既然2.2.1已经支持无锁读取，为什么还会产生需要获取lock table权限的错误，是否需要满足一定条件才能开启无锁读取？

**Comment by nayoaixgnat** [comment] 2022-07-01 09:28
i use datastream cdc 2.0.0 meet the same problem，
org.apache.kafka.connect.errors.ConnectException: An exception occurred in the change event producer. This connector will be stopped.
	at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:42)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:127)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.debezium.DebeziumException: io.debezium.DebeziumException: User does not have the 'LOCK TABLES' privilege required to obtain a consistent snapshot by preventing concurrent writes to tables.
	at io.debezium.pipeline.source.AbstractSnapshotChangeEventSource.execute(AbstractSnapshotChangeEventSource.java:82)
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:110)
	... 5 more
Caused by: io.debezium.DebeziumException: User does not have the 'LOCK TABLES' privilege required to obtain a consistent snapshot by preventing concurrent writes to tables.
	at io.debezium.connector.mysql.MySqlSnapshotChangeEventSource.tableLock(MySqlSnapshotChangeEventSource.java:531)
	at io.debezium.connector.mysql.MySqlSnapshotChangeEventSource.readTableStructure(MySqlSnapshotChangeEventSource.java:310)
	at io.debezium.relational.RelationalSnapshotChangeEventSource.doExecute(RelationalSnapshotChangeEventSource.java:122)
	at io.debezium.pipeline.source.AbstractSnapshotChangeEventSource.execute(AbstractSnapshotChangeEventSource.java:71)
	... 6 more

**Comment by nayoaixgnat** [comment] 2022-07-01 12:17
If 1 CDC task  is reading a table another cdc task  to read the same DB other table  this problem will occur

**Comment by PatrickRen** [comment] 2024-02-28 15:29
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:29 UTC
Labels: enhancement
