### ISSUE TITLE
[Bug] table column name is "rowid", oceanbase-cdc read null

### ISSUE THREAD

**Issue by zane-rl** [ververica/flink-cdc-connectors#2556] opened 2023-10-17 02:43 UTC
### Search before asking

- [X] I searched in the [issues](https://github.com/ververica/flink-cdc-connectors/issues) and found nothing similar.

### Flink version

flink V1.15.3

### Flink CDC version

flink-connector-oceanbase-cdc  V2.4.1

### Database and its version

oceanbase-ce:4.1.0.0

### Minimal reproduce step

1、create table products and insert datas:
```
CREATE TABLE products (
  rowid INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(512)
);
ALTER TABLE products AUTO_INCREMENT = 101;
INSERT INTO products
VALUES (default,"scooter","Small 2-wheel scooter"),
       (default,"car battery","12V car battery"),
       (default,"12-pack drill bits","12-pack of drill bits with sizes ranging from #40 to #3"),
       (default,"hammer","12oz carpenter's hammer"),
       (default,"hammer","14oz carpenter's hammer"),
       (default,"hammer","16oz carpenter's hammer"),
       (default,"rocks","box of assorted rocks"),
       (default,"jacket","water resistent black wind breaker"),
       (default,"spare tire","24 inch spare tire");
```

2、create java file:
```
public class OceanBaseCdcConnector {

    public static void main(String[] args) {

        StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
        env.enableCheckpointing(1000, CheckpointingMode.EXACTLY_ONCE);
        //env.getConfig()
        //env.getCheckpointConfig().setCheckpointStorage("file:///d:/checkpoint");
        env.getCheckpointConfig().setCheckpointStorage("file:///Users/boleyn/checkpoint");

        StreamTableEnvironment tenv = StreamTableEnvironment.create(env);
        //tenv.getConfig().getConfiguration().setString("table.exec.sink.not-null-enforcer", "DROP");

        tenv.executeSql("CREATE TABLE products (\n" +
                "    rowid INT,\n" +
                "    name STRING,\n" +
                "    description STRING,\n" +
                "    PRIMARY KEY (rowid) NOT ENFORCED\n" +
                "  ) WITH (\n" +
                "    'connector' = 'oceanbase-cdc',\n" +
                "    'scan.startup.mode' = 'initial',\n" +
                "    'username' = 'root@test',\n" +
                "    'password' = '123456',\n" +
                "    'tenant-name' = 'test',\n" +
                "    'database-name' = '^c4c197af-2d49-4c6e-9eae-c197e361b743$',\n" +
                "    'table-name' = '^products',\n" +
                "    'hostname' = '43.137.38.207',\n" +
                "    'port' = '2881',\n" +
                "    'rootserver-list' = '127.0.0.1:2882:2881',\n" +
                "    'logproxy.host' = '43.137.38.207',\n" +
                "    'logproxy.port' = '2983',\n" +
                "    'working-mode' = 'memory'\n" +
                " )");

        tenv.executeSql("select * from products").print();
    }
}
```

### What did you expect to see?

print result

### What did you see instead?

```
Source: products[1] -> ConstraintEnforcer[2] -> Sink: Collect table sink (1/1)#0] ERROR c.v.c.c.o.s.OceanBaseRichSourceFunction - [284] - Deserialize snapshot record failed 
org.apache.flink.streaming.runtime.tasks.ExceptionInChainedOperatorException: Could not forward element to next operator

Caused by: org.apache.flink.table.api.TableException: Column 'rowid' is NOT NULL, however, a null value is being written into it.
```

### Anything else?

rowid field name rename to id or other name is ok

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zane-rl** [comment] 2023-10-17 03:19
oblogproxy-ce-for-4x-1.1.3-20230815201457.tar.gz

**Comment by whhe** [comment] 2023-10-17 09:22
The jdbc driver got uppercase column name 'ROWID' from observer, which is different with column name in flink SQL. The root cause is that there is a compatibility bug in OceanBase, witch will be fixed in next BP release.

**Closed** 2024-02-05 03:03 UTC
Labels: bug
