### ISSUE TITLE
DDL Parsing Error When using multiple quotes

### ISSUE THREAD

**Issue by leesenlen** [ververica/flink-cdc-connectors#1506] opened 2022-08-24 10:25 UTC
**Describe the bug(Please use English)**

MySQLCDC, DataStreamAPI

DDL Parsing Error When using multiple quotes ( **_'....'_** ) after  _DEFAULT VALUE_ 

Expected **0** as default value , but get  string **_0'COLLATE'utf8_general_ci_**

>DDL SQL:
 create table test {
             ...
             is_delete TINYINT DEFAULT VALUE '**_0' COLLATE 'utf8_general_ci_**'
             ...
         }

> ExceptionTrace： 
Caused by: java.lang.NumberFormatException: For input string: "**_0'COLLATE'utf8_general_ci_**"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Short.parseShort(Short.java:118)
        at java.lang.Short.valueOf(Short.java:174)
        at java.lang.Short.valueOf(Short.java:200)
        at io.debezium.jdbc.JdbcValueConverters.lambda$convertSmallInt$40(JdbcValueConverters.java:865)
        at io.debezium.jdbc.JdbcValueConverters.convertValue(JdbcValueConverters.java:1288)
        at io.debezium.jdbc.JdbcValueConverters.convertSmallInt(JdbcValueConverters.java:853)
        at io.debezium.jdbc.JdbcValueConverters.lambda$converter$4(JdbcValueConverters.java:293)
        at io.debezium.connector.mysql.MySqlDefaultValueConverter.setColumnDefaultValue(MySqlDefaultValueConverter.java:405)
        at io.debezium.connector.mysql.antlr.listener.CreateTableParserListener.convertDefaultValueToSchemaType(CreateTableParserListener.java:147)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at io.debezium.connector.mysql.antlr.listener.CreateTableParserListener.lambda$exitColumnCreateTable$1(CreateTableParserListener.java:75)
        at io.debezium.connector.mysql.antlr.MySqlAntlrDdlParser.runIfNotNull(MySqlAntlrDdlParser.java:357)
        at io.debezium.connector.mysql.antlr.listener.CreateTableParserListener.exitColumnCreateTable(CreateTableParserListener.java:55)
        at io.debezium.ddl.parser.mysql.generated.MySqlParser$ColumnCreateTableContext.exitRule(MySqlParser.java:4733)
        at io.debezium.antlr.ProxyParseTreeListenerUtil.delegateExitRule(ProxyParseTreeListenerUtil.java:64)
        at io.debezium.connector.mysql.antlr.listener.MySqlAntlrDdlParserListener.exitEveryRule(MySqlAntlrDdlParserListener.java:106)
        at com.ververica.cdc.connectors.shaded.org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:48)
        at com.ververica.cdc.connectors.shaded.org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:30)
        at com.ververica.cdc.connectors.shaded.org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at com.ververica.cdc.connectors.shaded.org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at com.ververica.cdc.connectors.shaded.org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at com.ververica.cdc.connectors.shaded.org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at io.debezium.antlr.AntlrDdlParser.parse(AntlrDdlParser.java:87)
        at io.debezium.connector.mysql.MySqlDatabaseSchema.parseDdl(MySqlDatabaseSchema.java:213)
        at io.debezium.connector.mysql.MySqlDatabaseSchema.parseStreamingDdl(MySqlDatabaseSchema.java:200)
        at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleQueryEvent(MySqlStreamingChangeEventSource.java:574)
        at io.debezium.connector.mysql.MySqlStreamingChangeEventSource.handleEvent(MySqlStreamingChangeEventSource.java:352)

**Environment :**
 - Flink version :  1.14
 - Flink CDC version: 2.2
 - Database and version: MySQL 5.7

**To Reproduce**
1. The test data :
2. The test code :
3. The error :

**Additional Description**

**Comment by leonardBang** [comment] 2022-08-25 04:31
@ruanhang1993 Would you like to take a look this issue?

**Comment by ruanhang1993** [comment] 2022-08-26 01:42
OK, I will take a look at this problem.

**Comment by ruanhang1993** [comment] 2022-08-26 03:56
@leesenlen I have written a test about this, but this error does not occur. Could you help to check whether there is something wrong in my test.
I used the branch release-2.2 and the sql and test as following.
SQL:
```sql
CREATE TABLE self_customers1 (
  id INTEGER NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL DEFAULT 'flink',
  is_delete TINYINT DEFAULT '0' COLLATE 'utf8_general_ci'
);


INSERT INTO self_customers1
VALUES (101,"user_1",1),
       (102,"user_2",0);
```
test in `MySqlSourceITCase`:
```java
    @Test
    public void testDefaultColumn1() throws Exception {
        customDatabase.createAndInitialize();
        System.out.println(MYSQL_CONTAINER.getDatabasePort() + "/" + customDatabase.getDatabaseName());
        StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
        env.setParallelism(4);
        env.enableCheckpointing(200L);
        env.setRestartStrategy(RestartStrategies.fixedDelayRestart(1, 0));

        // The sleeping source will sleep awhile after send per record
        MySqlSource<RowData> sleepingSource = buildSource();
        DataStreamSource<RowData> source =
                env.fromSource(sleepingSource, WatermarkStrategy.noWatermarks(), "selfSource");
        TypeSerializer<RowData> serializer =
                source.getTransformation().getOutputType().createSerializer(env.getConfig());
        String accumulatorName = "dataStreamCollect_" + UUID.randomUUID();
        CollectSinkOperatorFactory<RowData> factory =
                new CollectSinkOperatorFactory(serializer, accumulatorName);
        CollectSinkOperator<RowData> operator = (CollectSinkOperator) factory.getOperator();
        CollectResultIterator<RowData> iterator =
                new CollectResultIterator(
                        operator.getOperatorIdFuture(),
                        serializer,
                        accumulatorName,
                        env.getCheckpointConfig());
        CollectStreamSink<RowData> sink = new CollectStreamSink(source, factory);
        sink.name("Data stream collect sink");
        env.addOperator(sink.getTransformation());
        JobClient jobClient = env.executeAsync("snapshotSplitTest");
        iterator.setJobClient(jobClient);
        while (iterator.hasNext()) {
            int i = 11;
        }
    }
```
After the test running, I alter the table use the sql.
```sql
alter table self_customers1 add column `state`  smallint(1) unsigned DEFAULT 0 COMMENT '禁用';
```
But my job does not throw an exception.

Please correct my mistake, Thanks~

**Comment by leesenlen** [comment] 2022-08-26 06:21
@ruanhang1993  

Try the ddl below

```
alter table self_customers1 add column `state_new`  smallint(1) DEFAULT '0' COLLATE 'utf8_general_ci' COMMENT '禁用';
```

This is happend when alter table with `COLLATE` after `DEFAULT` value with quotes(`'`)

**Comment by ruanhang1993** [comment] 2022-08-29 03:07
<img width="1723" alt="截屏2022-08-29 上午11 04 33" src="https://user-images.githubusercontent.com/17610579/187115047-5b328c0f-2e1a-4d02-ba99-18a0b3fed89a.png">
The default value is wrong when parsing the alter sql. Maybe it is a bug in the debezium. I will find a way to fix it.

**Comment by leesenlen** [comment] 2022-09-02 05:57
@ruanhang1993  Thanks for helping.
Is there a possible timeline for this problem? 
It often encounters in our situation. We are looking for a solution.

**Comment by leonardBang** [comment] 2022-09-02 10:03
fixed in https://github.com/ververica/flink-cdc-connectors/pull/1522

**Comment by ruanhang1993** [comment] 2022-09-05 02:03
@leonardBang This is another problem that has not be fixed. We should reopen it.

**Comment by ruanhang1993** [comment] 2022-09-06 11:17
> @ruanhang1993 Thanks for helping. Is there a possible timeline for this problem? It often encounters in our situation. We are looking for a solution.

Maybe you could cherry pick this PR as a quick fix version.

**Comment by ruanhang1993** [comment] 2022-09-19 09:52
@lijunkai I am not sure about the reason for your problem. But it seems that the error is not caused by this PR.  This PR only changes the behavior when converting the default string values.

**Closed** 2022-09-21 15:46 UTC
Labels: bug
