### ISSUE TITLE
[bug][tidb-connector]cdc event capture will stop after serial days running.

### ISSUE THREAD

**Issue by leozlliang** [ververica/flink-cdc-connectors#1672] opened 2022-10-28 10:13 UTC
cdc event capture will stop after serial days running.

Example: subscribe a table with 5 regions, after 2 days, region 1,2 abnormal, region 3,4,5 still normal.

when use <Arthas> to check threads, found too many grpc-exector running.

<img width="514" alt="企业微信截图_c25af964-c2f3-4293-9f06-076a84e26f7c" src="https://user-images.githubusercontent.com/9716704/198563507-25745232-08f9-4131-9cb4-e121a1bf6148.png">

**Comment by Mondler-Agmento** [comment] 2023-11-08 06:56
i've found your commit at 2022.11.2 ,which about event error handle.Is this also your resolution to this thread issue?
I met this issue too,now i just work around through throw exception to close the task.

**Comment by PatrickRen** [comment] 2024-02-28 15:02
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:02 UTC
Labels: bug
