### ISSUE TITLE
增加配置，不使用的字段更新时，不触发cdc计算

### ISSUE THREAD

**Issue by shizhengchao** [ververica/flink-cdc-connectors#40] opened 2020-09-19 16:17 UTC
源表中有多个字段，但往往只需要其中几个字段，在更新其它字段时，现在cdc也触发了计算，但一般情况下是不需要重复计算的。
增加配置决定是否触发计算

**Comment by PatrickRen** [comment] 2024-02-28 15:38
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:38 UTC
Labels: enhancement
