### ISSUE TITLE
inaccuracy type mapping for bit(1) in mysql doc

### ISSUE THREAD

**Issue by luoyuxia** [ververica/flink-cdc-connectors#751] opened 2021-12-24 07:40 UTC
Althogh the mysql doc has said when bit(1) should be mapped to boolean in Flink.
But it also contains anther mapping rule "BIT(n) - > BINARY(⌈n/8⌉).
And when user try to map BIT(1) to BINARY(1), it will throw exception.
![image](https://user-images.githubusercontent.com/20389154/147330373-add20448-a285-4d60-a777-399cf0e8c40f.png)
So, we need to fix the doc to avoid misleading.

**Comment by PatrickRen** [comment] 2024-02-28 15:32
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:32 UTC
Labels: bug
