### ISSUE TITLE
shuffle the table splits capture order

### ISSUE THREAD

**Issue by zhjwpku** [ververica/flink-cdc-connectors#897] opened 2022-03-01 03:52 UTC
**Is your feature request related to a problem? Please describe.**

In MySqlSnapshotSplitAssigner, the `getNext` will finish the remaining splits of the current table before split the next table,
this might limit the sink side speed if the stream job hope to `keyby` the table identifer.

**Describe the solution you'd like**

Add an option to enable shuffle the table splits capture order.

If we have 4 tables, each has 3 splits, 

In normal case, the capture order is:

t1.1, t1.2, t1.3, t2.1, t2.2, t2.3, t3.1, t3.2, t3.3

after the shuffle enabled, the capture order will be:

t1.1, t2.1, t3.1, t1.2, t2.2, t3.2, t1.3, t2.3, t3.3

**Comment by fuyun2024** [comment] 2022-03-05 15:01
I'm very interested in this task. Can you assign it to me

**Comment by zhjwpku** [comment] 2022-03-07 03:06
@leonardBang pls help to assign this issue to @fuyun2024 , I can help to review when it's done.

**Comment by leonardBang** [comment] 2022-03-07 03:54
Nice idea @fuyun2024 @zhjwpku , I also notice one issue that we should split the chunks asynchronously but we're splitting blocking now, would you like to improve this too?

**Comment by fuyun2024** [comment] 2022-03-07 11:35
Yes, I also noticed this problem. Next, I submitted two PR to solve these two problems. @leonardBang @zhjwpku I'm very glad that the two teachers can help me review the code.

**Comment by leonardBang** [comment] 2022-03-07 11:41
Thanks @fuyun2024 for taking this, could you create an issue for the later issue and then open the PR?

**Comment by fuyun2024** [comment] 2022-03-08 01:47
OK, I created a new issue #915

**Comment by PatrickRen** [comment] 2024-02-28 15:09
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:09 UTC
Labels: enhancement
