### ISSUE TITLE
once db contains one no primary key ,this job ,no error  and go on .

### ISSUE THREAD

**Issue by deepthinkin** [ververica/flink-cdc-connectors#1359] opened 2022-07-11 00:44 UTC
**Describe the bug(Please use English)**
 

**Environment :**
 - Flink version :  1.13.5
 - Flink CDC version:  2.2.0
 - Database and version: mysql 5.7.38

**To Reproduce**
1. Thes test data :
2. The test code ：
MySqlSource mysqlSource = MySqlSource.builder()
.hostname("192.168.XX.XX")
.port(3306)
.username("root")
.password("root")

         .databaseList("db01")
         .tablList(".*")
         .startupOptions(StartupOptions.initial())
         .deserializer(new JsonDebeziumDeserializationSchema())           
         .build();
4. The error :
 no throws  error , but get data Incomplete。for example , one db contains 3 tables , first table has primary key , sucessfully get data, secondly table no primary key , this code  dont throws error and job dont go on,  The final result is, only get  first table data . so ...

**Additional Description**

**Comment by PatrickRen** [comment] 2024-02-28 15:29
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:29 UTC
Labels: bug
