### ISSUE TITLE
[common] Shade kafka related denpencies to avoid conflicts

### ISSUE THREAD

**Issue by NobleYd** [ververica/flink-cdc-connectors#223] opened 2021-06-24 10:57 UTC
当前我遇到的问题是flink-connector-mysql-cdc这个包和我业务中kafka-clients的包冲突了。我仔细看了下这个包，目前这个包本身是shade了相关依赖的，但没做relocation。同时这个包的依赖看起来还很多，这意味着和具体的业务依赖冲突的可能性很大会。
推荐可以做个relocation然后再shade并重新发布到maven仓库中。如果觉得全部relocation太复杂，也应该谨慎挑选部分很常用的包进行relocation，比如kafka等。

**Comment by PatrickRen** [comment] 2024-02-28 15:13
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:13 UTC
Labels: enhancement, task
