### ISSUE TITLE
flink cdc postgresql always be canceling and kill the task manager in 180 seconds

### ISSUE THREAD

**Issue by yaoyi** [ververica/flink-cdc-connectors#1603] opened 2022-10-08 16:45 UTC
**Describe the bug(Please use English)**
we use flink cdc to transfer data from postgresql to apache doris, it works fine, but once we restart apache doris, the flink job gets stuck in CANCELLING state, never gets canceled, and after 180+ seconds, the task manager watchdog kills the task manager. 

**Environment :**
 - Flink version :  1.14.5
 - Flink CDC version: 2.2.1
 - Database and version: postgresql 11

**To Reproduce**
1. The test data : 
2. The test code :
3. The error :

**Additional Description**

**Comment by PatrickRen** [comment] 2024-02-28 15:28
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:28 UTC
Labels: bug
