### ISSUE TITLE
[task] Add metric supports for tidb-cdc connector

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#974] opened 2022-03-22 04:13 UTC
We introduce TiDB CDC Connector in #243 , we can support metrics for this connector

**Comment by PatrickRen** [comment] 2024-02-28 15:31
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:31 UTC
Labels: enhancement
