### ISSUE TITLE
will flink-cdc support to capture transactional information?

### ISSUE THREAD

**Issue by luguanxing** [ververica/flink-cdc-connectors#1600] opened 2022-10-07 07:16 UTC
When i update tables in one transaction, it seems that changelogs were captured and handled separately by flink-cdc, which means their connection to each other is lost.  So is there any way to keep the relevance between these changelogs? 
(e.g. When using flink-cdc summing total value from accounts, if one account's cash is transferred to another account,  then the total value may decrease at first and then increase back)

**Comment by PatrickRen** [comment] 2024-02-28 15:28
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:28 UTC
Labels: enhancement
