### ISSUE TITLE
Oracle supports xStream

### ISSUE THREAD

**Issue by luobo-te** [ververica/flink-cdc-connectors#1221] opened 2022-05-25 12:06 UTC
does oracle-cdc support xStream?  Debezium already supports
oracle-cdc支持oracle xstream采集吗 ？底层debezinum是支持的

**Comment by hehetown** [comment] 2022-05-26 02:31
Oracle-cdc supports Oracle XStream,You could write it like this: 'debezium.database.connection.adapter' = 'xstream',
    'debezium.database.out.server.name' = 'DBZXOUT_DEMO',

**Comment by gong** [comment] 2024-02-03 05:59
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you! 
cc @GOODBOY008

**Comment by PatrickRen** [comment] 2024-02-28 15:30
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:30 UTC
Labels: bug
