### ISSUE TITLE
Any plan for Oracle 10g? and When support for Flink 1.5+

### ISSUE THREAD

**Issue by moly52** [ververica/flink-cdc-connectors#1596] opened 2022-09-30 01:53 UTC
there is some db is oracle10g，and I want write data to oracle with flink-connector-jdbc.

**Comment by gong** [comment] 2024-02-03 05:31
Closing this issue as it is no longer valid or requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you! cc @GOODBOY008

**Comment by PatrickRen** [comment] 2024-02-28 15:28
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed as not planned by PatrickRen** 2024-02-28 15:28 UTC
Labels: enhancement
