### ISSUE TITLE
[feature] Support capture all MySQL tables of MySQL Database to TiDB

### ISSUE THREAD

**Issue by melin** [ververica/flink-cdc-connectors#507] opened 2021-10-18 04:01 UTC
能够支持mysql 按照数据库同步到tidb，支持mysql分库分表，同步到tidb一张表中。tidb 可以作为一个实时数仓比较理想选择，支持ddl sql同步变更，这是hudi，delta，iceberg 目前无法实现的。
现在用otter 全量同步公司所有数据库到tidb，otter 现在已经没有人维护了。

**Comment by jinghewang** [comment] 2021-10-22 01:02
为个功能是有必要的，不过我关注的是  mysql to  mysql/ hudi ，希望尽快加入功能。

**Comment by PatrickRen** [comment] 2024-02-28 15:11
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:11 UTC
Labels: enhancement
