### ISSUE TITLE
重启时Found existing offset，为啥不从offset开始读，还要做snapshot

### ISSUE THREAD

**Issue by zmr518** [ververica/flink-cdc-connectors#274] opened 2021-07-27 12:15 UTC
flink 1.11.2 + cdc 1.1.0 + mysql 5.7.x
snapshot.mode = when_needed
```
2021-07-27 17:44:38,783 INFO  [73] io.debezium.connector.mysql.MySqlConnectorTask               - Found existing offset: {ts_sec=1627373464, file=mysql-bin.279007, pos=80023, gtids=8ea1aec5-f832-11e8-953d-fa163eabed87:1-104128132, row=1, server_id=1, event=3}
2021-07-27 17:44:38,792 INFO  [73] io.debezium.relational.history.DatabaseHistoryMetrics        - Started database history recovery
2021-07-27 17:44:40,622 INFO  [73] io.debezium.relational.history.DatabaseHistoryMetrics        - Finished database history recovery of 3 change(s) in 1830 ms
2021-07-27 17:44:40,669 INFO  [73] io.debezium.connector.mysql.MySqlConnectorTask               - MySQL current GTID set 8ea1aec5-f832-11e8-953d-fa163eabed87:1-104146700 does contain the GTID set required by the connector 8ea1aec5-f832-11e8-953d-fa163eabed87:1-104128132
2021-07-27 17:44:40,721 INFO  [73] io.debezium.connector.mysql.MySqlConnectorTask               - GTIDs known by the server but not processed yet 8ea1aec5-f832-11e8-953d-fa163eabed87:104128133-104146700, for replication are available only 8ea1aec5-f832-11e8-953d-fa163eabed87:104133244-104146700
2021-07-27 17:44:40,722 INFO  [73] io.debezium.connector.mysql.MySqlConnectorTask               - Some of the GTIDs needed to replicate have been already purged
2021-07-27 17:44:40,778 INFO  [73] io.debezium.util.Threads                                     - Requested thread factory for connector MySqlConnector, id = mysql_binlog_source named = binlog-client
2021-07-27 17:44:40,825 INFO  [73] io.debezium.util.Threads                                     - Requested thread factory for connector MySqlConnector, id = mysql_binlog_source named = snapshot
2021-07-27 17:44:40,826 INFO  [73] io.debezium.util.Threads                                     - Creating thread debezium-mysqlconnector-mysql_binlog_source-snapshot
2021-07-27 17:44:40,828 INFO  [77] io.debezium.connector.mysql.SnapshotReader                   - Starting snapshot for jdbc:
```

**Comment by zmr518** [comment] 2021-07-27 12:23
snapshot mode设置为inital时，报错提示：Reconfigure the connector to use a snapshot when needed.
```
2021-07-27 20:20:51,862 INFO  [73] io.debezium.connector.mysql.MySqlConnectorTask               - Found existing offset: {ts_sec=1627384745, file=mysql-bin.279047, pos=1480250, gtids=8ea1aec5-f832-11e8-953d-fa163eabed87:1-104163053, row=1, server_id=1, event=15}
2021-07-27 20:20:51,872 INFO  [73] io.debezium.relational.history.DatabaseHistoryMetrics        - Started database history recovery
2021-07-27 20:20:53,842 INFO  [73] io.debezium.relational.history.DatabaseHistoryMetrics        - Finished database history recovery of 9 change(s) in 1970 ms
2021-07-27 20:20:53,931 INFO  [73] io.debezium.connector.mysql.MySqlConnectorTask               - MySQL current GTID set 8ea1aec5-f832-11e8-953d-fa163eabed87:1-104173893 does contain the GTID set required by the connector 8ea1aec5-f832-11e8-953d-fa163eabed87:1-104163053
2021-07-27 20:20:53,959 INFO  [73] io.debezium.connector.mysql.MySqlConnectorTask               - GTIDs known by the server but not processed yet 8ea1aec5-f832-11e8-953d-fa163eabed87:104163054-104173893, for replication are available only 8ea1aec5-f832-11e8-953d-fa163eabed87:104167358-104173893
2021-07-27 20:20:53,959 INFO  [73] io.debezium.connector.mysql.MySqlConnectorTask               - Some of the GTIDs needed to replicate have been already purged
2021-07-27 20:20:53,960 INFO  [73] io.debezium.connector.common.BaseSourceTask                  - Stopping down connector
2021-07-27 20:20:53,960 INFO  [73] io.debezium.connector.mysql.MySqlConnectorTask               - Stopping MySQL connector task
2021-07-27 20:20:53,962 ERROR [73] com.alibaba.ververica.cdc.debezium.DebeziumSourceFunction    - Reporting error:
org.apache.kafka.connect.errors.ConnectException: The connector is trying to read binlog starting at GTIDs 8ea1aec5-f832-11e8-953d-fa163eabed87:1-104163053 and binlog file 'mysql-bin.279047', pos=1480250, skipping 15 events plus 1 rows, but this is no longer available on the server. Reconfigure the connector to use a snapshot when needed.
	at io.debezium.connector.mysql.MySqlConnectorTask.start(MySqlConnectorTask.java:133) ~[product-flink-cdc-task-0.1.0-SNAPSHOT.jar:?]
	at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:101) ~[product-flink-cdc-task-0.1.0-SNAPSHOT.jar:?]
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:758) [product-flink-cdc-task-0.1.0-SNAPSHOT.jar:?]
	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:170) [product-flink-cdc-task-0.1.0-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```

**Comment by LiangXiam** [comment] 2021-07-30 07:00
我的理解做snapshot是减少重复操作。如Found existing offset，假设现在offset是3000，如果没有snapshot，则flink会从offset 0开始一直按照binlog重复mysql的操作到offset 3000的位置。有了snapshot，将重复到 offset 3000的位置时表的状态作一个 snapshot到flink状态中，这样重启后直接读取这个状态，并从这个offset 3000这个位置继续重复mysql的操作即可。

**Comment by PatrickRen** [comment] 2024-02-28 15:33
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:33 UTC
Labels: discussion
