### ISSUE TITLE
flink mysql cdc connector ,checkpoint恢复，数据重复抽取

### ISSUE THREAD

**Issue by ctysf** [ververica/flink-cdc-connectors#1654] opened 2022-10-25 11:24 UTC
flink mysql cdc connector,当作业出现checkpoint恢复的时候，原有的cdc连接保持没有清除，然后会新增加一个连接来抽取cdc数据。
从source的subtask观察得到，每ck重启一次，就会多一个subtask往下游发送数据，数据库的l连接也会多一条。有没有什么方法解决。

**Comment by PatrickRen** [comment] 2024-02-28 15:03
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:03 UTC
Labels: bug
