### ISSUE TITLE
com.ververica.cdc.debezium.DebeziumDeserializationSchema add open default method

### ISSUE THREAD

**Issue by MyLanPangzi** [ververica/flink-cdc-connectors#1078] opened 2022-04-17 03:20 UTC
**Is your feature request related to a problem? Please describe.**
Becuase DebeziumDeserializationSchema have not default open. we need put initialize in deserialize like this.
This manner cannot gracefully initialize some field.

```java
    @Override
    public void deserialize(SourceRecord record, Collector<String> out) throws Exception {
        if (jsonConverter == null) {
            initializeJsonConverter();
        }
        byte[] bytes =
                jsonConverter.fromConnectData(record.topic(), record.valueSchema(), record.value());
        out.collect(new String(bytes));
    }

```
Can we add defalut open method like this?

    void open() throws Exception {}

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by PatrickRen** [comment] 2024-02-28 15:09
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:09 UTC
Labels: enhancement
