### ISSUE TITLE
mysql-cdc在使用initial模式时，会反复出现尝试连接binlog的情况，使用latest-offset模式则不会

### ISSUE THREAD

**Issue by hnjincan** [ververica/flink-cdc-connectors#318] opened 2021-08-13 09:39 UTC
在使用initial模式时，控制台无限打日志，日志内容为监听binlog相关的内容，但是切换到latest-offset模式，日志监听只打一次日志

**Comment by hnjincan** [comment] 2021-08-13 09:43
![企业微信截图_20210813174054](https://user-images.githubusercontent.com/39942725/129338347-9307362e-37bd-4450-b215-b0cad13b44c9.png)
![企业微信截图_20210813174251](https://user-images.githubusercontent.com/39942725/129338337-404a2cf0-f66e-49a1-a8a5-f01b91776a41.png)

**Comment by hnjincan** [comment] 2021-08-13 09:44
上面是latest-offset，下面是initial模式，initial模式，瞬间就把日志给打满了

**Comment by leonardBang** [comment] 2021-08-13 13:01
不是反复出现尝试连接binlog ，而是每个chunk 都会读 对应的binlog，是预期行为，我看下日志如何优化

**Comment by PatrickRen** [comment] 2024-02-28 15:40
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:40 UTC
Labels: task
