### ISSUE TITLE
Error while insert data to es

### ISSUE THREAD

**Issue by Mediterranean90** [ververica/flink-cdc-connectors#1412] opened 2022-07-26 12:40 UTC
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :   flink-1.13.6
 - Flink CDC version:  flink-sql-connector-elasticsearch7_2.11-1.13.6.jar;flink-sql-connector-mysql-cdc-2.1.0.jar;flink-sql-connector-postgres-cdc-2.1.0.jar
 - Database and version: mysql-8.0.25

**To Reproduce**
When I insert data to elasticsearch, an error occurs:
Flink SQL> INSERT INTO enriched_orders
>  SELECT o.*, p.name, p.description, s.shipment_id, s.origin, s.destination, s.is_arrived
>  FROM orders AS o
>  LEFT JOIN products AS p ON o.product_id = p.id
>  LEFT JOIN shipments AS s ON o.order_id = s.order_id;
[INFO] Submitting SQL update statement to the cluster...
[ERROR] Could not execute SQL statement. Reason:
java.io.StreamCorruptedException: unexpected block data

It's ok when I use mysql 5.7. I don't how to fix it .

**Additional Description**

**Comment by PaddlePaddle-Gardener** [comment] 2022-07-26 13:05
https://github.com/ververica/flink-cdc-connectors/discussions/644
may be helpful

**Comment by PatrickRen** [comment] 2024-02-28 15:36
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:36 UTC
Labels: bug
