### ISSUE TITLE
HeartBeat timeout when connecting to the table using JDBC

### ISSUE THREAD

**Issue by fsk119** [ververica/flink-cdc-connectors#397] opened 2021-09-06 04:03 UTC
Here we get some feedbacks from the Dingtalk. We just create one issue to track the problem. We need more details to know why this problem happens. 

![1630399788344-f983d5ef-ee13-49e5-85d3-e4ec5e4ccb9b](https://user-images.githubusercontent.com/33114724/132159044-c99fd4b0-f376-41ab-95ad-45061f3bac19.png)

**Comment by PatrickRen** [comment] 2024-02-28 15:13
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:13 UTC
Labels: bug
