### ISSUE TITLE
TiDB CDC demo not work

### ISSUE THREAD

**Issue by wayne163** [ververica/flink-cdc-connectors#1581] opened 2022-09-26 07:56 UTC
Hi,

I followed the [DEMO: TiDB CDC to Elasticsearch](https://ververica.github.io/flink-cdc-connectors/release-2.2/content/quickstart/tidb-tutorial.html), start tidb, tikv, tipd, es, kibana with docker compose. and start flink cluster and sql-client with application mode by docker compose. 
I have created table orders and products in tidb, and create 3 tables in flink successfully as demo says, but cdc pipeline seems not run. There is no data and index in es.
And then I tried the select command as below which not works yet. No data selected. It seems flink sql occured error when selecting data from tidb.

![Screenshot from 2022-09-26 15-46-22](https://user-images.githubusercontent.com/6734452/192221511-00f62bf5-dfb9-4067-bb16-3061d076c64b.png)

These are create table command in flink
```
CREATE TABLE products (
    id INT,
    name STRING,
    description STRING,
    PRIMARY KEY (id) NOT ENFORCED
  ) WITH (
    'connector' = 'tidb-cdc',
    'tikv.grpc.timeout_in_ms' = '20000',
    'pd-addresses' = 'xx.xx.xx.xx:2379', // this is my virtual machine ip which runs tidb and es
    'database-name' = 'mydb',
    'table-name' = 'products'
  );


CREATE TABLE orders (
   order_id INT,
   order_date TIMESTAMP(3),
   customer_name STRING,
   price DECIMAL(10, 5),
   product_id INT,
   order_status BOOLEAN,
   PRIMARY KEY (order_id) NOT ENFORCED
 ) WITH (
    'connector' = 'tidb-cdc',
    'tikv.grpc.timeout_in_ms' = '20000',
    'pd-addresses' = 'xx.xx.xx.xx:2379', // this is my virtual machine ip which runs tidb and es
    'database-name' = 'mydb',
    'table-name' = 'orders'
);

CREATE TABLE enriched_orders (
   order_id INT,
   order_date DATE,
   customer_name STRING,
   order_status BOOLEAN,
   product_name STRING,
   product_description STRING,
   PRIMARY KEY (order_id) NOT ENFORCED
 ) WITH (
     'connector' = 'elasticsearch-7',
     'hosts' = 'http://xx.xx.xx.xx:9200', this is my virtual machine ip which runs tidb and es
     'index' = 'enriched_orders_1'
 );
```

TiDB: `v5.3.1`
Flink: `1.14.5-scala_2.12`

This flink docker compose yml
```
version: "2.2"
services:
  jobmanager:
    image: flink:1.14.5-scala_2.12
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - /home/weiyunshen/workspace/flink/flink-sql-connector-tidb-cdc-2.2.0.jar:/opt/flink/lib/flink-sql-connector-tidb-cdc-2.2.0.jar
      - /home/weiyunshen/workspace/flink/flink-sql-connector-elasticsearch7_2.11-1.13.2.jar:/opt/flink/lib/flink-sql-connector-elasticsearch7_2.11-1.13.2.jar
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager        

  taskmanager:
    image: flink:1.14.5-scala_2.12
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    volumes:
      - /home/weiyunshen/workspace/flink/flink-sql-connector-tidb-cdc-2.2.0.jar:/opt/flink/lib/flink-sql-connector-tidb-cdc-2.2.0.jar
      - /home/weiyunshen/workspace/flink/flink-sql-connector-elasticsearch7_2.11-1.13.2.jar:/opt/flink/lib/flink-sql-connector-elasticsearch7_2.11-1.13.2.jar
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2        
  sql-client:
    image: flink:1.14.5-scala_2.12
    command: sleep 3000
    volumes:
      - /home/weiyunshen/workspace/flink/flink-sql-connector-tidb-cdc-2.2.0.jar:/opt/flink/lib/flink-sql-connector-tidb-cdc-2.2.0.jar
      - /home/weiyunshen/workspace/flink/flink-sql-connector-elasticsearch7_2.11-1.13.2.jar:/opt/flink/lib/flink-sql-connector-elasticsearch7_2.11-1.13.2.jar
    depends_on:
      - jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
```

These are data in tidb
![Screenshot from 2022-09-26 15-55-25](https://user-images.githubusercontent.com/6734452/192223405-6b8b662b-8f25-4517-9f0e-800d45d3fff7.png)

![Screenshot from 2022-09-26 15-55-32](https://user-images.githubusercontent.com/6734452/192223310-eb0992d7-a253-46c8-bde0-0a1340dd0383.png)

These are error logs in flink-job-manager
```
2022-09-26 08:05:41,191 INFO  org.apache.flink.runtime.taskmanager.Task                    [] - ChangelogNormalize(key=[order_id]) -> Calc(select=[order_id, order_date, customer_name, order_status]) -> NotNullEnforcer(fields=[order_id]) -> Sink: Collect table sink (1/1)#6 (a3770ce7cde2c6b23dc5514e91175cb9) switched from DEPLOYING to INITIALIZING.
2022-09-26 08:05:41,225 WARN  org.apache.flink.runtime.taskmanager.Task                    [] - Source: TableSourceScan(table=[[default_catalog, default_database, orders]], fields=[order_id, order_date, customer_name, price, product_id, order_status]) (1/1)#6 (7e5edce87ccfef801062fd4e42863f48) switched from INITIALIZING to FAILED with failure cause: org.apache.flink.streaming.runtime.tasks.StreamTaskException: Cannot load user class: com.ververica.cdc.connectors.tidb.TiKVRichParallelSourceFunction
ClassLoader info: URL ClassLoader:
    file: '/tmp/blobStore-fac9f88c-2645-4209-8c62-7f7e71ec525b/job_fa3f74024f39fed5399c91c0745afdfe/blob_p-e9435fe7360ee6d1ec55633df93ff2ad28e2e3d8-8617271fc54d13808cad56485f0fca0f' (valid JAR)
    file: '/tmp/blobStore-fac9f88c-2645-4209-8c62-7f7e71ec525b/job_fa3f74024f39fed5399c91c0745afdfe/blob_p-2644d6d3c055fdc8327bfeadfac58623ae6163f5-910a2fb064d0468e9dcaac1c52447ce1' (valid JAR)
Class not resolvable through given classloader.
	at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperatorFactory(StreamConfig.java:338)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.<init>(OperatorChain.java:155)
	at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.<init>(RegularOperatorChain.java:63)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreInternal(StreamTask.java:666)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:654)
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:958)
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:927)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:766)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:575)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: com.ververica.cdc.connectors.tidb.TiKVRichParallelSourceFunction
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClassWithoutExceptionHandling(FlinkUserCodeClassLoader.java:64)
	at org.apache.flink.util.ChildFirstClassLoader.loadClassWithoutExceptionHandling(ChildFirstClassLoader.java:74)
	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClass(FlinkUserCodeClassLoader.java:48)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$SafetyNetWrapperClassLoader.loadClass(FlinkUserCodeClassLoaders.java:172)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.flink.util.InstantiationUtil$ClassLoaderObjectInputStream.resolveClass(InstantiationUtil.java:78)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1988)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1852)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2186)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2431)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2355)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2213)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2431)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2355)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2213)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:617)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:602)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:589)
	at org.apache.flink.util.InstantiationUtil.readObjectFromConfig(InstantiationUtil.java:543)
	at org.apache.flink.streaming.api.graph.StreamConfig.getStreamOperatorFactory(StreamConfig.java:324)
	... 9 more

```

**Comment by PatrickRen** [comment] 2024-02-28 15:28
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:28 UTC
