### ISSUE TITLE
How to deal with the password in product enviroment when use mysql-cdc?

### ISSUE THREAD

**Issue by yaoboxu** [ververica/flink-cdc-connectors#125] opened 2021-03-17 08:22 UTC

**Comment by PatrickRen** [comment] 2024-02-28 15:34
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:34 UTC
Labels: discussion
