### ISSUE TITLE
Flinkcdc 增量读取oralce ，正常输出数据一段时间后 异常关闭

### ISSUE THREAD

**Issue by wdzhanghao** [ververica/flink-cdc-connectors#1459] opened 2022-08-09 05:41 UTC
flinkcdc增量读取oralce数据库
报错： java.lang.IllegalStateException: Retrieve schema history failed, the schema records for engine 08c6c43f-e529-439b-9546-d1056524d389 has been removed, this might because the debezium engine has been shutdown due to other errors.
	at com.ververica.cdc.debezium.utils.DatabaseHistoryUtil.retrieveHistory(DatabaseHistoryUtil.java:77)
	at com.ververica.cdc.debezium.internal.FlinkDatabaseSchemaHistory.configure(FlinkDatabaseSchemaHistory.java:82)
	at io.debezium.relational.HistorizedRelationalDatabaseConnectorConfig.getDatabaseHistory(HistorizedRelationalDatabaseConnectorConfig.java:105)
	at io.debezium.relational.HistorizedRelationalDatabaseSchema.<init>(HistorizedRelationalDatabaseSchema.java:39)
	at io.debezium.connector.oracle.OracleDatabaseSchema.<init>(OracleDatabaseSchema.java:35)
	at io.debezium.connector.oracle.OracleConnectorTask.start(OracleConnectorTask.java:54)
	at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:130)
	at io.debezium.connector.common.BaseSourceTask.startIfNeededAndPossible(BaseSourceTask.java:207)
	at io.debezium.connector.common.BaseSourceTask.poll(BaseSourceTask.java:148)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:788)
	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:188)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Environment :**
 - Flink version :  1.13.1
 - Flink CDC version: 2.2.1
 - Database and version: oracle 11g

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :

**Additional Description**
2022-08-07 03:31:58,515 DEBUG org.apache.flink.runtime.io.network.partition.ResourceManagerPartitionTrackerImpl [] - Processing cluster partition report from task executor container_e92_1642414791080_10224_01_000002: PartitionReport{entries=[]}.
2022-08-07 03:31:58,541 DEBUG org.apache.flink.runtime.resourcemanager.active.ActiveResourceManager [] - Trigger heartbeat request.
2022-08-07 03:31:58,541 DEBUG org.apache.flink.runtime.jobmaster.JobMaster                 [] - Received heartbeat request from 16e2c7709ada250726d6361b0bd7b7c9.
2022-08-07 03:31:58,541 DEBUG org.apache.flink.runtime.resourcemanager.active.ActiveResourceManager [] - Received heartbeat from 2b7e87604695f4e1f737ca3897284ee8.
2022-08-07 03:31:59,841 DEBUG org.apache.flink.runtime.jobmaster.JobMaster                 [] - Trigger heartbeat request.
2022-08-07 03:31:59,843 DEBUG org.apache.flink.runtime.jobmaster.JobMaster                 [] - Received heartbeat from container_e92_1642414791080_10224_01_000003.
2022-08-07 03:31:59,843 DEBUG org.apache.flink.runtime.jobmaster.JobMaster                 [] - Received heartbeat from container_e92_1642414791080_10224_01_000002.
2022-08-07 03:31:59,843 DEBUG org.apache.flink.runtime.jobmaster.JobMaster                 [] - Received heartbeat from container_e92_1642414791080_10224_01_000004.
2022-08-07 03:31:59,843 DEBUG org.apache.flink.runtime.jobmaster.JobMaster                 [] - Received heartbeat from container_e92_1642414791080_10224_01_000005.
2022-08-07 03:31:59,844 DEBUG org.apache.flink.runtime.jobmaster.JobMaster                 [] - Received heartbeat from container_e92_1642414791080_10224_01_000006.
2022-08-07 03:32:00,220 DEBUG org.apache.flink.runtime.jobmaster.JobMaster                 [] - Archive local failure causing attempt a7bb32ade11f8400a55e761081eb0e46 to fail: java.lang.IllegalStateException: Retrieve schema history failed, the schema records for engine 08c6c43f-e529-439b-9546-d1056524d389 has been removed, this might because the debezium engine has been shutdown due to other errors.
	at com.ververica.cdc.debezium.utils.DatabaseHistoryUtil.retrieveHistory(DatabaseHistoryUtil.java:77)
	at com.ververica.cdc.debezium.internal.FlinkDatabaseSchemaHistory.configure(FlinkDatabaseSchemaHistory.java:82)
	at io.debezium.relational.HistorizedRelationalDatabaseConnectorConfig.getDatabaseHistory(HistorizedRelationalDatabaseConnectorConfig.java:105)
	at io.debezium.relational.HistorizedRelationalDatabaseSchema.<init>(HistorizedRelationalDatabaseSchema.java:39)
	at io.debezium.connector.oracle.OracleDatabaseSchema.<init>(OracleDatabaseSchema.java:35)
	at io.debezium.connector.oracle.OracleConnectorTask.start(OracleConnectorTask.java:54)
	at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:130)
	at io.debezium.connector.common.BaseSourceTask.startIfNeededAndPossible(BaseSourceTask.java:207)
	at io.debezium.connector.common.BaseSourceTask.poll(BaseSourceTask.java:148)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:788)
	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:188)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Mindfaker** [comment] 2023-08-28 02:02
I have the same problem

**Comment by meihuasannong** [comment] 2024-01-24 07:10
I have the same problem

**Comment by meihuasannong** [comment] 2024-01-24 07:55
I add

```
debezium.log.mining.strategy=online_catalog
debezium.log.mining.continuous.mine=true
```

it become ok

**Comment by gong** [comment] 2024-02-03 05:43
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
cc @GOODBOY008

**Comment by PatrickRen** [comment] 2024-02-28 15:05
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:05 UTC
Labels: bug

**Comment by Hub-Wling** [comment] 2024-08-12 13:58
I have the same problem，not solved
