### ISSUE TITLE
请问下我们这边需要同步多种云（阿里云，华为云，亚马逊云等）下面的mysql数据，这种场景下的flinkCDC要如何部署使用呢，有没有相关的文档介绍啊

### ISSUE THREAD

**Issue by xpf-demo** [ververica/flink-cdc-connectors#1288] opened 2022-06-17 03:41 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by qq443672581** [comment] 2022-06-28 09:01
找一个云或者现有云部署flink，其他云和flink所在云网络打通，在flink云部署多 source（一个实例一个source）的任务就好了

**Comment by PatrickRen** [comment] 2024-02-28 15:06
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:06 UTC
Labels: enhancement
