### ISSUE TITLE
[mysql] Received DML 'DELETE FROM `db`.`table`' for processing, binlog probably contains events generated with statement or mixed based replication format

### ISSUE THREAD

**Issue by qq443672581** [ververica/flink-cdc-connectors#1454] opened 2022-08-08 03:07 UTC
**Environment :**
 - Flink version :  1.13.5
 - Flink CDC version: 2.2.0
 - Database and version: 5.7.25-log

Caused by: io.debezium.DebeziumException: Received DML 'DELETE FROM `db`.`table`' for processing, binlog probably contains events generated with statement or mixed based replication format

**Comment by ruanhang1993** [comment] 2022-08-08 09:47
https://www.mail-archive.com/search?l=user-zh@flink.apache.org&q=subject:%22%E5%9B%9E%E5%A4%8D%EF%BC%9A%E5%85%B3%E4%BA%8Eflink+sql+cdc%22&o=newest&f=1
Maybe your binlog format changes in some sessions.

**Comment by ruanhang1993** [comment] 2022-08-11 09:57
Debezium has a issue to fix this (https://issues.redhat.com/browse/DBZ-3949). We could set [[event.deserialization.failure.handling.mode](https://debezium.io/documentation/reference/1.6/connectors/mysql.html#mysql-property-event-deserialization-failure-handling-mode)](https://debezium.io/documentation/reference/1.6/connectors/mysql.html#mysql-property-event-deserialization-failure-handling-mode) to warn to skip this failure.

**Comment by ruanhang1993** [comment] 2022-08-11 10:03
Dupliacted to #1017.

**Comment by PatrickRen** [comment] 2024-02-28 15:35
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:35 UTC
Labels: bug
