### ISSUE TITLE
[mysql] Add schema validation for table schema

### ISSUE THREAD

**Issue by leonardBang** [ververica/flink-cdc-connectors#493] opened 2021-10-11 06:50 UTC
For a mysql single table, we should verify that the fields declared by the user in the ddl are included in the database table. For the sub-database and sub-table scenarios, we should verify that the fields declared in the ddl are included in the widest table, and the widest The table is composed of these sub-tables

**Comment by PatrickRen** [comment] 2024-02-28 15:11
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:11 UTC
Labels: enhancement
