### ISSUE TITLE
flink cdc Oracle 在监听oracle日志期间,监听表添加了字段,导致丢数据

### ISSUE THREAD

**Issue by XiaoXin101** [ververica/flink-cdc-connectors#1495] opened 2022-08-22 13:58 UTC
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  1.14
 - Flink CDC version: 2.2.1
 - Database and version: 11c

**To Reproduce**
    flink cdc Oracle 在监听oracle日志期间,监听表添加了字段,导致丢数据
   场景:oracle数据库高并发写入期间,表新增了字段,监听出来的日志,
   
<img width="1783" alt="image" src="https://user-images.githubusercontent.com/37534395/185938977-80c61712-8bf7-4d55-b24b-eacd79833c02.png">

日志解析出来都是空的数据,是有什么特殊的机制么

**Additional Description**

**Comment by gong** [comment] 2024-02-03 05:40
Considering collaboration with developers around the world, please re-create your issue in English on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!  cc @GOODBOY008

**Comment by PatrickRen** [comment] 2024-02-28 15:04
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:04 UTC
Labels: bug
