### ISSUE TITLE
设置检查点后报错: java.sql.SQLNonTransientConnectionException: Can't call rollback when autocommit=true

### ISSUE THREAD

**Issue by 15608447849** [ververica/flink-cdc-connectors#186] opened 2021-05-16 02:32 UTC
检查点的配置:
![image](https://user-images.githubusercontent.com/19607623/118383548-5aebfd00-b631-11eb-8868-60662666069b.png)
debzium的配置:
min.row.count.to.stream.results = 0
snapshot.locking.mode = none
snapshot.fetch.size = 100000
snapshot.lock.timeout.ms = 300000
启动时间:
2021-05-16 02:22:00
报错时间:
2021-05-16 02:44:08
报错信息如下:
[log4j2 ERROR]2021-05-16 02:44:08:294 Failed due to error: Aborting snapshot due to error when last running 'SELECT * FROM `erp-global`.`td_sale_order_split`': Can't call rollback when autocommit=true
org.apache.kafka.connect.errors.ConnectException: Can't call rollback when autocommit=true Error code: 0; SQLSTATE: 08003.
	at io.debezium.connector.mysql.AbstractReader.wrap(AbstractReader.java:241) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
	at io.debezium.connector.mysql.AbstractReader.failed(AbstractReader.java:218) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
	at io.debezium.connector.mysql.SnapshotReader.execute(SnapshotReader.java:857) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.sql.SQLNonTransientConnectionException: Can't call rollback when autocommit=true
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
	at com.mysql.cj.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:1833) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
	at io.debezium.connector.mysql.SnapshotReader.execute(SnapshotReader.java:766) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
	... 3 more
[log4j2 ERROR]2021-05-16 02:47:08:035 Task did not exit gracefully within 180 + seconds.
org.apache.flink.util.FlinkRuntimeException: Task did not exit gracefully within 180 + seconds.
	at org.apache.flink.runtime.taskmanager.Task$TaskCancelerWatchDog.run(Task.java:1718) [flink-runtime_2.12-1.13.0.jar:1.13.0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[log4j2 ERROR]2021-05-16 02:47:08:036 TaskManager #0 failed.
org.apache.flink.util.FlinkRuntimeException: Task did not exit gracefully within 180 + seconds.
	at org.apache.flink.runtime.taskmanager.Task$TaskCancelerWatchDog.run(Task.java:1718) [flink-runtime_2.12-1.13.0.jar:1.13.0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

您好,请问这和检查点是否有关,  刚通过报错的行联系上下文及rechSourceFunction的实现,发现快照期间是主动设置检查点超时失败的;
这方面应该如何配置;
最大表扫描耗时余额15分钟;

**Comment by enterwhat** [comment] 2021-08-14 08:55
> 检查点的配置:
> ![image](https://user-images.githubusercontent.com/19607623/118383548-5aebfd00-b631-11eb-8868-60662666069b.png)
> debzium的配置:
> min.row.count.to.stream.results = 0
> snapshot.locking.mode = none
> snapshot.fetch.size = 100000
> snapshot.lock.timeout.ms = 300000
> 启动时间:
> 2021-05-16 02:22:00
> 报错时间:
> 2021-05-16 02:44:08
> 报错信息如下:
> [log4j2 ERROR]2021-05-16 02:44:08:294 Failed due to error: Aborting snapshot due to error when last running 'SELECT * FROM `erp-global`.`td_sale_order_split`': Can't call rollback when autocommit=true
> org.apache.kafka.connect.errors.ConnectException: Can't call rollback when autocommit=true Error code: 0; SQLSTATE: 08003.
> at io.debezium.connector.mysql.AbstractReader.wrap(AbstractReader.java:241) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
> at io.debezium.connector.mysql.AbstractReader.failed(AbstractReader.java:218) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
> at io.debezium.connector.mysql.SnapshotReader.execute(SnapshotReader.java:857) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
> Caused by: java.sql.SQLNonTransientConnectionException: Can't call rollback when autocommit=true
> at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
> at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
> at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
> at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
> at com.mysql.cj.jdbc.ConnectionImpl.rollback(ConnectionImpl.java:1833) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
> at io.debezium.connector.mysql.SnapshotReader.execute(SnapshotReader.java:766) ~[flink-connector-mysql-cdc-1.4.0.jar:1.4.0]
> ... 3 more
> [log4j2 ERROR]2021-05-16 02:47:08:035 Task did not exit gracefully within 180 + seconds.
> org.apache.flink.util.FlinkRuntimeException: Task did not exit gracefully within 180 + seconds.
> at org.apache.flink.runtime.taskmanager.Task$TaskCancelerWatchDog.run(Task.java:1718) [flink-runtime_2.12-1.13.0.jar:1.13.0]
> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
> [log4j2 ERROR]2021-05-16 02:47:08:036 TaskManager #0 failed.
> org.apache.flink.util.FlinkRuntimeException: Task did not exit gracefully within 180 + seconds.
> at org.apache.flink.runtime.taskmanager.Task$TaskCancelerWatchDog.run(Task.java:1718) [flink-runtime_2.12-1.13.0.jar:1.13.0]
> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
> 
> 您好,请问这和检查点是否有关, 刚通过报错的行联系上下文及rechSourceFunction的实现,发现快照期间是主动设置检查点超时失败的;
> 这方面应该如何配置;
> 最大表扫描耗时余额15分钟;

请问这个是什么原因？怎么解决的？我也遇到了

**Comment by PatrickRen** [comment] 2024-02-28 15:14
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:14 UTC
Labels: bug, question
