### ISSUE TITLE
Error when using flink-sql-connector-oracle-cdc-2.3.0.jar

### ISSUE THREAD

**Issue by doraemon424** [ververica/flink-cdc-connectors#1888] opened 2023-01-31 08:03 UTC
**Describe the bug(Please use English)**
I encountered an error when using flink-sql-connector-oracle-cdc-2.3.0.jar. But when I use flink-sql-connector-oracle-cdc-2.1.1.jar instead, the error will not occurred again.
```
Caused by: java.lang.ClassNotFoundException: com.ververica.cdc.connectors.oracle.source.OracleSourceBuilder$OracleIncrementalSource
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClassWithoutExceptionHandling(FlinkUserCodeClassLoader.java:67)
	at org.apache.flink.util.ChildFirstClassLoader.loadClassWithoutExceptionHandling(ChildFirstClassLoader.java:74)
	at org.apache.flink.util.FlinkUserCodeClassLoader.loadClass(FlinkUserCodeClassLoader.java:51)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.apache.flink.util.FlinkUserCodeClassLoaders$SafetyNetWrapperClassLoader.loadClass(FlinkUserCodeClassLoaders.java:192)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.apache.flink.util.InstantiationUtil$ClassLoaderObjectInputStream.resolveClass(InstantiationUtil.java:78)
	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2025)
	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1892)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2223)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1709)
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2518)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2412)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2250)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1709)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:500)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:458)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:617)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:602)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:589)
	at org.apache.flink.util.SerializedValue.deserializeValue(SerializedValue.java:67)
	at org.apache.flink.runtime.operators.coordination.OperatorCoordinatorHolder.create(OperatorCoordinatorHolder.java:488)
	at org.apache.flink.runtime.executiongraph.ExecutionJobVertex.createOperatorCoordinatorHolder(ExecutionJobVertex.java:286)
	at org.apache.flink.runtime.executiongraph.ExecutionJobVertex.initialize(ExecutionJobVertex.java:223)
	... 20 more
```

**Environment :**
 - Flink version :  1.16.0
 - Flink CDC version: 2.3.0
 - Database and version:

**Comment by GeminiGuy** [comment] 2023-03-06 11:22
do you have solved this problem?

**Comment by ariesy** [comment] 2023-09-14 09:58
I also encountered this issue.
Flink version 1.17.1
flink-sql-connector-oracle-cdc version: 2.4.1

**Comment by ariesy** [comment] 2023-09-18 01:31
I found the cause and submitted a PR, anyone who has a similar issue can take a look and checkpick to your branch to build the jar file by yourself.

**Comment by GOODBOY008** [comment] 2024-02-01 11:09
Closing this issue as it is no longer valid or requires additional information. If the issue still exists, please report it on [Apache Jira](https://issues.apache.org/jira) under the project `Flink`, using the component tag `Flink CDC`. Thank you!

**Closed by GOODBOY008** 2024-02-01 11:09 UTC
Labels: bug
