### ISSUE TITLE
debezium.snapshot.select.statement.overrides

### ISSUE THREAD

**Issue by lykpass** [ververica/flink-cdc-connectors#728] opened 2021-12-16 02:32 UTC
For the split table, I want to pass a same statement,but now,I must write many 'debezium.snapshot.select.statement.overrides',hope to simplify the process
![image](https://user-images.githubusercontent.com/48595535/146297200-e037fb36-7dc5-4e22-af8b-7c9c1a70d800.png)

**Comment by PatrickRen** [comment] 2024-02-28 15:32
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:32 UTC
Labels: enhancement
