### ISSUE TITLE
Set -Dio.grpc.ManagedChannel.enableAllocationTracking=true to enable it

### ISSUE THREAD

**Issue by luxl6** [ververica/flink-cdc-connectors#1355] opened 2022-07-07 02:38 UTC
**Describe the bug(Please use English)**

**Environment :**
 - Flink version :  1.14.4
 - Flink CDC version: 2.2.1
 - Database and version: tidb 6.1

**To Reproduce**
1. Thes test data :
2. The test code :
3. The error :ManagedChannel allocation site

**Additional Description**

**Comment by PatrickRen** [comment] 2024-02-28 15:29
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:29 UTC
Labels: bug
