### ISSUE TITLE
Cannot read binlogs Mysql-CDC

### ISSUE THREAD

**Issue by muhammadali54321** [ververica/flink-cdc-connectors#1021] opened 2022-03-29 16:41 UTC
Caused by: java.lang.IllegalStateException: The connector is trying to read binlog starting at Struct{version=1.5.4.Final,connector=mysql,name=mysql_binlog_source,ts_ms=1648567265495,db=,server_id=0,file=mysql-bin.000090,pos=154,row=0}, but this is no longer available on the server. Reconfigure the connector to use a snapshot when needed.

my.cnf params:

logs_bin = on
expire_logs_day = 4
log-bin=/logs/database/proddb/bin_logs/mysql-bin                  
server-id=27
gtid_mode = off

When I run the following command on Mysql,
Show master status;

![image](https://user-images.githubusercontent.com/58175928/160662030-75770dca-b46b-4b88-863a-5fb64f3eb0ab.png)

As per error, It is pointing the correct binlog file and position(154). I need to know what is currently missing in my configuration

Table Setup:

   CREATE TABLE productmysql (
    id INT,
    name STRING,
    description STRING,
    PRIMARY KEY (id) NOT ENFORCED
  ) WITH (
    'connector' = 'mysql-cdc',
    'hostname' = '*******',
    'port' = '***',
    'username' = '*****',
    'password' = '******',
    'database-name' = 'mydb',
    'table-name' = 'products'
  );

**Environment :**
 - Flink version :  1.14.4
 - Flink CDC version: flink-sql-connector-mysql-cdc-2.2.0.jar
 - Database and version: mysql 5.7.29

**Comment by zhilinli123** [comment] 2022-04-26 02:25
Is there any good solution to this problem that I have encountered at present

**Comment by lzshlzsh** [comment] 2022-05-18 07:22
Is the problem solved ? How ?

**Comment by deepthinkin** [comment] 2022-11-14 03:14
Is the problem solved  ?

**Comment by deepthinkin** [comment] 2022-11-14 05:54
debezium.snapshot.mode = when_needed   add this kv ，What will happen ？

**Comment by PatrickRen** [comment] 2024-02-28 15:31
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:31 UTC
Labels: bug
