### ISSUE TITLE
Why there is not primary key flag for a table?

### ISSUE THREAD

**Issue by foobarrer** [ververica/flink-cdc-connectors#1565] opened 2022-09-20 06:44 UTC
**Is your feature request related to a problem? Please describe.**

I make a mysql sink function for write the data from kafka to mysql

***When use the dataStream API , Why there is not primary key in the captured data***
it's quiet a big problem for me, cuz I can't do some action like update or delete in the target mysql table by a unique key
besides for current version of *flink cdc*, the table that has been captured by *flink cdc* must have a primary key, 

**Describe the solution you'd like**

I think it's a good idea to have the primary key flag in date captured data like below

![image](https://user-images.githubusercontent.com/46312795/191186325-a5538976-a25c-417b-8c28-10db78ae81bf.png)

**Describe alternatives you've considered**
No

**Comment by PatrickRen** [comment] 2024-02-28 15:03
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:03 UTC
Labels: enhancement
