### ISSUE TITLE
[mysql] change the CREATE record to READ record in upsertBinlog

### ISSUE THREAD

**Issue by zhjwpku** [ververica/flink-cdc-connectors#840] opened 2022-02-09 09:14 UTC
**Is your feature request related to a problem? Please describe.**

In our work scenario, we want to make some distinction of the Snapshot record 
and the Binlog record, but since the `upsertBinlog` logic but the `CREATE` binlog
record directly to the normalizedRecords, so there will be some `CREATE` record
for the Snapshot phase, we hope to make all the Snapshot record has the 'READ'
Operation.

**Describe the solution you'd like**
In `upsertBinlog`, for the `CREATE` operation, change it to `READ` operation.

```
                         case CREATE:
-                            snapshotRecords.put(key, binlog);
-                            break;
+                            {
+                                Envelope envelope = Envelope.fromSchema(binlog.valueSchema());
+                                Struct source = value.getStruct(Envelope.FieldName.SOURCE);
+                                Struct create = value.getStruct(Envelope.FieldName.AFTER);
+                                Instant fetchTs =
+                                        Instant.ofEpochMilli(
+                                                (Long) source.get(Envelope.FieldName.TIMESTAMP));
+                                SourceRecord record =
+                                        new SourceRecord(
+                                                binlog.sourcePartition(),
+                                                binlog.sourceOffset(),
+                                                binlog.topic(),
+                                                binlog.kafkaPartition(),
+                                                binlog.keySchema(),
+                                                binlog.key(),
+                                                binlog.valueSchema(),
+                                                envelope.read(create, source, fetchTs));
+                                snapshotRecords.put(key, record);
+                                break;
+                            }

```

**Comment by PatrickRen** [comment] 2024-02-28 15:10
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:10 UTC
Labels: enhancement
