### ISSUE TITLE
Oracle CDC startupoptions.initial (), does not perform increments after the full quantity is executed.

### ISSUE THREAD

**Issue by hezhenghongmail** [ververica/flink-cdc-connectors#1456] opened 2022-08-08 08:19 UTC
**Describe the bug(Please use English)**
Oracle CDC startupoptions.initial (), does not perform increments after the full quantity is executed.

**Environment :**
 - Flink version :  1.14.2
 - Flink CDC version:  2.1.1
 - Database and version:  Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production

**To Reproduce**
1. Thes test data : test
2. The test code : test
3. The error : test
![image](https://user-images.githubusercontent.com/109778487/183371937-c15fdf52-3594-48b4-9872-3cde8ecc2ee4.png)
After executing the full amount, it has been stuck。

![image](https://user-images.githubusercontent.com/109778487/183372493-26d4e00f-634b-4538-be84-56f561cd43ff.png)
set to StartupOptions.latest()，Can read incremental information correctly. 
**Additional Description**

**Comment by GOODBOY008** [comment] 2022-08-08 08:45
@hezhenghongmail Thanks for your reporting this issue.Can you use verison `2.2.1` ?

**Comment by hezhenghongmail** [comment] 2022-08-08 09:20
ok, Try on this side。

**Comment by phalix** [comment] 2022-11-17 10:18
Same problem with Version 2.3 and 2.4-SNAPSHOT here.

**Comment by gong** [comment] 2024-02-03 05:47
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!
cc @GOODBOY008

**Comment by PatrickRen** [comment] 2024-02-28 15:35
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:35 UTC
Labels: bug
