### ISSUE TITLE
Generate Flink SQL DDL by MySQL/PG DDL

### ISSUE THREAD

**Issue by Jiezhi** [ververica/flink-cdc-connectors#468] opened 2021-09-27 10:31 UTC
**Is your feature request related to a problem? Please describe.**

As I learned for now, we must create Flink SQL table with maually set column name and type, is there a way to auto generate ddl by MySQL/PG DDL (columns part).

**Describe the solution you'd like**
If we want to add lots of table from mysql to flink and sink to hudi, we need create at least twice DDL to finish data flow.
For example, Sqoop's import would generate Hive table automaticlly by source table DDL.

**Describe alternatives you've considered**
Or it might be done by Fllink?

**Comment by PatrickRen** [comment] 2024-02-28 15:12
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:12 UTC
Labels: enhancement
