### ISSUE TITLE
CDC sharding fails due to the change of the primary key format generation rule of the mysql database table string

### ISSUE THREAD

**Issue by lgh1122** [ververica/flink-cdc-connectors#1143] opened 2022-04-29 06:55 UTC
**Describe the bug**
When using cdc for data synchronization，One of our business table，Because the generation rules of the string primary key id in the early stage and the id in the later stage are different，when cdc sharding，Using ObjectUtils.compare(chunkEnd, max) does not return the expected value correctly，cause sharding to fail，All data is centralized in one shard
pre id format ：logistics2018092521000003  
post id format ：ORLOGIAP202111041130281601000001 

**Environment :**
 - Flink version :  1.3.2
 - Flink CDC version: 2.1.0
 - Database and version: 5.7

**To Reproduce**
1. Thes test data :  
 min : logistics2018092521000003  max ORLOGIAP202111041130281601000001 chunkEnd: logistics2018111811000003  

![1637130476278_6F8574C5-8500-4442-9654-EDC9047E77D5](https://user-images.githubusercontent.com/31307232/142147548-fc9dd898-cd3b-4742-b409-d1156bffad47.png)
![1637130557145_7A684A27-D376-4bf3-8AF4-49F93D13A389](https://user-images.githubusercontent.com/31307232/142147604-564dbdd6-f2c1-4d18-a5ff-75e1333c2868.png)

**Comment by choucmei** [comment] 2022-05-05 14:59
In mysql use utf8_general_ci will case，eaxmple :  'a' = ‘A'  , use utf8_bin will sort by asscii  ,example:  'A' < 'a'.
But will sort by asscii  in java. 
 i will fix soon

**Comment by PatrickRen** [comment] 2024-02-28 15:07
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:07 UTC
Labels: bug
