### ISSUE TITLE
Multiple DB instances synchronization solution(`minimum cost`)

### ISSUE THREAD

**Issue by minchowang** [ververica/flink-cdc-connectors#979] opened 2022-03-22 09:31 UTC
**Is your feature request related to a problem? Please describe.**

In the **SAAS** case, we have **thousands of DB instances**,  and real-time data synchronization is our **highest cost** (Now one Flink-CDC job to synchronize multiple tables of one DB instance, so multiple DB instances need multiple Flink-CDC jobs ).

**Describe the solution you'd like**

We hope to have a **minimum cost**  multiple DB instances synchronization solutions.

**Describe alternatives you've considered**
- In the one Flink-CDC job， we to union multiple instances as our data sources, but they are not well isolated.
<img width="591" alt="image" src="https://user-images.githubusercontent.com/33626973/201135825-e11652dd-ac65-43cb-87cc-427ad9951018.png">
- As users, we accept a short time for failure recovery, but we have the below case: 

 For the failure database instance that cannot be recovered, the multiple DB instances synchronization jobs will do infinite fault recovery now.
 Solving this problem will that is the key to reducing costs and keeping a high SLA.

**Comment by LXin96** [comment] 2022-11-11 12:43
whether it means the readers 's num at least greater than nums of db instance or let split have self-sourceconfig

**Comment by minchowang** [comment] 2022-11-19 07:08
> whether it means the readers 's num at least greater than nums of db instance or let split have self-sourceconfig

If the readers' nums is greater than the nums of db instance, it will cause create too many TaskManagers. **That not is our expected minimum cost.**

So one TaskManager(with one slot) can support multis db-instances way is our expected minimum cost. But a single TaskManager occurred fault will affect multis db-instances subscription on this TaskManager,  we use Flink HA restart-strategy to do quick recovery, and our business is acceptable for it. 

**The worst problem** is to use the Flink HA restart-strategy does not recover, e.g. **some db-instance server/binlog Exceptions.**

**Comment by PatrickRen** [comment] 2024-02-28 15:31
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:31 UTC
Labels: enhancement
