### ISSUE TITLE
Support Scala 2.12

### ISSUE THREAD

**Issue by cnDenis** [ververica/flink-cdc-connectors#745] opened 2021-12-22 05:56 UTC
Support Scala 2.12 please.

Flink is shipped with both Scala 2.11 and 2.12, the connectors should support both version.

**Comment by leonardBang** [comment] 2021-12-30 06:35
Make sense to me, would you like to support this feature ? @cnDenis

**Comment by daniuEvan** [comment] 2022-01-20 08:57
Support Scala 2.12 please.

**Comment by PatrickRen** [comment] 2024-02-28 15:32
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:32 UTC
Labels: enhancement
