### ISSUE TITLE
Refactor the test dependency in the cdc connectors

### ISSUE THREAD

**Issue by ruanhang1993** [ververica/flink-cdc-connectors#1281] opened 2022-06-15 09:03 UTC
There are several test util dependencies in each connector module. For example, there are three dependencies (flink-test-utils, flink-connector-test-utils and flink-connector-test-util) in mysql cdc connector. These dependencies can easily conflict with each other. 

I think we should refactor the dependencies about tests, and put all dependencies in the module: flink-connector-test-util. Each connector module just needs to import the flink-connector-test-util dependency for all the tests.

**Comment by PatrickRen** [comment] 2024-02-28 15:06
Closing this issue because it was created before version 2.3.0 (2022-11-10). Please try the latest version of Flink CDC to see if the issue has been resolved. If the issue is still valid, kindly report it on [Apache Jira](https://issues.apache.org/jira) under project `Flink` with component tag `Flink CDC`. Thank you!

**Closed by PatrickRen** 2024-02-28 15:06 UTC
Labels: enhancement
